## test_plat45_three_media.nim — PLAT-45. **Same panes, same places, three
## media**, each read from its OWN output.
##
## PLAT-45's first real-stack row: open the `calc` recording in every
## front-end at depth 0 — the desktop, the GPUI window, the terminal at
## ultra-wide — read the arrangement from what each one PRODUCED, reduce each
## to PLAT-20's medium-independent relation (pairwise BEFORE, stack membership;
## `headless_app/arrangement_relation`), and require all three to equal the
## shared tree's relation. Comparing the model with itself is the trap
## Verification-Harness-Traps §4a names, so no medium's side is derived from
## the `Layout` it was given:
##
##   * **terminal** — a real session on `calc` in this process (the host's own
##     `openTuiSession`, a real `replay-server`), painted at 300x80: the
##     `CellArea` rectangles of the frame (`ShellScreen.projection`), and each
##     stacked region's active tab read back off the PAINTED strip;
##   * **GPUI** — the windowed `codetracer-gpui` on `calc`, in a real window
##     on a headless sway, READ OFF ITS PIXELS by PLAT-39's reader
##     (`ci/test/plat45-arrangement-window.sh` frames it,
##     `screen_oracle/plat45_window_record.nim` locates the cells from the
##     gutters and OCRs each cell's tab strip and heading) into
##     `src/tests/visual/plat45-gpui-arrangement.json`. Also the shipped
##     binary's dock document (`--dock-out`) and its render plan, so a window
##     that drew something other than what it was told is caught by the
##     difference between the two;
##   * **desktop** — the real Electron app, captured by `just
##     plat45-capture-electron` into
##     `src/tests/visual/answers/plat45-default-arrangement.electron.json`: every
##     GoldenLayout stack's DOM rectangle with its tabs' `Content` ordinals, on
##     the product's FIRST-RUN path (no user layout), plus the config as
##     loaded. The file's absence FAILS by name, naming the recipe.
##
## The same record carries a second capture from a prefix whose default was
## GENERATED BY A SCRATCH BUILD of the shared tree with one edit (the right
## column's two stacks swapped): the desktop's default must change with the
## tree, which is what makes `default_layout.json` an output of the tree and
## not a copy of it.
##
## No mocks: a real recording, real processes, real files.

import std/[json, options, os, osproc, sets, streams, strtabs, strutils, tempfiles,
            unicode, unittest]

import headless_app/layout_model
import headless_app/desktop_panes
import headless_app/arrangement_relation
import ../../../common/types

import ../app/runtime
import ../app/tui_app
import ../app/theme/capabilities
import ../app/layout/profile
import ../app/layout/project
import ../app/views/shell
import ../host/native_host
import ../host/tui_session
import ./fixtures/fixture_provider
import ../../gpui/app/pane_names

var CHECKS = 0
template ck(cond: untyped) =
  inc CHECKS
  check(cond)

const
  FixtureName = "calc"
  AnswersFile = "src/tests/visual/answers/plat45-default-arrangement.electron.json"
  CaptureRecipe = "just plat45-capture-electron"
  GpuiWindowFile = "src/tests/visual/plat45-gpui-arrangement.json"
  GpuiWindowRecipe = "just plat45-arrangement-window && just plat45-window-record"
  Cols = 300
  Rows = 80

let repo = getEnv("CODETRACER_REPO_ROOT", getCurrentDir())

const PinnedArrangement =
  "row(stack[fileTree*,vcs,testResults],editor,column(row(" &
  "stack[state*,scratchpad],stack[calltrace*,agentActivity])," &
  "stack[eventLog*,timeline,terminalOutput]))"
  ## **THE PRODUCT DECISION, PINNED**: the shared default's arrangement — the
  ## desktop's DEBUG-mode layout (PLAT-47 deliverable 1; the user, 2026-09-27:
  ## "The default layout of desktop is the shared arrangement. It has been
  ## reviewed and used for a long time."): TESTS a tab of the FILES panel
  ## beside VCS, no CONSTRAINTS. Each medium is compared with this AS WELL AS
  ## with the model's own relation, so an edit that the front-ends faithfully
  ## follow still turns every one of them red here: the default moved, and
  ## moving it is a decision a reviewer must see.

proc sharedRelation(): Arrangement = ofTree(sharedDefaultLayout().tree)

proc scratchTree(): LayoutNode =
  ## The shared default with the scratch build's one edit applied
  ## (`scripts/plat45-capture-electron.sh`, to the BUNDLED tree the desktop
  ## derives its Debug-mode default from): the state and call-trace stacks in
  ## the other order.
  result = clone(sharedDefaultLayout().tree)
  let upper = result.children[2].children[0]
  doAssert upper.kind == lnRow and upper.children.len == 2
  swap(upper.children[0], upper.children[1])

# ---------------------------------------------------------------------------
# Each medium, from its own output
# ---------------------------------------------------------------------------

proc paneOfTerminalName(name: string): string =
  for k in PaneKind:
    if terminalPaneName(k) == name: return $k
  "unknown:" & name

proc activeTabLabel(row: StyledRow; col, width: int): string =
  ## The label the terminal PAINTED as the active tab on a strip: the cells in
  ## the active-tab role (PLAT-47: a tab strip carries no brackets, so which
  ## tab is active is read off the paint, not off the text).
  var at = 0
  for span in row:
    let w = span.text.runeLen
    if span.style.role == srTabActive and at + w > col and at < col + width:
      result.add span.text
    at += w
  result = result.strip()

proc terminalRelation(tracePath: string; paintedActive: var seq[string]):
    Arrangement =
  ## A real session on `calc`, painted at 300x80, reduced from the frame.
  let caps = resolveCapabilities(
    initTerminalEnv(term = "xterm-256color", colorterm = "truecolor",
                    lang = "en_US.UTF-8"), initCapabilityFlags())
  let app = newTuiApp()
  let rt = newTuiRuntime(app, caps, Cols, Rows)
  let session = openTuiSession(tracePath, viewportHeight = Rows - 6)
  defer: session.close()
  session.header(rt)
  session.refresh(rt)
  let screen = rt.shellScreenOf()
  doAssert screen.projection.status == prOk
  var regions: seq[RegionRect] = @[]
  for r in screen.projection.regions:
    var tabs: seq[string] = @[]
    var active = 0
    if r.activeTab >= 0 and r.tabs.len > 0:
      for t in r.tabs: tabs.add paneOfTerminalName(t)
      active = r.activeTab
      # THE ACTIVE TAB, READ BACK OFF THE PAINTED STRIP.
      let painted = activeTabLabel(screen.styledRows[r.area.row], r.area.col,
                                   r.area.width)
      if painted.len > 0: paintedActive.add paneOfTerminalName(painted)
    else:
      tabs.add $r.pane
    regions.add RegionRect(x: float(r.area.col), y: float(r.area.row),
                           w: float(r.area.width), h: float(r.area.height),
                           tabs: tabs, active: active)
  ofRegions(regions, tolerance = 0.5)

proc dockRegions(n: JsonNode; x, y, w, h: float; into: var seq[RegionRect]) =
  case n["panel_name"].getStr
  of "StackPanel":
    let info = n["info"]["stack"]
    let horizontal = info["axis"].getInt == 0
    var total = 0.0
    for s in info["sizes"]: total += s.getFloat
    var cursor = if horizontal: x else: y
    for i, c in n["children"].getElems:
      let share = info["sizes"][i].getFloat / total
      if horizontal:
        dockRegions(c, cursor, y, w * share, h, into)
        cursor += w * share
      else:
        dockRegions(c, x, cursor, w, h * share, into)
        cursor += h * share
  of "TabPanel":
    var tabs: seq[string] = @[]
    for c in n["children"]:
      tabs.add c["info"]["panel"]["pane"].getStr
    into.add RegionRect(x: x, y: y, w: w, h: h, tabs: tabs,
                        active: n["info"]["tabs"]["active_index"].getInt)
  else:
    discard

proc gpuiRun(): (int, JsonNode, JsonNode, string) =
  ## The shipped window on `calc`: `(rc, plan, dock document, stderr)`.
  let bin = repo / "build/bin/codetracer-gpui"
  let shimDir = getEnv("ISONIM_GPUI_SHIM_DIR",
                   repo.parentDir / "isonim-gpui/rust/target/debug")
  let state = createTempDir("plat45-three-", "")
  var env = newStringTable()
  for k, v in envPairs(): env[k] = v
  env["LD_LIBRARY_PATH"] = shimDir &
    (if existsEnv("LD_LIBRARY_PATH"): ":" & getEnv("LD_LIBRARY_PATH") else: "")
  env["CODETRACER_TUI_LAYOUT_DIR"] = state
  let errFile = state / "err.txt"
  let dockFile = state / "dock.json"
  let calc = resolveFixture(FixtureName).tracePath
  let p = startProcess("/bin/sh",
    args = @["-c", "exec \"$0\" \"$@\" 2>" & quoteShell(errFile), bin,
             "--report-plan", "--width=1440", "--height=900",
             "--dock-out=" & dockFile, calc],
    env = env, options = {})
  let output = p.outputStream.readAll()
  let rc = p.waitForExit()
  p.close()
  let err = if fileExists(errFile): readFile(errFile) else: ""
  var plan, dock: JsonNode = nil
  if rc == 0:
    plan = parseJson(output)
    dock = parseJson(readFile(dockFile))
  removeDir(state)
  (rc, plan, dock, err)

proc planPanes(plan: JsonNode): HashSet[string] =
  proc walk(n: JsonNode; acc: var HashSet[string]) =
    if n.kind != JObject: return
    if n.hasKey("attributes") and n["attributes"].kind == JObject and
       n["attributes"].hasKey("data-ct-pane"):
      acc.incl n["attributes"]["data-ct-pane"].getStr
    if n.hasKey("children") and n["children"].kind == JArray:
      for c in n["children"]: walk(c, acc)
  walk(plan, result)

proc paneOfGpuiLabel(label: string): string =
  ## A label the GPUI window drew, back to the pane it names.
  for k in PaneKind:
    if gpuiPaneName(k) == label: return $k
  "unknown:" & label

proc gpuiWindowRelation(frame: JsonNode): Arrangement =
  ## The GPUI window's arrangement, from the cells PLAT-39's reader located in
  ## its frame and the tab strips it read. The window's gaps are 8 px.
  var regions: seq[RegionRect] = @[]
  for r in frame["regions"]:
    var tabs: seq[string] = @[]
    for t in r["tabs"]: tabs.add paneOfGpuiLabel(t.getStr)
    regions.add RegionRect(x: r["x"].getFloat, y: r["y"].getFloat,
                           w: r["w"].getFloat, h: r["h"].getFloat, tabs: tabs,
                           active: max(0, tabs.find(
                             paneOfGpuiLabel(r["active"].getStr))))
  ofRegions(regions, tolerance = 10.0)

proc desktopPaneName(content: int): string =
  ## A desktop tab's `Content` ordinal, through THE table. Every document the
  ## editor opens — source, the "NO SOURCE" placeholder, the CALLS view — is
  ## the editor pane.
  if content in [ord(Content.EditorView), ord(Content.NoInfo),
                 ord(Content.CalltraceEditor)]:
    return $paneEditor
  let p = paneOfContent(content)
  if p.isSome: $p.get else: "content#" & $content

proc desktopRelation(capture: JsonNode): Arrangement =
  ## The desktop's arrangement, from the DOM rectangles of the stacks the real
  ## app drew. GoldenLayout's splitters are 4 px, so a cut may cross that much.
  var regions: seq[RegionRect] = @[]
  for s in capture["stacks"]:
    var tabs: seq[string] = @[]
    var activeName = ""
    for i, c in s["contents"].getElems:
      let name = desktopPaneName(c.getInt)
      if i == s["active"].getInt: activeName = name
      if name notin tabs: tabs.add name
    regions.add RegionRect(x: s["x"].getFloat, y: s["y"].getFloat,
                           w: s["w"].getFloat, h: s["h"].getFloat,
                           tabs: tabs, active: max(0, tabs.find(activeName)))
  ofRegions(regions, tolerance = 6.0)

var tracePath = ""

suite "PLAT-45: same panes, same places, three media":

  test "the prerequisites are here":
    let resolved = resolveFixture(FixtureName)
    if resolved.outcome != foRecorded:
      checkpoint("the `calc` fixture is unavailable: " & resolved.detail)
    ck resolved.outcome == foRecorded
    tracePath = resolved.tracePath
    ck fileExists(repo / "build/bin/codetracer-gpui")
    if not fileExists(repo / AnswersFile):
      checkpoint("the desktop capture is absent: run `" & CaptureRecipe & "`")
    ck fileExists(repo / AnswersFile)
    if not fileExists(repo / GpuiWindowFile):
      checkpoint("the GPUI window record is absent: run `" & GpuiWindowRecipe & "`")
    ck fileExists(repo / GpuiWindowFile)

  test "the terminal at ultra-wide shows the shared default, read from its frame":
    ck depthFor(pmDebug, Cols, Rows) == 0
    var painted: seq[string] = @[]
    let got = terminalRelation(tracePath, painted)
    checkpoint("terminal: " & got.canonical)
    checkpoint("shared:   " & sharedRelation().canonical)
    ck got.problem.len == 0
    ck sameArrangement(got, sharedRelation())
    ck got.canonical == PinnedArrangement
    # The strips the terminal PAINTED name the active tab of every stack.
    var activeFromRelation = initHashSet[string]()
    for g in got.groups:
      if g.startsWith("stack["):
        for t in g[6 ..< g.len - 1].split(','):
          if t.endsWith("*"): activeFromRelation.incl t[0 ..< t.len - 1]
      else:
        # A one-tab stack reduces to its bare pane, painted as the active tab.
        activeFromRelation.incl g
    ck painted.len > 0
    for p in painted:
      ck p in activeFromRelation

  test "the GPUI window shows the shared default, read off its pixels":
    let record = parseJson(readFile(repo / GpuiWindowFile))
    let frame = record["frames"]["shared"]
    ck frame["located"].getBool
    # Every cell the reader located named what it holds.
    for r in frame["regions"]:
      checkpoint("cell (" & $r["x"].getInt & "," & $r["y"].getInt & ") strip '" &
                 r["strip"].getStr & "' active '" & r["active"].getStr & "'")
      ck r["tabs"].len > 0
      ck r["active"].getStr.len > 0
    let got = gpuiWindowRelation(frame)
    checkpoint("gpui window: " & got.canonical)
    ck got.problem.len == 0
    ck sameArrangement(got, sharedRelation())
    ck got.canonical == PinnedArrangement
    # THE NEGATIVE CONTROL: the same reader on a compositor with no window
    # finds no arrangement at all, so the reading above is of the window.
    ck not record["frames"]["blank"]["located"].getBool

  test "the GPUI binary's dock document is the shared default too":
    let (rc, plan, dock, err) = gpuiRun()
    if rc != 0: checkpoint(err)
    ck rc == 0
    var regions: seq[RegionRect] = @[]
    dockRegions(dock["center"], 0, 0, 1440, 900, regions)
    let got = ofRegions(regions)
    checkpoint("gpui:   " & got.canonical)
    ck got.problem.len == 0
    ck sameArrangement(got, sharedRelation())
    ck got.canonical == PinnedArrangement
    # Every pane of the shared default is a leaf of the plan (data or report).
    var shared = initHashSet[string]()
    for p in allPanes(sharedDefaultLayout().tree): shared.incl $p
    ck planPanes(plan) == shared

  test "the desktop shows the shared default, read from the DOM of the real app":
    let record = parseJson(readFile(repo / AnswersFile))
    ck record.hasKey("generated")
    let cap = record["generated"]
    ck not cap.hasKey("error")
    ck cap["stacks"].len > 0
    let got = desktopRelation(cap)
    checkpoint("desktop: " & got.canonical)
    ck got.problem.len == 0
    ck sameArrangement(got, sharedRelation())
    ck got.canonical == PinnedArrangement
    # AND THE FILE IT LOADED WAS THE GENERATED ONE, byte for byte: the
    # capture hashed the prefix's `config/default_layout.json`, and that is the
    # committed file `ci/test/default-layout-fresh.sh` holds to the generator.
    let committed = strutils.splitWhitespace(execProcess("sha256sum",
      args = [repo / "src/config/default_layout.json"],
      options = {poUsePath}))[0]
    checkpoint("loaded " & cap["prefixDefaultSha256"].getStr & ", committed " &
               committed)
    ck cap["prefixDefaultSha256"].getStr == committed

  test "and all three agree with each other, not only with the model":
    var painted: seq[string] = @[]
    let term = terminalRelation(tracePath, painted)
    let (rc, _, dock, _) = gpuiRun()
    ck rc == 0
    var regions: seq[RegionRect] = @[]
    dockRegions(dock["center"], 0, 0, 1440, 900, regions)
    let gpui = ofRegions(regions)
    let desk = desktopRelation(parseJson(readFile(repo / AnswersFile))["generated"])
    let window = gpuiWindowRelation(
      parseJson(readFile(repo / GpuiWindowFile))["frames"]["shared"])
    ck sameArrangement(term, gpui)
    ck sameArrangement(gpui, desk)
    ck sameArrangement(term, desk)
    # …and the GPUI WINDOW drew what its dock document said.
    ck sameArrangement(window, gpui)
    ck sameArrangement(window, desk)
    ck sameArrangement(window, term)

  test "a scratch build of the shared tree changes the desktop's default with it":
    let record = parseJson(readFile(repo / AnswersFile))
    ck record.hasKey("scratch")
    let scratch = desktopRelation(record["scratch"])
    checkpoint("desktop (scratch build): " & scratch.canonical)
    ck scratch.problem.len == 0
    # THE EDIT REACHED THE DESKTOP…
    ck sameArrangement(scratch, ofTree(scratchTree()))
    # …AND IT IS A DIFFERENT ARRANGEMENT, so the equality above is not the
    # default read twice.
    ck not sameArrangement(scratch, sharedRelation())
    ck record["scratch"]["prefixDefaultSha256"].getStr !=
       record["generated"]["prefixDefaultSha256"].getStr

echo "CHECKS: ", CHECKS
