#!/usr/bin/env bash
# =============================================================================
# Contract suite for ci/test/electron-supply-chain.sh.
#
# The guard it covers answers two questions about a built desktop artefact:
# WHICH Electron is in it, and WHAT ELSE came with it. Its own header explains
# why both needed a guard; this suite is about the failure side, because every
# way this guard could be wrong looks exactly like it working.
#
#   * PASSING ON A RANGE. `^44.0.0` is the shape the defect had — the only
#     version string in the shipped artefact was a caret range npm had written
#     itself. A pin check that accepts a range compares a version against a set
#     and passes on any member of it, which is the original defect wearing a
#     lockfile. One arm declares a range and requires refusal.
#
#   * REPORTING THE DECLARATION INSTEAD OF THE ARTEFACT. The whole point is
#     that the resolved version is not the declared one. An arm sets the
#     artefact to 44.0.0 while the pin says 44.1.1 and requires BOTH numbers in
#     the diagnostic, so a reader is told what drifted rather than that
#     something did.
#
#   * CALLING A STUB A RUNTIME. The published 2026-08-30 AppImage contained the
#     npm `electron` package with a correct-looking `package.json` and no
#     `dist/` — no Chromium at all. A check that stopped at the version string
#     would have passed that artefact. An arm removes `dist/` and requires the
#     word STUB.
#
#   * COUNTING WITHOUT NAMING. "550 packages outside the closure" is not
#     actionable; the answer a reader needs is WHICH. An arm plants one
#     dev-only package and requires it BY NAME in the output.
#
#   * A CLOSURE THAT IS QUIETLY EMPTY. If the yarn.lock parser breaks, every
#     package in the artefact falls outside a closure of size zero and the
#     guard fails loudly — but if it breaks the other way, or if a root cannot
#     be resolved, the closure silently shrinks and real dev dependencies get
#     reported as fine. Three arms cover the exact parse shapes that were
#     WRONG during development and produced false positives on the real tree:
#     a multi-descriptor group header (yarn quotes the group, not each member),
#     a yarn alias descriptor whose range itself contains an '@', and a package
#     declared under BOTH `dependencies` and `devDependencies`, where only one
#     of the two ranges survives into the lock.
#
# Every mutation arm reddens ITS OWN assertion: the arm is applied and the
# suite requires the specific diagnostic for that arm, not merely a non-zero
# exit. The fixture is a throwaway tree under mktemp; the real repository is
# never written to.
# =============================================================================

set -uo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

PASS=0
FAIL=0
OUT=""
RC=0
FIX=""

pass() {
	PASS=$((PASS + 1))
	printf '  ok   %s\n' "$1"
}

fail() {
	FAIL=$((FAIL + 1))
	printf '  FAIL %s\n' "$1" >&2
	if [ -n "${2:-}" ]; then
		printf '%s\n' "$2" | sed 's/^/       | /' >&2
	fi
}

cleanup() {
	[ -n "${FIX}" ] && rm -rf "${FIX}"
}
trap cleanup EXIT

# -----------------------------------------------------------------------------
# The fixture: a minimal tree with exactly the files the guard reads.
#
# The lock below is small but not simplified in the ways that would matter. It
# carries a multi-descriptor group header, an alias descriptor, a scoped
# package and a name declared in both dependency fields, because those four
# shapes are where a lockfile parser goes wrong, and where this one did.
# -----------------------------------------------------------------------------
make_fixture() {
	[ -n "${FIX}" ] && rm -rf "${FIX}"
	FIX="$(mktemp -d)"

	mkdir -p "${FIX}/ci/test" "${FIX}/appimage-scripts/electron" "${FIX}/node-packages"
	cp "${REPO_ROOT}/ci/test/electron-supply-chain.sh" "${FIX}/ci/test/"
	cp "${REPO_ROOT}/ci/test/electron-supply-chain-closure.py" "${FIX}/ci/test/"

	cat >"${FIX}/appimage-scripts/electron/package.json" <<'EOF'
{
  "name": "fixture-electron",
  "private": true,
  "dependencies": {
    "electron": "44.1.1"
  }
}
EOF

	cat >"${FIX}/appimage-scripts/electron/package-lock.json" <<'EOF'
{
  "name": "fixture-electron",
  "lockfileVersion": 3,
  "packages": {
    "node_modules/electron": { "version": "44.1.1" }
  }
}
EOF

	cat >"${FIX}/node-packages/package.json" <<'EOF'
{
  "name": "codetracer",
  "dependencies": {
    "@scope/prod": "^1.0.0",
    "aliased": "npm:real-pkg@^2.0.0",
    "prod-root": "^1.0.0",
    "shared": "1.0.0"
  },
  "devDependencies": {
    "dev-root": "^1.0.0",
    "shared": "^1.0.0"
  }
}
EOF

	cat >"${FIX}/node-packages/yarn.lock" <<'EOF'
# This file is generated by running "yarn install" inside your project.

__metadata:
  version: 8
  cacheKey: 10c0

"@scope/prod@npm:^1.0.0":
  version: 1.0.0
  resolution: "@scope/prod@npm:1.0.0"
  languageName: node
  linkType: hard

"aliased@npm:real-pkg@^2.0.0":
  version: 2.0.0
  resolution: "real-pkg@npm:2.0.0"
  languageName: node
  linkType: hard

"codetracer@workspace:.":
  version: 0.0.0-use.local
  resolution: "codetracer@workspace:."
  dependencies:
    "@scope/prod": "npm:^1.0.0"
    aliased: "npm:real-pkg@^2.0.0"
    dev-root: "npm:^1.0.0"
    prod-root: "npm:^1.0.0"
    shared: "npm:^1.0.0"
  languageName: unknown
  linkType: soft

"dev-leaf@npm:^1.0.0":
  version: 1.0.0
  resolution: "dev-leaf@npm:1.0.0"
  languageName: node
  linkType: hard

"dev-root@npm:^1.0.0":
  version: 1.0.0
  resolution: "dev-root@npm:1.0.0"
  dependencies:
    dev-leaf: "npm:^1.0.0"
  languageName: node
  linkType: hard

"prod-leaf@npm:^1.0.0, prod-leaf@npm:^1.0.1":
  version: 1.0.1
  resolution: "prod-leaf@npm:1.0.1"
  languageName: node
  linkType: hard

"prod-root@npm:^1.0.0":
  version: 1.0.0
  resolution: "prod-root@npm:1.0.0"
  dependencies:
    prod-leaf: "npm:^1.0.0"
  languageName: node
  linkType: hard

"shared@npm:^1.0.0":
  version: 1.0.0
  resolution: "shared@npm:1.0.0"
  languageName: node
  linkType: hard
EOF

	make_artefact
}

# A staged AppDir in the shape install_electron.sh + setup_node_deps.sh leave
# behind: the pinned Electron with a runtime under dist/, and a node_modules
# holding exactly the production closure.
make_artefact() {
	local art="${FIX}/appdir"
	rm -rf "${art}"
	mkdir -p "${art}/electron/node_modules/electron/dist"
	printf '{ "name": "electron", "version": "44.1.1" }\n' \
		>"${art}/electron/node_modules/electron/package.json"
	printf '#!/bin/false\n' >"${art}/electron/node_modules/electron/dist/electron"

	mkdir -p "${art}/node_modules"
	local name
	for name in prod-root prod-leaf aliased shared; do
		mkdir -p "${art}/node_modules/${name}"
		printf '{ "name": "%s" }\n' "${name}" >"${art}/node_modules/${name}/package.json"
	done
	mkdir -p "${art}/node_modules/@scope/prod"
	printf '{ "name": "@scope/prod" }\n' >"${art}/node_modules/@scope/prod/package.json"
}

plant_package() {
	local name="$1"
	mkdir -p "${FIX}/appdir/node_modules/${name}"
	printf '{ "name": "%s" }\n' "${name}" \
		>"${FIX}/appdir/node_modules/${name}/package.json"
}

run_guard() {
	OUT="$(bash "${FIX}/ci/test/electron-supply-chain.sh" "$@" 2>&1)"
	RC=$?
}

expect_rc() {
	local want="$1" what="$2"
	if [ "${RC}" -eq "${want}" ]; then
		pass "${what} (exit ${RC})"
	else
		fail "${what}: expected exit ${want}, got ${RC}" "$(printf '%s' "${OUT}" | tail -12)"
	fi
}

expect_says() {
	local needle="$1" what="$2"
	if grep -qF -- "${needle}" <<<"${OUT}"; then
		pass "${what}"
	else
		fail "${what}: output does not contain '${needle}'" "$(printf '%s' "${OUT}" | tail -12)"
	fi
}

expect_silent_on() {
	local needle="$1" what="$2"
	if grep -qF -- "${needle}" <<<"${OUT}"; then
		fail "${what}: output wrongly contains '${needle}'" "$(printf '%s' "${OUT}" | tail -12)"
	else
		pass "${what}"
	fi
}

echo "electron supply-chain guard contract"

# -----------------------------------------------------------------------------
# 1. The happy path, so every later arm's redness is attributable to the arm.
# -----------------------------------------------------------------------------
echo
echo "green: a pinned Electron and a pruned artefact"
make_fixture
run_guard "${FIX}/appdir"
expect_rc 0 "an exact pin, a matching lock and a production-only artefact pass"
expect_says "declared Electron version is EXACT (44.1.1)" "the pass names the version it checked"
expect_says "outside closure    : 0 packages" "and reports the dependency count it measured"
expect_says "RESULT: PASSED" "and reports PASSED"
expect_says "NOT a vulnerability" "the passing line still declares what it does not cover"

# The three parse shapes that produced false positives during development. On
# the green artefact these must be INSIDE the closure; a regression in the
# lockfile parser shows up here as one of them being named as an offender.
expect_silent_on "+ prod-leaf" "a package reached through a multi-descriptor lock header is in the closure"
expect_silent_on "+ aliased" "a yarn alias descriptor resolves to the aliasing name"
expect_silent_on "+ shared" "a name in BOTH dependency fields resolves via the lock's workspace entry"
expect_silent_on "+ @scope/prod" "a scoped package resolves"
expect_silent_on "unresolved edges" "and every production root was found in the lock"

# -----------------------------------------------------------------------------
# 2. MUTATION unpin-the-declaration — a caret range where an exact version goes.
#    This is the shape the original defect had.
# -----------------------------------------------------------------------------
echo
echo "mutation: unpin-the-declaration"
make_fixture
python3 - "${FIX}/appimage-scripts/electron/package.json" <<'PY'
import json, sys
p = sys.argv[1]
d = json.load(open(p))
d["dependencies"]["electron"] = "^44.1.1"
json.dump(d, open(p, "w"))
PY
run_guard "${FIX}/appdir"
expect_rc 1 "a caret range in the pin manifest is refused"
expect_says "is EXACT (got '^44.1.1', which is a range)" "and the diagnostic says a range is not a version"

# -----------------------------------------------------------------------------
# 3. MUTATION drift-the-lock — the declaration and the lock disagree, which is
#    how a pin edited without regenerating the lock would look.
# -----------------------------------------------------------------------------
echo
echo "mutation: drift-the-lock"
make_fixture
python3 - "${FIX}/appimage-scripts/electron/package-lock.json" <<'PY'
import json, sys
p = sys.argv[1]
d = json.load(open(p))
d["packages"]["node_modules/electron"]["version"] = "44.0.0"
json.dump(d, open(p, "w"))
PY
run_guard "${FIX}/appdir"
expect_rc 1 "a lock that resolves elsewhere than the declaration is refused"
expect_says "lock resolves electron to '44.0.0', declared is '44.1.1'" "and the diagnostic names BOTH versions"

# -----------------------------------------------------------------------------
# 4. MUTATION float-the-installer — reintroduce the exact line that shipped a
#    different Chromium on every build.
# -----------------------------------------------------------------------------
echo
echo "mutation: float-the-installer"
make_fixture
mkdir -p "${FIX}/appimage-scripts"
cat >"${FIX}/appimage-scripts/install_electron.sh" <<'EOF'
#!/usr/bin/env bash
npm install electron --prefix "${APP_DIR}/electron"
EOF
run_guard "${FIX}/appdir"
expect_rc 1 "an unversioned 'npm install electron' in a build script is refused"
expect_says "install electron without a version" "and the diagnostic says what is missing"
expect_says "install_electron.sh" "and names the file it found it in"

# A version-carrying install must NOT trip it, or the guard would be unusable.
make_fixture
cat >"${FIX}/appimage-scripts/install_electron.sh" <<'EOF'
#!/usr/bin/env bash
npm install electron@44.1.1 --prefix "${APP_DIR}/electron"
EOF
run_guard "${FIX}/appdir"
expect_rc 0 "but a version-carrying install is accepted"

# Prose that TELLS a developer to run the command is not a build step.
make_fixture
cat >"${FIX}/appimage-scripts/hint.sh" <<'EOF'
#!/usr/bin/env bash
echo "  npx yarn add electron --force"
EOF
run_guard "${FIX}/appdir"
expect_rc 0 "and the same command inside an echo is not mistaken for one"

# -----------------------------------------------------------------------------
# 5. MUTATION artefact-drift — the artefact carries an Electron other than the
#    pin. This is the check the declaration alone cannot make.
# -----------------------------------------------------------------------------
echo
echo "mutation: artefact-drift"
make_fixture
printf '{ "name": "electron", "version": "44.0.0" }\n' \
	>"${FIX}/appdir/electron/node_modules/electron/package.json"
run_guard "${FIX}/appdir"
expect_rc 1 "an artefact whose Electron differs from the pin is refused"
expect_says "artefact Electron is '44.0.0', declared pin is '44.1.1'" "and the diagnostic names both"
expect_says "resolved: 44.0.0" "and prints the resolved version as a value"

# -----------------------------------------------------------------------------
# 6. MUTATION stub-only-runtime — the package.json is right and there is no
#    Chromium. This is what downloads.codetracer.com actually served.
# -----------------------------------------------------------------------------
echo
echo "mutation: stub-only-runtime"
make_fixture
rm -rf "${FIX}/appdir/electron/node_modules/electron/dist"
run_guard "${FIX}/appdir"
expect_rc 1 "an artefact with the npm stub and no runtime is refused"
expect_says "STUB and no runtime" "and the diagnostic says the runtime is what is missing"
expect_says "dist/:    0 file(s)" "and prints the file count it measured"

# -----------------------------------------------------------------------------
# 7. MUTATION reintroduce-a-dev-dep — one package outside the production
#    closure, which must be reported BY NAME and not only counted.
# -----------------------------------------------------------------------------
echo
echo "mutation: reintroduce-a-dev-dep"
make_fixture
plant_package "dev-root"
run_guard "${FIX}/appdir"
expect_rc 1 "a dev-only package staged into the artefact is refused"
expect_says "outside closure    : 1 packages" "and the count is printed"
expect_says "+ dev-root" "and the offender is named, not merely counted"

# Its transitive closure counts too — 29 declared devDependencies pulled 549
# packages, and a check that only knew the roots would have reported 29.
make_fixture
plant_package "dev-leaf"
run_guard "${FIX}/appdir"
expect_rc 1 "a TRANSITIVE dev dependency is refused as well"
expect_says "+ dev-leaf" "and named, though it appears in no devDependencies list"

# `electron` is staged by install_electron.sh from its own lock, so it is
# legitimately outside the yarn closure and must not be reported.
make_fixture
plant_package "electron"
run_guard "${FIX}/appdir"
expect_rc 0 "but the separately-pinned electron package is not an offender"

# -----------------------------------------------------------------------------
# 8. MUTATION hide-the-lock — the pin is on disk and not in git.
#
#    This is not hypothetical. `.gitignore` carries a blanket
#    `package-lock.json` rule because the project uses yarn, and it swallowed
#    the pin on the first attempt to commit it: every version check above
#    passed against a file a fresh clone would not have. The check is skipped
#    outside a git work tree, so both arms build one.
# -----------------------------------------------------------------------------
echo
echo "mutation: hide-the-lock"
make_fixture
git -C "${FIX}" init -q 2>/dev/null
git -C "${FIX}" add -A -f >/dev/null 2>&1
run_guard "${FIX}/appdir"
expect_rc 0 "a tracked pin lockfile passes"
expect_says "the pin lockfile is tracked by git" "and the pass says so"

make_fixture
git -C "${FIX}" init -q 2>/dev/null
printf 'package-lock.json\n' >"${FIX}/.gitignore"
git -C "${FIX}" add -A >/dev/null 2>&1
run_guard "${FIX}/appdir"
expect_rc 1 "a pin lockfile that .gitignore hides is refused"
expect_says "is NOT tracked by git (check .gitignore)" "and the diagnostic names where to look"

# -----------------------------------------------------------------------------
# 9. The static half must be runnable with no artefact at all, because that is
#    how the lint lane invokes it — and it must SAY that it skipped, rather
#    than reporting a clean pass over an artefact it never looked at.
# -----------------------------------------------------------------------------
echo
echo "the artefact-less invocation"
make_fixture
run_guard
expect_rc 0 "the static half passes with no artefact"
expect_says "artefact checks SKIPPED" "and says out loud that it measured no artefact"
expect_silent_on "outside closure" "reporting no dependency verdict it did not earn"

# -----------------------------------------------------------------------------
echo
if [ "${FAIL}" -ne 0 ]; then
	printf 'RESULT: FAILED — %d of %d assertion(s) failed.\n' "${FAIL}" "$((PASS + FAIL))" >&2
	exit 1
fi
if [ "${PASS}" -eq 0 ]; then
	printf 'RESULT: FAILED — 0 assertions ran; this suite proved nothing.\n' >&2
	exit 1
fi
printf 'RESULT: PASSED — %d assertion(s).\n' "${PASS}"
