#!/usr/bin/env bash
#
# reclaim-hook-dispatchers-test.sh -- contract suite for
# ci/dev/reclaim-hook-dispatchers.sh and its wiring into the dev shell.
#
# THE DEFECT. `pre-commit install` finds Reprobuild's hook dispatcher in its
# slot, moves it to `<hook>.legacy` ("migration mode") and writes its own shim
# there. Reprobuild's managed hooks -- for pre-push, the publication gate --
# then run only because pre-commit's shim happens to chain `.legacy`, until
# somebody runs `repro hooks ensure --vcs`. Reprobuild's coexistence model is
# the other way round: the dispatcher owns the slot and runs the repository's
# own hook from `<hook>.repro-local`.
#
# WHAT IS PINNED.
#   * after a migration-mode install, the dispatcher is back in the slot, the
#     pre-commit shim is chained as `.repro-local`, and no `.legacy` remains;
#   * a real `git commit` then runs both the shim and the managed hook;
#   * a stale `.legacy` dispatcher next to a dispatcher in the slot is dropped;
#   * a hand-written `.repro-local` and a hand-written slot hook are left alone;
#   * a repository with no dispatcher is not touched;
#   * nix/shells/main.nix runs the reclaim right after the installer.
#
# Mocks: the dispatcher and the pre-commit shim are small stand-in scripts
# carrying the real marker lines ("# reprobuild hook dispatcher" and "# File
# generated by pre-commit"), because those markers are all the reclaim reads,
# and the real ones need a Reprobuild build and a pre-commit installation.
# The commits are real.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
TOOL="$REPO_ROOT/ci/dev/reclaim-hook-dispatchers.sh"

assertions=0
failures=0
ok() {
	assertions=$((assertions + 1))
	printf '  ok   %s\n' "$1"
}
fail() {
	assertions=$((assertions + 1))
	failures=$((failures + 1))
	printf '  FAIL %s\n' "$1"
	shift
	for line in "$@"; do printf '         %s\n' "$line"; done
}

if [ ! -f "$TOOL" ]; then
	echo "FAIL: $TOOL is missing; the dev shell leaves the dispatchers displaced"
	exit 1
fi

tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT
export GIT_CONFIG_GLOBAL="$tmp/gitconfig" GIT_CONFIG_NOSYSTEM=1
: >"$GIT_CONFIG_GLOBAL"

dispatcher() { # HOOK -> a dispatcher that runs .repro-local then records itself
	cat <<EOF
#!/bin/sh
# reprobuild hook dispatcher protocol=2
d=\$(dirname "\$0")
[ -x "\$d/$1.repro-local" ] && { "\$d/$1.repro-local" "\$@" || exit \$?; }
echo managed >>"$tmp/ran"
EOF
}
shim() {
	cat <<EOF
#!/bin/sh
# File generated by pre-commit: https://pre-commit.com
echo shim >>"$tmp/ran"
[ -x "\$(dirname "\$0")/pre-commit.legacy" ] && exec "\$(dirname "\$0")/pre-commit.legacy" "\$@"
exit 0
EOF
}

repo() {
	rm -rf "$tmp/r" "$tmp/ran"
	git init -q "$tmp/r"
	git -C "$tmp/r" config user.email t@example.com
	git -C "$tmp/r" config user.name t
	hooks="$tmp/r/.git/hooks"
	rm -f "$hooks"/*.sample
}

# What `pre-commit install` leaves over a dispatcher.
migrated() {
	repo
	dispatcher pre-commit >"$hooks/pre-commit.legacy"
	shim >"$hooks/pre-commit"
	chmod +x "$hooks"/*
}

reclaim() { (cd "$tmp/r" && bash "$TOOL" >/dev/null 2>&1); }
marker() { sed -n 2p "$1" 2>/dev/null; }

echo "reclaim-hook-dispatchers.sh"

# 1: migration-mode layout is turned back into the dispatcher layout.
migrated
reclaim
slot_marker="$(marker "$hooks/pre-commit")"
local_marker="$(marker "$hooks/pre-commit.repro-local")"
if [[ $slot_marker == "# reprobuild hook dispatcher"* ]] &&
	[[ $local_marker == "# File generated by pre-commit"* ]] &&
	[ ! -e "$hooks/pre-commit.legacy" ]; then
	ok "the dispatcher is back in the slot and the shim is chained as .repro-local"
else
	fail "the dispatcher is back in the slot and the shim is chained as .repro-local" "$(ls "$hooks")"
fi

# 2: and a real commit runs both, the shim first, each exactly once.
git -C "$tmp/r" commit -q --allow-empty -m probe
if [ "$(tr '\n' ' ' <"$tmp/ran")" = "shim managed " ]; then
	ok "a commit runs the pre-commit shim and the managed hook, once each"
else
	fail "a commit runs the pre-commit shim and the managed hook, once each" "ran: $(tr '\n' ' ' <"$tmp/ran")"
fi

# 3: a stale .legacy dispatcher beside a dispatcher in the slot is dropped.
repo
dispatcher pre-commit >"$hooks/pre-commit"
dispatcher pre-commit >"$hooks/pre-commit.legacy"
chmod +x "$hooks"/*
reclaim
if [ ! -e "$hooks/pre-commit.legacy" ] && [[ "$(marker "$hooks/pre-commit")" == "# reprobuild hook dispatcher"* ]]; then
	ok "a stale .legacy dispatcher next to the dispatcher is dropped"
else
	fail "a stale .legacy dispatcher next to the dispatcher is dropped" "$(ls "$hooks")"
fi

# 4: a hand-written .repro-local is never overwritten by the shim.
migrated
printf '#!/bin/sh\n# mine\n' >"$hooks/pre-commit.repro-local"
reclaim
if [ "$(marker "$hooks/pre-commit.repro-local")" = "# mine" ] && [ -e "$hooks/pre-commit.legacy" ]; then
	ok "a hand-written .repro-local is left alone, and so is the layout"
else
	fail "a hand-written .repro-local is left alone" "$(ls "$hooks")"
fi

# 5: a hand-written hook in the slot is left alone.
repo
dispatcher pre-push >"$hooks/pre-push.legacy"
printf '#!/bin/sh\n# mine\n' >"$hooks/pre-push"
reclaim
if [ "$(marker "$hooks/pre-push")" = "# mine" ] && [ -e "$hooks/pre-push.legacy" ]; then
	ok "a hand-written hook in the slot is left alone"
else
	fail "a hand-written hook in the slot is left alone" "$(ls "$hooks")"
fi

# 6: without Reprobuild nothing changes.
repo
shim >"$hooks/pre-commit"
chmod +x "$hooks/pre-commit"
snapshot() { ls "$hooks" && cat "$hooks/pre-commit"; }
before="$(snapshot)"
reclaim
if [ "$(snapshot)" = "$before" ]; then
	ok "a repository without dispatchers is not touched"
else
	fail "a repository without dispatchers is not touched" "$(ls "$hooks")"
fi

echo "the dev shell"

# 7: wired in, right after the installer.
shell_nix="$REPO_ROOT/nix/shells/main.nix"
l_install="$(grep -n 'installationScript}' "$shell_nix" | head -1 | cut -d: -f1)"
l_reclaim="$(grep -n 'reclaim-hook-dispatchers.sh' "$shell_nix" | grep -v '#' | head -1 | cut -d: -f1)"
if [ -n "$l_install" ] && [ -n "$l_reclaim" ] && [ "$l_reclaim" -gt "$l_install" ] &&
	[ "$((l_reclaim - l_install))" -lt 15 ]; then
	ok "nix/shells/main.nix reclaims the dispatchers right after the installer"
else
	fail "nix/shells/main.nix reclaims the dispatchers right after the installer" \
		"installer line: ${l_install:-none}, reclaim line: ${l_reclaim:-none}"
fi

echo
if [ "$assertions" -ne 7 ]; then
	echo "FAIL: ran $assertions assertions, expected 7"
	failures=$((failures + 1))
fi
if [ "$failures" -ne 0 ]; then
	echo "$failures of $assertions assertions failed"
	exit 1
fi
echo "all $assertions assertions passed"
