//! Build script for the codetracer db-backend crate.
//!
//! F5c-1 (Browser-Replay): compile the Nim MCR emulator into a shared
//! library and link it into db-backend so that an `EmulatorReplaySession`
//! can drive MCR traces without spawning ct-native-replay.
//!
//! F5c-2 extends this to wasm32: the WASM build feature set
//! (`browser-transport`) does NOT include `codetracer_trace_writer_nim`,
//! so there is no second Nim runtime to collide with and we can use a
//! plain static archive — much simpler than the .so + version script
//! dance the native build needs.
//!
//! ## Why a shared library on native, a static archive on wasm32
//!
//! db-backend's native build already links `codetracer_trace_writer_nim`,
//! which ships its own Nim runtime (`@psystem.nim.c.o`, `NimMain`,
//! `allocSharedImpl`, ...). Linking a second Nim runtime in via
//! `cc::Build::compile()` produces "multiple definition" errors at the
//! final `rustc -C link` step, because static archives merge all their
//! object files into the consumer's symbol namespace.
//!
//! Shared libraries solve this cleanly: their internal symbols are
//! private to the .so unless explicitly exported, so two independent Nim
//! runtimes can coexist as long as each lives behind its own dynamic
//! library boundary. We compile the emulator's generated C files with
//! `-fvisibility=hidden` and link them into a `cdylib`; only the `mcr*`
//! symbols (and `NimMain`) carry `__attribute__((visibility("default")))`
//! by virtue of Nim's `{.exportc, dynlib.}` semantics — for the others
//! we tighten visibility ourselves via a linker version script.
//!
//! The wasm32 build does not pull in `codetracer_trace_writer_nim`
//! (see the `browser-transport` feature in `Cargo.toml`), so there is
//! exactly one Nim runtime in the final wasm module. A static archive
//! is therefore safe and avoids the cost of building a wasm `cdylib`.

use std::env;
use std::path::{Path, PathBuf};
use std::process::Command;

fn main() {
    println!("cargo:rerun-if-changed=build.rs");

    let target_arch = env::var("CARGO_CFG_TARGET_ARCH").unwrap_or_default();
    let target_os = env::var("CARGO_CFG_TARGET_OS").unwrap_or_default();

    // Windows port: the recorder's emulator C generation pipeline is
    // bash + direnv + GNU-ld --version-script. None of those mechanisms
    // exist on Windows, and producing a true MSVC/Windows-equivalent
    // (DLL with .def export file, no rpath, no version script) is a
    // larger porting task than the initial Windows bring-up needs. So
    // we emit a stub object that defines all `mcr*` and `NimMain`
    // symbols as no-ops/panics. The FFI module continues to reference
    // them at link time, and runtime use of MCR replay on Windows will
    // hit clear "not implemented" sentinels (returning -1/0). See
    // emulator_ffi.rs / emulator_session.rs for the consumers; the
    // MCR replay path is only entered when the user opens a CTFS
    // bundle that contains MCR data, which is not a Windows scenario
    // today.
    if target_os == "windows" {
        build_windows_stub();
        return;
    }

    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let recorder_root = manifest_dir
        .join("../../../codetracer-native-recorder")
        .canonicalize()
        .expect("expected sibling codetracer-native-recorder repo");
    let emulator_dir = recorder_root.join("ct_emulator");

    if target_arch == "wasm32" {
        build_wasm32(&emulator_dir);
    } else {
        build_native(&emulator_dir, &target_arch);
    }
}

// =====================================================================
// Windows stub target: emit a tiny static archive with no-op
// implementations of every symbol that emulator_ffi.rs imports. This
// lets the link step succeed on Windows even though the real Nim MCR
// emulator (Linux/macOS shared library with GNU --version-script) is
// not yet ported. Runtime callers will see "not implemented" return
// codes (-1) from the side-effecting functions and zero from the
// accessors, which surfaces as a clear failure in higher-level MCR
// code paths without panicking the whole process. The MCR replay
// session is not reachable through normal Windows usage today —
// it only fires when opening a CTFS bundle with embedded MCR data.
// =====================================================================
fn build_windows_stub() {
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    let stub_c = out_dir.join("mcr_emulator_windows_stub.c");
    std::fs::write(
        &stub_c,
        r#"/* Auto-generated by db-backend/build.rs for Windows builds.
 * Provides link-time stubs for the Nim MCR emulator FFI surface. The
 * real implementation lives in ../codetracer-native-recorder and is
 * Linux/macOS-only today (uses bash, direnv, GNU --version-script).
 */
#include <stdint.h>

#ifdef _MSC_VER
#  define MCR_EXPORT __declspec(dllexport)
#else
#  define MCR_EXPORT
#endif

MCR_EXPORT void NimMain(void) { /* nothing to initialise in the stub */ }
MCR_EXPORT void mcrInit(void) { /* nothing to reset */ }

MCR_EXPORT int mcrLoadMemoryRegion(uint64_t address, const uint8_t* data, int data_len) {
    (void)address; (void)data; (void)data_len; return -1;
}

MCR_EXPORT void mcrSetRegisters(
    uint64_t rax, uint64_t rbx, uint64_t rcx, uint64_t rdx,
    uint64_t rsi, uint64_t rdi, uint64_t rbp, uint64_t rsp,
    uint64_t r8,  uint64_t r9,  uint64_t r10, uint64_t r11,
    uint64_t r12, uint64_t r13, uint64_t r14, uint64_t r15,
    uint64_t rip, uint64_t rflags) {
    (void)rax; (void)rbx; (void)rcx; (void)rdx;
    (void)rsi; (void)rdi; (void)rbp; (void)rsp;
    (void)r8;  (void)r9;  (void)r10; (void)r11;
    (void)r12; (void)r13; (void)r14; (void)r15;
    (void)rip; (void)rflags;
}

MCR_EXPORT int mcrAddSyscallEvent(uint64_t number, int64_t return_value) {
    (void)number; (void)return_value; return -1;
}

MCR_EXPORT int mcrStep(void) { return -1; }
MCR_EXPORT int mcrRun(int max_instructions) { (void)max_instructions; return -1; }
MCR_EXPORT int mcrReadMemory(uint64_t address, uint8_t* buf, int length) {
    (void)address; (void)buf; (void)length; return -1;
}
MCR_EXPORT uint64_t mcrGetPC(void) { return 0; }
MCR_EXPORT uint64_t mcrGetSP(void) { return 0; }
MCR_EXPORT uint64_t mcrGetRegister(int index) { (void)index; return 0; }
MCR_EXPORT uint64_t mcrGetStepCounter(void) { return 0; }
"#,
    )
    .expect("write windows stub C file");

    // Use cc::Build to produce a static archive (libmcr_emulator.a /
    // mcr_emulator.lib depending on the toolchain) that cargo will
    // pass to the final linker. We pick a static archive on Windows
    // rather than a DLL because there is no second Nim runtime to
    // collide with here — the stub has zero internal state.
    let mut build = cc::Build::new();
    build.file(&stub_c);
    build.compile("mcr_emulator");

    println!(
        "cargo:warning=db-backend: Windows build using MCR emulator stub (see build.rs); \
         MCR replay sessions will return errors at runtime."
    );
}

// =====================================================================
// Native target: shared library + version script.
// =====================================================================

fn build_native(emulator_dir: &Path, target_arch: &str) {
    let native_c_dir = emulator_dir.join("build").join("native_c_files");

    println!(
        "cargo:rerun-if-changed={}",
        emulator_dir.join("src/ct_emulator/emulator_wasm_api.nim").display()
    );
    println!(
        "cargo:rerun-if-changed={}",
        emulator_dir.join("build_native_api.sh").display()
    );
    println!("cargo:rerun-if-changed={}", native_c_dir.display());

    if !native_c_dir.join("@memulator_wasm_api.nim.c").exists() {
        regenerate_c(emulator_dir, "build_native_api.sh", &native_c_dir);
    }

    let nim_lib = read_nim_lib_path(&native_c_dir);

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    let obj_dir = out_dir.join("mcr_emulator_obj");
    std::fs::create_dir_all(&obj_dir).expect("create obj_dir");

    let mut object_files = Vec::new();
    for entry in std::fs::read_dir(&native_c_dir).expect("read native_c_files dir") {
        let entry = entry.expect("dir entry");
        let path = entry.path();
        if path.extension().is_some_and(|e| e == "c") {
            let obj = compile_c_to_obj_native(&path, &obj_dir, &nim_lib, emulator_dir);
            object_files.push(obj);
        }
    }
    assert!(
        !object_files.is_empty(),
        "no .c files found in {} — did Nim regeneration succeed?",
        native_c_dir.display()
    );

    let so_path = link_shared(&object_files, &out_dir, target_arch);

    let parent = so_path.parent().expect("so has parent");
    println!("cargo:rustc-link-search=native={}", parent.display());
    println!("cargo:rustc-link-lib=dylib=mcr_emulator");
    println!("cargo:rustc-link-arg=-Wl,-rpath,{}", parent.display());

    println!(
        "cargo:warning=db-backend: linked Nim MCR emulator ({} TUs) from {} as {}",
        object_files.len(),
        native_c_dir.display(),
        so_path.display()
    );
}

/// Compile a single .c file into an object file with hidden-visibility
/// defaults so that the Nim runtime symbols stay private to the .so.
fn compile_c_to_obj_native(src: &Path, obj_dir: &Path, nim_lib: &Path, emulator_dir: &Path) -> PathBuf {
    let stem = src
        .file_name()
        .expect("src has file_name")
        .to_string_lossy()
        .replace('@', "_");
    let obj = obj_dir.join(format!("{stem}.o"));

    let mut build = cc::Build::new();
    build
        .file(src)
        .include(nim_lib)
        .include(emulator_dir.join("src/ct_emulator"))
        .flag_if_supported("-w")
        .flag_if_supported("-fno-strict-aliasing")
        .flag_if_supported("-fno-math-errno")
        // Position-independent code is required for a shared library.
        .flag_if_supported("-fPIC");
    // Note: we intentionally do NOT pass `-fvisibility=hidden` here. Doing
    // so promotes every Nim-emitted symbol (including the `mcr*` exports)
    // to ELF visibility HIDDEN, which the linker version script then cannot
    // promote back to default. Visibility filtering is done entirely at
    // link time via the version script in `link_shared` below — that
    // approach keeps the explicit `mcr*` allowlist authoritative.

    let compiler = build.get_compiler();
    let mut cmd = compiler.to_command();
    cmd.arg("-c").arg(src).arg("-o").arg(&obj);
    let status = cmd.status().expect("invoke C compiler");
    assert!(status.success(), "failed compiling {}", src.display());
    obj
}

/// Link the previously-compiled object files into a shared library and
/// return the path to the resulting `lib<name>.so` (or `.dylib`).
fn link_shared(objects: &[PathBuf], out_dir: &Path, target_arch: &str) -> PathBuf {
    let so_name = if cfg!(target_os = "macos") {
        "libmcr_emulator.dylib"
    } else {
        "libmcr_emulator.so"
    };
    let so_path = out_dir.join(so_name);

    let version_script = out_dir.join("mcr_emulator.ver");
    std::fs::write(
        &version_script,
        "{\n\
            global:\n\
                NimMain;\n\
                mcrInit;\n\
                mcrLoadMemoryRegion;\n\
                mcrSetRegisters;\n\
                mcrAddSyscallEvent;\n\
                mcrStep;\n\
                mcrRun;\n\
                mcrGetPC;\n\
                mcrGetSP;\n\
                mcrGetRegister;\n\
                mcrReadMemory;\n\
                mcrGetStepCounter;\n\
            local:\n\
                *;\n\
        };\n",
    )
    .expect("write version script");

    let _ = target_arch;

    let cc = env::var("CC").unwrap_or_else(|_| "cc".to_string());
    let mut cmd = Command::new(cc);
    cmd.arg("-shared").arg("-fPIC").arg("-o").arg(&so_path);
    for obj in objects {
        cmd.arg(obj);
    }
    cmd.arg("-pthread")
        .arg(format!("-Wl,--version-script,{}", version_script.display()));
    let status = cmd.status().expect("invoke linker");
    assert!(status.success(), "failed linking {}", so_path.display());
    so_path
}

// =====================================================================
// wasm32 target: plain static archive via cc::Build.
// =====================================================================

fn build_wasm32(emulator_dir: &Path) {
    let wasm_c_dir = emulator_dir.join("build").join("wasm_c_files");

    println!(
        "cargo:rerun-if-changed={}",
        emulator_dir.join("src/ct_emulator/emulator_wasm_api.nim").display()
    );
    println!(
        "cargo:rerun-if-changed={}",
        emulator_dir.join("build_wasm_api.sh").display()
    );
    println!("cargo:rerun-if-changed={}", wasm_c_dir.display());

    if !wasm_c_dir.join("@memulator_wasm_api.nim.c").exists() {
        regenerate_c(emulator_dir, "build_wasm_api.sh", &wasm_c_dir);
    }

    let nim_lib = read_nim_lib_path(&wasm_c_dir);

    // wasm-sysroot path lives next to the consumer crate (db-backend),
    // not the recorder, because it is specific to the db-backend wasm
    // build's chosen libc surface.
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let wasm_sysroot_include = manifest_dir.join("wasm-sysroot/include");
    assert!(
        wasm_sysroot_include.exists(),
        "expected wasm-sysroot/include at {}",
        wasm_sysroot_include.display()
    );

    // Collect the generated .c files. The cc::Build call below produces
    // a single static archive `libmcr_emulator.a` in OUT_DIR, which
    // cargo links into the final wasm binary alongside Rust object files.
    let mut sources = Vec::new();
    for entry in std::fs::read_dir(&wasm_c_dir).expect("read wasm_c_files dir") {
        let entry = entry.expect("dir entry");
        let path = entry.path();
        if path.extension().is_some_and(|e| e == "c") {
            sources.push(path);
        }
    }
    assert!(
        !sources.is_empty(),
        "no .c files found in {} — did Nim regeneration succeed?",
        wasm_c_dir.display()
    );

    let mut build = cc::Build::new();
    build
        // Explicit target: build_wasm.sh sets CC_wasm32_unknown_unknown=clang
        // and AR_wasm32_unknown_unknown=llvm-ar, but the `cc` crate also
        // needs `--target=...` on the clang command line itself because a
        // generic `clang` binary defaults to the host triple. The cc crate
        // will inject this automatically when CARGO_CFG_TARGET_ARCH is
        // wasm32, but we set it explicitly to be robust against future
        // changes in the crate's defaults.
        .target("wasm32-unknown-unknown")
        .flag("--target=wasm32-unknown-unknown")
        // No host CRT in wasm32; Nim's emitted code only needs
        // <limits.h>, <stddef.h>, <stdbool.h>, <stdint.h>, <stdlib.h>,
        // and <string.h>. The first four come from clang's resource dir;
        // the rest come from our trimmed sysroot.
        .include(&wasm_sysroot_include)
        .include(&nim_lib)
        .include(emulator_dir.join("src/ct_emulator"))
        // Suppress Nim's noisy warnings; we don't own this generated code.
        .flag_if_supported("-w")
        .flag_if_supported("-fno-strict-aliasing")
        .flag_if_supported("-fno-math-errno")
        // wasm32 has no exception-handling lowering by default; Nim's
        // --exceptions:goto already avoids unwinder dependencies, but
        // belt-and-braces.
        .flag_if_supported("-fno-exceptions")
        // The trimmed wasm-sysroot's stdlib.h declares the standard
        // allocator surface but not `exit`. clang 21 turns implicit
        // function declarations into hard errors by default, so we
        // demote the diagnostic back to a warning (which `-w` then
        // silences) and supply `exit` from `emulator_wasm_libc_shims.rs`.
        // Tightening the sysroot to declare `exit` would force every
        // other consumer of `wasm-sysroot/include/stdlib.h` to confront
        // the same symbol; keeping the override local is less invasive.
        .flag_if_supported("-Wno-implicit-function-declaration")
        .files(&sources);
    build.compile("mcr_emulator");

    // Allow the wasm-ld pass to leave a few libc symbols undefined.
    // Rust's `compiler_builtins` will resolve `memcpy`/`memset`/`memmove`
    // at link time, and our `c_compat`/`emulator_wasm_libc_shims` modules
    // resolve `malloc`/`free`/`realloc`/`calloc`/`exit`. Anything we have
    // missed (Nim runtime versions evolve) should still be allowed at
    // link time so the build surfaces a clear "wasm-bindgen-side import"
    // error rather than a hard link failure — easier to diagnose.
    println!("cargo:rustc-link-arg=--import-undefined");

    println!(
        "cargo:warning=db-backend: linked Nim MCR emulator ({} TUs) from {} into wasm32 static archive",
        sources.len(),
        wasm_c_dir.display()
    );
}

// =====================================================================
// Shared helpers.
// =====================================================================

/// Regenerate the recorder's C output by invoking the named helper
/// script under `direnv exec` (so the Nim toolchain from the recorder's
/// flake is on PATH).
fn regenerate_c(emulator_dir: &Path, script_name: &str, output_dir: &Path) {
    eprintln!(
        "db-backend build.rs: generated C missing at {}; invoking {}",
        output_dir.display(),
        script_name,
    );

    let recorder_root = emulator_dir.parent().expect("emulator_dir has a parent").to_path_buf();

    let status = Command::new("direnv")
        .arg("exec")
        .arg(&recorder_root)
        .arg("bash")
        .arg(emulator_dir.join(script_name))
        .status();

    match status {
        Ok(s) if s.success() => {}
        Ok(s) => panic!(
            "{script_name} exited with status {s}; \
             run it manually via `direnv exec {} bash ct_emulator/{script_name}`",
            recorder_root.display(),
        ),
        Err(e) => panic!(
            "failed to spawn `direnv exec` for {script_name}: {e}. \
             Ensure direnv is on PATH and the recorder's .envrc has been allowed."
        ),
    }
}

/// Read the Nim stdlib include path written by build_*_api.sh, with a
/// best-effort fallback to `nim dump` if the marker file is missing.
fn read_nim_lib_path(c_dir: &Path) -> PathBuf {
    let marker = c_dir.join(".nim_lib_path");
    if let Ok(s) = std::fs::read_to_string(&marker) {
        let trimmed = s.trim();
        if !trimmed.is_empty() {
            return PathBuf::from(trimmed);
        }
    }

    let output = Command::new("nim")
        .arg("dump")
        .output()
        .expect("nim not on PATH and .nim_lib_path missing");
    for line in String::from_utf8_lossy(&output.stderr).lines() {
        if let Some(rest) = line.strip_prefix("lib: ") {
            return PathBuf::from(rest.trim());
        }
    }
    panic!(
        "could not determine Nim stdlib include path; \
         re-run the emulator build script to populate .nim_lib_path"
    );
}
