#!/usr/bin/env bash

# Build the Rust FFI static library for codetracer_trace_writer_ffi.
# This is needed by codetracer-wasm-recorder (wazero) for CGO linking.
#
# depends on: cargo/rust installed, capnp on PATH (brew install capnp on macOS)

set -e

echo "==========="
echo "codetracer build: build trace-writer-ffi"
echo "-----------"

: "${ROOT_DIR:=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
: "${DEPS_DIR:=$PWD/deps}"

TRACE_FORMAT_DIR="$ROOT_DIR/libs/codetracer-trace-format"
FFI_STAGE_DIR="$DEPS_DIR/trace-writer-ffi"

# --- pre-flight checks ---

if [ ! -f "$TRACE_FORMAT_DIR/Cargo.toml" ]; then
	echo "ERROR: codetracer-trace-format submodule not initialized."
	echo "  Run: git submodule update --init libs/codetracer-trace-format"
	exit 1
fi

if ! command -v capnp &>/dev/null; then
	echo "ERROR: capnp not found on PATH (needed by codetracer_trace_format_capnp)."
	echo "  On macOS: brew install capnp"
	exit 1
fi

# --- build ---

pushd "$TRACE_FORMAT_DIR"
cargo build --release -p codetracer_trace_writer_ffi
popd

# --- stage artifacts (static library only → forces static linking) ---

mkdir -p "$FFI_STAGE_DIR/lib" "$FFI_STAGE_DIR/include"

# Static library
if [ -f "$TRACE_FORMAT_DIR/target/release/libcodetracer_trace_writer_ffi.a" ]; then
	cp "$TRACE_FORMAT_DIR/target/release/libcodetracer_trace_writer_ffi.a" "$FFI_STAGE_DIR/lib/"
else
	echo "ERROR: static library not found after build"
	exit 1
fi

# Header (generated by cbindgen during build)
if [ -f "$TRACE_FORMAT_DIR/codetracer_trace_writer_ffi/codetracer_trace_writer.h" ]; then
	cp "$TRACE_FORMAT_DIR/codetracer_trace_writer_ffi/codetracer_trace_writer.h" "$FFI_STAGE_DIR/include/"
else
	echo "ERROR: header codetracer_trace_writer.h not found after build"
	exit 1
fi

echo "trace-writer-ffi staged to $FFI_STAGE_DIR"
echo "==========="
