#!/usr/bin/env bash

echo "codetracer setup:"
git rev-parse HEAD
echo ""

# TODO: research this in depth, not critical for db-backend itself for now
# git submodule update --init --recursive

rustup component add clippy
rustup component add rustfmt

pushd src/db-backend || exit
cargo build
popd || exit

pushd src/tui || exit
cargo build
popd || exit

pushd src/small-lang || exit
cargo build
popd || exit
