#!/usr/bin/env bash

echo "codetracer setup:"
echo $(git rev-parse HEAD)
echo ""

# TODO: research this in depth, not critical for db-backend itself for now 
# git submodule update --init --recursive

rustup component add clippy
rustup component add rustfmt

cd src/db-backend
cargo build
cd ../../

cd src/tui
cargo build
cd ../../

cd src/small-lang
cargo build
cd ../../

