#!/usr/bin/env bash

echo "codetracer setup:"
echo $(git rev-parse HEAD)
echo ""

# TODO: research this in depth, not critical for db-backend itself for now 
# git submodule update --init --recursive

cd src/db-backend
cargo build
cd ../..

nix develop .#devShells.x86_64-linux.default -c ./codex-setup-in-nix.sh


