//! Nim macro sourcemap support for the db-backend.
//!
//! This module provides macro sourcemap parsing and expansion lookup for
//! the db-backend's trace replay. It reuses the same JSON format as the
//! native backend's `macro_sourcemap` module but with types adapted for
//! the db-backend's `task::Location`.
//!
//! ## Macro sourcemap file format (schema 2)
//!
//! Generated by the patched Nim compiler with `--sourcemap:on`. The schema
//! is defined by `codetracer-nim` SHA `82da134b8` (§2-M1 in
//! `codetracer-specs/Nim-Compiler-Patches.md`). Top-level `"schema": 2`
//! is required; older shapes are rejected so consumers can rely on the
//! column data being present.
//!
//! - `schema`: schema version (always 2).
//! - `expansions[]`: expansion records — `site` and `definition` are
//!   `{file, line, col}` objects.
//! - `locations{}`: expanded-file line -> expansion info (statement
//!   granularity; entries include `siteCol` and `entryExpandedCol`).
//! - `expressionLocations{}`: `"<line>:<col>"` -> expansion info
//!   (expression granularity; added in schema 2 so the GUI can highlight
//!   individual sub-expressions).
//! - `expandedFilename`: path of the generated `expanded.nim`.
//! - `expandedEntries{}`: original path -> original line -> expanded line.
//! - `topLevelLines{}`: expanded line -> (original path, original line).

use std::collections::HashMap;
use std::fs;
use std::path::Path;

use log::{info, warn};
use serde::Deserialize;

use crate::task::Location;

/// Schema version this parser supports. Bumped to 2 by `codetracer-nim`
/// SHA `82da134b8`.
pub const MACRO_SOURCEMAP_SUPPORTED_SCHEMA: i64 = 2;

/// A `{file, line, col}` source position carried by `expansions[].site`
/// and `.definition` in schema 2.
#[derive(Debug, Clone, Deserialize, Default)]
#[serde(rename_all = "camelCase")]
pub struct PositionInLayer {
    pub file: String,
    pub line: i64,
    pub col: i64,
}

/// A single macro expansion record.
#[derive(Debug, Clone, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Expansion {
    pub path: String,
    pub first_line: i64,
    pub last_line: i64,
    /// Call site of the macro invocation (file/line/col). Schema 2.
    pub site: PositionInLayer,
    /// Definition site of the macro (file/line/col). Schema 2.
    pub definition: PositionInLayer,
    #[serde(default)]
    pub name: String,
    #[serde(default)]
    pub from_macro: bool,
}

/// Metadata linking an expanded-file position back to the expansion it
/// belongs to. Both the line-keyed `locations` table and the
/// `(line, col)`-keyed `expressionLocations` table use this shape.
#[derive(Debug, Clone, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ExpansionInfo {
    /// Call site file path.
    pub site_file: String,
    /// Call site line.
    pub site_line: i64,
    /// Call site column. Added in schema 2.
    pub site_col: i64,
    pub expansion_id: usize,
    /// Entry line in the next-deeper expansion layer, or -1 if absent.
    pub entry_expanded_line: i64,
    /// Column counterpart to `entry_expanded_line`. Added in schema 2.
    /// Negative when there is no chained expansion entry.
    pub entry_expanded_col: i64,
}

/// Expansion level base, matching the frontend `MacroExpansionLevelBase` enum.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MacroExpansionLevelBase {
    TopLevel,
    Deepest,
}

/// The current expansion level for a root location.
#[derive(Debug, Clone)]
pub struct MacroExpansionLevel {
    pub base: MacroExpansionLevelBase,
    pub level: usize,
}

impl Default for MacroExpansionLevel {
    fn default() -> Self {
        MacroExpansionLevel {
            base: MacroExpansionLevelBase::TopLevel,
            level: 0,
        }
    }
}

/// Update kind for macro expansion requests from the frontend.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Deserialize)]
pub enum MacroExpansionUpdateKind {
    MacroUpdateExpand,
    MacroUpdateExpandAll,
    MacroUpdateCollapse,
    MacroUpdateCollapseAll,
}

/// An expansion level update request from the frontend.
#[derive(Debug, Clone, Deserialize)]
pub struct MacroExpansionLevelUpdate {
    pub kind: MacroExpansionUpdateKind,
    #[serde(default)]
    pub times: usize,
}

/// Arguments for the `ct/update-expansion` DAP request.
#[derive(Debug, Clone, Deserialize)]
pub struct UpdateExpansionArgs {
    pub path: String,
    pub line: i64,
    pub update: MacroExpansionLevelUpdate,
}

/// A parsed macro sourcemap.
#[derive(Debug, Clone)]
pub struct MacroSourceMap {
    /// Schema version. Always `MACRO_SOURCEMAP_SUPPORTED_SCHEMA` for
    /// successfully-parsed sourcemaps; the parser rejects others.
    pub schema: i64,
    pub expansions: Vec<Expansion>,
    /// Statement-granularity map: expanded-file line -> expansion info.
    pub locations: HashMap<i64, ExpansionInfo>,
    /// Expression-granularity map: `(expanded-file line, col)` ->
    /// expansion info. Added in schema 2.
    pub expression_locations: HashMap<(i64, i64), ExpansionInfo>,
    pub expanded_filename: String,
    pub expanded_entries: HashMap<String, HashMap<i64, i64>>,
    pub top_level_lines: HashMap<i64, (String, i64)>,
}

/// Raw JSON structure for deserialization.
#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
struct RawMacroSourceMap {
    #[serde(default)]
    schema: i64,
    expansions: Vec<Expansion>,
    #[serde(default)]
    locations: serde_json::Value,
    #[serde(default)]
    expression_locations: serde_json::Value,
    #[serde(default)]
    expanded_filename: String,
    #[serde(default)]
    expanded_entries: serde_json::Value,
    #[serde(default)]
    top_level_lines: serde_json::Value,
}

/// Parent entry in the expansion chain: (path, line, expansion_first_line).
#[derive(Debug, Clone)]
struct ExpansionParent {
    path: String,
    line: i64,
    first_line: i64,
}

impl MacroSourceMap {
    /// Look up the expanded-file line for an original source location.
    pub fn load_macro_expanded_entries(&self, path: &str, line: i64) -> (String, i64) {
        let mut loop_path = path.to_string();
        let mut loop_line = line;
        while let Some(path_map) = self.expanded_entries.get(&loop_path) {
            if let Some(&expanded_line) = path_map.get(&loop_line) {
                loop_line = expanded_line;
                loop_path.clone_from(&self.expanded_filename);
            } else {
                break;
            }
        }
        (loop_path, loop_line)
    }

    /// Build the expansion chain for a location in the expanded file.
    ///
    /// Returns parent entries from deepest to shallowest.
    fn build_expansion_chain(&self, path: &str, line: i64) -> Vec<ExpansionParent> {
        if !path.ends_with("/expanded.nim") && path != self.expanded_filename {
            return vec![];
        }

        let mut chain: Vec<ExpansionParent> = vec![ExpansionParent {
            path: path.to_string(),
            line,
            first_line: -1,
        }];

        let mut location_line = line;
        let mut expanded_info: Option<&ExpansionInfo> = None;

        loop {
            if let Some(info) = expanded_info {
                location_line = info.site_line;
            }
            match self.locations.get(&location_line) {
                Some(info) => {
                    expanded_info = Some(info);
                    let expansion = &self.expansions[info.expansion_id];
                    chain.push(ExpansionParent {
                        path: info.site_file.clone(),
                        line: info.site_line,
                        first_line: expansion.first_line,
                    });

                    if let Some((top_path, top_line)) = self.top_level_lines.get(&location_line)
                        && top_path != "???"
                        && *top_line > 0
                    {
                        break;
                    }

                    if info.site_file != self.expanded_filename {
                        break;
                    }
                }
                None => break,
            }
        }

        chain
    }

    /// Follow top-level lines to resolve the final original source location.
    fn follow_top_level_lines(&self, path: &str, line: i64) -> (String, i64) {
        let mut current_path = path.to_string();
        let mut current_line = line;
        while current_path == self.expanded_filename {
            if let Some((top_path, top_line)) = self.top_level_lines.get(&current_line) {
                if top_path == "???" || *top_line <= 0 {
                    break;
                }
                current_path = top_path.clone();
                current_line = *top_line;
            } else {
                break;
            }
        }
        (current_path, current_line)
    }

    /// Resolve a macro expansion and populate a Location with expansion fields.
    ///
    /// This is the db-backend equivalent of the legacy Python
    /// `update_expansion_level` + `load_expanded_level_location`.
    pub fn resolve_expansion_to_location(&self, path: &str, line: i64, level: &MacroExpansionLevel) -> Location {
        let chain = self.build_expansion_chain(path, line);
        if chain.is_empty() {
            return Location::default();
        }

        let num_levels = chain.len();

        let (location_idx, parents_start) = match level.base {
            MacroExpansionLevelBase::TopLevel => {
                if level.level + 1 > num_levels {
                    (0, 1)
                } else {
                    let idx = num_levels - level.level - 1;
                    (idx, idx + 1)
                }
            }
            MacroExpansionLevelBase::Deepest => {
                if level.level >= num_levels {
                    (num_levels - 1, num_levels)
                } else {
                    (level.level, level.level + 1)
                }
            }
        };

        let location = &chain[location_idx];
        let parents: Vec<(String, i64, i64)> = chain[parents_start..]
            .iter()
            .map(|p| (p.path.clone(), p.line, p.first_line))
            .collect();

        let (expansion_id, expansion_first_line, expansion_last_line) = if location.path != self.expanded_filename {
            (-1i64, -1i64, -1i64)
        } else if let Some(info) = self.locations.get(&location.line) {
            let exp = &self.expansions[info.expansion_id];
            (info.expansion_id as i64, exp.first_line, exp.last_line)
        } else {
            (-1, -1, -1)
        };

        let (final_path, final_line) = if parents.is_empty() {
            self.follow_top_level_lines(&location.path, location.line)
        } else {
            (location.path.clone(), location.line)
        };

        let is_expanded = !parents.is_empty();
        let expansion_depth = parents.len();

        Location {
            path: "unknown".to_string(),
            line: -1,
            high_level_path: final_path,
            high_level_line: final_line,
            expansion_parents: parents,
            expansion_depth,
            expansion_id,
            expansion_first_line,
            expansion_last_line,
            is_expanded,
            ..Location::default()
        }
    }
}

/// A collection of loaded macro sourcemaps.
#[derive(Debug, Clone, Default)]
pub struct MacroSourceMapCollection {
    pub maps: Vec<MacroSourceMap>,
    /// Cached expansion levels: root_path -> root_line -> level.
    pub levels: HashMap<String, HashMap<i64, MacroExpansionLevel>>,
    /// Cached expansion roots: path -> line -> (root_path, root_line).
    pub expansion_roots: HashMap<String, HashMap<i64, (String, i64)>>,
}

impl MacroSourceMapCollection {
    pub fn is_empty(&self) -> bool {
        self.maps.is_empty()
    }

    /// Look up expanded entries for a source location across all loaded maps.
    pub fn load_macro_expanded_entries(&self, path: &str, line: i64) -> (String, i64) {
        for map in &self.maps {
            let (result_path, result_line) = map.load_macro_expanded_entries(path, line);
            if result_path != path || result_line != line {
                return (result_path, result_line);
            }
        }
        (path.to_string(), line)
    }

    /// Apply an expansion level update and resolve the expansion.
    ///
    /// This implements the full flow: look up roots, apply the level update,
    /// resolve the expansion, and return a populated Location.
    pub fn update_expansion(&mut self, path: &str, line: i64, update: &MacroExpansionLevelUpdate) -> Location {
        // Find the expansion root for this location
        let root = self
            .expansion_roots
            .get(path)
            .and_then(|m| m.get(&line))
            .cloned()
            .unwrap_or_else(|| (path.to_string(), line));

        let (root_path, root_line) = root;

        // Get or create the expansion level
        let level = self
            .levels
            .entry(root_path.clone())
            .or_default()
            .entry(root_line)
            .or_default();

        // Apply the update
        apply_expansion_level_update(level, update);
        let level_snapshot = level.clone();

        // Find the appropriate sourcemap and resolve
        for map in &self.maps {
            if map.expanded_entries.contains_key(path)
                || path == map.expanded_filename
                || path.ends_with("/expanded.nim")
            {
                // First, get the expanded entry
                let (expanded_path, expanded_line) = map.load_macro_expanded_entries(path, line);
                let loc = map.resolve_expansion_to_location(&expanded_path, expanded_line, &level_snapshot);

                // Cache the root mapping
                self.expansion_roots
                    .entry(path.to_string())
                    .or_default()
                    .insert(line, (root_path.clone(), root_line));

                if loc.is_expanded || loc.expansion_id >= 0 {
                    return loc;
                }
            }
        }

        Location::default()
    }
}

/// Apply a level update to the current expansion level.
///
/// Mirrors the legacy Python `apply_expansion_level_update`.
fn apply_expansion_level_update(level: &mut MacroExpansionLevel, update: &MacroExpansionLevelUpdate) {
    match update.kind {
        MacroExpansionUpdateKind::MacroUpdateExpand => {
            level.base = MacroExpansionLevelBase::TopLevel;
            level.level += update.times;
        }
        MacroExpansionUpdateKind::MacroUpdateExpandAll => {
            level.base = MacroExpansionLevelBase::Deepest;
            level.level = 0;
        }
        MacroExpansionUpdateKind::MacroUpdateCollapse => {
            if level.base == MacroExpansionLevelBase::TopLevel {
                if level.level >= update.times {
                    level.level -= update.times;
                } else {
                    level.level = 0;
                }
            } else {
                level.base = MacroExpansionLevelBase::TopLevel;
                // Reset to collapsed when switching from deepest
                level.level = 0;
            }
        }
        MacroExpansionUpdateKind::MacroUpdateCollapseAll => {
            level.base = MacroExpansionLevelBase::TopLevel;
            level.level = 0;
        }
    }
}

/// Parse the `locations` JSON object.
fn parse_locations(val: &serde_json::Value) -> HashMap<i64, ExpansionInfo> {
    let mut map = HashMap::new();
    if let Some(obj) = val.as_object() {
        for (key, value) in obj {
            if let Ok(line) = key.parse::<i64>()
                && let Ok(info) = serde_json::from_value::<ExpansionInfo>(value.clone())
            {
                map.insert(line, info);
            }
        }
    }
    map
}

/// Parse the `expandedEntries` JSON object.
fn parse_expanded_entries(val: &serde_json::Value) -> HashMap<String, HashMap<i64, i64>> {
    let mut map = HashMap::new();
    if let Some(obj) = val.as_object() {
        for (path, inner) in obj {
            let mut inner_map = HashMap::new();
            if let Some(inner_obj) = inner.as_object() {
                for (line_str, expanded_line_val) in inner_obj {
                    if let Ok(line) = line_str.parse::<i64>()
                        && let Some(expanded_line) = expanded_line_val.as_i64()
                    {
                        inner_map.insert(line, expanded_line);
                    }
                }
            }
            map.insert(path.clone(), inner_map);
        }
    }
    map
}

/// Parse the `topLevelLines` JSON object.
fn parse_top_level_lines(val: &serde_json::Value) -> HashMap<i64, (String, i64)> {
    let mut map = HashMap::new();
    if let Some(obj) = val.as_object() {
        for (key, value) in obj {
            if let Ok(line) = key.parse::<i64>() {
                if let Some(arr) = value.as_array() {
                    if arr.len() >= 2
                        && let (Some(path), Some(orig_line)) = (arr[0].as_str(), arr[1].as_i64())
                    {
                        map.insert(line, (path.to_string(), orig_line));
                    }
                } else if let Some(obj) = value.as_object()
                    && let (Some(path), Some(orig_line)) = (
                        obj.get("Field1").and_then(|v| v.as_str()),
                        obj.get("Field2").and_then(|v| v.as_i64()),
                    )
                {
                    map.insert(line, (path.to_string(), orig_line));
                }
            }
        }
    }
    map
}

/// Parse the `expressionLocations` JSON object (`"<line>:<col>"` keys ->
/// `ExpansionInfo`). Malformed keys are skipped silently.
fn parse_expression_locations(val: &serde_json::Value) -> HashMap<(i64, i64), ExpansionInfo> {
    let mut map = HashMap::new();
    if let Some(obj) = val.as_object() {
        for (key, value) in obj {
            let Some((line_str, col_str)) = key.split_once(':') else {
                continue;
            };
            let Ok(line) = line_str.parse::<i64>() else {
                continue;
            };
            let Ok(col) = col_str.parse::<i64>() else {
                continue;
            };
            if let Ok(info) = serde_json::from_value::<ExpansionInfo>(value.clone()) {
                map.insert((line, col), info);
            }
        }
    }
    map
}

/// Parse a JSON string into a `MacroSourceMap`.
///
/// Validates the top-level `schema` field; any value other than
/// `MACRO_SOURCEMAP_SUPPORTED_SCHEMA` (2) is rejected to avoid silently
/// producing partially-populated structs from pre-M1 files (whose
/// `site`/`definition` are 2-element arrays incompatible with the
/// schema-2 object shape).
pub fn parse_macro_sourcemap(content: &str) -> Option<MacroSourceMap> {
    let raw: RawMacroSourceMap = match serde_json::from_str(content) {
        Ok(raw) => raw,
        Err(e) => {
            warn!("macro_sourcemap: JSON parse failed: {e}");
            return None;
        }
    };

    if raw.schema != MACRO_SOURCEMAP_SUPPORTED_SCHEMA {
        warn!(
            "macro_sourcemap: unsupported schema {} (expected {})",
            raw.schema, MACRO_SOURCEMAP_SUPPORTED_SCHEMA
        );
        return None;
    }

    Some(MacroSourceMap {
        schema: raw.schema,
        expansions: raw.expansions,
        locations: parse_locations(&raw.locations),
        expression_locations: parse_expression_locations(&raw.expression_locations),
        expanded_filename: raw.expanded_filename,
        expanded_entries: parse_expanded_entries(&raw.expanded_entries),
        top_level_lines: parse_top_level_lines(&raw.top_level_lines),
    })
}

impl MacroSourceMap {
    /// Load and parse a `macro_sourcemap_*.json` file from disk.
    pub fn load(path: &Path) -> Result<MacroSourceMap, String> {
        let content =
            fs::read_to_string(path).map_err(|e| format!("macro_sourcemap: cannot read {}: {e}", path.display()))?;
        parse_macro_sourcemap(&content).ok_or_else(|| format!("macro_sourcemap: parse failed for {}", path.display()))
    }
}

/// Find and parse all `macro_sourcemap*.json` files in a directory.
pub fn load_macro_sourcemaps(trace_dir: &Path) -> MacroSourceMapCollection {
    let mut collection = MacroSourceMapCollection::default();

    let entries = match fs::read_dir(trace_dir) {
        Ok(entries) => entries,
        Err(e) => {
            info!("macro_sourcemap: could not read directory {}: {e}", trace_dir.display());
            return collection;
        }
    };

    for entry in entries.flatten() {
        let name = entry.file_name();
        let name_str = name.to_string_lossy();
        if !name_str.starts_with("macro_sourcemap") || !name_str.ends_with(".json") {
            continue;
        }

        let path = entry.path();
        let content = match fs::read_to_string(&path) {
            Ok(c) => c,
            Err(e) => {
                warn!("macro_sourcemap: could not read {}: {e}", path.display());
                continue;
            }
        };

        match parse_macro_sourcemap(&content) {
            Some(map) => {
                info!(
                    "macro_sourcemap: loaded {} ({} expansions, expanded_filename={})",
                    path.display(),
                    map.expansions.len(),
                    map.expanded_filename,
                );
                collection.maps.push(map);
            }
            None => {
                warn!("macro_sourcemap: could not parse {}", path.display());
            }
        }
    }

    collection
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::expect_used)]
mod tests {
    use super::*;

    fn sample_json() -> &'static str {
        // Schema-2 fixture matching the spec at
        // codetracer-specs/Nim-Compiler-Patches.md §2-M1.
        r#"{
            "schema": 2,
            "expansions": [
                {
                    "path": "expanded.nim",
                    "firstLine": 10,
                    "lastLine": 20,
                    "site": { "file": "original.nim", "line": 5, "col": 2 },
                    "definition": { "file": "macros.nim", "line": 100, "col": 4 },
                    "name": "myMacro",
                    "fromMacro": true
                }
            ],
            "locations": {
                "10": {
                    "siteFile": "original.nim",
                    "siteLine": 5,
                    "siteCol": 2,
                    "expansionId": 0,
                    "entryExpandedLine": 10,
                    "entryExpandedCol": 0
                }
            },
            "expressionLocations": {
                "10:7": {
                    "siteFile": "original.nim",
                    "siteLine": 5,
                    "siteCol": 9,
                    "expansionId": 0,
                    "entryExpandedLine": -1,
                    "entryExpandedCol": -1
                }
            },
            "expandedFilename": "/tmp/expanded.nim",
            "expandedEntries": {
                "original.nim": {
                    "5": 10
                }
            },
            "topLevelLines": {
                "15": ["original.nim", 5]
            }
        }"#
    }

    fn pre_m1_fixture() -> &'static str {
        // Pre-M1 file with no `schema` field. Must be rejected.
        r#"{
            "expansions": [],
            "locations": {},
            "expandedEntries": {},
            "expandedFilename": "",
            "topLevelLines": {}
        }"#
    }

    #[test]
    fn test_parse_macro_sourcemap() {
        let map = parse_macro_sourcemap(sample_json()).unwrap();
        assert_eq!(map.schema, MACRO_SOURCEMAP_SUPPORTED_SCHEMA);
        assert_eq!(map.expansions.len(), 1);
        let exp = &map.expansions[0];
        assert_eq!(exp.name, "myMacro");
        assert_eq!(exp.site.col, 2);
        assert_eq!(exp.definition.col, 4);
        assert_eq!(map.expanded_filename, "/tmp/expanded.nim");
        assert!(map.locations.contains_key(&10));
        let loc = &map.locations[&10];
        assert_eq!(loc.site_col, 2);
        assert_eq!(loc.entry_expanded_col, 0);
        assert_eq!(map.expression_locations.len(), 1);
        let e7 = &map.expression_locations[&(10, 7)];
        assert_eq!(e7.site_col, 9);
    }

    #[test]
    fn test_parse_rejects_pre_m1_shape() {
        assert!(parse_macro_sourcemap(pre_m1_fixture()).is_none());
    }

    #[test]
    fn test_load_real_schema2_file() {
        let real_path = std::path::Path::new("/tmp/macro_sourcemap_m2_test_bin.json");
        if !real_path.exists() {
            return;
        }
        let map = MacroSourceMap::load(real_path).expect("schema-2 file should parse");
        assert_eq!(map.schema, MACRO_SOURCEMAP_SUPPORTED_SCHEMA);
        assert!(!map.expansions.is_empty());
        assert!(!map.expression_locations.is_empty());
    }

    #[test]
    fn test_load_macro_expanded_entries() {
        let map = parse_macro_sourcemap(sample_json()).unwrap();
        let (path, line) = map.load_macro_expanded_entries("original.nim", 5);
        assert_eq!(path, "/tmp/expanded.nim");
        assert_eq!(line, 10);
    }

    #[test]
    fn test_load_macro_expanded_entries_no_match() {
        let map = parse_macro_sourcemap(sample_json()).unwrap();
        let (path, line) = map.load_macro_expanded_entries("other.nim", 5);
        assert_eq!(path, "other.nim");
        assert_eq!(line, 5);
    }

    #[test]
    fn test_apply_expand_update() {
        let mut level = MacroExpansionLevel::default();
        apply_expansion_level_update(
            &mut level,
            &MacroExpansionLevelUpdate {
                kind: MacroExpansionUpdateKind::MacroUpdateExpand,
                times: 1,
            },
        );
        assert_eq!(level.level, 1);
        assert_eq!(level.base, MacroExpansionLevelBase::TopLevel);
    }

    #[test]
    fn test_apply_collapse_update() {
        let mut level = MacroExpansionLevel {
            base: MacroExpansionLevelBase::TopLevel,
            level: 2,
        };
        apply_expansion_level_update(
            &mut level,
            &MacroExpansionLevelUpdate {
                kind: MacroExpansionUpdateKind::MacroUpdateCollapse,
                times: 1,
            },
        );
        assert_eq!(level.level, 1);
    }

    #[test]
    fn test_apply_collapse_all_update() {
        let mut level = MacroExpansionLevel {
            base: MacroExpansionLevelBase::TopLevel,
            level: 5,
        };
        apply_expansion_level_update(
            &mut level,
            &MacroExpansionLevelUpdate {
                kind: MacroExpansionUpdateKind::MacroUpdateCollapseAll,
                times: 0,
            },
        );
        assert_eq!(level.level, 0);
    }

    #[test]
    fn test_apply_expand_all_update() {
        let mut level = MacroExpansionLevel::default();
        apply_expansion_level_update(
            &mut level,
            &MacroExpansionLevelUpdate {
                kind: MacroExpansionUpdateKind::MacroUpdateExpandAll,
                times: 0,
            },
        );
        assert_eq!(level.base, MacroExpansionLevelBase::Deepest);
    }

    #[test]
    fn test_follow_top_level_lines() {
        let map = parse_macro_sourcemap(sample_json()).unwrap();
        let (path, line) = map.follow_top_level_lines("/tmp/expanded.nim", 15);
        assert_eq!(path, "original.nim");
        assert_eq!(line, 5);
    }
}
