# This file is generated by running "yarn install" inside your project.
# Manual changes might be lost - proceed with caution!

{ lib, stdenv, nodejs, git, cacert, fetchurl, writeShellScript, writeShellScriptBin }:
{ src, overrideAttrs ? null, ... } @ args:

let

  yarnBin = ./.yarn/releases/yarn-4.5.0.cjs;

  cacheFolder = ".yarn/cache";
  lockfile = ./yarn.lock;

  # Call overrideAttrs on a derivation if a function is provided.
  optionalOverride = fn: drv:
    if fn == null then drv else drv.overrideAttrs fn;

  # Simple stub that provides the global yarn command.
  yarn = writeShellScriptBin "yarn" ''
    exec '${nodejs}/bin/node' '${yarnBin}' "$@"
  '';

  # Common attributes between Yarn derivations.
  drvCommon = {
    # Make sure the build uses the right Node.js version everywhere.
    buildInputs = [ nodejs yarn ];
    # All dependencies should already be cached.
    yarn_enable_network = "0";
    # Tell node-gyp to use the provided Node.js headers for native code builds.
    npm_config_nodedir = nodejs;
  };

  # Comman variables that we set in a Nix build, but not in a Nix shell.
  buildVars = ''
    # Make Yarn produce friendlier logging for automated builds.
    export CI=1
    # Tell node-pre-gyp to never fetch binaries / always build from source.
    export npm_config_build_from_source=true
    # Disable Nixify plugin to save on some unnecessary processing.
    export yarn_enable_nixify=false
  '';

  # ``yarn nixify fetch`` only populates the cache for the *current*
  # architecture (Yarn 4 defaults to ``supportedArchitectures: ["current"]``).
  # Our ``yarn.lock`` pins platform-specific optional dependencies (esbuild,
  # @parcel/watcher, ...) for every OS/CPU, so the resulting cache - and hence
  # the fixed-output hash - differs per build platform. Select the hash for the
  # host system; the Linux hash is what CI / the binary cache is built against.
  #
  # To add a new platform, or to refresh a stale one: you cannot simply build
  # and wait for a "hash mismatch" error. ``cacheDrv`` is a *fixed-output*
  # derivation, so its store path is a function of the hash written here, not
  # of ``yarn.lock``. If the value below is a hash that was ever valid, Nix
  # finds that exact path in the binary cache, substitutes it, and NEVER RUNS
  # THE BUILDER -- so no mismatch is ever reported. What you get instead is a
  # pile of ``YN0056: Cache entry required but missing`` from ``yarn install``
  # further down the build, naming the packages whose lockfile entries changed.
  #
  # To force the real hash out, first invalidate the entry deliberately:
  #
  #   "x86_64-linux" = sentinelHash;   # see below
  #
  # No substitute can exist for the sentinel path, so the builder runs for
  # real and the "hash mismatch" error reports the true ``got:`` value. Paste
  # that in. (``nix-build --rebuild`` is not a substitute for this: it needs a
  # local realisation of the path to compare against.)
  #
  # NOTE: any change to ``yarn.lock`` invalidates BOTH hashes below, so they
  # have to be refreshed in the same commit range as the lockfile change or
  # every nix build fails with a hash mismatch. Running *any* yarn command in
  # this directory also makes the nixify plugin rewrite this file and DELETE
  # this whole per-system block, collapsing it to a single ``outputHash`` for
  # whichever machine happened to run yarn -- see commit 2c4b0a76, which had
  # to restore it once already. It did it five more times while the security
  # bumps in this branch were being prepared. Always check
  # ``git diff node-packages/yarn-project.nix`` after invoking yarn.
  # A hash that is valid in form but cannot match any real output, so the
  # fixed-output store path it names has no substitute anywhere. Assigning it
  # to a platform below forces that platform's cache to be built for real, and
  # the resulting "hash mismatch" error prints the true ``got:`` value.
  sentinelHash =
    "sha512-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==";

  cacheOutputHashes = {
    # Refreshed for the ``electron-rebuild@3.2.9`` -> ``@electron/rebuild@4.2.0``
    # swap that drops ``tar@6.2.1`` (GHSA-23hp-3jrh-7fpw). That lockfile change
    # invalidated both hashes below, exactly as the NOTE above warns.
    #
    # Forced with ``sentinelHash`` rather than by waiting for a mismatch, per the
    # procedure above -- the previous values were real, so Nix would have
    # substituted the stale caches from the binary cache and never run the
    # builder, surfacing as ``YN0056: Cache entry required but missing``.
    # Measured on CI (run 34337422212) after the sentinel forced a real build of
    # yarn-cache.drv on x86_64-linux -- no Linux builder is configured on the
    # machine this branch was prepared on, so this value could not be obtained
    # locally. Three independent jobs -- test-non-gui (nixos, eph-linux-x64-g1),
    # reprobuild-linux-smoke, and ct-test release gate (M16 provider matrix) --
    # each built /nix/store/jkmf1s93nsmg5n2hyxc9hggwyj044yqv-yarn-cache.drv and
    # reported this identical ``got:`` value.
    "x86_64-linux" = "sha512-YOh4Lqjn3A2V2gYD+sspl5ZVOZJ+SCRPLHwp+DD03wq9t4eHQv2kXEv6aqhYW4ybT5itznWOe6E1SxfFDC57sg==";
    # Measured locally on aarch64-darwin: the sentinel above forced a real build
    # of yarn-cache.drv (no substitute can exist for it), and the mismatch
    # reported this ``got:``. Re-pinned and rebuilt to confirm it is stable.
    "aarch64-darwin" = "sha512-rJ3Oka4DrMUZPVorCFF5usgDOBwQaXM/6AfzvVohcMiR7qB1EkYkr+hCNn3AVu+9Hl4TAZ472TBFhfSwxE8XJw==";
  };

  cacheOutputHash =
    cacheOutputHashes.${stdenv.hostPlatform.system} or (throw ''
      No yarn-cache outputHash pinned for system '${stdenv.hostPlatform.system}'.
      Add one to cacheOutputHashes in node-packages/yarn-project.nix: build once
      and copy the 'got:' hash reported by the hash-mismatch error.
    '');

  cacheDrv = stdenv.mkDerivation {
    name = "yarn-cache";
    buildInputs = [ yarn git cacert ];
    buildCommand = ''
      cp --reflink=auto --recursive '${src}' ./src
      cd ./src/
      ${buildVars}
      HOME="$TMP" yarn_enable_global_cache=false yarn_cache_folder="$out" \
        yarn nixify fetch
      rm $out/.gitignore
    '';
    outputHashMode = "recursive";
    outputHash = cacheOutputHash;
  };

  # Main project derivation.
  project = stdenv.mkDerivation (drvCommon // {
    inherit src;
    name = "codetracer";

    configurePhase = ''
      ${buildVars}

      # Copy over the Yarn cache.
      rm -fr '${cacheFolder}'
      mkdir -p '${cacheFolder}'
      cp --reflink=auto --recursive ${cacheDrv}/* '${cacheFolder}/'

      # Yarn may need a writable home directory.
      export yarn_global_folder="$TMP"

      # Ensure global cache is disabled. Cache must be part of our output.
      touch .yarnrc.yml
      sed -i -e '/^enableGlobalCache/d' .yarnrc.yml
      echo 'enableGlobalCache: false' >> .yarnrc.yml

      # Some node-gyp calls may call out to npm, which could fail due to an
      # read-only home dir.
      export HOME="$TMP"

      # running preConfigure after the cache is populated allows for
      # preConfigure to contain substituteInPlace for dependencies as well as the
      # main project. This is necessary for native bindings that maybe have
      # hardcoded values.
      runHook preConfigure

      # Run normal Yarn install to complete dependency installation.
      yarn install --immutable --immutable-cache

      runHook postConfigure
    '';

    buildPhase = ''
      runHook preBuild
      runHook postBuild
    '';

    installPhase = ''
      runHook preInstall

      # Move the package contents to the output directory.
      if grep -q '"workspaces"' package.json; then
        # We can't use `yarn pack` in a workspace setup, because it only
        # packages the outer workspace.
        mkdir -p "$out/libexec"
        mv $PWD "$out/libexec/$name"
      else
        # - If the package.json has a `files` field, only files matching those patterns are copied
        # - Otherwise all files are copied.
        yarn pack --out package.tgz
        mkdir -p "$out/libexec/$name"
        tar xzf package.tgz --directory "$out/libexec/$name" --strip-components=1

        cp --reflink=auto .yarnrc* "$out/libexec/$name"
        cp --reflink=auto ${lockfile} "$out/libexec/$name/yarn.lock"
        cp --reflink=auto --recursive .yarn "$out/libexec/$name"

        # Copy the Yarn linker output into the package.
        cp --reflink=auto --recursive node_modules "$out/libexec/$name"
      fi

      cd "$out/libexec/$name"

      # Invoke a plugin internal command to setup binaries.
      mkdir -p "$out/bin"
      yarn nixify install-bin $out/bin

      # A package with node_modules doesn't need the cache
      yarn cache clean

      runHook postInstall
    '';

    passthru = {
      inherit nodejs;
      yarn-freestanding = yarn;
      yarn = writeShellScriptBin "yarn" ''
        exec '${yarn}/bin/yarn' --cwd '${overriddenProject}/libexec/${overriddenProject.name}' "$@"
      '';
    };
  });

  overriddenProject = optionalOverride overrideAttrs project;

in overriddenProject
