/* Generated by the Nim Compiler v1.6.20 */
var framePtr = null;
var excHandler = 0;
var lastJSError = null;
var NTI33555127 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555117 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555128 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33554456 = {size: 0,kind: 31,base: null,node: null,finalizer: null};
var NTI637540277 = {size: 0,kind: 31,base: null,node: null,finalizer: null};
var NTI637540756 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI33555124 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555131 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555133 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555086 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555168 = {size: 0, kind: 22, base: null, node: null, finalizer: null};
var NTI33554439 = {size: 0,kind: 28,base: null,node: null,finalizer: null};
var NTI33555167 = {size: 0, kind: 22, base: null, node: null, finalizer: null};
var NTI33555115 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555116 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555123 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555125 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33554440 = {size: 0,kind: 29,base: null,node: null,finalizer: null};
var NTI704643086 = {size: 0, kind: 24, base: null, node: null, finalizer: null};
NTI704643086.base = NTI33554440;
var NNI33555125 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555125.node = NNI33555125;
var NNI33555123 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555123.node = NNI33555123;
var NNI33555116 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555116.node = NNI33555116;
NTI33555167.base = NTI33555115;
NTI33555168.base = NTI33555115;
var NNI33555115 = {kind: 2, len: 5, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "parent", len: 0, typ: NTI33555167, name: "parent", sons: null},
{kind: 1, offset: "name", len: 0, typ: NTI33554440, name: "name", sons: null},
{kind: 1, offset: "message", len: 0, typ: NTI33554439, name: "msg", sons: null},
{kind: 1, offset: "trace", len: 0, typ: NTI33554439, name: "trace", sons: null},
{kind: 1, offset: "up", len: 0, typ: NTI33555168, name: "up", sons: null}]};
NTI33555115.node = NNI33555115;
var NNI33555086 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555086.node = NNI33555086;
NTI33555115.base = NTI33555086;
NTI33555116.base = NTI33555115;
NTI33555123.base = NTI33555116;
NTI33555125.base = NTI33555123;
var NNI33555133 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555133.node = NNI33555133;
NTI33555133.base = NTI33555116;
var NNI33555131 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555131.node = NNI33555131;
NTI33555131.base = NTI33555116;
var NNI33555124 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555124.node = NNI33555124;
NTI33555124.base = NTI33555123;
var NNI637540756 = {kind: 2, len: 2, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "a", len: 0, typ: NTI637540277, name: "a", sons: null},
{kind: 1, offset: "b", len: 0, typ: NTI33554456, name: "b", sons: null}]};
NTI637540756.node = NNI637540756;
var NNI33555128 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555128.node = NNI33555128;
var NNI33555117 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555117.node = NNI33555117;
NTI33555117.base = NTI33555115;
NTI33555128.base = NTI33555117;
var NNI33555127 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555127.node = NNI33555127;
NTI33555127.base = NTI33555116;
        var defaultArgs_704643082 = ["acp"];

function setConstr() {
        var result = {};
    for (var i = 0; i < arguments.length; ++i) {
      var x = arguments[i];
      if (typeof(x) == "object") {
        for (var j = x[0]; j <= x[1]; ++j) {
          result[j] = true;
        }
      } else {
        result[x] = true;
      }
    }
    return result;



}
var ConstSet1 = setConstr(17, 16, 4, 18, 27, 19, 23, 22, 21);

function nimCopy(dest_33557140, src_33557141, ti_33557142) {
  var result_33557151 = null;

    switch (ti_33557142.kind) {
    case 21:
    case 22:
    case 23:
    case 5:
      if (!(isFatPointer_33557131(ti_33557142))) {
      result_33557151 = src_33557141;
      }
      else {
        result_33557151 = [src_33557141[0], src_33557141[1]];
      }

      break;
    case 19:
            if (dest_33557140 === null || dest_33557140 === undefined) {
        dest_33557140 = {};
      }
      else {
        for (var key in dest_33557140) { delete dest_33557140[key]; }
      }
      for (var key in src_33557141) { dest_33557140[key] = src_33557141[key]; }
      result_33557151 = dest_33557140;

      break;
    case 18:
    case 17:
      if (!((ti_33557142.base == null))) {
      result_33557151 = nimCopy(dest_33557140, src_33557141, ti_33557142.base);
      }
      else {
      if ((ti_33557142.kind == 17)) {
      result_33557151 = (dest_33557140 === null || dest_33557140 === undefined) ? {m_type: ti_33557142} : dest_33557140;
      }
      else {
        result_33557151 = (dest_33557140 === null || dest_33557140 === undefined) ? {} : dest_33557140;
      }
      }
      nimCopyAux(result_33557151, src_33557141, ti_33557142.node);
      break;
    case 24:
    case 4:
    case 27:
    case 16:
            if (src_33557141 === null) {
        result_33557151 = null;
      }
      else {
        if (dest_33557140 === null || dest_33557140 === undefined || dest_33557140.length != src_33557141.length) {
          dest_33557140 = new Array(src_33557141.length);
        }
        result_33557151 = dest_33557140;
        for (var i = 0; i < src_33557141.length; ++i) {
          result_33557151[i] = nimCopy(result_33557151[i], src_33557141[i], ti_33557142.base);
        }
      }

      break;
    case 28:
            if (src_33557141 !== null) {
        result_33557151 = src_33557141.slice(0);
      }

      break;
    default:
      result_33557151 = src_33557141;
      break;
    }

  return result_33557151;

}

function toJSStr(s_33556807) {
                    var Temporary5;

  var result_33556808 = null;

    var res_33556842 = newSeq_33556825((s_33556807).length);
    var i_33556843 = 0;
    var j_33556844 = 0;
    Label1: do {
        Label2: while (true) {
        if (!(i_33556843 < (s_33556807).length)) break Label2;
          var c_33556845 = s_33556807[i_33556843];
          if ((c_33556845 < 128)) {
          res_33556842[j_33556844] = String.fromCharCode(c_33556845);
          i_33556843 += 1;
          }
          else {
            var helper_33556857 = newSeq_33556825(0);
            Label3: do {
                Label4: while (true) {
                if (!true) break Label4;
                  var code_33556858 = c_33556845.toString(16);
                  if ((((code_33556858) == null ? 0 : (code_33556858).length) == 1)) {
                  helper_33556857.push("%0");;
                  }
                  else {
                  helper_33556857.push("%");;
                  }

                  helper_33556857.push(code_33556858);;
                  i_33556843 += 1;
                    if (((s_33556807).length <= i_33556843)) Temporary5 = true; else {                      Temporary5 = (s_33556807[i_33556843] < 128);                    }                  if (Temporary5) {
                  break Label3;
                  }

                  c_33556845 = s_33556807[i_33556843];
                }
            } while (false);
++excHandler;
            try {
            res_33556842[j_33556844] = decodeURIComponent(helper_33556857.join(""));
--excHandler;
} catch (EXCEPTION) {
 var prevJSError = lastJSError;
 lastJSError = EXCEPTION;
 --excHandler;
            res_33556842[j_33556844] = helper_33556857.join("");
            lastJSError = prevJSError;
            } finally {
            }
          }

          j_33556844 += 1;
        }
    } while (false);
    if (res_33556842.length < j_33556844) { for (var i = res_33556842.length ; i < j_33556844 ; ++i) res_33556842.push(null); }
               else { res_33556842.length = j_33556844; };
    result_33556808 = res_33556842.join("");

  return result_33556808;

}

function rawEcho() {
          var buf = "";
      for (var i = 0; i < arguments.length; ++i) {
        buf += toJSStr(arguments[i]);
      }
      console.log(buf);



}

function mnewString(len_33556893) {
        return new Array(len_33556893);



}

function makeNimstrLit(c_33556801) {
      var result = [];
  for (var i = 0; i < c_33556801.length; ++i) {
    result[i] = c_33556801.charCodeAt(i);
  }
  return result;



}

function raiseException(e_33556667, ename_33556668) {
    e_33556667.name = ename_33556668;
    if ((excHandler == 0)) {
    unhandledException(e_33556667);
    }

    throw e_33556667;


}

function addInt(a_33556940, b_33556941) {
        var result = a_33556940 + b_33556941;
    checkOverflowInt(result);
    return result;



}
var ConstSet2 = setConstr(60, 62, 94);

function chckRange(i_33557189, a_33557190, b_33557191) {
      var Temporary1;

  var result_33557192 = 0;

  BeforeRet: do {
      if (!(a_33557190 <= i_33557189)) Temporary1 = false; else {        Temporary1 = (i_33557189 <= b_33557191);      }    if (Temporary1) {
    result_33557192 = i_33557189;
    break BeforeRet;
    }
    else {
    raiseRangeError();
    }

  } while (false);

  return result_33557192;

}

function chckIndx(i_33557184, a_33557185, b_33557186) {
      var Temporary1;

  var result_33557187 = 0;

  BeforeRet: do {
      if (!(a_33557185 <= i_33557184)) Temporary1 = false; else {        Temporary1 = (i_33557184 <= b_33557186);      }    if (Temporary1) {
    result_33557187 = i_33557184;
    break BeforeRet;
    }
    else {
    raiseIndexError(i_33557184, a_33557185, b_33557186);
    }

  } while (false);

  return result_33557187;

}
var ConstSet3 = setConstr(60, 62, 94);
var ConstSet4 = setConstr(45, 43, 32);
var ConstSet5 = setConstr([48, 57]);
var ConstSet6 = setConstr([48, 57]);
var ConstSet7 = setConstr([48, 57]);

function subInt(a_33556944, b_33556945) {
        var result = a_33556944 - b_33556945;
    checkOverflowInt(result);
    return result;



}

function divInt(a_33556952, b_33556953) {
        if (b_33556953 == 0) raiseDivByZero();
    if (b_33556953 == -1 && a_33556952 == 2147483647) raiseOverflow();
    return Math.trunc(a_33556952 / b_33556953);



}

function mulInt(a_33556948, b_33556949) {
        var result = a_33556948 * b_33556949;
    checkOverflowInt(result);
    return result;



}
var ConstSet8 = setConstr([65, 90], [97, 122]);

function addChar(x_33557255, c_33557256) {
    x_33557255.push(c_33557256);


}

function cstrToNimstr(c_33556804) {
      var ln = c_33556804.length;
  var result = new Array(ln);
  var r = 0;
  for (var i = 0; i < ln; ++i) {
    var ch = c_33556804.charCodeAt(i);

    if (ch < 128) {
      result[r] = ch;
    }
    else {
      if (ch < 2048) {
        result[r] = (ch >> 6) | 192;
      }
      else {
        if (ch < 55296 || ch >= 57344) {
          result[r] = (ch >> 12) | 224;
        }
        else {
            ++i;
            ch = 65536 + (((ch & 1023) << 10) | (c_33556804.charCodeAt(i) & 1023));
            result[r] = (ch >> 18) | 240;
            ++r;
            result[r] = ((ch >> 12) & 63) | 128;
        }
        ++r;
        result[r] = ((ch >> 6) & 63) | 128;
      }
      ++r;
      result[r] = (ch & 63) | 128;
    }
    ++r;
  }
  return result;



}
if (!Math.trunc) {
  Math.trunc = function(v) {
    v = +v;
    if (!isFinite(v)) return v;
    return (v - v % 1) || (v < 0 ? -0 : v === 0 ? v : 0);
  };
}

var objectID_889192610 = [0];
const __acpSdk = require('@agentclientprotocol/sdk');

function isFatPointer_33557131(ti_33557132) {
  var result_33557133 = false;

  BeforeRet: do {
    result_33557133 = !((ConstSet1[ti_33557132.base.kind] != undefined));
    break BeforeRet;
  } while (false);

  return result_33557133;

}

function nimCopyAux(dest_33557144, src_33557145, n_33557146) {
    switch (n_33557146.kind) {
    case 0:
      break;
    case 1:
            dest_33557144[n_33557146.offset] = nimCopy(dest_33557144[n_33557146.offset], src_33557145[n_33557146.offset], n_33557146.typ);

      break;
    case 2:
          for (var i = 0; i < n_33557146.sons.length; i++) {
      nimCopyAux(dest_33557144, src_33557145, n_33557146.sons[i]);
    }

      break;
    case 3:
            dest_33557144[n_33557146.offset] = nimCopy(dest_33557144[n_33557146.offset], src_33557145[n_33557146.offset], n_33557146.typ);
      for (var i = 0; i < n_33557146.sons.length; ++i) {
        nimCopyAux(dest_33557144, src_33557145, n_33557146.sons[i][1]);
      }

      break;
    }


}

function newSeq_33556825(len_33556827) {
  var result_33556828 = [];

    result_33556828 = new Array(len_33556827); for (var i = 0 ; i < len_33556827 ; ++i) { result_33556828[i] = null; }
  return result_33556828;

}

function add_33556419(x_33556420, x_33556420_Idx, y_33556421) {
          if (x_33556420[x_33556420_Idx] === null) { x_33556420[x_33556420_Idx] = []; }
      var off = x_33556420[x_33556420_Idx].length;
      x_33556420[x_33556420_Idx].length += y_33556421.length;
      for (var i = 0; i < y_33556421.length; ++i) {
        x_33556420[x_33556420_Idx][off+i] = y_33556421.charCodeAt(i);
      }



}

function unhandledException(e_33556663) {
    var buf_33556664 = [[]];
    if (!(((e_33556663.message).length == 0))) {
    buf_33556664[0].push.apply(buf_33556664[0], makeNimstrLit("Error: unhandled exception: "));;
    buf_33556664[0].push.apply(buf_33556664[0], e_33556663.message);;
    }
    else {
    buf_33556664[0].push.apply(buf_33556664[0], makeNimstrLit("Error: unhandled exception"));;
    }

    buf_33556664[0].push.apply(buf_33556664[0], makeNimstrLit(" ["));;
    add_33556419(buf_33556664, 0, e_33556663.name);
    buf_33556664[0].push.apply(buf_33556664[0], makeNimstrLit("]\x0A"));;
    var cbuf_33556665 = toJSStr(buf_33556664[0]);
      if (typeof(Error) !== "undefined") {
    throw new Error(cbuf_33556665);
  }
  else {
    throw cbuf_33556665;
  }



}

function raiseOverflow() {
    raiseException({message: makeNimstrLit("over- or underflow"), parent: null, m_type: NTI33555125, name: null, trace: [], up: null}, "OverflowDefect");


}

function checkOverflowInt(a_33556938) {
        if (a_33556938 > 2147483647 || a_33556938 < -2147483648) raiseOverflow();



}

function raiseRangeError() {
    raiseException({message: makeNimstrLit("value out of range"), parent: null, m_type: NTI33555133, name: null, trace: [], up: null}, "RangeDefect");


}

function addChars_251658415(result_251658417, result_251658417_Idx, x_251658418, start_251658419, n_251658420) {
    var old_251658421 = (result_251658417[result_251658417_Idx]).length;
    (result_251658417[result_251658417_Idx].length = chckRange(addInt(old_251658421, n_251658420), 0, 2147483647));
    Label1: do {
      var iHEX60gensym4_251658435 = 0;
      var i_704643361 = 0;
      Label2: do {
          Label3: while (true) {
          if (!(i_704643361 < n_251658420)) break Label3;
            iHEX60gensym4_251658435 = i_704643361;
            result_251658417[result_251658417_Idx][chckIndx(addInt(old_251658421, iHEX60gensym4_251658435), 0, (result_251658417[result_251658417_Idx]).length - 1)] = x_251658418.charCodeAt(chckIndx(addInt(start_251658419, iHEX60gensym4_251658435), 0, (x_251658418).length - 1));
            i_704643361 = addInt(i_704643361, 1);
          }
      } while (false);
    } while (false);


}

function addChars_251658411(result_251658413, result_251658413_Idx, x_251658414) {
    addChars_251658415(result_251658413, result_251658413_Idx, x_251658414, 0, ((x_251658414) == null ? 0 : (x_251658414).length));


}

function addInt_251658436(result_251658437, result_251658437_Idx, x_251658438) {
    addChars_251658411(result_251658437, result_251658437_Idx, ((x_251658438) + ""));


}

function addInt_251658457(result_251658458, result_251658458_Idx, x_251658459) {
    addInt_251658436(result_251658458, result_251658458_Idx, x_251658459);


}

function HEX24_335544323(x_335544324) {
  var result_335544325 = [[]];

    addInt_251658457(result_335544325, 0, x_335544324);

  return result_335544325[0];

}

function raiseIndexError(i_33556754, a_33556755, b_33556756) {
    var Temporary1;

    if ((b_33556756 < a_33556755)) {
    Temporary1 = makeNimstrLit("index out of bounds, the container is empty");
    }
    else {
    Temporary1 = (makeNimstrLit("index ") || []).concat(HEX24_335544323(i_33556754) || [],makeNimstrLit(" not in ") || [],HEX24_335544323(a_33556755) || [],makeNimstrLit(" .. ") || [],HEX24_335544323(b_33556756) || []);
    }

    raiseException({message: nimCopy(null, Temporary1, NTI33554439), parent: null, m_type: NTI33555131, name: null, trace: [], up: null}, "IndexDefect");


}

function raiseDivByZero() {
    raiseException({message: makeNimstrLit("division by zero"), parent: null, m_type: NTI33555124, name: null, trace: [], up: null}, "DivByZeroDefect");


}

function parseSaturatedNatural_469762364(s_469762365, b_469762366, b_469762366_Idx, start_469762367) {
      var Temporary1;
          var Temporary4;

  var result_469762368 = 0;

    var i_469762369 = start_469762367;
    if (((i_469762369 < (s_469762365).length) && (s_469762365[chckIndx(i_469762369, 0, (s_469762365).length - 1)] == 43))) {
    i_469762369 = addInt(i_469762369, 1);
    }

      if (!(i_469762369 < (s_469762365).length)) Temporary1 = false; else {        Temporary1 = (ConstSet6[s_469762365[chckIndx(i_469762369, 0, (s_469762365).length - 1)]] != undefined);      }    if (Temporary1) {
    b_469762366[b_469762366_Idx] = 0;
    Label2: do {
        Label3: while (true) {
          if (!(i_469762369 < (s_469762365).length)) Temporary4 = false; else {            Temporary4 = (ConstSet7[s_469762365[chckIndx(i_469762369, 0, (s_469762365).length - 1)]] != undefined);          }        if (!Temporary4) break Label3;
          var c_469762388 = subInt(s_469762365[chckIndx(i_469762369, 0, (s_469762365).length - 1)], 48);
          if ((b_469762366[b_469762366_Idx] <= divInt(subInt(2147483647, c_469762388), 10))) {
          b_469762366[b_469762366_Idx] = addInt(mulInt(b_469762366[b_469762366_Idx], 10), c_469762388);
          }
          else {
            b_469762366[b_469762366_Idx] = 2147483647;
          }

          i_469762369 = addInt(i_469762369, 1);
          Label5: do {
              Label6: while (true) {
              if (!((i_469762369 < (s_469762365).length) && (s_469762365[chckIndx(i_469762369, 0, (s_469762365).length - 1)] == 95))) break Label6;
                i_469762369 = addInt(i_469762369, 1);
              }
          } while (false);
        }
    } while (false);
    result_469762368 = subInt(i_469762369, start_469762367);
    }


  return result_469762368;

}

function HEX5BHEX5D_637537448(s_637537451, x_637537452) {
  var result_637537453 = [];

    var a_637537455 = x_637537452.a;
    var L_637537457 = addInt(subInt(subInt((s_637537451).length, x_637537452.b), a_637537455), 1);
    result_637537453 = nimCopy(null, mnewString(chckRange(L_637537457, 0, 2147483647)), NTI33554439);
    Label1: do {
      var i_637537462 = 0;
      var i_704643366 = 0;
      Label2: do {
          Label3: while (true) {
          if (!(i_704643366 < L_637537457)) break Label3;
            i_637537462 = i_704643366;
            result_637537453[chckIndx(i_637537462, 0, (result_637537453).length - 1)] = s_637537451[chckIndx(addInt(i_637537462, a_637537455), 0, (s_637537451).length - 1)];
            i_704643366 = addInt(i_704643366, 1);
          }
      } while (false);
    } while (false);

  return result_637537453;

}

function HEX2EHEX2E_637537421(a_637537424, b_637537425) {
  var result_637537428 = ({a: 0, b: 0});

    result_637537428 = nimCopy(result_637537428, {a: a_637537424, b: b_637537425}, NTI637540756);

  return result_637537428;

}

function parseStandardFormatSpecifier_973078586(s_973078587, start_973078588, ignoreUnknownSuffix_973078589) {
      var Temporary1;
      var Temporary2;
      var Temporary3;

  var result_973078590 = ({fill: 0, align: 0, sign: 0, alternateForm: false, padWithZero: false, minimumWidth: 0, precision: 0, typ: 0, endPosition: 0});

    result_973078590.fill = 32;
    result_973078590.align = 0;
    result_973078590.sign = 45;
    var i_973078592 = start_973078588;
    if (((addInt(i_973078592, 1) < (s_973078587).length) && (ConstSet2[s_973078587[chckIndx(addInt(i_973078592, 1), 0, (s_973078587).length - 1)]] != undefined))) {
    result_973078590.fill = s_973078587[chckIndx(i_973078592, 0, (s_973078587).length - 1)];
    result_973078590.align = s_973078587[chckIndx(addInt(i_973078592, 1), 0, (s_973078587).length - 1)];
    i_973078592 = addInt(i_973078592, 2);
    }
    else {
    if (((i_973078592 < (s_973078587).length) && (ConstSet3[s_973078587[chckIndx(i_973078592, 0, (s_973078587).length - 1)]] != undefined))) {
    result_973078590.align = s_973078587[chckIndx(i_973078592, 0, (s_973078587).length - 1)];
    i_973078592 = addInt(i_973078592, 1);
    }
    }
    if (((i_973078592 < (s_973078587).length) && (ConstSet4[s_973078587[chckIndx(i_973078592, 0, (s_973078587).length - 1)]] != undefined))) {
    result_973078590.sign = s_973078587[chckIndx(i_973078592, 0, (s_973078587).length - 1)];
    i_973078592 = addInt(i_973078592, 1);
    }

    if (((i_973078592 < (s_973078587).length) && (s_973078587[chckIndx(i_973078592, 0, (s_973078587).length - 1)] == 35))) {
    result_973078590.alternateForm = true;
    i_973078592 = addInt(i_973078592, 1);
    }

      if (!((addInt(i_973078592, 1) < (s_973078587).length) && (s_973078587[chckIndx(i_973078592, 0, (s_973078587).length - 1)] == 48))) Temporary1 = false; else {        Temporary1 = (ConstSet5[s_973078587[chckIndx(addInt(i_973078592, 1), 0, (s_973078587).length - 1)]] != undefined);      }    if (Temporary1) {
    result_973078590.padWithZero = true;
    i_973078592 = addInt(i_973078592, 1);
    }

    var parsedLength_973078629 = parseSaturatedNatural_469762364(s_973078587, result_973078590, "minimumWidth", i_973078592);
    i_973078592 = addInt(i_973078592, parsedLength_973078629);
    if (((i_973078592 < (s_973078587).length) && (s_973078587[chckIndx(i_973078592, 0, (s_973078587).length - 1)] == 46))) {
    i_973078592 = addInt(i_973078592, 1);
    var parsedLengthB_973078638 = parseSaturatedNatural_469762364(s_973078587, result_973078590, "precision", i_973078592);
    i_973078592 = addInt(i_973078592, parsedLengthB_973078638);
    }
    else {
      result_973078590.precision = -1;
    }

      if (!(i_973078592 < (s_973078587).length)) Temporary2 = false; else {        Temporary2 = (ConstSet8[s_973078587[chckIndx(i_973078592, 0, (s_973078587).length - 1)]] != undefined);      }    if (Temporary2) {
    result_973078590.typ = s_973078587[chckIndx(i_973078592, 0, (s_973078587).length - 1)];
    i_973078592 = addInt(i_973078592, 1);
    }

    result_973078590.endPosition = i_973078592;
      if (!!((i_973078592 == (s_973078587).length))) Temporary3 = false; else {        Temporary3 = !(ignoreUnknownSuffix_973078589);      }    if (Temporary3) {
    raiseException({message: (makeNimstrLit("invalid format string, cannot parse: ") || []).concat(HEX5BHEX5D_637537448(s_973078587, HEX2EHEX2E_637537421(i_973078592, 1)) || []), parent: null, m_type: NTI33555128, name: null, trace: [], up: null}, "ValueError");
    }


  return result_973078590;

}

function nucruneLen(s_637534218) {
  var result_637534219 = 0;

    result_637534219 = 0;
    var i_637534220 = 0;
    Label1: do {
        Label2: while (true) {
        if (!(i_637534220 < (s_637534218).length)) break Label2;
          if ((s_637534218[chckIndx(i_637534220, 0, (s_637534218).length - 1)] <= 127)) {
          i_637534220 = addInt(i_637534220, 1);
          }
          else {
          if (((s_637534218[chckIndx(i_637534220, 0, (s_637534218).length - 1)] >>> 5) == 6)) {
          i_637534220 = addInt(i_637534220, 2);
          }
          else {
          if (((s_637534218[chckIndx(i_637534220, 0, (s_637534218).length - 1)] >>> 4) == 14)) {
          i_637534220 = addInt(i_637534220, 3);
          }
          else {
          if (((s_637534218[chckIndx(i_637534220, 0, (s_637534218).length - 1)] >>> 3) == 30)) {
          i_637534220 = addInt(i_637534220, 4);
          }
          else {
          if (((s_637534218[chckIndx(i_637534220, 0, (s_637534218).length - 1)] >>> 2) == 62)) {
          i_637534220 = addInt(i_637534220, 5);
          }
          else {
          if (((s_637534218[chckIndx(i_637534220, 0, (s_637534218).length - 1)] >>> 1) == 126)) {
          i_637534220 = addInt(i_637534220, 6);
          }
          else {
          i_637534220 = addInt(i_637534220, 1);
          }
          }}}}}
          result_637534219 = addInt(result_637534219, 1);
        }
    } while (false);

  return result_637534219;

}

function runeLenAt_637534273(s_637534274, i_637534275) {
  var result_637534276 = 0;

    if ((s_637534274[chckIndx(i_637534275, 0, (s_637534274).length - 1)] <= 127)) {
    result_637534276 = 1;
    }
    else {
    if (((s_637534274[chckIndx(i_637534275, 0, (s_637534274).length - 1)] >>> 5) == 6)) {
    result_637534276 = 2;
    }
    else {
    if (((s_637534274[chckIndx(i_637534275, 0, (s_637534274).length - 1)] >>> 4) == 14)) {
    result_637534276 = 3;
    }
    else {
    if (((s_637534274[chckIndx(i_637534275, 0, (s_637534274).length - 1)] >>> 3) == 30)) {
    result_637534276 = 4;
    }
    else {
    if (((s_637534274[chckIndx(i_637534275, 0, (s_637534274).length - 1)] >>> 2) == 62)) {
    result_637534276 = 5;
    }
    else {
    if (((s_637534274[chckIndx(i_637534275, 0, (s_637534274).length - 1)] >>> 1) == 126)) {
    result_637534276 = 6;
    }
    else {
      result_637534276 = 1;
    }
    }}}}}

  return result_637534276;

}

function runeOffset_637534845(s_637534846, pos_637534847, start_637534848) {
  var result_637534849 = 0;

  BeforeRet: do {
    var i_637534850 = 0;
    var o_637534851 = start_637534848;
    Label1: do {
        Label2: while (true) {
        if (!(i_637534850 < pos_637534847)) break Label2;
          o_637534851 = addInt(o_637534851, chckRange(runeLenAt_637534273(s_637534846, o_637534851), 0, 2147483647));
          if (((s_637534846).length <= o_637534851)) {
          result_637534849 = -1;
          break BeforeRet;
          }

          i_637534850 = addInt(i_637534850, 1);
        }
    } while (false);
    result_637534849 = o_637534851;
    break BeforeRet;
  } while (false);

  return result_637534849;

}

function validateUtf8_637534485(s_637534486) {
            var Temporary3;
            var Temporary4;
            var Temporary5;
            var Temporary6;
            var Temporary7;
            var Temporary8;

  var result_637534487 = 0;

  BeforeRet: do {
    var i_637534488 = 0;
    var L_637534489 = (s_637534486).length;
    Label1: do {
        Label2: while (true) {
        if (!(i_637534488 < L_637534489)) break Label2;
          if ((s_637534486[chckIndx(i_637534488, 0, (s_637534486).length - 1)] <= 127)) {
          i_637534488 = addInt(i_637534488, 1);
          }
          else {
          if (((s_637534486[chckIndx(i_637534488, 0, (s_637534486).length - 1)] >>> 5) == 6)) {
          if ((s_637534486[chckIndx(i_637534488, 0, (s_637534486).length - 1)] < 194)) {
          result_637534487 = i_637534488;
          break BeforeRet;
          }

            if (!(addInt(i_637534488, 1) < L_637534489)) Temporary3 = false; else {              Temporary3 = ((s_637534486[chckIndx(addInt(i_637534488, 1), 0, (s_637534486).length - 1)] >>> 6) == 2);            }          if (Temporary3) {
          i_637534488 = addInt(i_637534488, 2);
          }
          else {
            result_637534487 = i_637534488;
            break BeforeRet;
          }

          }
          else {
          if (((s_637534486[chckIndx(i_637534488, 0, (s_637534486).length - 1)] >>> 4) == 14)) {
            if (!(addInt(i_637534488, 2) < L_637534489)) Temporary5 = false; else {              Temporary5 = ((s_637534486[chckIndx(addInt(i_637534488, 1), 0, (s_637534486).length - 1)] >>> 6) == 2);            }            if (!Temporary5) Temporary4 = false; else {              Temporary4 = ((s_637534486[chckIndx(addInt(i_637534488, 2), 0, (s_637534486).length - 1)] >>> 6) == 2);            }          if (Temporary4) {
          i_637534488 = addInt(i_637534488, 3);
          }
          else {
            result_637534487 = i_637534488;
            break BeforeRet;
          }

          }
          else {
          if (((s_637534486[chckIndx(i_637534488, 0, (s_637534486).length - 1)] >>> 3) == 30)) {
            if (!(addInt(i_637534488, 3) < L_637534489)) Temporary8 = false; else {              Temporary8 = ((s_637534486[chckIndx(addInt(i_637534488, 1), 0, (s_637534486).length - 1)] >>> 6) == 2);            }            if (!Temporary8) Temporary7 = false; else {              Temporary7 = ((s_637534486[chckIndx(addInt(i_637534488, 2), 0, (s_637534486).length - 1)] >>> 6) == 2);            }            if (!Temporary7) Temporary6 = false; else {              Temporary6 = ((s_637534486[chckIndx(addInt(i_637534488, 3), 0, (s_637534486).length - 1)] >>> 6) == 2);            }          if (Temporary6) {
          i_637534488 = addInt(i_637534488, 4);
          }
          else {
            result_637534487 = i_637534488;
            break BeforeRet;
          }

          }
          else {
            result_637534487 = i_637534488;
            break BeforeRet;
          }
          }}}
        }
    } while (false);
    result_637534487 = -1;
    break BeforeRet;
  } while (false);

  return result_637534487;

}

function nsuRepeatChar(c_452985848, count_452985849) {
  var result_452985850 = [];

    result_452985850 = nimCopy(null, mnewString(count_452985849), NTI33554439);
    Label1: do {
      var i_452985855 = 0;
      var colontmp__704643372 = 0;
      colontmp__704643372 = subInt(count_452985849, 1);
      var res_704643373 = 0;
      Label2: do {
          Label3: while (true) {
          if (!(res_704643373 <= colontmp__704643372)) break Label3;
            i_452985855 = res_704643373;
            result_452985850[chckIndx(i_452985855, 0, (result_452985850).length - 1)] = c_452985848;
            res_704643373 = addInt(res_704643373, 1);
          }
      } while (false);
    } while (false);

  return result_452985850;

}

function alignString_973078548(s_973078549, minimumWidth_973078550, align_973078551, fill_973078552) {
      var Temporary1;

  var result_973078553 = [];

    if ((minimumWidth_973078550 == 0)) {
    result_973078553 = nimCopy(null, s_973078549, NTI33554439);
    }
    else {
      if ((validateUtf8_637534485(s_973078549) == -1)) {
      Temporary1 = nucruneLen(s_973078549);
      }
      else {
      Temporary1 = (s_973078549).length;
      }

      var sRuneLen_973078554 = Temporary1;
      var toFill_973078555 = subInt(minimumWidth_973078550, sRuneLen_973078554);
      if ((toFill_973078555 <= 0)) {
      result_973078553 = nimCopy(null, s_973078549, NTI33554439);
      }
      else {
      if (((align_973078551 == 60) || (align_973078551 == 0))) {
      result_973078553 = nimCopy(null, (s_973078549 || []).concat(nsuRepeatChar(fill_973078552, chckRange(toFill_973078555, 0, 2147483647)) || []), NTI33554439);
      }
      else {
      if ((align_973078551 == 94)) {
      var half_973078556 = divInt(toFill_973078555, 2);
      result_973078553 = nimCopy(null, (nsuRepeatChar(fill_973078552, chckRange(half_973078556, 0, 2147483647)) || []).concat(s_973078549 || [],nsuRepeatChar(fill_973078552, chckRange(subInt(toFill_973078555, half_973078556), 0, 2147483647)) || []), NTI33554439);
      }
      else {
        result_973078553 = nimCopy(null, (nsuRepeatChar(fill_973078552, chckRange(toFill_973078555, 0, 2147483647)) || []).concat(s_973078549 || []), NTI33554439);
      }
      }}
    }


  return result_973078553;

}

function formatValue_973078690(result_973078691, result_973078691_Idx, value_973078692, specifier_973078693) {
    var spec_973078694 = parseStandardFormatSpecifier_973078586(specifier_973078693, 0, false);
    var value_973078695 = nimCopy(null, value_973078692, NTI33554439);
    switch (spec_973078694.typ) {
    case 115:
    case 0:
      break;
    default:
      raiseException({message: (makeNimstrLit("invalid type in format string for string, expected \'s\', but got ") || []).concat([spec_973078694.typ]), parent: null, m_type: NTI33555128, name: null, trace: [], up: null}, "ValueError");
      break;
    }
    if (!((spec_973078694.precision == -1))) {
    if ((spec_973078694.precision < nucruneLen(value_973078695))) {
    (value_973078695.length = chckRange(runeOffset_637534845(value_973078695, chckRange(spec_973078694.precision, 0, 2147483647), 0), 0, 2147483647));
    }

    }

    result_973078691[result_973078691_Idx].push.apply(result_973078691[result_973078691_Idx], alignString_973078548(value_973078695, spec_973078694.minimumWidth, spec_973078694.align, spec_973078694.fill));;


}

function addEscapedChar_33557860(s_33557861, s_33557861_Idx, c_33557862) {
    switch (c_33557862) {
    case 7:
      s_33557861[s_33557861_Idx].push.apply(s_33557861[s_33557861_Idx], makeNimstrLit("\\a"));;
      break;
    case 8:
      s_33557861[s_33557861_Idx].push.apply(s_33557861[s_33557861_Idx], makeNimstrLit("\\b"));;
      break;
    case 9:
      s_33557861[s_33557861_Idx].push.apply(s_33557861[s_33557861_Idx], makeNimstrLit("\\t"));;
      break;
    case 10:
      s_33557861[s_33557861_Idx].push.apply(s_33557861[s_33557861_Idx], makeNimstrLit("\\n"));;
      break;
    case 11:
      s_33557861[s_33557861_Idx].push.apply(s_33557861[s_33557861_Idx], makeNimstrLit("\\v"));;
      break;
    case 12:
      s_33557861[s_33557861_Idx].push.apply(s_33557861[s_33557861_Idx], makeNimstrLit("\\f"));;
      break;
    case 13:
      s_33557861[s_33557861_Idx].push.apply(s_33557861[s_33557861_Idx], makeNimstrLit("\\r"));;
      break;
    case 27:
      s_33557861[s_33557861_Idx].push.apply(s_33557861[s_33557861_Idx], makeNimstrLit("\\e"));;
      break;
    case 92:
      s_33557861[s_33557861_Idx].push.apply(s_33557861[s_33557861_Idx], makeNimstrLit("\\\\"));;
      break;
    case 39:
      s_33557861[s_33557861_Idx].push.apply(s_33557861[s_33557861_Idx], makeNimstrLit("\\\'"));;
      break;
    case 34:
      s_33557861[s_33557861_Idx].push.apply(s_33557861[s_33557861_Idx], makeNimstrLit("\\\""));;
      break;
    case 32:
    case 33:
    case 35:
    case 36:
    case 37:
    case 38:
    case 40:
    case 41:
    case 42:
    case 43:
    case 44:
    case 45:
    case 46:
    case 47:
    case 48:
    case 49:
    case 50:
    case 51:
    case 52:
    case 53:
    case 54:
    case 55:
    case 56:
    case 57:
    case 58:
    case 59:
    case 60:
    case 61:
    case 62:
    case 63:
    case 64:
    case 65:
    case 66:
    case 67:
    case 68:
    case 69:
    case 70:
    case 71:
    case 72:
    case 73:
    case 74:
    case 75:
    case 76:
    case 77:
    case 78:
    case 79:
    case 80:
    case 81:
    case 82:
    case 83:
    case 84:
    case 85:
    case 86:
    case 87:
    case 88:
    case 89:
    case 90:
    case 91:
    case 93:
    case 94:
    case 95:
    case 96:
    case 97:
    case 98:
    case 99:
    case 100:
    case 101:
    case 102:
    case 103:
    case 104:
    case 105:
    case 106:
    case 107:
    case 108:
    case 109:
    case 110:
    case 111:
    case 112:
    case 113:
    case 114:
    case 115:
    case 116:
    case 117:
    case 118:
    case 119:
    case 120:
    case 121:
    case 122:
    case 123:
    case 124:
    case 125:
    case 126:
      addChar(s_33557861[s_33557861_Idx], c_33557862);;
      break;
    default:
      s_33557861[s_33557861_Idx].push.apply(s_33557861[s_33557861_Idx], makeNimstrLit("\\x"));;
      var n_33557872 = c_33557862;
      addChar(s_33557861[s_33557861_Idx], makeNimstrLit("0123456789ABCDEF")[chckIndx(((n_33557872 & 240) >> 4), 0, (makeNimstrLit("0123456789ABCDEF")).length - 1)]);;
      addChar(s_33557861[s_33557861_Idx], makeNimstrLit("0123456789ABCDEF")[chckIndx((n_33557872 & 15), 0, (makeNimstrLit("0123456789ABCDEF")).length - 1)]);;
      break;
    }


}

function addQuoted_704643209(s_704643211, s_704643211_Idx, x_704643212) {
    s_704643211[s_704643211_Idx].push.apply(s_704643211[s_704643211_Idx], makeNimstrLit("\""));;
    Label1: do {
      var c_704643213 = 0;
      var iHEX60gensym6_704643382 = 0;
      var nHEX60gensym6_704643383 = ((x_704643212) == null ? 0 : (x_704643212).length);
      Label2: do {
          Label3: while (true) {
          if (!(iHEX60gensym6_704643382 < nHEX60gensym6_704643383)) break Label3;
            c_704643213 = x_704643212.charCodeAt(chckIndx(iHEX60gensym6_704643382, 0, (x_704643212).length - 1));
            if ((c_704643213 <= 127)) {
            addEscapedChar_33557860(s_704643211, s_704643211_Idx, c_704643213);
            }
            else {
            addChar(s_704643211[s_704643211_Idx], c_704643213);;
            }

            iHEX60gensym6_704643382 = addInt(iHEX60gensym6_704643382, 1);
          }
      } while (false);
    } while (false);
    s_704643211[s_704643211_Idx].push.apply(s_704643211[s_704643211_Idx], makeNimstrLit("\""));;


}

function sysFatal_218103842(message_218103845) {
    raiseException({message: nimCopy(null, message_218103845, NTI33554439), m_type: NTI33555127, parent: null, name: null, trace: [], up: null}, "AssertionDefect");


}

function raiseAssert_218103840(msg_218103841) {
    sysFatal_218103842(msg_218103841);


}

function failedAssertImpl_218103864(msg_218103865) {
    raiseAssert_218103840(msg_218103865);


}

function collectionToString_704643176(x_704643178, prefix_704643179, separator_704643180, suffix_704643181) {
  var result_704643182 = [[]];

    result_704643182[0] = nimCopy(null, prefix_704643179, NTI33554439);
    var firstElement_704643183 = true;
    Label1: do {
      var value_704643205 = null;
      var i_704643377 = 0;
      var L_704643378 = (x_704643178).length;
      Label2: do {
          Label3: while (true) {
          if (!(i_704643377 < L_704643378)) break Label3;
            value_704643205 = x_704643178[i_704643377];
            if (firstElement_704643183) {
            firstElement_704643183 = false;
            }
            else {
            result_704643182[0].push.apply(result_704643182[0], separator_704643180);;
            }

            if ((value_704643205 == null)) {
            result_704643182[0].push.apply(result_704643182[0], makeNimstrLit("nil"));;
            }
            else {
            addQuoted_704643209(result_704643182, 0, value_704643205);
            }

            i_704643377 += 1;
            if (!(((x_704643178).length == L_704643378))) {
            failedAssertImpl_218103864(makeNimstrLit("/nix/store/j65r5dnbk40vnpx9dz9w0s8aa1wcs3wg-nim-unwrapped-1.6.20/nim/lib/system/iterators.nim:240:11 `len(a) == L` the length of the seq changed while iterating over it"));
            }

          }
      } while (false);
    } while (false);
    result_704643182[0].push.apply(result_704643182[0], suffix_704643181);;

  return result_704643182[0];

}

function HEX24_704643172(x_704643174) {
  var result_704643175 = [];

    result_704643175 = nimCopy(null, collectionToString_704643176(x_704643174, makeNimstrLit("@["), makeNimstrLit(", "), makeNimstrLit("]")), NTI33554439);

  return result_704643175;

}

function formatValue_704643167(result_704643169, result_704643169_Idx, value_704643170, specifier_704643171) {
    formatValue_973078690(result_704643169, result_704643169_Idx, HEX24_704643172(value_704643170), specifier_704643171);


}
async function main_704643141() {
      var Temporary2;
      var Temporary4;

  var result_704643143 = null;

  BeforeRet: do {
    Label1: do {
      var envCmd_704643149 = (process.env["OPENCODE_ACP_CMD"] || '');
      if ((0 < ((envCmd_704643149) == null ? 0 : (envCmd_704643149).length))) {
      Temporary2 = envCmd_704643149;
      }
      else {
      Temporary2 = "opencode";
      }

    } while (false);
    var cmd_704643150 = Temporary2;
    Label3: do {
      var envArgs_704643151 = (process.env["OPENCODE_ACP_ARGS"] || '');
      if ((0 < ((envArgs_704643151) == null ? 0 : (envArgs_704643151).length))) {
      Temporary4 = ((val) => val ? val.split(' ').filter(Boolean) : [])(envArgs_704643151);
      }
      else {
      Temporary4 = defaultArgs_704643082;
      }

    } while (false);
    var args_704643152 = nimCopy(null, Temporary4, NTI704643086);
    Label5: do {
      var fmtRes_704643161 = [mnewString(0)];
      fmtRes_704643161[0].push.apply(fmtRes_704643161[0], makeNimstrLit("[demo] launching "));;
      add_33556419(fmtRes_704643161, 0, cmd_704643150);
      fmtRes_704643161[0].push.apply(fmtRes_704643161[0], makeNimstrLit(" "));;
      formatValue_704643167(fmtRes_704643161, 0, args_704643152, []);
    } while (false);
    rawEcho(fmtRes_704643161[0]);
    var procHandle_704643223 = require('child_process').spawn(cmd_704643150, args_704643152, { stdio: ['pipe', 'pipe', 'inherit'] });
    var stream_704643224 = __acpSdk.ndJsonStream(require('node:stream').Writable.toWeb(procHandle_704643223.stdin), require('node:stream').Readable.toWeb(procHandle_704643223.stdout));
    var clientConn_704643225 = (new __acpSdk.ClientSideConnection((function(v){ return function(){ return v; }; })((() => ({ requestPermission: async () => ({ outcome: { outcome: 'denied', optionId: '' } }), sessionUpdate: async (params) => { console.log('[client] sessionUpdate', params); }, writeTextFile: async () => ({}), readTextFile: async () => ({ content: '' }), createTerminal: async () => ({ id: 'term-1' }), extMethod: async () => ({}), extNotification: async () => {} }))()), stream_704643224));
    var initResp_704643230 = (await clientConn_704643225.initialize(({ protocolVersion: __acpSdk.PROTOCOL_VERSION, clientCapabilities: {} })));
    rawEcho(makeNimstrLit("[demo] initialized response raw="), cstrToNimstr(JSON.stringify(initResp_704643230)));
    var session1Resp_704643235 = (await clientConn_704643225.newSession(({ cwd: process.cwd(), mcpServers: [] })));
    var session2Resp_704643240 = (await clientConn_704643225.newSession(({ cwd: process.cwd(), mcpServers: [] })));
    var session1Id_704643241 = ((resp) => (resp && resp.sessionId) || 'session-1')(session1Resp_704643235);
    var session2Id_704643242 = ((resp) => (resp && resp.sessionId) || 'session-1')(session2Resp_704643240);
    Label6: do {
      var fmtRes_704643247 = [mnewString(0)];
      fmtRes_704643247[0].push.apply(fmtRes_704643247[0], makeNimstrLit("[demo] sessionId="));;
      add_33556419(fmtRes_704643247, 0, session1Id_704643241);
    } while (false);
    rawEcho(fmtRes_704643247[0]);
    Label7: do {
      var fmtRes_704643252 = [mnewString(0)];
      fmtRes_704643252[0].push.apply(fmtRes_704643252[0], makeNimstrLit("[demo] sessionId="));;
      add_33556419(fmtRes_704643252, 0, session2Id_704643242);
    } while (false);
    rawEcho(fmtRes_704643252[0]);
    var promptResp_704643257 = (await clientConn_704643225.prompt(({ sessionId: session1Id_704643241, prompt: [{ type: 'text', text: '"Hello, how are you"' }] })));
    Label8: do {
      var fmtRes_704643262 = mnewString(0);
      fmtRes_704643262.push.apply(fmtRes_704643262, makeNimstrLit("[demo] promptResp:"));;
    } while (false);
    rawEcho(fmtRes_704643262);
    console.log(promptResp_704643257);
    Label9: do {
      var fmtRes_704643267 = [mnewString(0)];
      fmtRes_704643267[0].push.apply(fmtRes_704643267[0], makeNimstrLit("[demo] stopReason="));;
      add_33556419(fmtRes_704643267, 0, ((resp) => (resp && resp.stopReason) || '')(promptResp_704643257));
    } while (false);
    rawEcho(fmtRes_704643267[0]);
    promptResp_704643257 = (await clientConn_704643225.prompt(({ sessionId: session2Id_704643242, prompt: [{ type: 'text', text: '"When was Osama bin laden born"' }] })));
    console.log(promptResp_704643257);
    Label10: do {
      var fmtRes_704643276 = [mnewString(0)];
      fmtRes_704643276[0].push.apply(fmtRes_704643276[0], makeNimstrLit("[demo] stopReason="));;
      add_33556419(fmtRes_704643276, 0, ((resp) => (resp && resp.stopReason) || '')(promptResp_704643257));
    } while (false);
    rawEcho(fmtRes_704643276[0]);
    promptResp_704643257 = (await clientConn_704643225.prompt(({ sessionId: session1Id_704643241, prompt: [{ type: 'text', text: '"When was barack obama born"' }] })));
    console.log(promptResp_704643257);
    Label11: do {
      var fmtRes_704643285 = [mnewString(0)];
      fmtRes_704643285[0].push.apply(fmtRes_704643285[0], makeNimstrLit("[demo] stopReason="));;
      add_33556419(fmtRes_704643285, 0, ((resp) => (resp && resp.stopReason) || '')(promptResp_704643257));
    } while (false);
    rawEcho(fmtRes_704643285[0]);
    promptResp_704643257 = (await clientConn_704643225.prompt(({ sessionId: session2Id_704643242, prompt: [{ type: 'text', text: '"Who won the 2022 world football cup"' }] })));
    console.log(promptResp_704643257);
    Label12: do {
      var fmtRes_704643294 = [mnewString(0)];
      fmtRes_704643294[0].push.apply(fmtRes_704643294[0], makeNimstrLit("[demo] stopReason="));;
      add_33556419(fmtRes_704643294, 0, ((resp) => (resp && resp.stopReason) || '')(promptResp_704643257));
    } while (false);
    rawEcho(fmtRes_704643294[0]);
    result_704643143 = undefined;
    break BeforeRet;
  } while (false);

  return result_704643143;

}
var _ = main_704643141();
