[package]
name = "ct"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.49", features = ["derive"] }
# bundled feature statically links libsql
rusqlite = { version = "0.37.0", features = ["bundled"] }
