## Entry resolution — Noir-Studio.md §1b.0's five forms and §1b.3's precedence.
##
## "A link must reconstruct not just *a project* but **the moment**." This
## module turns a URL into the decision of what to open, and it is pure: no
## fetch, no storage, no clock. Everything it needs about the world arrives as
## `LocalState`, so `test_bare_url_resolves_by_local_state` is a table of
## inputs and expected verdicts rather than a browser test.
##
## ## The origin is configuration and never a constant
##
## The hosted product's domain has moved once already (`cloud.codetracer.com`
## → `web.codetracer.com` → `ide.codetracer.com`), and each move found a
## constant somewhere. So no origin appears in this file at all. `EntryRequest`
## carries a *path* and a *fragment*, both of which the browser hands over
## already stripped of the origin, and `web_deployment.nim` — which does need
## to name hosts, because it generates the hosting configuration — takes the
## origin as a parameter with no default.
##
## ## Two rules that are enforced by *absence* rather than by a check
##
## - **Rule 1, no identifier is minted on arrival.** There is no id generator
##   here and `EntryResolution` carries no id field for the bare and `/new`
##   forms. A visit resolves to `erTemplate` or `erLocalWorkspace`, neither of
##   which names anything the server issued. The project's own store id is
##   generated by `web_platform.nim` at *creation*, and rule 1's second half —
##   "never enters the URL" — is enforced by there being no form in
##   `EntryForm` that carries one.
## - **Rule 2, the product defines no query parameters.** `parseEntry` reads
##   the query string only to *discard* it, and `declaredQueryParameters` is an
##   empty set that a test asserts over. That is deliberately an assertion on a
##   value rather than a grep: a grep for `?` in the source would pass while
##   somebody built a URL at run time.

type
  EntryForm* = enum
    ## §1b.0's table, plus the two ways a path can fail to be one of them.
    efBare
      ## `/noir`, `/noir/` — the language entry point.
    efNew
      ## `/noir/new`.
    efInline
      ## `#p=<encoded>`. The fragment never leaves the browser.
    efSnapshot
      ## `/s/<sourceBundleId>` — immutable, content-addressed.
    efProject
      ## `/p/<slug>-<projectId>` — a mutable pointer.
    efProjectList
      ## `/projects` — the one dynamic surface.
    efSession
      ## `/collab/join/<inviteToken>`.
    efUnknown

  EntryRequest* = object
    ## What the browser handed us, origin already removed.
    path*: string
    fragment*: string
      ## Without the leading `#`.
    query*: string
      ## Without the leading `?`. Present so the product can *prove* it ignores
      ## it — see `ignoredQuery` below.

  LocalState* = object
    ## What the store knows before any network call. §1b.0 rule 5 resolves the
    ## bare URL against this and nothing else.
    hasWorkspace*: bool
    mostRecentProjectId*: string
    cachedSnapshotIds*: seq[string]
      ## Snapshots this browser has seen. §1b.3 step 2: "If the pointer cannot
      ## be refreshed but a previously seen snapshot is cached, open that and
      ## say it may be stale."

  EntryVerdict* = enum
    evTemplate
      ## The bundled hello-world. §1b.0 rule 5's first row, and the fallback of
      ## last resort in §1b.3 step 6.
    evLocalWorkspace
    evSnapshot
    evProjectPointer
    evInlineProject
    evProjectList
    evCollabSession

  Position* = object
    ## §1b.0 rule 2's fragment keys. Each degrades independently — §1b.3 step 5.
    file*: string
    line*: int
    view*: string
    coordinate*: string
    test*: string
    session*: int

  EntryResolution* = object
    form*: EntryForm
    verdict*: EntryVerdict
    languageEntry*: string
      ## `noir` for `/noir`, empty for the language-neutral roots. Rule 0: "the
      ## language is an entry point, not a namespace", so this selects the
      ## initial template and is carried nowhere else.
    locator*: string
      ## The snapshot id, project id, inline payload or invite token.
    projectSlug*: string
      ## Decorative and ignored — §1b.1. Kept so a view can render it.
    position*: Position
    replacesHistoryEntry*: bool
      ## `/new` "instantiates a fresh template and **replaces** the history
      ## entry so Back does not re-trigger it" — rule 5's third row.
    opensAsNewProject*: bool
      ## Rule 4: "Opening a link never overwrites local work. A link opens as a
      ## **new project in the store**, always." True for every form that
      ## carries content, so no call site has to remember the rule.
    mayBeStale*: bool
    explanation*: string
      ## What was asked for and could not be found — §1b.3 step 6: "Never a
      ## blank editor, never an error page."

const declaredQueryParameters*: seq[string] = @[]
  ## Rule 2: "**The product defines no query parameters at all**; any present
  ## are ignored, so analytics or campaign parameters remain harmless."
  ##
  ## An empty list rather than an absent concept, so
  ## `test_no_user_content_reaches_an_access_log` can assert emptiness. A rule
  ## with no representation cannot be checked, and this one has to survive
  ## everyone who will later want "just one" parameter.

# ---------------------------------------------------------------------------
# Small string helpers, local for the same reason `paths.nim`'s are
# ---------------------------------------------------------------------------

proc splitOn(text: string; separator: char): seq[string] =
  var current = ""
  for c in text:
    if c == separator:
      result.add current
      current = ""
    else:
      current.add c
  result.add current

proc find(s: string; c: char): int =
  result = -1
  for i in 0 ..< s.len:
    if s[i] == c: return i

proc trimSlashes(path: string): string =
  var start = 0
  var stop = path.len - 1
  while start <= stop and path[start] == '/': inc start
  while stop >= start and path[stop] == '/': dec stop
  if start > stop: "" else: path[start .. stop]

proc parseNonNegative(text: string): int =
  if text.len == 0: return -1
  result = 0
  for c in text:
    if c < '0' or c > '9': return -1
    result = result * 10 + (ord(c) - ord('0'))

proc lastIndexOf(text: string; c: char): int =
  result = -1
  for i in countdown(text.len - 1, 0):
    if text[i] == c: return i

# ---------------------------------------------------------------------------
# The fragment
# ---------------------------------------------------------------------------

proc parsePosition*(fragment: string): Position =
  ## `f=main.nr:42&view=constraints&t=<coordinate>&test=x&session=2`.
  ##
  ## An unparseable value leaves its field at the default rather than failing
  ## the whole fragment — §1b.3 step 5: "each degrading independently — an
  ## unresolvable `t` opens the project at rest rather than failing the whole
  ## link."
  result.line = 0
  result.session = 0
  for pair in splitOn(fragment, '&'):
    let cut = pair.find('=')
    if cut <= 0: continue
    let key = pair[0 ..< cut]
    let value = pair[cut + 1 .. ^1]
    case key
    of "f":
      let colon = lastIndexOf(value, ':')
      if colon > 0:
        let parsed = parseNonNegative(value[colon + 1 .. ^1])
        if parsed > 0:
          result.file = value[0 ..< colon]
          result.line = parsed
        else:
          result.file = value
      else:
        result.file = value
    of "view": result.view = value
    of "t": result.coordinate = value
    of "test": result.test = value
    of "session":
      let parsed = parseNonNegative(value)
      if parsed >= 0: result.session = parsed
    else: discard

proc inlinePayload*(fragment: string): string =
  for pair in splitOn(fragment, '&'):
    if pair.len > 2 and pair[0 ..< 2] == "p=":
      return pair[2 .. ^1]
  ""

# ---------------------------------------------------------------------------
# The path
# ---------------------------------------------------------------------------

const knownLanguageEntries* = ["noir"]
  ## Rule 0. A second language is one more entry in this array and no change
  ## anywhere else — which is the property the rule exists to buy, and is
  ## checkable because the array is the only place a language appears.

proc isLanguageEntry(segment: string): bool =
  for entry in knownLanguageEntries:
    if entry == segment: return true
  false

proc classifyPath*(path: string): tuple[form: EntryForm, language, locator: string] =
  ## Path → form. Deliberately separate from `resolveEntry`, because §1b.4's
  ## "one rewrite rule ... per-prefix" is generated from the same
  ## classification, and two implementations of "which prefixes exist" is how
  ## a form reaches the SPA in the code and 404s at the CDN.
  let segments = splitOn(trimSlashes(path), '/')
  if segments.len == 0 or (segments.len == 1 and segments[0].len == 0):
    return (efBare, "", "")

  if isLanguageEntry(segments[0]):
    if segments.len == 1: return (efBare, segments[0], "")
    if segments.len == 2 and segments[1].len == 0:
      return (efBare, segments[0], "")
    if segments.len == 2 and segments[1] == "new":
      return (efNew, segments[0], "")
    return (efUnknown, segments[0], "")

  case segments[0]
  of "s":
    if segments.len >= 2 and segments[1].len > 0:
      return (efSnapshot, "", segments[1])
    return (efUnknown, "", "")
  of "p":
    if segments.len >= 2 and segments[1].len > 0:
      return (efProject, "", segments[1])
    return (efUnknown, "", "")
  of "projects":
    if segments.len == 1: return (efProjectList, "", "")
    return (efUnknown, "", "")
  of "collab":
    if segments.len == 3 and segments[1] == "join" and segments[2].len > 0:
      return (efSession, "", segments[2])
    return (efUnknown, "", "")
  else:
    return (efUnknown, "", "")

proc splitProjectLocator*(locator: string): tuple[slug, projectId: string] =
  ## §1b.1: "`/p/hello-world-3f9a2c` resolves on the suffix; the slug is for
  ## humans and is ignored." So the split is at the LAST hyphen, and a locator
  ## with no hyphen is all id and no slug — which is what a project whose name
  ## produced an empty slug looks like.
  let cut = lastIndexOf(locator, '-')
  if cut <= 0: return ("", locator)
  (locator[0 ..< cut], locator[cut + 1 .. ^1])

# ---------------------------------------------------------------------------
# The precedence order — §1b.3
# ---------------------------------------------------------------------------

proc resolveEntry*(request: EntryRequest; local: LocalState;
                   pointerReachable = true): EntryResolution =
  ## §1b.3's six steps, in order.
  ##
  ## `pointerReachable` is the caller's report of whether `current.json` could
  ## be fetched, not something this module discovers. That keeps the module
  ## pure and makes step 2's degradation — "a project link degrades to its last
  ## known state rather than to nothing" — a case in a table rather than a
  ## network test.
  let classified = classifyPath(request.path)
  result.form = classified.form
  result.languageEntry = classified.language
  result.position = parsePosition(request.fragment)

  case classified.form
  of efSnapshot:
    # Step 1. Content-addressed, so it either resolves exactly or is gone.
    result.verdict = evSnapshot
    result.locator = classified.locator
    result.opensAsNewProject = true
  of efProject:
    # Step 2.
    let split = splitProjectLocator(classified.locator)
    result.projectSlug = split.slug
    result.locator = split.projectId
    result.opensAsNewProject = true
    if pointerReachable:
      result.verdict = evProjectPointer
    elif split.projectId in local.cachedSnapshotIds:
      result.verdict = evSnapshot
      result.mayBeStale = true
      result.explanation =
        "this project's pointer could not be refreshed, so it has opened at " &
        "the last version this browser saw; it may be out of date"
    else:
      result.verdict = evTemplate
      result.explanation =
        "the project '" & classified.locator & "' could not be reached and " &
        "this browser has no copy of it, so a new project was opened instead"
    if result.position.coordinate.len > 0 and
       result.verdict == evProjectPointer:
      # §1b.3: "A project link carrying a replay coordinate is a contradiction
      # and is treated as one." Resolved against the current snapshot, and said
      # so, rather than dropped or honoured silently.
      result.explanation =
        "this link carries a position in a recorded run, but a project link " &
        "always opens the latest saved state; the position is applied to " &
        "that and may no longer fit"
  of efProjectList:
    result.verdict = evProjectList
  of efSession:
    result.verdict = evCollabSession
    result.locator = classified.locator
  of efNew:
    # Rule 5's third row.
    result.verdict = evTemplate
    result.replacesHistoryEntry = true
    result.opensAsNewProject = true
  of efBare, efInline, efUnknown:
    let payload = inlinePayload(request.fragment)
    if payload.len > 0:
      # Step 3.
      result.form = efInline
      result.verdict = evInlineProject
      result.locator = payload
      result.opensAsNewProject = true
    elif classified.form == efUnknown:
      # Step 6.
      result.verdict = evTemplate
      result.explanation =
        "'" & request.path & "' is not an address this product serves, so a " &
        "new project was opened instead"
    elif local.hasWorkspace:
      # Step 4, rule 5's second row.
      result.verdict = evLocalWorkspace
      result.locator = local.mostRecentProjectId
    else:
      # Rule 5's first row.
      result.verdict = evTemplate

proc writesOnArrival*(resolution: EntryResolution): bool =
  ## Rule 1, as a value. **Always false**, for every form, and the point of
  ## writing it as a proc rather than as a comment is that
  ## `test_arrival_writes_nothing_and_mints_no_address` can assert it over
  ## every form at once — including forms added later, which is when the rule
  ## will actually be at risk.
  ##
  ## Opening a *project* does write to the local store, but that is a
  ## consequence of the user having arrived, not of the arrival: it happens
  ## after `readyForEditing`, on our side of the network, and touches no
  ## storage of ours in §1b.0's sense.
  false

proc mintsServerIdentifier*(resolution: EntryResolution): bool =
  ## The other half of rule 1. Also always false, and also a value so it can be
  ## asserted over the whole enum.
  false

proc ignoredQuery*(request: EntryRequest): string =
  ## Whatever was in the query string. Returned so a test can show a URL
  ## carrying campaign parameters resolving identically to one without them —
  ## rule 2's "any present are ignored".
  request.query

# ---------------------------------------------------------------------------
# Building links — the other direction, and where rule 2 is easiest to break
# ---------------------------------------------------------------------------

proc encodePosition*(position: Position): string =
  ## Every piece of client state, in the fragment. There is no code path here
  ## that can put anything in a query string, which is what makes
  ## `test_no_user_content_reaches_an_access_log` a property of the builder
  ## rather than an observation about today's call sites.
  var parts: seq[string] = @[]
  if position.file.len > 0:
    if position.line > 0:
      parts.add "f=" & position.file & ":" & $position.line
    else:
      parts.add "f=" & position.file
  if position.view.len > 0: parts.add "view=" & position.view
  if position.coordinate.len > 0: parts.add "t=" & position.coordinate
  if position.test.len > 0: parts.add "test=" & position.test
  if position.session > 0: parts.add "session=" & $position.session
  for i, part in parts:
    if i > 0: result.add "&"
    result.add part

proc snapshotPath*(sourceBundleId: string): string =
  "/s/" & sourceBundleId

proc projectPath*(slug, projectId: string): string =
  if slug.len == 0: "/p/" & projectId else: "/p/" & slug & "-" & projectId

proc entryPath*(language: string): string =
  if language.len == 0: "/" else: "/" & language

proc newProjectPath*(language: string): string =
  if language.len == 0: "/new" else: "/" & language & "/new"
