# === mode
test: false

# === features

calltrace: true
flow:
  enabled: true
  # preload flow:
  #   you can have parallel, inline or multiline
  ui: parallel
trace: true
events: true
# history: experimental support
history: true
repl: true

trace-sharing:
  enabled: false
  # for now local setup
  base-url: http://localhost:55504/api/codetracer/v1
  download-api: /download
  upload-api: /upload
  delete-api: /delete
  get-upload-url-api: /get/upload/url

# === feature settings

# orthogonal to calltrace:
#   should we load args/return values for
#   callstack/calltrace
call-args: true

# enable or disable telemetry:
# if you enable it, it will collect colored logs
#   in your terminal (and comlog.txt) which are visible when you directly ./run.sh id
#   yaml logs in telemetry.log which can be converted back to colored logs with format.js
#   if you have a problem you can send back telemetry.log
#
# MAKE SURE THERE IS NO SENSITIVE INFO IN
# telemetry.log
telemetry: false

# debug message
debug: true

# layout:
#   currently we miss the changed layout: TODO
layout: default_layout

# theme:
#   you can also choose default_white or default_dark
theme: default_dark

# project open
default: ""

# what command to use by default for build and update while editing
default-build: ""

# === editor/shortcut settings
show-minimap: true

# # you can use KEY+OTHER
# # use PageUp, PageDown, CTRL, ALT, SHIFT
# # we'll fix it, but for now have to match to two api-s and to process it more
bindings:
  forward-continue: "F8 F2"
  reverse-continue: "SHIFT+F8"
  forward-next: "F10"
  reverse-next: "SHIFT+F10"
  forward-step: "F11"
  reverse-step: "SHIFT+F11"
  forward-step-out: "F12"
  reverse-step-out: "SHIFT+F12"
  stop: "SHIFT+F5"
  build: "CTRL+B"
  switch-tab-left: "CTRL+PageUp"
  switch-tab-right: "CTRL+PageDown"
  switch-tab-history: "CTRL+Tab"
  open-file: "CTRL+O"
  new-tab: "CTRL+N"
  reopen-tab: "CTRL+SHIFT+T"
  close-tab: "CTRL+W"
  go-up: "Up"
  go-down: "Down"
  page-up: "PageUp"
  page-down: "PageDown"
  switch-debug: "CTRL+D"
  switch-edit: "CTRL+E"
  file-search: "CTRL+P"
  command-search: "ALT+P"
  fixed-search: "CTRL+SHIFT+P"
  go-right: "Right"
  go-left: "Left"
  goto-start: "Home"
  goto-end: "End"
  a-enter: "Enter"
  a-escape: "Esc"
  find-or-filter: "CTRL+F"
  zoom-in: "CTRL+="
  zoom-out: "CTRL+-"
  example: "CTRL+L"
  a-menu: "CTRL+M"
  a-low-level-1: "ALT+1"
  switch-focused-loop-level-up: "CTRL+SHIFT+Q"
  switch-focused-loop-level-down: "CTRL+SHIFT+A"
  set-flow-type-to-multiline: "ALT+SHIFT+M"
  set-flow-type-to-parallel: "ALT+SHIFT+P"
  set-flow-type-to-inline: "ALT+SHIFT+I"
  find-in-files: "CTRL+SHIFT+F"
  find-symbol: "CTRL+T"
  a-restart: "CTRL+F4"

rr-backend:
  enabled: false
  path: ""
  ct-paths: ""
  debug-info-tool-path: ""

# TODO: Use this somehow
version: "0.1alpha"
