## trace_index_migration_test.nim
##
## Acceptance tests for the trace_index schema versions: version 1, where
## `recordings.lang` stores the `Lang` enum NAME rather than `ord(Lang)`, and
## version 2 (LRS-5), where it stores the FOUR-AXIS TOKEN rather than the
## name.  The database carries its version in SQLite's `PRAGMA user_version`
## and the two steps COMPOSE — a version-0 database runs 0 -> 1 -> 2 on one
## open.
##
## ## Why this is tested harder than a normal change
##
## `trace_index.db` is **user data**.  It is not regenerated by a rebuild and
## it has no fixture: a user's recording index is the only copy of the mapping
## from a recording-id to the program, folder and language that produced it.  A
## migration that half-applies leaves a database no release can read and no
## rebuild can repair.  So the properties below are not "the happy path works":
##
##   1. an **old** database is remapped correctly, value for value: all 40
##      schema-version-0 ordinals through the 0 -> 1 step, and all 41
##      schema-version-1 names through the 1 -> 2 step, each to a DISTINCT
##      target;
##   2. a **new** database is not touched;
##   3. running the migration **twice** is a no-op;
##   4. a **partial** application cannot be observed — the failure is
##      constructed at five separate points inside the transactions (three in
##      0 -> 1, two in 1 -> 2), and the rollback is proved rather than
##      asserted;
##   5. the **version gate** gates in both directions.
##
## ## Why `PRAGMA user_version`
##
## `isOldSchemaDb` in `src/common/trace_index.nim` detects a pre-M-REC-2
## database by probing for the retired `trace_values` table.  That is a
## *structural* probe, blind by construction to a change in the meaning of a
## value in a column that keeps its name and its type — exactly what happened
## to `lang`.  `user_version` is a slot in the SQLite file header: it needs no
## table, and it reads back 0 for every database nobody stamped, so every
## pre-existing user database is already correctly labelled "version 0" with no
## backfill.  Crucially it is also *transactional*; the all-or-nothing property
## rests on that, so "user_version rolls back with the transaction around it"
## is asserted here as a property of the SQLite in use rather than assumed.
##
## ## Why names, not renumbered ordinals
##
## The trigger for all of this was a then-pending move of `LangUnknown` to
## ordinal 0, which LRS-4 made on 2026-09-21 — against a column that by then
## held names, which is exactly why this migration came first.
## Storing the ordinal makes the *declaration order of a Nim enum* a persisted
## user-data format.  Storing the name ends that: afterwards the reorder
## touches no persisted data, and this is the last migration the column needs.
## It is a one-way door — a database written after it cannot be read by a
## codetracer from before it — and it is chosen anyway, because the old
## binary's failure on a name is a loud parse error in `loadTrace`, whereas its
## failure on a renumbered ordinal would be a silently mislabelled recording.
##
## No test here touches the developer's real
## `~/.local/share/codetracer/trace_index.db`.  Every database is built from
## scratch in a temp directory; the two subprocess scenarios run with `HOME`
## and `XDG_DATA_HOME` redirected into one.

import std/[algorithm, exitprocs, os, osproc, sequtils, streams, strtabs, strutils,
            tempfiles, unittest]

when NimMajor >= 2:
  import ../../db_connector/db_sqlite
else:
  import impure/db_sqlite

import ../../common/lang
import ../../common/types
import ../../common/trace_index
import json_serialization

# ---------------------------------------------------------------------------
# Loader bootstrap
# ---------------------------------------------------------------------------

const relaunchGuardEnv = "CT_TRACE_INDEX_MIGRATION_TEST_RELAUNCHED"

proc ensureSqliteLoadable() =
  ## `db_sqlite` reaches `libsqlite3.so` through `dlopen`.  In the Nix dev
  ## shell that library sits on `CT_LD_LIBRARY_PATH` rather than on the
  ## loader's path (see `nix/shells/ci-base.nix`), and glibc reads
  ## `LD_LIBRARY_PATH` once, at process start — so calling `putEnv` here would
  ## be too late.  Re-exec once, with the augmented environment and a guard so
  ## the child cannot loop.
  ##
  ## The alternative — letting the load fail and skipping — is exactly the
  ## "reports success while doing nothing" shape this suite is written against.
  ## If the library genuinely is not there, the dlopen failure aborts the
  ## process with `could not load: libsqlite3.so`, and the lane reports a
  ## failure rather than a pass.
  if getEnv(relaunchGuardEnv).len > 0:
    return
  let ctLd = getEnv("CT_LD_LIBRARY_PATH", getEnv("CODETRACER_LD_LIBRARY_PATH"))
  if ctLd.len == 0:
    return
  let existing = getEnv("LD_LIBRARY_PATH")
  if existing.len > 0 and ctLd in existing:
    return
  var env = newStringTable(modeCaseSensitive)
  for k, v in envPairs():
    env[k] = v
  env["LD_LIBRARY_PATH"] =
    if existing.len > 0: ctLd & ":" & existing else: ctLd
  env[relaunchGuardEnv] = "1"
  let p = startProcess(
    getAppFilename(), args = commandLineParams(), env = env,
    options = {poParentStreams})
  let code = p.waitForExit()
  p.close()
  quit(code)

ensureSqliteLoadable()

# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------

const LEGACY_RECORDINGS_DDL = """CREATE TABLE recordings (
      recording_id TEXT PRIMARY KEY,
      program TEXT NOT NULL,
      args TEXT,
      compile_command TEXT,
      env TEXT,
      workdir TEXT,
      output TEXT,
      source_folders TEXT,
      low_level_folder TEXT,
      output_folder TEXT,
      lang INTEGER NOT NULL,
      imported INTEGER DEFAULT 0,
      shell_id INTEGER,
      rr_pid INTEGER,
      exit_code INTEGER,
      calltrace INTEGER,
      calltrace_mode TEXT,
      recorded_at TEXT NOT NULL,
      remote_share_download_key TEXT,
      remote_share_control_id TEXT,
      remote_share_expire_time INTEGER DEFAULT -1
  );"""
  ## Frozen copy of the schema-version-0 DDL.  Deriving the *old* shape from
  ## the *current* source would make this test stop testing the migration the
  ## moment the current source changed.

const LEGACY_SIDE_TABLES = @[
  """CREATE TABLE record_pid_recording_map (
      pid INTEGER,
      recording_id TEXT NOT NULL,
      FOREIGN KEY (recording_id) REFERENCES recordings(recording_id)
  );""",
  """CREATE TABLE recent_folders (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      path TEXT UNIQUE,
      name TEXT,
      last_opened TEXT
  );""",
  """CREATE INDEX idx_recordings_program ON recordings(program);""",
  """CREATE INDEX idx_recordings_recorded_at ON recordings(recorded_at DESC);""",
]

var scratchRoot = ""

proc workDir(name: string): string =
  ## One directory per test case, under a single per-run temp root.
  if scratchRoot.len == 0:
    scratchRoot = createTempDir("ct-trace-index-migration-", "")
  result = scratchRoot / name
  createDir(result)

addExitProc(proc() =
  if scratchRoot.len > 0:
    try: removeDir(scratchRoot) except OSError: discard)

proc openFixture(path: string): DBConn =
  result = open(path, "", "", "")
  result.exec(sql"PRAGMA busy_timeout = 10000;")
  result.exec(sql"PRAGMA journal_mode=WAL;")

proc insertRecording(db: DBConn; id, langValue: string) =
  ## Every non-`lang` column gets a distinct non-default value so that a
  ## rebuild which dropped or reordered a column shows up as a row diff.
  db.exec(sql"""INSERT INTO recordings
      (recording_id, program, args, compile_command, env, workdir, output,
       source_folders, low_level_folder, output_folder, lang, imported,
       shell_id, rr_pid, exit_code, calltrace, calltrace_mode, recorded_at,
       remote_share_download_key, remote_share_control_id,
       remote_share_expire_time)
      VALUES (?, ?, 'a b', 'cc --x', 'E=1', '/wd', 'out', '/src', '/low', ?,
              ?, 0, -1, 7, 9, 1, 'FullRecord', '2026/08/25', 'dk', 'ci', -1)""",
    id, "/tmp/prog-" & id, "/tmp/trace-" & id, langValue)

proc makeLegacyDb(dir: string; rows: seq[(string, string)]): string =
  ## A schema-version-0 database: `lang INTEGER NOT NULL` holding ordinals,
  ## `PRAGMA user_version` never stamped (so it reads back 0).
  result = dir / "trace_index.db"
  let db = openFixture(result)
  defer: db.close()
  db.exec(sql(LEGACY_RECORDINGS_DDL))
  for statement in LEGACY_SIDE_TABLES:
    db.exec(sql(statement))
  for row in rows:
    insertRecording(db, row[0], row[1])

proc makeTextLangDb(dir: string; rows: seq[(string, string)];
                    stampedAt: int): string =
  ## A database with `lang` declared TEXT, stamped at `stampedAt`.  Two
  ## versions have that shape and differ only in what the cells say, so one
  ## builder serves both: version 1 holds `Lang` NAMES, version 2 holds
  ## four-axis TOKENS.
  result = dir / "trace_index.db"
  let db = openFixture(result)
  defer: db.close()
  db.exec(sql(LEGACY_RECORDINGS_DDL.replace(
    "lang INTEGER NOT NULL", "lang TEXT NOT NULL")))
  for statement in LEGACY_SIDE_TABLES:
    db.exec(sql(statement))
  for row in rows:
    insertRecording(db, row[0], row[1])
  db.exec(sql("PRAGMA user_version = " & $stampedAt))

proc makeCurrentDb(dir: string; rows: seq[(string, string)]): string =
  ## A database at the version this build writes: TEXT `lang`, four-axis
  ## tokens, stamped at `TRACE_INDEX_SCHEMA_VERSION`.
  makeTextLangDb(dir, rows, TRACE_INDEX_SCHEMA_VERSION)

proc makeV1Db(dir: string; rows: seq[(string, string)]): string =
  ## A schema-version-1 database: TEXT `lang` holding `Lang` NAMES, stamped
  ## at 1.  This is the input to the 1 -> 2 remap, and it is the shape the
  ## live developer database was in before LRS-5.
  makeTextLangDb(dir, rows, TRACE_INDEX_SCHEMA_VERSION_LANG_NAMES)

proc rowsSnapshot(path: string): string =
  ## Every row of `recordings`, every column, in a stable order.
  let db = open(path, "", "", "")
  defer: db.close()
  result = ""
  for row in db.getAllRows(sql"SELECT * FROM recordings ORDER BY recording_id"):
    result.add("row " & row.join(" | ") & "\n")

proc snapshot(path: string): string =
  ## A textual fingerprint of everything the migration can change: the schema
  ## version, the whole `sqlite_master` DDL, and every row.
  ##
  ## The *file bytes* are deliberately not compared.  The fixtures run in WAL
  ## mode, where a rolled-back transaction can still have appended to the
  ## `-wal` sidecar; a byte comparison would therefore report a difference
  ## with no observable effect, and the temptation would be to relax it.
  ## Comparing the logical content is the property that actually matters and
  ## is strictly harder to fake.
  let db = open(path, "", "", "")
  result = "user_version=" & db.getValue(sql"PRAGMA user_version") & "\n"
  for row in db.getAllRows(
      sql"SELECT type, name, sql FROM sqlite_master ORDER BY type, name"):
    result.add("schema " & row[0] & " " & row[1] & " :: " &
               row[2].splitWhitespace.join(" ") & "\n")
  db.close()
  result.add(rowsSnapshot(path))

proc langCell(path, id: string): string =
  let db = open(path, "", "", "")
  defer: db.close()
  db.getValue(sql"SELECT lang FROM recordings WHERE recording_id = ?", id)

proc declaredLangType(path: string): string =
  let db = open(path, "", "", "")
  defer: db.close()
  db.getValue(
    sql"SELECT type FROM pragma_table_info('recordings') WHERE name = 'lang'")

proc backupsBeside(path, bakSuffix: string): seq[string] =
  ## Every `*<bakSuffix>*` file next to `path`.  A second entry appearing is
  ## direct evidence that the step ran a second time, which is what
  ## "idempotent" forbids: `VACUUM INTO` refuses to overwrite, so a re-run has
  ## to write a *new* suffixed file.
  ##
  ## The suffix is a parameter since LRS-5: the two steps take one snapshot
  ## each, under different suffixes, so that restoring one gives back the
  ## original version-0 file and restoring the other a working version-1 one.
  result = @[]
  for kind, entry in walkDir(path.parentDir):
    if kind == pcFile and bakSuffix in entry.lastPathPart:
      result.add(entry.lastPathPart)

proc nameBackupsBeside(path: string): seq[string] =
  backupsBeside(path, langNameMigrationBakSuffix)

proc tokenBackupsBeside(path: string): seq[string] =
  backupsBeside(path, langTokenMigrationBakSuffix)

proc migrateAt(path: string) =
  let db = open(path, "", "", "")
  defer: db.close()
  db.exec(sql"PRAGMA busy_timeout = 10000;")
  migrateTraceIndex(db, path)

proc verifyAt(path: string): seq[string] =
  let db = open(path, "", "", "")
  defer: db.close()
  verifyTraceIndexSchema(db)

proc verifyTraceIndexSchemaAtPath(path: string; version: int): seq[string] =
  ## `verifyTraceIndexSchemaAt` against a path.  The version is a parameter
  ## since LRS-5, because the intermediate state the 0 -> 1 step leaves is a
  ## legitimate database that the latest version's verifier must reject and
  ## version 1's must accept.
  let db = open(path, "", "", "")
  defer: db.close()
  verifyTraceIndexSchemaAt(db, version)

proc readSchemaVersionAt(path: string): int =
  let db = open(path, "", "", "")
  defer: db.close()
  readSchemaVersion(db)

proc migrateExpectingError(path: string): string =
  ## Run the migration, require it to raise `TraceIndexMigrationError`, and
  ## return the message.  A migration that *succeeds* here fails the test
  ## rather than passing vacuously — a negative test that cannot fail is one
  ## more "reports success while doing nothing" defect, and this initiative
  ## has already found nine of those in the product.
  try:
    migrateAt(path)
  except TraceIndexMigrationError as e:
    return e.msg
  raise newException(ValueError,
    "migrateTraceIndex(" & path & ") returned normally; it was required to " &
    "raise TraceIndexMigrationError")

const LANG_V0_ENTRY_COUNT = 40
  ## Written as a literal on purpose.  `ord(high(Lang)) + 1` was 40 when this
  ## was written, is 39 since LRS-4, and would be whatever the live enum
  ## happens to be tomorrow — which is the very substitution these tests exist
  ## to forbid, and which LRS-4's renumber would have silently broken.

proc langOrdinalsAndNames(): seq[(string, string)] =
  ## The schema-version-0 ordinal → name pairs, taken from the **frozen**
  ## `langV0OrdinalNames` snapshot in `trace_index.nim` and never from `Lang`.
  ##
  ## This used to read `for lang in Lang: result.add(($ord(lang), $lang))`.
  ## That made the test agree with the production code by construction: both
  ## sides derived the mapping from today's enum, so a renumber moved both and
  ## the test could not see it.  With the snapshot on both sides the test is
  ## still tautological for an *unmutated* build — which is why milestone
  ## LRS-0's verification requires running it against a deliberately mutated
  ## `Lang`, where the two sides part company unless the freeze is real.
  result = @[]
  for entry in langV0OrdinalNames:
    result.add(($entry.ordinal, entry.name))

# ---------------------------------------------------------------------------
# Subprocess helper — the two end-to-end scenarios
# ---------------------------------------------------------------------------

let helperSource =
  currentSourcePath.parentDir.parentDir.parentDir /
  "common" / "trace_index_test_helper.nim"

var helperBin = ""
var helperCompileOutput = ""

proc compileHelper() =
  ## Compile `src/common/trace_index_test_helper.nim`.  A failure here is a
  ## hard test failure with the compiler output attached — never a skip.  The
  ## two scenarios it carries are the only coverage of the migration's
  ## *wiring*, and a silently-absent wiring test is worse than no test.
  let cache = getTempDir() / "ct-trace-index-migration-helper"
  removeDir(cache)
  createDir(cache)
  let bin = cache / "trace_index_test_helper"
  let cmd = "nim c --hints:off --warnings:off --mm:refc " &
            "--nimcache:" & quoteShell(cache) & " " &
            "--out:" & quoteShell(bin) & " " &
            quoteShell(helperSource)
  let (output, code) = execCmdEx(cmd)
  helperCompileOutput = output
  if code == 0:
    helperBin = bin

proc runHelper(scenario: string): tuple[ok: bool, outp, errp: string] =
  let home = createTempDir("ct-trace-index-migration-" & scenario & "-", "")
  defer: removeDir(home)
  var env = newStringTable(modeCaseSensitive)
  for k, v in envPairs():
    env[k] = v
  env["HOME"] = home
  env["XDG_DATA_HOME"] = home
  env["TMPDIR"] = home
  # The fault hook must not leak into a scenario that expects success.
  env.del(traceIndexMigrationFaultEnv)
  # In the Nix dev shell libsqlite3.so is on CT_LD_LIBRARY_PATH, not on the
  # loader's default path.
  let ctLd = getEnv("CT_LD_LIBRARY_PATH")
  if ctLd.len > 0:
    let existing = getEnv("LD_LIBRARY_PATH")
    env["LD_LIBRARY_PATH"] =
      if existing.len > 0: ctLd & ":" & existing else: ctLd
  let p = startProcess(helperBin, args = @[scenario], env = env, options = {})
  defer: p.close()
  let outp = p.outputStream.readAll()
  let errp = p.errorStream.readAll()
  (p.waitForExit() == 0, outp, errp)

compileHelper()

# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------

suite "trace_index schema version 1 — lang ordinal to name":

  test "TRACE_INDEX_SCHEMA_VERSION is 2 and an unstamped DB reads back as 0":
    ## The whole gate rests on SQLite reporting 0 for a database nobody
    ## stamped.  Were that untrue, every existing user database would need a
    ## backfill before the gate meant anything.
    ##
    ## Both version numbers are written as LITERALS.  The 0 -> 1 step must go
    ## on stamping 1 now that the latest version is 2, and a test that said
    ## `TRACE_INDEX_SCHEMA_VERSION_LANG_NAMES == TRACE_INDEX_SCHEMA_VERSION - 1`
    ## would agree with a step that stamped the wrong thing.
    check TRACE_INDEX_SCHEMA_VERSION == 2
    check TRACE_INDEX_SCHEMA_VERSION_LANG_NAMES == 1
    let path = makeLegacyDb(workDir("unstamped"), @[])
    let db = open(path, "", "", "")
    defer: db.close()
    check readSchemaVersion(db) == 0

  test "PRAGMA user_version rolls back with the transaction around it":
    ## Asserted as a property of the SQLite in use, not assumed.  The
    ## all-or-nothing guarantee is exactly this behaviour; if a future SQLite
    ## stopped journalling the header slot, the migration could commit data
    ## without its version (or the reverse) and this is the only test that
    ## would notice.
    let path = makeLegacyDb(workDir("uvtxn"), @[("id-a", "0")])
    let db = open(path, "", "", "")
    defer: db.close()
    db.exec(sql"BEGIN IMMEDIATE")
    db.exec(sql"PRAGMA user_version = 7")
    check readSchemaVersion(db) == 7
    db.exec(sql"ROLLBACK")
    check readSchemaVersion(db) == 0

  test "the frozen version-0 ordinal table is 40 entries, 0..39, no repeats":
    ## Milestone LRS-0.  `langV0OrdinalNames` is a snapshot of `Lang` as it
    ## stood when schema-version-0 rows were written; it decodes integers that
    ## an *older* build put on disk, so it must not be regenerated from the
    ## enum this build was compiled with.
    ##
    ## Every assertion below is written against literals and against the
    ## snapshot itself.  Not one mentions `Lang`, `ord`, `low` or `high` — so
    ## the whole test still holds, and still means the same thing, after `Lang`
    ## is renumbered, reordered or shrunk.  A test that said
    ## `langV0OrdinalNames.len == ord(high(Lang)) + 1` would agree with a
    ## renumbered enum by construction and would prove nothing.
    check langV0OrdinalNames.len == LANG_V0_ENTRY_COUNT

    var seenOrdinals: seq[int] = @[]
    var seenNames: seq[string] = @[]
    for entry in langV0OrdinalNames:
      check entry.ordinal notin seenOrdinals
      check entry.name notin seenNames
      check entry.name.startsWith("Lang")
      seenOrdinals.add(entry.ordinal)
      seenNames.add(entry.name)

    for expected in 0 ..< LANG_V0_ENTRY_COUNT:
      check expected in seenOrdinals

    check langV0MinOrdinal == 0
    check langV0MaxOrdinal == LANG_V0_ENTRY_COUNT - 1

    # Spot-check the three ordinals that carry the most rows in the live
    # developer database, and the sentinel the pending reorder moves.  These
    # are the values a renumber would silently re-point.
    check langV0NameForOrdinal(0) == "LangC"
    check langV0NameForOrdinal(14) == "LangRubyDb"
    check langV0NameForOrdinal(15) == "LangJavascript"
    check langV0NameForOrdinal(21) == "LangPythonDb"
    check langV0NameForOrdinal(22) == "LangUnknown"
    check langV0NameForOrdinal(37) == "LangElixir"
    check langV0NameForOrdinal(39) == "LangPhp"

    # Membership, not arithmetic, is what "a legal version-0 ordinal" means.
    check langV0NameForOrdinal(-1) == ""
    check langV0NameForOrdinal(LANG_V0_ENTRY_COUNT) == ""

  test "an old database is remapped: every Lang ordinal becomes its own token":
    ## The anti-drift check, COMPOSED.  All 40 version-0 ordinals, not a
    ## sample: the failure this migration exists to prevent is precisely a
    ## single variant landing on the wrong side of a renumber.  Since LRS-5
    ## one `migrateTraceIndex` call runs 0 -> 1 -> 2, so the observable result
    ## is the four-axis token, and the assertion walks BOTH frozen tables --
    ## ordinal to name, then name to token -- which is exactly the composition
    ## a version-0 user gets.
    let pairs = langOrdinalsAndNames()
    check pairs.len == LANG_V0_ENTRY_COUNT
    var rows: seq[(string, string)] = @[]
    for pair in pairs:
      rows.add(("id-" & pair[0], pair[0]))
    let path = makeLegacyDb(workDir("remap-all"), rows)

    migrateAt(path)

    check verifyAt(path).len == 0
    check declaredLangType(path) == "TEXT"
    var targets: seq[string] = @[]
    for pair in pairs:
      checkpoint("ordinal " & pair[0] & " (" & pair[1] & ")")
      let expected = langV2TokenForV1Name(pair[1])
      check expected.len > 0
      check langCell(path, "id-" & pair[0]) == expected
      check expected notin targets
      targets.add(expected)

  test "the remap preserves every other column verbatim":
    ## A rebuild that copied the columns in the wrong order, or dropped one,
    ## would still pass the `lang` assertions above.
    let path = makeLegacyDb(workDir("remap-cols"), @[("id-elixir", "37")])
    let before = rowsSnapshot(path)
    check "| 37 |" in before

    migrateAt(path)

    let after = rowsSnapshot(path)
    check "| ex-beam-unknown-instrumented |" in after
    check before.replace("| 37 |", "| LANG |") ==
          after.replace("| ex-beam-unknown-instrumented |", "| LANG |")

  test "the rebuilt table keeps both recordings indexes":
    ## `DROP TABLE recordings` takes its indexes with it; forgetting to
    ## recreate them would silently turn `ct list` into a table scan.
    let path = makeLegacyDb(workDir("indexes"), @[("id-elixir", "37")])
    migrateAt(path)
    let db = open(path, "", "", "")
    defer: db.close()
    let names = db.getAllRows(sql"""SELECT name FROM sqlite_master
        WHERE type='index' AND tbl_name='recordings' ORDER BY name""").mapIt(it[0])
    check "idx_recordings_program" in names
    check "idx_recordings_recorded_at" in names

  test "a database with pre-existing orphan foreign keys still migrates":
    ## **Regression.**  This is the defect the first real database caught.
    ##
    ## `record_pid_recording_map` declares
    ## `FOREIGN KEY (recording_id) REFERENCES recordings(recording_id)`, but
    ## SQLite only enforces foreign keys when `PRAGMA foreign_keys` is ON and
    ## nothing in `trace_index.nim` turns it on — so orphan pid rows are the
    ## normal state of a working database, not a fault.  The developer
    ## database read on 2026-08-25 held **685 orphans among 932 pid rows**
    ## before this migration existed.
    ##
    ## An earlier version of the migration used a whole-database
    ## `PRAGMA foreign_key_check` as its post-condition and aborted on those
    ## 685 — failing a migration that had in fact succeeded (every recording
    ## id preserved, every ordinal correctly mapped), and, because the check
    ## ran *after* COMMIT, printing "the local recording index was left
    ## unchanged" about a database it had just changed.
    ##
    ## Every fixture above is orphan-free, which is exactly why none of them
    ## caught it.
    let path = makeLegacyDb(
      workDir("fk-orphans"), @[("id-elixir", "37"), ("id-c", "0")])
    block:
      let db = open(path, "", "", "")
      defer: db.close()
      for i in 1 .. 5:
        db.exec(sql"""INSERT INTO record_pid_recording_map (pid, recording_id)
                      VALUES (?, ?)""", $i, "no-such-recording-" & $i)
      # A pid row that DOES resolve, so the fixture is not uniformly broken.
      db.exec(sql"""INSERT INTO record_pid_recording_map (pid, recording_id)
                    VALUES (?, ?)""", "99", "id-elixir")
      check db.getAllRows(sql"PRAGMA foreign_key_check").len == 5

    migrateAt(path)

    check verifyAt(path).len == 0
    check langCell(path, "id-elixir") == "ex-beam-unknown-instrumented"
    check langCell(path, "id-c") == "c-native-unknown-mcr"
    let db = open(path, "", "", "")
    defer: db.close()
    # The orphans are carried through untouched: the migration rewrites one
    # column of one table and is not a data-cleanup pass.
    check db.getAllRows(sql"PRAGMA foreign_key_check").len == 5
    check db.getValue(sql"SELECT count(*) FROM record_pid_recording_map") == "6"

  test "the rebuild preserves the recording count exactly":
    ## The assertion that replaced the absolute foreign-key check.  A rebuild
    ## that dropped or duplicated rows is the failure most worth catching, and
    ## `PRAGMA foreign_key_check` never looked for it.
    let dir = workDir("rowcount")
    var rows: seq[(string, string)] = @[]
    for i in 0 .. 9:
      rows.add(("id-" & $i, "37"))
    let path = makeLegacyDb(dir, rows)
    check rowsSnapshot(path).splitLines.len - 1 == 10

    migrateAt(path)

    let db = open(path, "", "", "")
    defer: db.close()
    check db.getValue(sql"SELECT count(*) FROM recordings") == "10"
    check db.getValue(sql"""SELECT count(*) FROM recordings
      WHERE lang = 'ex-beam-unknown-instrumented'""") == "10"

  test "a pre-migration snapshot is written beside the database":
    ## The transaction makes the migration atomic against a crash or an
    ## error.  It cannot protect against a migration that commits
    ## successfully while being logically wrong, which is why a snapshot is
    ## taken first.
    let path = makeLegacyDb(workDir("snapshot"), @[("id-elixir", "37")])
    migrateAt(path)

    let bak = path & langNameMigrationBakSuffix
    check fileExists(bak)
    block:
      let bakDb = open(bak, "", "", "")
      defer: bakDb.close()
      check bakDb.getValue(
        sql"SELECT lang FROM recordings WHERE recording_id = 'id-elixir'") == "37"
      check bakDb.getValue(sql"PRAGMA user_version") == "0"
    # The 1 -> 2 step takes its own, under its own suffix: restoring this one
    # gives back a working version-1 database rather than the version-0 file.
    let tokenBak = path & langTokenMigrationBakSuffix
    check fileExists(tokenBak)
    let tokenBakDb = open(tokenBak, "", "", "")
    defer: tokenBakDb.close()
    check tokenBakDb.getValue(
      sql"SELECT lang FROM recordings WHERE recording_id = 'id-elixir'") ==
      "LangElixir"
    check tokenBakDb.getValue(sql"PRAGMA user_version") ==
      $TRACE_INDEX_SCHEMA_VERSION_LANG_NAMES

  test "a new database is left untouched — no rebuild, no snapshot":
    let path = makeCurrentDb(
      workDir("already-new"), @[("id-elixir", "ex-beam-unknown-instrumented")])
    let before = snapshot(path)

    migrateAt(path)

    check snapshot(path) == before
    check nameBackupsBeside(path).len == 0
    check tokenBackupsBeside(path).len == 0
    check verifyAt(path).len == 0

  test "running the migration twice is a no-op":
    ## Idempotence, proved two ways: the logical content is identical after
    ## the second run, and no second snapshot was taken.
    let path = makeLegacyDb(
      workDir("twice"), @[("id-elixir", "37"), ("id-c", "0")])

    migrateAt(path)
    let afterFirst = snapshot(path)
    let nameBackupsAfterFirst = nameBackupsBeside(path)
    let tokenBackupsAfterFirst = tokenBackupsBeside(path)

    migrateAt(path)

    check snapshot(path) == afterFirst
    # One snapshot per STEP, not per run: a version-0 database runs both.
    check nameBackupsAfterFirst.len == 1
    check tokenBackupsAfterFirst.len == 1
    check nameBackupsBeside(path) == nameBackupsAfterFirst
    check tokenBackupsBeside(path) == tokenBackupsAfterFirst
    check verifyAt(path).len == 0

  test "the version gate detects an unmigrated DB and clears a migrated one":
    let path = makeLegacyDb(workDir("gate"), @[("id-elixir", "37")])

    let problemsBefore = verifyAt(path)
    check problemsBefore.len > 0
    check problemsBefore.anyIt("user_version is 0" in it)
    check problemsBefore.anyIt("declared INTEGER" in it)

    migrateAt(path)
    check verifyAt(path).len == 0

  test "a database from a NEWER schema version is refused, not guessed at":
    ## The downgrade direction.  Reading a future database with today's
    ## assumptions is the same class of mistake as reading an ordinal against
    ## the wrong enum order.
    let path = makeCurrentDb(
      workDir("newer"), @[("id-elixir", "ex-beam-unknown-instrumented")])
    block:
      let db = open(path, "", "", "")
      defer: db.close()
      db.exec(sql"PRAGMA user_version = 99")
    let before = snapshot(path)

    let msg = migrateExpectingError(path)
    check "schema version 99" in msg
    check "Refusing to open it" in msg
    check snapshot(path) == before

  test "an ordinal outside the Lang range is refused before anything is written":
    ## Pre-flight validation.  There is no name to map 999 to, and inventing
    ## one would mislabel the recording rather than lose it.
    let path = makeLegacyDb(
      workDir("outofrange"), @[("id-ok", "2"), ("id-bad", "999")])
    let before = snapshot(path)

    let msg = migrateExpectingError(path)
    check "not schema-version-0 Lang ordinals" in msg
    check "999" in msg
    check snapshot(path) == before
    check nameBackupsBeside(path).len == 0
    check tokenBackupsBeside(path).len == 0

  test "all out-of-range ordinals are reported, not just the first":
    ## The upper bound comes from the frozen snapshot, not from
    ## `ord(high(Lang))`: after the language/recording-type split the live
    ## enum's high is 35, and a test written against it would start demanding
    ## that the perfectly valid stored ordinals 36..39 be *rejected*.
    let justAboveV0 = $(langV0MaxOrdinal + 1)
    let path = makeLegacyDb(
      workDir("outofrange-many"),
      @[("id-a", "-1"), ("id-b", justAboveV0), ("id-c", "12345")])
    let msg = migrateExpectingError(path)
    check "-1" in msg
    check justAboveV0 in msg
    check "12345" in msg

  test "a half-migrated database (names at version 0) is refused":
    ## The state this design exists to make unreachable.  If it is reached
    ## anyway it must be named, not papered over: a second rebuild pass over
    ## names would map every one of them to NULL.
    let path = makeLegacyDb(workDir("half"), @[("id-elixir", "37")])
    block:
      let db = open(path, "", "", "")
      defer: db.close()
      db.exec(sql"UPDATE recordings SET lang = 'LangElixir'")
    let before = snapshot(path)

    let msg = migrateExpectingError(path)
    check "already holds enum name" in msg
    check "half-migrated" in msg
    check snapshot(path) == before

  test "a failure after the row rewrite rolls the whole migration back":
    let path = makeLegacyDb(
      workDir("fault-rewrite"), @[("id-elixir", "37"), ("id-c", "0")])
    let before = snapshot(path)

    putEnv(traceIndexMigrationFaultEnv, "after-table-rewrite")
    let msg = migrateExpectingError(path)
    delEnv(traceIndexMigrationFaultEnv)

    check "injected fault at fault-point 'after-table-rewrite'" in msg
    check snapshot(path) == before
    check declaredLangType(path) == "INTEGER"

  test "a failure after the table SWAP rolls the whole migration back":
    ## The strongest of the three: at this fault point the original table has
    ## already been dropped and the rebuilt one renamed over it, so
    ## mid-transaction the database *is* migrated.  All of it must still come
    ## back — rows, declared type, indexes and version.
    let path = makeLegacyDb(
      workDir("fault-swap"), @[("id-elixir", "37"), ("id-c", "0")])
    let before = snapshot(path)

    putEnv(traceIndexMigrationFaultEnv, "after-table-swap")
    let msg = migrateExpectingError(path)
    delEnv(traceIndexMigrationFaultEnv)

    check "injected fault at fault-point 'after-table-swap'" in msg
    check snapshot(path) == before
    check declaredLangType(path) == "INTEGER"
    check langCell(path, "id-elixir") == "37"
    let db = open(path, "", "", "")
    defer: db.close()
    check db.getAllRows(sql"""SELECT name FROM sqlite_master
        WHERE type='table' AND name LIKE 'recordings_schema_migration%'""").len == 0

  test "a failure after the version stamp rolls the version back too":
    ## Data and version are stamped in the same transaction; neither may
    ## outlive the other.
    let path = makeLegacyDb(workDir("fault-stamp"), @[("id-elixir", "37")])
    let before = snapshot(path)

    putEnv(traceIndexMigrationFaultEnv, "after-version-stamp")
    let msg = migrateExpectingError(path)
    delEnv(traceIndexMigrationFaultEnv)

    check "injected fault at fault-point 'after-version-stamp'" in msg
    check snapshot(path) == before
    check verifyAt(path).anyIt("user_version is 0" in it)

  test "a rolled-back database still migrates cleanly on the next attempt":
    ## "Unmigrated" has to be a resting state you can leave, not a corner you
    ## are stuck in.
    let path = makeLegacyDb(workDir("fault-retry"), @[("id-elixir", "37")])

    putEnv(traceIndexMigrationFaultEnv, "after-table-swap")
    discard migrateExpectingError(path)
    delEnv(traceIndexMigrationFaultEnv)

    migrateAt(path)
    check verifyAt(path).len == 0
    check langCell(path, "id-elixir") == "ex-beam-unknown-instrumented"

  test "langFromColumnValue round-trips every Lang and rejects a bare ordinal":
    for lang in Lang:
      check langFromColumnValue(langToColumnValue(lang)) == lang
      let column = decodeLangColumn(langToColumnValue(lang))
      check column.lang == lang
      check column.retiredName == ""
    for raw in ["37", "0", "", "Elixir", "LangNotAThing"]:
      var raised = false
      try:
        discard langFromColumnValue(raw)
      except TraceIndexSchemaError as e:
        raised = true
        # The diagnostic moved with the column format (LRS-5): it now names
        # BOTH accepted formats, because both are read.  What is asserted is
        # unchanged -- a bare ordinal, an empty cell and a foreign string are
        # refused loudly rather than guessed at.
        check "neither a four-axis token nor a Lang enum name" in e.msg
      check raised

  test "the two names LRS-4 retired decode as retired through the PRODUCTION list":
    ## `LangPython` (v0 ordinal 12) and `LangRuby` (13) were deleted from
    ## `Lang` on 2026-09-21.  Both are in the frozen `langV0OrdinalNames`
    ## snapshot and therefore in `langNamesEverPersisted` with no edit -- the
    ## append-only list already covered them, which is what it was for.  With
    ## the DEFAULT `everPersisted` (production callers take it) each decodes
    ## to the sentinel with the name, never raises, and is not a live member.
    for name in ["LangPython", "LangRuby"]:
      checkpoint("retired name: " & name)
      check name in langNamesEverPersisted
      var raised = false
      var column: LangColumn
      try:
        column = decodeLangColumn(name)
      except TraceIndexSchemaError:
        raised = true
      check(not raised)
      check column.lang == LangUnknown
      check column.retiredName == name
      check langFromColumnValue(name) == LangUnknown
      var live = false
      for lang in Lang:
        if $lang == name: live = true
      check(not live)
    # The frozen v0 ordinals still carry the retired names, so a version-0
    # database with rows at 12 and 13 remaps to those names and then decodes
    # as retired -- the two policies compose.
    check langV0NameForOrdinal(12) == "LangPython"
    check langV0NameForOrdinal(13) == "LangRuby"
    check decodeLangColumn(langV0NameForOrdinal(12)).retiredName == "LangPython"
    # `LangRustWasm` / `LangCppWasm` are NOT retired (kept until LRS-5), so
    # their v0 names still decode to themselves.
    check decodeLangColumn("LangRustWasm") == LangColumn(lang: LangRustWasm, retiredName: "")
    check decodeLangColumn("LangCppWasm") == LangColumn(lang: LangCppWasm, retiredName: "")

  test "a RETIRED name decodes to LangUnknown with the name preserved, and never raises":
    ## The retired-name policy (`src/common/trace_index.nim`, LRS-2B): a cell
    ## holding the name of a member a later build removed must not turn every
    ## recording made before the removal into a hard failure at open.  This
    ## case predates the first real retirement (LRS-4, the case above) and
    ## drives the path through the `everPersisted` parameter with a name that
    ## is in the historical list but not in the live enum — which is exactly
    ## what a retired name is; kept because it pins the mechanism
    ## independently of which members happen to be retired today.
    const Retired = "LangRetiredForThisTest"
    let historical = langNamesEverPersisted & @[Retired]
    var raised = false
    var column: LangColumn
    try:
      column = decodeLangColumn(Retired, historical)
    except TraceIndexSchemaError:
      raised = true
    check(not raised)
    check column.lang == LangUnknown
    check column.retiredName == Retired
    # The bare-`Lang` view is the sentinel, never a neighbour.
    # The same string WITHOUT the historical entry is still foreign and still
    # raises: the policy is scoped to names that were members, so it cannot
    # silently admit corruption or an unmigrated integer column.
    raised = false
    try:
      discard decodeLangColumn(Retired)
    except TraceIndexSchemaError as e:
      raised = true
      check "neither a four-axis token nor a Lang enum name" in e.msg
    check raised
    raised = false
    try:
      discard decodeLangColumn("37", historical)
    except TraceIndexSchemaError:
      raised = true
    check raised
    # A LIVE name is never reported as retired, even if it is also historical
    # (every live name is).
    let live = decodeLangColumn("LangElixir", historical)
    check live.lang == LangElixir
    check live.retiredName == ""

  test "every name ever persisted decodes without raising, today and after a retirement":
    ## Every historical name that is still live decodes to itself, and the
    ## two LRS-4 retired decode as retired; the assertion that matters is the
    ## first one — no raise — because that is what a member removal must not
    ## change.  (Until LRS-4 every historical name was live.)
    var retired: seq[string] = @[]
    for name in langNamesEverPersisted:
      var raised = false
      var column: LangColumn
      try:
        column = decodeLangColumn(name)
      except TraceIndexSchemaError:
        raised = true
      checkpoint("historical name: " & name)
      check(not raised)
      if column.retiredName.len == 0:
        check $column.lang == name
      else:
        check column.lang == LangUnknown
        check column.retiredName == name
        retired.add(name)
    retired.sort()
    check retired == @["LangPython", "LangRuby"]

  test "every live Lang name has been recorded as persisted (the list is append-only)":
    ## A member added to `Lang` must be appended to `langNamesAddedSinceV0`
    ## so that, if it is ever removed again, its name is recognised as retired
    ## rather than foreign.  This is the assertion that forces the append.
    ## (A member REMOVED from `Lang` is never removed from the list -- LRS-4's
    ## two are still in it, asserted above -- so the list is a superset of
    ## the enum, never equal to it.)
    for lang in Lang:
      checkpoint("live member: " & $lang)
      check ($lang) in langNamesEverPersisted
    var liveCount = 0
    for _ in Lang: inc liveCount
    check langNamesEverPersisted.len == liveCount + 2   # + LangPython, LangRuby
    # And the frozen list is a superset built from two frozen literals, not
    # from `Lang`: it has every version-0 name plus the additions, no repeats.
    check langNamesEverPersisted.len == LANG_V0_ENTRY_COUNT + langNamesAddedSinceV0.len
    var seen: seq[string] = @[]
    for name in langNamesEverPersisted:
      check name notin seen
      seen.add(name)

  test "ct trace-metadata encodes lang as its NAME, and a retired row as the sentinel plus the name":
    ## `trace_index.nim` opts `Lang` into text (`serializesAsTextInJson`), so
    ## the JSON the Electron main process receives from `ct trace-metadata`
    ## says `"lang":"LangPythonDb"`, which `decodeLangName` on the JS side
    ## turns back into the member.  It used to say `"lang":21` (the ordinal),
    ## unnoticed because the renderer's old map only ran for a string.  The
    ## rule is pinned from the same module `ct trace-metadata` imports it
    ## from; the first draft put it in `metadata.nim` and THIS test showed it
    ## ignored.  The placement is load-bearing, and the reason is narrower
    ## than "the first module to encode a `Trace` wins": measured at review,
    ## a rule declared in ANY module downstream of `trace_index.nim` is
    ## ignored -- including the first such module and including the very
    ## module doing the `Json.encode`.  See the comment beside the rule.
    let live = Json.encode(Trace(lang: LangPythonDb, recordingId: "r1"))
    check "\"lang\":\"LangPythonDb\"" in live
    check "\"lang\":20" notin live
    let retired = Json.encode(Trace(lang: LangUnknown, langRetiredName: "LangRuby",
                                    recordingId: "r2"))
    check "\"lang\":\"LangUnknown\"" in retired
    check "\"langRetiredName\":\"LangRuby\"" in retired
    for lang in Lang:
      check ("\"lang\":\"" & $lang & "\"") in Json.encode(Trace(lang: lang))

  test "a retired row keeps its label in a listing":
    ## `langLabel` is what `ct list` and the upload listing print.  A retired
    ## row shows the name it was recorded under, a live row its live name.
    var t = Trace(lang: LangElixir)
    check t.langLabel == "LangElixir"
    t = Trace(lang: LangUnknown, langRetiredName: "LangRetiredForThisTest")
    check t.langLabel == "LangRetiredForThisTest"
    t = Trace(lang: LangUnknown)
    check t.langLabel == "LangUnknown"

  test "verifyTraceIndexSchema names a surviving migration scratch table":
    ## The one shape a rollback failure would leave behind.  `verify` is what
    ## a diagnostic would call, so it has to see it.
    let path = makeCurrentDb(
      workDir("scratch-survivor"), @[("id-elixir", "ex-beam-unknown-instrumented")])
    block:
      let db = open(path, "", "", "")
      defer: db.close()
      db.exec(sql"CREATE TABLE recordings_schema_migration_scratch (x INTEGER)")
    check verifyAt(path).anyIt("half-migrated" in it)

  # -- end to end, through the real ensureDB ---------------------------------

  test "trace_index_test_helper compiles":
    ## Hard failure with the compiler output attached, never a skip.
    if helperBin.len == 0:
      echo helperCompileOutput
    check helperBin.len > 0

  test "e2e: recordTrace writes a language NAME and find reads it back":
    require helperBin.len > 0
    let (ok, outp, errp) = runHelper("lang-name-roundtrip")
    if not ok or "PASS" notin outp:
      echo "stdout: ", outp
      echo "stderr: ", errp
    check ok
    check "PASS" in outp

  test "e2e: a trace_index row holding a RETIRED name loads through find/all/findRecentTraces":
    ## The fixture the retired-name policy was written for, through the
    ## production loader rather than the decoder alone: rows whose `lang`
    ## cell says `LangRuby` / `LangPython` -- names LRS-4 deleted from the
    ## enum -- beside a live row, in a real database opened by `ensureDB`.
    require helperBin.len > 0
    let (ok, outp, errp) = runHelper("retired-lang-rows")
    if not ok or "PASS" notin outp:
      echo "stdout: ", outp
      echo "stderr: ", errp
    check ok
    check "PASS" in outp

  test "e2e: ensureDB migrates a legacy database on open":
    ## Proves the migration is actually called on the production path.  A
    ## correct migration nobody invokes is worth nothing.
    require helperBin.len > 0
    let (ok, outp, errp) = runHelper("migrate-legacy-db")
    if not ok or "PASS" notin outp:
      echo "stdout: ", outp
      echo "stderr: ", errp
    check ok
    check "PASS" in outp
    # Both steps announce themselves: the composition is visible to a user,
    # not just to the version gate.
    check "migrated to schema version 1" in errp
    check "migrated to schema version 2" in errp

# ---------------------------------------------------------------------------
# Schema version 2 — the Lang NAME becomes the four-axis TOKEN (LRS-5)
# ---------------------------------------------------------------------------
#
# Everything above is version 1 and is unchanged in intent.  What follows is
# the second step, held to the same bar: all 41 names, each to a DISTINCT
# target, from a FROZEN literal, with the rollback proved at every fault point
# rather than asserted, and with the foreign-key claim stated as a DELTA.

const LANG_V1_NAME_COUNT = 41
  ## Written as a literal on purpose, and it is **41, not the 40** the design
  ## document and the milestone entry both say.  Corrected here under
  ## milestone rule 7: those two were counting the PRE-SPLIT `Lang`, and
  ## `LangGdScript` was appended to the enum while schema version 1 was the
  ## live column format — so version 1 could, and can, write it.  The set is
  ## therefore the 40 frozen version-0 names plus `langNamesAddedSinceV0`,
  ## which is what `langNamesEverPersisted` already is.
  ##
  ## `ord(high(Lang)) + 1` is 39 and is NOT this number: two of the 41
  ## (`LangPython`, `LangRuby`) are names LRS-4 deleted from the enum, which
  ## is exactly why rule 3 applies here with full force.

proc v1NamesAndTokens(): seq[(string, string)] =
  ## The frozen schema-version-1 name -> schema-version-2 token pairs, taken
  ## from the **frozen** `langV1NameToV2Token` literal in `trace_index.nim`
  ## and never from `Lang`.  A generator over the live enum could not produce
  ## two of these rows at all.
  result = @[]
  for entry in langV1NameToV2Token:
    result.add((entry.name, entry.token))

suite "trace_index schema version 2 — lang name to four-axis token":

  test "the frozen 1 -> 2 table is 41 entries, no repeated name, no repeated target":
    ## Obligation 6 of the design's §5.4, the lossless-history obligation:
    ## every legacy value has a DISTINCT target, so the mapping is injective
    ## and no two recordings that were distinguishable become the same.
    ##
    ## Not one assertion below mentions `Lang`, `ord`, `low` or `high`, so the
    ## whole test still holds and still means the same thing after the enum is
    ## renumbered, reordered or shrunk again — which LRS-5's own second
    ## deletion round will do to four more members.
    check langV1NameToV2Token.len == LANG_V1_NAME_COUNT
    var names: seq[string] = @[]
    var tokens: seq[string] = @[]
    for entry in langV1NameToV2Token:
      checkpoint(entry.name & " -> " & entry.token)
      check entry.name.startsWith("Lang")
      check entry.name notin names
      check entry.token notin tokens
      check entry.token.len > 0
      names.add(entry.name)
      tokens.add(entry.token)

  test "every entry's target is a legal token, and decodes back":
    ## A frozen literal can be mistyped.  Each target is parsed with the
    ## production decoder, so a typo is a failure here rather than a database
    ## nothing can read.
    for entry in langV1NameToV2Token:
      checkpoint(entry.name & " -> " & entry.token)
      var axes: TargetAxes
      check parseAxesToken(entry.token, axes)
      check encodeAxesToken(axes) == entry.token

  test "the four targets that are easy to get wrong are the ones decided":
    ## Named individually in the milestone entry because each is a decision
    ## rather than a derivation, and each has an obvious wrong answer.
    # Q3: the sentinel is the BARE token.  `unknown-unknown-unknown-unknown`
    # is the mutation this line kills.
    check langV2TokenForV1Name("LangUnknown") == "unknown"
    # Q4a: `midenasm`, not `masm` — `masm` is reserved and unallocated.
    check langV2TokenForV1Name("LangMasm") == "midenasm-midenvm-unknown-vm"
    check "masm" notin langV2TokenForV1Name("LangMasm").split('-')
    # The two LRS-4 deleted, recorded as the fact they were: an rr backend.
    check langV2TokenForV1Name("LangPython") == "py-interpreted-unknown-rr"
    check langV2TokenForV1Name("LangRuby") == "rb-interpreted-unknown-rr"
    # The wasm pair, RE-DERIVED under four axes rather than copied from the
    # two-axis `rs-wasm` / `cpp-wasm` the design's §5.4 table still shows:
    # wasm is an ISA and the approach is VM emulation, the same approach
    # `nargo` and every blockchain recorder uses.
    check langV2TokenForV1Name("LangRustWasm") == "rs-wasm-unknown-vm"
    check langV2TokenForV1Name("LangCppWasm") == "cpp-wasm-unknown-vm"
    # And each of those four is distinguishable from its surviving partner.
    check langV2TokenForV1Name("LangPython") != langV2TokenForV1Name("LangPythonDb")
    check langV2TokenForV1Name("LangRuby") != langV2TokenForV1Name("LangRubyDb")
    check langV2TokenForV1Name("LangRustWasm") != langV2TokenForV1Name("LangRust")
    check langV2TokenForV1Name("LangCppWasm") != langV2TokenForV1Name("LangCpp")
    # Membership, not arithmetic, is what "a legal version-1 cell" means.
    check langV2TokenForV1Name("LangNotAThing") == ""
    check langV2TokenForV1Name("") == ""

  test "the frozen table covers exactly the names version 1 could write":
    ## The assertion that forces the append.  `langNamesEverPersisted` is
    ## itself built from two frozen literals (rule 3) and is the definition of
    ## "a name a CodeTracer build ever put in this column"; a member added to
    ## `Lang` and appended there, but given no token here, would migrate to
    ## NULL and abort the transaction on somebody's real database.  It fails
    ## here instead.
    check langNamesEverPersisted.len == LANG_V1_NAME_COUNT
    for name in langNamesEverPersisted:
      checkpoint("ever persisted: " & name)
      check langV2TokenForV1Name(name).len > 0
    for entry in langV1NameToV2Token:
      checkpoint("frozen target for: " & entry.name)
      check entry.name in langNamesEverPersisted

  test "the frozen table agrees with the live encoder on every LIVE member":
    ## The frozen literal and `langToColumnValue` must say the same thing
    ## today — otherwise a row migrated from version 1 and a row written fresh
    ## would disagree about the same recording.  Asserting the agreement is
    ## not the same as deriving one from the other: the table stays a literal,
    ## and the two names it covers that the enum no longer has are checked
    ## against literals in the test above.
    var liveCovered = 0
    for lang in Lang:
      checkpoint("live member: " & $lang)
      check langV2TokenForV1Name($lang) == langToColumnValue(lang)
      inc liveCovered
    # Exactly two of the 41 are unreachable from the live enum, and that is
    # the whole reason rule 3 exists.
    check LANG_V1_NAME_COUNT - liveCovered == 2

  test "a version-1 database holding ALL 41 legacy names migrates, each to its own target":
    ## The milestone's stated bar.  Not a sample: the failure this step exists
    ## to prevent is precisely one name landing on another's target, and the
    ## two names that cannot be reached through `parseEnum[Lang]` are in the
    ## fixture on purpose — a 1 -> 2 map routed through the live enum fails
    ## here, on `LangPython`, and nowhere else.
    let entries = v1NamesAndTokens()
    check entries.len == LANG_V1_NAME_COUNT
    var rows: seq[(string, string)] = @[]
    for i in 0 ..< entries.len:
      rows.add(("id-" & $i, entries[i][0]))
    let path = makeV1Db(workDir("v2-all-names"), rows)

    # Orphan pid rows, so the foreign-key claim is made against a database
    # that is not artificially clean.  `PRAGMA foreign_key_check` is normally
    # non-zero and an earlier version of the 0 -> 1 step aborted a successful
    # run by asserting the absolute number was zero.
    var fkBefore = 0
    block:
      let db = open(path, "", "", "")
      defer: db.close()
      for i in 1 .. 7:
        db.exec(sql"""INSERT INTO record_pid_recording_map (pid, recording_id)
                      VALUES (?, ?)""", $i, "no-such-recording-" & $i)
      db.exec(sql"""INSERT INTO record_pid_recording_map (pid, recording_id)
                    VALUES (?, ?)""", "99", "id-0")
      fkBefore = db.getAllRows(sql"PRAGMA foreign_key_check").len
    check fkBefore == 7

    migrateAt(path)

    check verifyAt(path).len == 0
    check declaredLangType(path) == "TEXT"
    var targets: seq[string] = @[]
    for i in 0 ..< entries.len:
      checkpoint("legacy name: " & entries[i][0])
      check langCell(path, "id-" & $i) == entries[i][1]
      check entries[i][1] notin targets
      targets.add(entries[i][1])
    check targets.len == LANG_V1_NAME_COUNT

    let db = open(path, "", "", "")
    defer: db.close()
    # **The DELTA, not the absolute value.**
    let fkAfter = db.getAllRows(sql"PRAGMA foreign_key_check").len
    checkpoint("foreign_key_check before " & $fkBefore & ", after " & $fkAfter)
    check fkAfter - fkBefore == 0
    check db.getValue(sql"SELECT count(*) FROM recordings") ==
      $LANG_V1_NAME_COUNT
    check db.getValue(sql"SELECT count(*) FROM record_pid_recording_map") == "8"

  test "every migrated row reads back through the production decoder":
    ## The target being distinct is necessary and not sufficient: it also has
    ## to mean something to `loadTrace`.  A row whose token no live `Lang`
    ## summarises decodes to the sentinel with the token preserved, which is
    ## the retired-name policy one column format later.
    let entries = v1NamesAndTokens()
    var rows: seq[(string, string)] = @[]
    for i in 0 ..< entries.len:
      rows.add(("id-" & $i, entries[i][0]))
    let path = makeV1Db(workDir("v2-decode-back"), rows)
    migrateAt(path)

    var unsummarised: seq[string] = @[]
    for i in 0 ..< entries.len:
      checkpoint("legacy name: " & entries[i][0])
      let column = decodeLangColumn(langCell(path, "id-" & $i))
      if column.retiredName.len > 0:
        check column.lang == LangUnknown
        check column.retiredName == entries[i][1]
        unsummarised.add(entries[i][0])
      else:
        check $column.lang == entries[i][0]
    unsummarised.sort()
    # Exactly the two members LRS-4 deleted: their recordings are still
    # readable, still distinguishable from the surviving Python and Ruby, and
    # still labelled by what they say rather than by "unknown".
    check unsummarised == @["LangPython", "LangRuby"]

  test "a version-0 database runs 0 -> 1 -> 2 in one call":
    ## The composition, end to end, through the public entry point.  A 1 -> 2
    ## step that did not compose with the existing gate would leave this
    ## database at version 1 holding names.
    let path = makeLegacyDb(
      workDir("compose"),
      @[("id-elixir", "37"), ("id-c", "0"), ("id-unknown", "22"),
        ("id-python", "12")])

    migrateAt(path)

    let db = open(path, "", "", "")
    defer: db.close()
    check db.getValue(sql"PRAGMA user_version") == $TRACE_INDEX_SCHEMA_VERSION
    check langCell(path, "id-elixir") == "ex-beam-unknown-instrumented"
    check langCell(path, "id-c") == "c-native-unknown-mcr"
    # Ordinal 22 was `LangUnknown` in the version-0 enum: it becomes the BARE
    # sentinel, not `unknown-unknown-unknown-unknown`.
    check langCell(path, "id-unknown") == "unknown"
    # Ordinal 12 was `LangPython`, a member this build does not have.  Both
    # frozen tables carry it and neither consults the live enum.
    check langCell(path, "id-python") == "py-interpreted-unknown-rr"
    check nameBackupsBeside(path).len == 1
    check tokenBackupsBeside(path).len == 1

  test "a version-1 database is migrated even when the 0 -> 1 step has nothing to do":
    ## The gate that makes the composition work: 1 -> 2 is reached because
    ## the stored version is below 2, not because the 0 -> 1 step ran.
    let path = makeV1Db(
      workDir("v1-only"), @[("id-js", "LangJavascript")])
    migrateAt(path)
    check verifyAt(path).len == 0
    check langCell(path, "id-js") == "js-interpreted-unknown-instrumented"
    # 0 -> 1 had nothing to rebuild, so it took no snapshot; 1 -> 2 did.
    check nameBackupsBeside(path).len == 0
    check tokenBackupsBeside(path).len == 1

  test "a version-1 database already holding tokens is refused as half-migrated":
    ## The state the design makes unreachable.  If it is reached anyway it
    ## must be named, not papered over: a second remap pass over tokens would
    ## map every one of them to NULL.
    let path = makeV1Db(
      workDir("v2-half"), @[("id-js", "js-interpreted-unknown-instrumented")])
    let before = snapshot(path)

    let msg = migrateExpectingError(path)
    check "already holds four-axis token" in msg
    check "half-migrated" in msg
    check snapshot(path) == before
    check tokenBackupsBeside(path).len == 0

  test "a version-1 cell that was never a Lang name is refused before anything is written":
    ## Pre-flight validation.  There is no token to map it to, and inventing
    ## one would mislabel the recording rather than lose it.  A **bare slug**
    ## is in the fixture on purpose: `py` is exactly what a decoder that
    ## "helpfully" applied the default tables would have accepted.
    let path = makeV1Db(
      workDir("v2-foreign"),
      @[("id-ok", "LangRust"), ("id-bad", "Elixir"), ("id-slug", "py"),
        ("id-int", "37")])
    let before = snapshot(path)

    let msg = migrateExpectingError(path)
    check "not schema-version-1 Lang names" in msg
    check "Elixir" in msg
    check "py" in msg
    check "37" in msg
    check snapshot(path) == before
    check tokenBackupsBeside(path).len == 0

  test "a pre-remap snapshot is written beside the database":
    ## The transaction makes the remap atomic against a crash or an error.
    ## It cannot protect against a remap that commits successfully while
    ## being logically wrong, which is why a snapshot is taken first.  Its
    ## absence is what makes the rollback proof below unprovable.
    let path = makeV1Db(workDir("v2-snapshot"), @[("id-elixir", "LangElixir")])
    migrateAt(path)

    let bak = path & langTokenMigrationBakSuffix
    check fileExists(bak)
    let bakDb = open(bak, "", "", "")
    defer: bakDb.close()
    check bakDb.getValue(
      sql"SELECT lang FROM recordings WHERE recording_id = 'id-elixir'") ==
      "LangElixir"
    check bakDb.getValue(sql"PRAGMA user_version") ==
      $TRACE_INDEX_SCHEMA_VERSION_LANG_NAMES

  test "a failure after the token remap rolls the whole step back":
    ## The 1 -> 2 analogue of `after-table-swap`, and the strongest of the
    ## two: at this fault point every cell has already been rewritten, so
    ## mid-transaction the column IS migrated.  All of it must come back —
    ## values and version.
    let path = makeV1Db(
      workDir("v2-fault-remap"),
      @[("id-elixir", "LangElixir"), ("id-python", "LangPython")])
    let before = snapshot(path)

    putEnv(traceIndexMigrationFaultEnv, "after-token-remap")
    let msg = migrateExpectingError(path)
    delEnv(traceIndexMigrationFaultEnv)

    check "injected fault at fault-point 'after-token-remap'" in msg
    check "the database is unchanged and a snapshot of it is at" in msg
    check snapshot(path) == before
    check langCell(path, "id-elixir") == "LangElixir"
    check langCell(path, "id-python") == "LangPython"
    check readSchemaVersionAt(path) == TRACE_INDEX_SCHEMA_VERSION_LANG_NAMES

  test "a failure after the token version stamp rolls the version back too":
    ## Values and version are stamped in the same transaction; neither may
    ## outlive the other.
    let path = makeV1Db(
      workDir("v2-fault-stamp"), @[("id-elixir", "LangElixir")])
    let before = snapshot(path)

    putEnv(traceIndexMigrationFaultEnv, "after-token-version-stamp")
    let msg = migrateExpectingError(path)
    delEnv(traceIndexMigrationFaultEnv)

    check "injected fault at fault-point 'after-token-version-stamp'" in msg
    check snapshot(path) == before
    check readSchemaVersionAt(path) == TRACE_INDEX_SCHEMA_VERSION_LANG_NAMES
    check verifyAt(path).anyIt("user_version is 1" in it)

  test "a rolled-back remap still migrates cleanly on the next attempt":
    ## "Version 1" has to be a resting state you can leave, not a corner you
    ## are stuck in.
    let path = makeV1Db(
      workDir("v2-fault-retry"), @[("id-elixir", "LangElixir")])

    putEnv(traceIndexMigrationFaultEnv, "after-token-remap")
    discard migrateExpectingError(path)
    delEnv(traceIndexMigrationFaultEnv)

    migrateAt(path)
    check verifyAt(path).len == 0
    check langCell(path, "id-elixir") == "ex-beam-unknown-instrumented"
    # A second snapshot, because `VACUUM INTO` refuses to overwrite: the
    # aborted attempt's residue, exactly as the 0 -> 1 step documents.
    check tokenBackupsBeside(path).len == 2

  test "a fault in 1 -> 2 leaves a WORKING version-1 database, not a wreck":
    ## The step that already committed is not undone by the step that failed,
    ## and that is correct: 0 -> 1 is a complete, self-consistent migration
    ## whose result a version-1 build reads.  This is also the only place the
    ## intermediate shape is observable, so it is where "the 0 -> 1 step still
    ## writes NAMES" is asserted now that one call runs both.
    let path = makeLegacyDb(
      workDir("v2-fault-intermediate"), @[("id-elixir", "37"), ("id-c", "0")])

    putEnv(traceIndexMigrationFaultEnv, "after-token-remap")
    discard migrateExpectingError(path)
    delEnv(traceIndexMigrationFaultEnv)

    check readSchemaVersionAt(path) == TRACE_INDEX_SCHEMA_VERSION_LANG_NAMES
    check declaredLangType(path) == "TEXT"
    check langCell(path, "id-elixir") == "LangElixir"
    check langCell(path, "id-c") == "LangC"
    check verifyTraceIndexSchemaAtPath(path, TRACE_INDEX_SCHEMA_VERSION_LANG_NAMES).len == 0
    # And it is not stuck: the next open finishes the job.
    migrateAt(path)
    check verifyAt(path).len == 0
    check langCell(path, "id-elixir") == "ex-beam-unknown-instrumented"

  test "the remap preserves every other column verbatim":
    ## A remap that touched a second column, or dropped a row, would still
    ## pass the `lang` assertions above.
    let path = makeV1Db(workDir("v2-cols"), @[("id-elixir", "LangElixir")])
    let before = rowsSnapshot(path)
    check "| LangElixir |" in before

    migrateAt(path)

    let after = rowsSnapshot(path)
    check "| ex-beam-unknown-instrumented |" in after
    check before.replace("| LangElixir |", "| LANG |") ==
          after.replace("| ex-beam-unknown-instrumented |", "| LANG |")

  test "the remapped table keeps both recordings indexes":
    ## The 1 -> 2 step is an UPDATE and drops nothing, so this should be free
    ## — which is exactly why it is asserted: a future author who reached for
    ## the 0 -> 1 rebuild machinery here would break it silently.
    let path = makeV1Db(workDir("v2-indexes"), @[("id-elixir", "LangElixir")])
    migrateAt(path)
    let db = open(path, "", "", "")
    defer: db.close()
    let names = db.getAllRows(sql"""SELECT name FROM sqlite_master
        WHERE type='index' AND tbl_name='recordings' ORDER BY name""").mapIt(it[0])
    check "idx_recordings_program" in names
    check "idx_recordings_recorded_at" in names

  test "langToColumnValue writes a token, and the column decoder refuses a bare slug":
    ## Design question Q1's rule at the only place a persisted value is read:
    ## *a default may be applied at parse time; a default may never be
    ## IMPLIED by a persisted value.*  `target_axes_test.nim` asserts it of
    ## the grammar decoder over a wide sweep; this asserts it of the COLUMN
    ## decoder, which is the one a database actually reaches.
    check langToColumnValue(LangPythonDb) == "py-interpreted-unknown-instrumented"
    check langToColumnValue(LangUnknown) == "unknown"
    check langToColumnValue(LangRustWasm) == "rs-wasm-unknown-vm"
    for bare in ["py", "rs", "js", "nim", "c", "cpp", "midenasm", "mcr",
                 "native", "interpreted", "instrumented", "cargo",
                 "unknown-unknown-unknown-unknown"]:
      checkpoint("bare cell: " & bare)
      var raised = false
      try:
        discard decodeLangColumn(bare)
      except TraceIndexSchemaError as e:
        raised = true
        check "neither a four-axis token nor a Lang enum name" in e.msg
      check raised
    # The sentinel, and only the sentinel, is hyphen-free and accepted.
    check decodeLangColumn("unknown") == LangColumn(lang: LangUnknown, retiredName: "")

  test "a version-1 NAME still decodes after version 2, and keeps its label":
    ## The legacy branch of `decodeLangColumn`.  A row written by an older
    ## build must not become a hard failure at open just because the column's
    ## live format moved on — the same obligation the retired-name policy
    ## states, one format later.
    check decodeLangColumn("LangElixir") ==
      LangColumn(lang: LangElixir, retiredName: "")
    let retired = decodeLangColumn("LangPython")
    check retired.lang == LangUnknown
    check retired.retiredName == "LangPython"
    var t = Trace(lang: LangUnknown, langRetiredName: "LangPython")
    check t.langLabel == "LangPython"
    # And a token no live member summarises labels by what the cell says,
    # which is strictly more than the name it replaced.
    let unsummarised = decodeLangColumn("py-interpreted-unknown-rr")
    check unsummarised.lang == LangUnknown
    check unsummarised.retiredName == "py-interpreted-unknown-rr"
    t = Trace(lang: LangUnknown, langRetiredName: "py-interpreted-unknown-rr")
    check t.langLabel == "py-interpreted-unknown-rr"

  test "verifyTraceIndexSchemaAt judges each version by ITS OWN cell format":
    ## The parameterised verifier is what lets each step check itself from
    ## inside its own transaction.  A verifier that only knew the latest
    ## version would fail the intermediate state the first step legitimately
    ## produces.
    let v1 = makeV1Db(workDir("v2-verify-v1"), @[("id-elixir", "LangElixir")])
    check verifyTraceIndexSchemaAtPath(v1, TRACE_INDEX_SCHEMA_VERSION_LANG_NAMES).len == 0
    let atLatest = verifyTraceIndexSchemaAtPath(v1, TRACE_INDEX_SCHEMA_VERSION)
    check atLatest.anyIt("user_version is 1" in it)
    check atLatest.anyIt("not a four-axis language token" in it)

    let v2 = makeCurrentDb(
      workDir("v2-verify-v2"), @[("id-elixir", "ex-beam-unknown-instrumented")])
    check verifyTraceIndexSchemaAtPath(v2, TRACE_INDEX_SCHEMA_VERSION).len == 0
    let atNames = verifyTraceIndexSchemaAtPath(v2, TRACE_INDEX_SCHEMA_VERSION_LANG_NAMES)
    check atNames.anyIt("user_version is 2" in it)
    check atNames.anyIt("not a Lang enum name" in it)

  test "the two accepted cell formats are disjoint, so the decode ORDER cannot matter":
    ## `decodeLangColumn`'s doc comment calls the order of its two branches
    ## "the decision".  It is a safe decision only because the two languages
    ## do not overlap — and that is asserted here rather than argued, because
    ## a reader who swaps the branches to "try the cheap check first" must be
    ## able to see, from a test, that nothing observable changes.
    ##
    ## *Direction 1 — no schema-version-1 `Lang` NAME is a legal four-axis
    ## token.*  A Nim enum member name cannot contain the separator, and none
    ## of them is the bare `unknown`, so the grammar refuses every one.
    for name in langNamesEverPersisted:
      checkpoint("legacy name: " & name)
      check AxisSeparator notin name
      check name != UnknownToken
      var axes: TargetAxes
      check(not parseAxesToken(name, axes))

    ## *Direction 2 — no token the grammar can produce is a `Lang` name, live
    ## or retired.*  Swept over the WHOLE product rather than over the frozen
    ## map, because the claim has to hold for every cell a future writer can
    ## emit, not only for the ones the migration writes today.
    var swept = 0
    var overlaps: seq[string] = @[]
    for language in SourceLanguage:
      for targetIsa in TargetIsa:
        for toolchain in Toolchain:
          for approach in RecordingApproach:
            let cell = encodeAxesToken(
              TargetAxes(language: language, targetIsa: targetIsa,
                         toolchain: toolchain, approach: approach))
            inc swept
            for lang in Lang:
              if $lang == cell and overlaps.len < 5:
                overlaps.add(cell & " is a LIVE Lang name")
            for name in langNamesEverPersisted:
              if name == cell and overlaps.len < 5:
                overlaps.add(cell & " is a RETIRED Lang name")
    checkpoint("tokens swept: " & $swept)
    checkpoint("first overlaps: " & $overlaps)
    check swept == 35 * 20 * 24 * 6
    check overlaps.len == 0
