## trace_index_migration_test.nim
##
## Acceptance tests for trace_index schema version 1: `recordings.lang` stores
## the `Lang` enum NAME rather than `ord(Lang)`, and the database carries a
## schema version in SQLite's `PRAGMA user_version`.
##
## ## Why this is tested harder than a normal change
##
## `trace_index.db` is **user data**.  It is not regenerated by a rebuild and
## it has no fixture: a user's recording index is the only copy of the mapping
## from a recording-id to the program, folder and language that produced it.  A
## migration that half-applies leaves a database no release can read and no
## rebuild can repair.  So the properties below are not "the happy path works":
##
##   1. an **old** database is remapped correctly, value for value, for all 40
##      `Lang` variants;
##   2. a **new** database is not touched;
##   3. running the migration **twice** is a no-op;
##   4. a **partial** application cannot be observed — the failure is
##      constructed at three separate points inside the transaction, and the
##      rollback is proved rather than asserted;
##   5. the **version gate** gates in both directions.
##
## ## Why `PRAGMA user_version`
##
## `isOldSchemaDb` in `src/common/trace_index.nim` detects a pre-M-REC-2
## database by probing for the retired `trace_values` table.  That is a
## *structural* probe, blind by construction to a change in the meaning of a
## value in a column that keeps its name and its type — exactly what happened
## to `lang`.  `user_version` is a slot in the SQLite file header: it needs no
## table, and it reads back 0 for every database nobody stamped, so every
## pre-existing user database is already correctly labelled "version 0" with no
## backfill.  Crucially it is also *transactional*; the all-or-nothing property
## rests on that, so "user_version rolls back with the transaction around it"
## is asserted here as a property of the SQLite in use rather than assumed.
##
## ## Why names, not renumbered ordinals
##
## The trigger for all of this is a pending move of `LangUnknown` to ordinal 0.
## Storing the ordinal makes the *declaration order of a Nim enum* a persisted
## user-data format.  Storing the name ends that: afterwards the reorder
## touches no persisted data, and this is the last migration the column needs.
## It is a one-way door — a database written after it cannot be read by a
## codetracer from before it — and it is chosen anyway, because the old
## binary's failure on a name is a loud parse error in `loadTrace`, whereas its
## failure on a renumbered ordinal would be a silently mislabelled recording.
##
## No test here touches the developer's real
## `~/.local/share/codetracer/trace_index.db`.  Every database is built from
## scratch in a temp directory; the two subprocess scenarios run with `HOME`
## and `XDG_DATA_HOME` redirected into one.

import std/[exitprocs, os, osproc, sequtils, streams, strtabs, strutils,
            tempfiles, unittest]

when NimMajor >= 2:
  import ../../db_connector/db_sqlite
else:
  import impure/db_sqlite

import ../../common/lang
import ../../common/trace_index

# ---------------------------------------------------------------------------
# Loader bootstrap
# ---------------------------------------------------------------------------

const relaunchGuardEnv = "CT_TRACE_INDEX_MIGRATION_TEST_RELAUNCHED"

proc ensureSqliteLoadable() =
  ## `db_sqlite` reaches `libsqlite3.so` through `dlopen`.  In the Nix dev
  ## shell that library sits on `CT_LD_LIBRARY_PATH` rather than on the
  ## loader's path (see `nix/shells/ci-base.nix`), and glibc reads
  ## `LD_LIBRARY_PATH` once, at process start — so calling `putEnv` here would
  ## be too late.  Re-exec once, with the augmented environment and a guard so
  ## the child cannot loop.
  ##
  ## The alternative — letting the load fail and skipping — is exactly the
  ## "reports success while doing nothing" shape this suite is written against.
  ## If the library genuinely is not there, the dlopen failure aborts the
  ## process with `could not load: libsqlite3.so`, and the lane reports a
  ## failure rather than a pass.
  if getEnv(relaunchGuardEnv).len > 0:
    return
  let ctLd = getEnv("CT_LD_LIBRARY_PATH", getEnv("CODETRACER_LD_LIBRARY_PATH"))
  if ctLd.len == 0:
    return
  let existing = getEnv("LD_LIBRARY_PATH")
  if existing.len > 0 and ctLd in existing:
    return
  var env = newStringTable(modeCaseSensitive)
  for k, v in envPairs():
    env[k] = v
  env["LD_LIBRARY_PATH"] =
    if existing.len > 0: ctLd & ":" & existing else: ctLd
  env[relaunchGuardEnv] = "1"
  let p = startProcess(
    getAppFilename(), args = commandLineParams(), env = env,
    options = {poParentStreams})
  let code = p.waitForExit()
  p.close()
  quit(code)

ensureSqliteLoadable()

# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------

const LEGACY_RECORDINGS_DDL = """CREATE TABLE recordings (
      recording_id TEXT PRIMARY KEY,
      program TEXT NOT NULL,
      args TEXT,
      compile_command TEXT,
      env TEXT,
      workdir TEXT,
      output TEXT,
      source_folders TEXT,
      low_level_folder TEXT,
      output_folder TEXT,
      lang INTEGER NOT NULL,
      imported INTEGER DEFAULT 0,
      shell_id INTEGER,
      rr_pid INTEGER,
      exit_code INTEGER,
      calltrace INTEGER,
      calltrace_mode TEXT,
      recorded_at TEXT NOT NULL,
      remote_share_download_key TEXT,
      remote_share_control_id TEXT,
      remote_share_expire_time INTEGER DEFAULT -1
  );"""
  ## Frozen copy of the schema-version-0 DDL.  Deriving the *old* shape from
  ## the *current* source would make this test stop testing the migration the
  ## moment the current source changed.

const LEGACY_SIDE_TABLES = @[
  """CREATE TABLE record_pid_recording_map (
      pid INTEGER,
      recording_id TEXT NOT NULL,
      FOREIGN KEY (recording_id) REFERENCES recordings(recording_id)
  );""",
  """CREATE TABLE recent_folders (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      path TEXT UNIQUE,
      name TEXT,
      last_opened TEXT
  );""",
  """CREATE INDEX idx_recordings_program ON recordings(program);""",
  """CREATE INDEX idx_recordings_recorded_at ON recordings(recorded_at DESC);""",
]

var scratchRoot = ""

proc workDir(name: string): string =
  ## One directory per test case, under a single per-run temp root.
  if scratchRoot.len == 0:
    scratchRoot = createTempDir("ct-trace-index-migration-", "")
  result = scratchRoot / name
  createDir(result)

addExitProc(proc() =
  if scratchRoot.len > 0:
    try: removeDir(scratchRoot) except OSError: discard)

proc openFixture(path: string): DBConn =
  result = open(path, "", "", "")
  result.exec(sql"PRAGMA busy_timeout = 10000;")
  result.exec(sql"PRAGMA journal_mode=WAL;")

proc insertRecording(db: DBConn; id, langValue: string) =
  ## Every non-`lang` column gets a distinct non-default value so that a
  ## rebuild which dropped or reordered a column shows up as a row diff.
  db.exec(sql"""INSERT INTO recordings
      (recording_id, program, args, compile_command, env, workdir, output,
       source_folders, low_level_folder, output_folder, lang, imported,
       shell_id, rr_pid, exit_code, calltrace, calltrace_mode, recorded_at,
       remote_share_download_key, remote_share_control_id,
       remote_share_expire_time)
      VALUES (?, ?, 'a b', 'cc --x', 'E=1', '/wd', 'out', '/src', '/low', ?,
              ?, 0, -1, 7, 9, 1, 'FullRecord', '2026/08/25', 'dk', 'ci', -1)""",
    id, "/tmp/prog-" & id, "/tmp/trace-" & id, langValue)

proc makeLegacyDb(dir: string; rows: seq[(string, string)]): string =
  ## A schema-version-0 database: `lang INTEGER NOT NULL` holding ordinals,
  ## `PRAGMA user_version` never stamped (so it reads back 0).
  result = dir / "trace_index.db"
  let db = openFixture(result)
  defer: db.close()
  db.exec(sql(LEGACY_RECORDINGS_DDL))
  for statement in LEGACY_SIDE_TABLES:
    db.exec(sql(statement))
  for row in rows:
    insertRecording(db, row[0], row[1])

proc makeCurrentDb(dir: string; rows: seq[(string, string)]): string =
  ## A schema-version-1 database, built the way `ensureDB` builds a fresh one:
  ## current DDL, then stamped.
  result = dir / "trace_index.db"
  let db = openFixture(result)
  defer: db.close()
  db.exec(sql(LEGACY_RECORDINGS_DDL.replace(
    "lang INTEGER NOT NULL", "lang TEXT NOT NULL")))
  for statement in LEGACY_SIDE_TABLES:
    db.exec(sql(statement))
  for row in rows:
    insertRecording(db, row[0], row[1])
  db.exec(sql("PRAGMA user_version = " & $TRACE_INDEX_SCHEMA_VERSION))

proc rowsSnapshot(path: string): string =
  ## Every row of `recordings`, every column, in a stable order.
  let db = open(path, "", "", "")
  defer: db.close()
  result = ""
  for row in db.getAllRows(sql"SELECT * FROM recordings ORDER BY recording_id"):
    result.add("row " & row.join(" | ") & "\n")

proc snapshot(path: string): string =
  ## A textual fingerprint of everything the migration can change: the schema
  ## version, the whole `sqlite_master` DDL, and every row.
  ##
  ## The *file bytes* are deliberately not compared.  The fixtures run in WAL
  ## mode, where a rolled-back transaction can still have appended to the
  ## `-wal` sidecar; a byte comparison would therefore report a difference
  ## with no observable effect, and the temptation would be to relax it.
  ## Comparing the logical content is the property that actually matters and
  ## is strictly harder to fake.
  let db = open(path, "", "", "")
  result = "user_version=" & db.getValue(sql"PRAGMA user_version") & "\n"
  for row in db.getAllRows(
      sql"SELECT type, name, sql FROM sqlite_master ORDER BY type, name"):
    result.add("schema " & row[0] & " " & row[1] & " :: " &
               row[2].splitWhitespace.join(" ") & "\n")
  db.close()
  result.add(rowsSnapshot(path))

proc langCell(path, id: string): string =
  let db = open(path, "", "", "")
  defer: db.close()
  db.getValue(sql"SELECT lang FROM recordings WHERE recording_id = ?", id)

proc declaredLangType(path: string): string =
  let db = open(path, "", "", "")
  defer: db.close()
  db.getValue(
    sql"SELECT type FROM pragma_table_info('recordings') WHERE name = 'lang'")

proc backupsBeside(path: string): seq[string] =
  ## Every `*.pre-lang-name-migration.bak*` file next to `path`.  A second
  ## entry appearing is direct evidence that the rebuild ran a second time,
  ## which is what "idempotent" forbids: `VACUUM INTO` refuses to overwrite,
  ## so a re-run has to write a *new* suffixed file.
  result = @[]
  for kind, entry in walkDir(path.parentDir):
    if kind == pcFile and langNameMigrationBakSuffix in entry.lastPathPart:
      result.add(entry.lastPathPart)

proc migrateAt(path: string) =
  let db = open(path, "", "", "")
  defer: db.close()
  db.exec(sql"PRAGMA busy_timeout = 10000;")
  migrateTraceIndex(db, path)

proc verifyAt(path: string): seq[string] =
  let db = open(path, "", "", "")
  defer: db.close()
  verifyTraceIndexSchema(db)

proc migrateExpectingError(path: string): string =
  ## Run the migration, require it to raise `TraceIndexMigrationError`, and
  ## return the message.  A migration that *succeeds* here fails the test
  ## rather than passing vacuously — a negative test that cannot fail is one
  ## more "reports success while doing nothing" defect, and this initiative
  ## has already found nine of those in the product.
  try:
    migrateAt(path)
  except TraceIndexMigrationError as e:
    return e.msg
  raise newException(ValueError,
    "migrateTraceIndex(" & path & ") returned normally; it was required to " &
    "raise TraceIndexMigrationError")

const LANG_V0_ENTRY_COUNT = 40
  ## Written as a literal on purpose.  `ord(high(Lang)) + 1` is 40 today and
  ## would be whatever the live enum happens to be tomorrow, which is the very
  ## substitution these tests exist to forbid.

proc langOrdinalsAndNames(): seq[(string, string)] =
  ## The schema-version-0 ordinal → name pairs, taken from the **frozen**
  ## `langV0OrdinalNames` snapshot in `trace_index.nim` and never from `Lang`.
  ##
  ## This used to read `for lang in Lang: result.add(($ord(lang), $lang))`.
  ## That made the test agree with the production code by construction: both
  ## sides derived the mapping from today's enum, so a renumber moved both and
  ## the test could not see it.  With the snapshot on both sides the test is
  ## still tautological for an *unmutated* build — which is why milestone
  ## LRS-0's verification requires running it against a deliberately mutated
  ## `Lang`, where the two sides part company unless the freeze is real.
  result = @[]
  for entry in langV0OrdinalNames:
    result.add(($entry.ordinal, entry.name))

# ---------------------------------------------------------------------------
# Subprocess helper — the two end-to-end scenarios
# ---------------------------------------------------------------------------

let helperSource =
  currentSourcePath.parentDir.parentDir.parentDir /
  "common" / "trace_index_test_helper.nim"

var helperBin = ""
var helperCompileOutput = ""

proc compileHelper() =
  ## Compile `src/common/trace_index_test_helper.nim`.  A failure here is a
  ## hard test failure with the compiler output attached — never a skip.  The
  ## two scenarios it carries are the only coverage of the migration's
  ## *wiring*, and a silently-absent wiring test is worse than no test.
  let cache = getTempDir() / "ct-trace-index-migration-helper"
  removeDir(cache)
  createDir(cache)
  let bin = cache / "trace_index_test_helper"
  let cmd = "nim c --hints:off --warnings:off --mm:refc " &
            "--nimcache:" & quoteShell(cache) & " " &
            "--out:" & quoteShell(bin) & " " &
            quoteShell(helperSource)
  let (output, code) = execCmdEx(cmd)
  helperCompileOutput = output
  if code == 0:
    helperBin = bin

proc runHelper(scenario: string): tuple[ok: bool, outp, errp: string] =
  let home = createTempDir("ct-trace-index-migration-" & scenario & "-", "")
  defer: removeDir(home)
  var env = newStringTable(modeCaseSensitive)
  for k, v in envPairs():
    env[k] = v
  env["HOME"] = home
  env["XDG_DATA_HOME"] = home
  env["TMPDIR"] = home
  # The fault hook must not leak into a scenario that expects success.
  env.del(traceIndexMigrationFaultEnv)
  # In the Nix dev shell libsqlite3.so is on CT_LD_LIBRARY_PATH, not on the
  # loader's default path.
  let ctLd = getEnv("CT_LD_LIBRARY_PATH")
  if ctLd.len > 0:
    let existing = getEnv("LD_LIBRARY_PATH")
    env["LD_LIBRARY_PATH"] =
      if existing.len > 0: ctLd & ":" & existing else: ctLd
  let p = startProcess(helperBin, args = @[scenario], env = env, options = {})
  defer: p.close()
  let outp = p.outputStream.readAll()
  let errp = p.errorStream.readAll()
  (p.waitForExit() == 0, outp, errp)

compileHelper()

# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------

suite "trace_index schema version 1 — lang ordinal to name":

  test "TRACE_INDEX_SCHEMA_VERSION is 1 and an unstamped DB reads back as 0":
    ## The whole gate rests on SQLite reporting 0 for a database nobody
    ## stamped.  Were that untrue, every existing user database would need a
    ## backfill before the gate meant anything.
    check TRACE_INDEX_SCHEMA_VERSION == 1
    let path = makeLegacyDb(workDir("unstamped"), @[])
    let db = open(path, "", "", "")
    defer: db.close()
    check readSchemaVersion(db) == 0

  test "PRAGMA user_version rolls back with the transaction around it":
    ## Asserted as a property of the SQLite in use, not assumed.  The
    ## all-or-nothing guarantee is exactly this behaviour; if a future SQLite
    ## stopped journalling the header slot, the migration could commit data
    ## without its version (or the reverse) and this is the only test that
    ## would notice.
    let path = makeLegacyDb(workDir("uvtxn"), @[("id-a", "0")])
    let db = open(path, "", "", "")
    defer: db.close()
    db.exec(sql"BEGIN IMMEDIATE")
    db.exec(sql"PRAGMA user_version = 7")
    check readSchemaVersion(db) == 7
    db.exec(sql"ROLLBACK")
    check readSchemaVersion(db) == 0

  test "the frozen version-0 ordinal table is 40 entries, 0..39, no repeats":
    ## Milestone LRS-0.  `langV0OrdinalNames` is a snapshot of `Lang` as it
    ## stood when schema-version-0 rows were written; it decodes integers that
    ## an *older* build put on disk, so it must not be regenerated from the
    ## enum this build was compiled with.
    ##
    ## Every assertion below is written against literals and against the
    ## snapshot itself.  Not one mentions `Lang`, `ord`, `low` or `high` — so
    ## the whole test still holds, and still means the same thing, after `Lang`
    ## is renumbered, reordered or shrunk.  A test that said
    ## `langV0OrdinalNames.len == ord(high(Lang)) + 1` would agree with a
    ## renumbered enum by construction and would prove nothing.
    check langV0OrdinalNames.len == LANG_V0_ENTRY_COUNT

    var seenOrdinals: seq[int] = @[]
    var seenNames: seq[string] = @[]
    for entry in langV0OrdinalNames:
      check entry.ordinal notin seenOrdinals
      check entry.name notin seenNames
      check entry.name.startsWith("Lang")
      seenOrdinals.add(entry.ordinal)
      seenNames.add(entry.name)

    for expected in 0 ..< LANG_V0_ENTRY_COUNT:
      check expected in seenOrdinals

    check langV0MinOrdinal == 0
    check langV0MaxOrdinal == LANG_V0_ENTRY_COUNT - 1

    # Spot-check the three ordinals that carry the most rows in the live
    # developer database, and the sentinel the pending reorder moves.  These
    # are the values a renumber would silently re-point.
    check langV0NameForOrdinal(0) == "LangC"
    check langV0NameForOrdinal(14) == "LangRubyDb"
    check langV0NameForOrdinal(15) == "LangJavascript"
    check langV0NameForOrdinal(21) == "LangPythonDb"
    check langV0NameForOrdinal(22) == "LangUnknown"
    check langV0NameForOrdinal(37) == "LangElixir"
    check langV0NameForOrdinal(39) == "LangPhp"

    # Membership, not arithmetic, is what "a legal version-0 ordinal" means.
    check langV0NameForOrdinal(-1) == ""
    check langV0NameForOrdinal(LANG_V0_ENTRY_COUNT) == ""

  test "an old database is remapped: every Lang ordinal becomes its name":
    ## The anti-drift check.  All 40 variants, not a sample: the failure this
    ## migration exists to prevent is precisely a single variant landing on
    ## the wrong side of a renumber.
    let pairs = langOrdinalsAndNames()
    check pairs.len == LANG_V0_ENTRY_COUNT
    var rows: seq[(string, string)] = @[]
    for pair in pairs:
      rows.add(("id-" & pair[0], pair[0]))
    let path = makeLegacyDb(workDir("remap-all"), rows)

    migrateAt(path)

    check verifyAt(path).len == 0
    check declaredLangType(path) == "TEXT"
    for pair in pairs:
      check langCell(path, "id-" & pair[0]) == pair[1]

  test "the remap preserves every other column verbatim":
    ## A rebuild that copied the columns in the wrong order, or dropped one,
    ## would still pass the `lang` assertions above.
    let path = makeLegacyDb(workDir("remap-cols"), @[("id-elixir", "37")])
    let before = rowsSnapshot(path)
    check "| 37 |" in before

    migrateAt(path)

    let after = rowsSnapshot(path)
    check "| LangElixir |" in after
    check before.replace("| 37 |", "| LANG |") ==
          after.replace("| LangElixir |", "| LANG |")

  test "the rebuilt table keeps both recordings indexes":
    ## `DROP TABLE recordings` takes its indexes with it; forgetting to
    ## recreate them would silently turn `ct list` into a table scan.
    let path = makeLegacyDb(workDir("indexes"), @[("id-elixir", "37")])
    migrateAt(path)
    let db = open(path, "", "", "")
    defer: db.close()
    let names = db.getAllRows(sql"""SELECT name FROM sqlite_master
        WHERE type='index' AND tbl_name='recordings' ORDER BY name""").mapIt(it[0])
    check "idx_recordings_program" in names
    check "idx_recordings_recorded_at" in names

  test "a database with pre-existing orphan foreign keys still migrates":
    ## **Regression.**  This is the defect the first real database caught.
    ##
    ## `record_pid_recording_map` declares
    ## `FOREIGN KEY (recording_id) REFERENCES recordings(recording_id)`, but
    ## SQLite only enforces foreign keys when `PRAGMA foreign_keys` is ON and
    ## nothing in `trace_index.nim` turns it on — so orphan pid rows are the
    ## normal state of a working database, not a fault.  The developer
    ## database read on 2026-08-25 held **685 orphans among 932 pid rows**
    ## before this migration existed.
    ##
    ## An earlier version of the migration used a whole-database
    ## `PRAGMA foreign_key_check` as its post-condition and aborted on those
    ## 685 — failing a migration that had in fact succeeded (every recording
    ## id preserved, every ordinal correctly mapped), and, because the check
    ## ran *after* COMMIT, printing "the local recording index was left
    ## unchanged" about a database it had just changed.
    ##
    ## Every fixture above is orphan-free, which is exactly why none of them
    ## caught it.
    let path = makeLegacyDb(
      workDir("fk-orphans"), @[("id-elixir", "37"), ("id-c", "0")])
    block:
      let db = open(path, "", "", "")
      defer: db.close()
      for i in 1 .. 5:
        db.exec(sql"""INSERT INTO record_pid_recording_map (pid, recording_id)
                      VALUES (?, ?)""", $i, "no-such-recording-" & $i)
      # A pid row that DOES resolve, so the fixture is not uniformly broken.
      db.exec(sql"""INSERT INTO record_pid_recording_map (pid, recording_id)
                    VALUES (?, ?)""", "99", "id-elixir")
      check db.getAllRows(sql"PRAGMA foreign_key_check").len == 5

    migrateAt(path)

    check verifyAt(path).len == 0
    check langCell(path, "id-elixir") == "LangElixir"
    check langCell(path, "id-c") == "LangC"
    let db = open(path, "", "", "")
    defer: db.close()
    # The orphans are carried through untouched: the migration rewrites one
    # column of one table and is not a data-cleanup pass.
    check db.getAllRows(sql"PRAGMA foreign_key_check").len == 5
    check db.getValue(sql"SELECT count(*) FROM record_pid_recording_map") == "6"

  test "the rebuild preserves the recording count exactly":
    ## The assertion that replaced the absolute foreign-key check.  A rebuild
    ## that dropped or duplicated rows is the failure most worth catching, and
    ## `PRAGMA foreign_key_check` never looked for it.
    let dir = workDir("rowcount")
    var rows: seq[(string, string)] = @[]
    for i in 0 .. 9:
      rows.add(("id-" & $i, "37"))
    let path = makeLegacyDb(dir, rows)
    check rowsSnapshot(path).splitLines.len - 1 == 10

    migrateAt(path)

    let db = open(path, "", "", "")
    defer: db.close()
    check db.getValue(sql"SELECT count(*) FROM recordings") == "10"
    check db.getValue(
      sql"SELECT count(*) FROM recordings WHERE lang = 'LangElixir'") == "10"

  test "a pre-migration snapshot is written beside the database":
    ## The transaction makes the migration atomic against a crash or an
    ## error.  It cannot protect against a migration that commits
    ## successfully while being logically wrong, which is why a snapshot is
    ## taken first.
    let path = makeLegacyDb(workDir("snapshot"), @[("id-elixir", "37")])
    migrateAt(path)

    let bak = path & langNameMigrationBakSuffix
    check fileExists(bak)
    let bakDb = open(bak, "", "", "")
    defer: bakDb.close()
    check bakDb.getValue(
      sql"SELECT lang FROM recordings WHERE recording_id = 'id-elixir'") == "37"
    check bakDb.getValue(sql"PRAGMA user_version") == "0"

  test "a new database is left untouched — no rebuild, no snapshot":
    let path = makeCurrentDb(workDir("already-new"), @[("id-elixir", "LangElixir")])
    let before = snapshot(path)

    migrateAt(path)

    check snapshot(path) == before
    check backupsBeside(path).len == 0
    check verifyAt(path).len == 0

  test "running the migration twice is a no-op":
    ## Idempotence, proved two ways: the logical content is identical after
    ## the second run, and no second snapshot was taken.
    let path = makeLegacyDb(
      workDir("twice"), @[("id-elixir", "37"), ("id-c", "0")])

    migrateAt(path)
    let afterFirst = snapshot(path)
    let backupsAfterFirst = backupsBeside(path)

    migrateAt(path)

    check snapshot(path) == afterFirst
    check backupsAfterFirst.len == 1
    check backupsBeside(path) == backupsAfterFirst
    check verifyAt(path).len == 0

  test "the version gate detects an unmigrated DB and clears a migrated one":
    let path = makeLegacyDb(workDir("gate"), @[("id-elixir", "37")])

    let problemsBefore = verifyAt(path)
    check problemsBefore.len > 0
    check problemsBefore.anyIt("user_version is 0" in it)
    check problemsBefore.anyIt("declared INTEGER" in it)

    migrateAt(path)
    check verifyAt(path).len == 0

  test "a database from a NEWER schema version is refused, not guessed at":
    ## The downgrade direction.  Reading a future database with today's
    ## assumptions is the same class of mistake as reading an ordinal against
    ## the wrong enum order.
    let path = makeCurrentDb(workDir("newer"), @[("id-elixir", "LangElixir")])
    block:
      let db = open(path, "", "", "")
      defer: db.close()
      db.exec(sql"PRAGMA user_version = 99")
    let before = snapshot(path)

    let msg = migrateExpectingError(path)
    check "schema version 99" in msg
    check "Refusing to open it" in msg
    check snapshot(path) == before

  test "an ordinal outside the Lang range is refused before anything is written":
    ## Pre-flight validation.  There is no name to map 999 to, and inventing
    ## one would mislabel the recording rather than lose it.
    let path = makeLegacyDb(
      workDir("outofrange"), @[("id-ok", "2"), ("id-bad", "999")])
    let before = snapshot(path)

    let msg = migrateExpectingError(path)
    check "not schema-version-0 Lang ordinals" in msg
    check "999" in msg
    check snapshot(path) == before
    check backupsBeside(path).len == 0

  test "all out-of-range ordinals are reported, not just the first":
    ## The upper bound comes from the frozen snapshot, not from
    ## `ord(high(Lang))`: after the language/recording-type split the live
    ## enum's high is 35, and a test written against it would start demanding
    ## that the perfectly valid stored ordinals 36..39 be *rejected*.
    let justAboveV0 = $(langV0MaxOrdinal + 1)
    let path = makeLegacyDb(
      workDir("outofrange-many"),
      @[("id-a", "-1"), ("id-b", justAboveV0), ("id-c", "12345")])
    let msg = migrateExpectingError(path)
    check "-1" in msg
    check justAboveV0 in msg
    check "12345" in msg

  test "a half-migrated database (names at version 0) is refused":
    ## The state this design exists to make unreachable.  If it is reached
    ## anyway it must be named, not papered over: a second rebuild pass over
    ## names would map every one of them to NULL.
    let path = makeLegacyDb(workDir("half"), @[("id-elixir", "37")])
    block:
      let db = open(path, "", "", "")
      defer: db.close()
      db.exec(sql"UPDATE recordings SET lang = 'LangElixir'")
    let before = snapshot(path)

    let msg = migrateExpectingError(path)
    check "already holds enum name" in msg
    check "half-migrated" in msg
    check snapshot(path) == before

  test "a failure after the row rewrite rolls the whole migration back":
    let path = makeLegacyDb(
      workDir("fault-rewrite"), @[("id-elixir", "37"), ("id-c", "0")])
    let before = snapshot(path)

    putEnv(traceIndexMigrationFaultEnv, "after-table-rewrite")
    let msg = migrateExpectingError(path)
    delEnv(traceIndexMigrationFaultEnv)

    check "injected fault at fault-point 'after-table-rewrite'" in msg
    check snapshot(path) == before
    check declaredLangType(path) == "INTEGER"

  test "a failure after the table SWAP rolls the whole migration back":
    ## The strongest of the three: at this fault point the original table has
    ## already been dropped and the rebuilt one renamed over it, so
    ## mid-transaction the database *is* migrated.  All of it must still come
    ## back — rows, declared type, indexes and version.
    let path = makeLegacyDb(
      workDir("fault-swap"), @[("id-elixir", "37"), ("id-c", "0")])
    let before = snapshot(path)

    putEnv(traceIndexMigrationFaultEnv, "after-table-swap")
    let msg = migrateExpectingError(path)
    delEnv(traceIndexMigrationFaultEnv)

    check "injected fault at fault-point 'after-table-swap'" in msg
    check snapshot(path) == before
    check declaredLangType(path) == "INTEGER"
    check langCell(path, "id-elixir") == "37"
    let db = open(path, "", "", "")
    defer: db.close()
    check db.getAllRows(sql"""SELECT name FROM sqlite_master
        WHERE type='table' AND name LIKE 'recordings_schema_migration%'""").len == 0

  test "a failure after the version stamp rolls the version back too":
    ## Data and version are stamped in the same transaction; neither may
    ## outlive the other.
    let path = makeLegacyDb(workDir("fault-stamp"), @[("id-elixir", "37")])
    let before = snapshot(path)

    putEnv(traceIndexMigrationFaultEnv, "after-version-stamp")
    let msg = migrateExpectingError(path)
    delEnv(traceIndexMigrationFaultEnv)

    check "injected fault at fault-point 'after-version-stamp'" in msg
    check snapshot(path) == before
    check verifyAt(path).anyIt("user_version is 0" in it)

  test "a rolled-back database still migrates cleanly on the next attempt":
    ## "Unmigrated" has to be a resting state you can leave, not a corner you
    ## are stuck in.
    let path = makeLegacyDb(workDir("fault-retry"), @[("id-elixir", "37")])

    putEnv(traceIndexMigrationFaultEnv, "after-table-swap")
    discard migrateExpectingError(path)
    delEnv(traceIndexMigrationFaultEnv)

    migrateAt(path)
    check verifyAt(path).len == 0
    check langCell(path, "id-elixir") == "LangElixir"

  test "langFromColumnValue round-trips every Lang and rejects a bare ordinal":
    for lang in Lang:
      check langFromColumnValue(langToColumnValue(lang)) == lang
    for raw in ["37", "0", "", "Elixir", "LangNotAThing"]:
      var raised = false
      try:
        discard langFromColumnValue(raw)
      except TraceIndexSchemaError as e:
        raised = true
        check "not a Lang enum name" in e.msg
      check raised

  test "verifyTraceIndexSchema names a surviving migration scratch table":
    ## The one shape a rollback failure would leave behind.  `verify` is what
    ## a diagnostic would call, so it has to see it.
    let path = makeCurrentDb(
      workDir("scratch-survivor"), @[("id-elixir", "LangElixir")])
    block:
      let db = open(path, "", "", "")
      defer: db.close()
      db.exec(sql"CREATE TABLE recordings_schema_migration_scratch (x INTEGER)")
    check verifyAt(path).anyIt("half-migrated" in it)

  # -- end to end, through the real ensureDB ---------------------------------

  test "trace_index_test_helper compiles":
    ## Hard failure with the compiler output attached, never a skip.
    if helperBin.len == 0:
      echo helperCompileOutput
    check helperBin.len > 0

  test "e2e: recordTrace writes a language NAME and find reads it back":
    require helperBin.len > 0
    let (ok, outp, errp) = runHelper("lang-name-roundtrip")
    if not ok or "PASS" notin outp:
      echo "stdout: ", outp
      echo "stderr: ", errp
    check ok
    check "PASS" in outp

  test "e2e: ensureDB migrates a legacy database on open":
    ## Proves the migration is actually called on the production path.  A
    ## correct migration nobody invokes is worth nothing.
    require helperBin.len > 0
    let (ok, outp, errp) = runHelper("migrate-legacy-db")
    if not ok or "PASS" notin outp:
      echo "stdout: ", outp
      echo "stderr: ", errp
    check ok
    check "PASS" in outp
    check "migrated to schema version 1" in errp
