//! Canonical UUIDv7 `recording_id`s for the committed example recordings.
//!
//! Mirror of
//! [`codetracer-example-recordings/FIXTURE_IDS.md`](../../../../codetracer-example-recordings/FIXTURE_IDS.md)
//! and the Nim sibling
//! [`codetracer/src/common/fixture_ids.nim`](../../../common/fixture_ids.nim).
//!
//! **Authority:** the Markdown file. If you change a fixture's id, change
//! it in all three places. The Rust side is `const &str` so misspellings
//! are caught at compile time when tests reference them.
//!
//! ## Why a module instead of inline literals
//!
//! Two reasons:
//!
//! 1. **Single point of update.** A new test that wants to assert
//!    "this is the python flow_test recording" imports
//!    `PYTHON_FLOW_TEST_RECORDING_ID` rather than re-typing the UUID.
//!    If we ever need to rotate an id (e.g. because the embedded
//!    timestamp leaked into a user-visible URL and we want a tidier
//!    one) we change exactly one constant.
//!
//! 2. **Documentation co-location.** Each constant carries a one-line
//!    comment naming the fixture path it pins, so `grep` on a UUID
//!    string from a failing test goes straight to a human-readable
//!    description.
//!
//! ## Why `pub const &str` and not `Uuid`
//!
//! db-backend's wire types carry `recording_id: String` (M-REC-4). The
//! crate does not (yet) introduce a typed wrapper, so the constants are
//! exposed as `&'static str` to match the field type at the use site
//! without `.to_string()` ceremony.
//!
//! Generated by M-REC-12 (Recording-Identifier Migration, fixture
//! freeze). See
//! [`codetracer-specs/Refactoring-Plans/Recording-Identifier-Migration.md`](https://github.com/metacraft-labs/codetracer-specs)
//! §6.10.

#![allow(dead_code)]

// ── Language-flow fixtures (`codetracer-example-recordings/<lang>/flow_test/`) ──

/// `recording_id` for `c/flow_test/` — RR-recorded C trace.
pub const C_FLOW_TEST_RECORDING_ID: &str = "019e3a35-2530-7c00-8aaa-43ff10010001";

/// `recording_id` for `go/flow_test/` — RR-recorded Go trace.
pub const GO_FLOW_TEST_RECORDING_ID: &str = "019e3a35-2531-7600-8aaa-43ff10020001";

/// `recording_id` for `javascript/flow_test/` — JavaScript materialized trace.
///
/// Lives in the `codetracer/examples/recordings/` submodule rather than the
/// sibling `codetracer-example-recordings/` repo. Same migration story.
pub const JAVASCRIPT_FLOW_TEST_RECORDING_ID: &str = "019e3a35-2532-7100-8aaa-43ff10030001";

/// `recording_id` for `nim/flow_test/` — RR-recorded Nim trace.
pub const NIM_FLOW_TEST_RECORDING_ID: &str = "019e3a35-2533-7e00-8aaa-43ff10040001";

/// `recording_id` for `python/flow_test/` — `codetracer-python-recorder` materialized trace.
pub const PYTHON_FLOW_TEST_RECORDING_ID: &str = "019e3a35-2534-7000-8aaa-43ff10050001";

/// `recording_id` for `ruby/flow_test/` — `codetracer-pure-ruby-recorder` materialized trace.
pub const RUBY_FLOW_TEST_RECORDING_ID: &str = "019e3a35-2535-7b00-8aaa-43ff10060001";

/// `recording_id` for `rust/flow_test/` — RR-recorded Rust trace.
pub const RUST_FLOW_TEST_RECORDING_ID: &str = "019e3a35-2536-7900-8aaa-43ff10070001";

// ── MCR portable-trace fixtures (`codetracer-example-recordings/mcr/<platform>/`) ──

/// `recording_id` for `mcr/linux-x86_64/trace.ct` — raw MCR trace.
pub const MCR_LINUX_X86_64_RECORDING_ID: &str = "019e3a35-2540-7a00-8aaa-43ff20010001";

/// `recording_id` for `mcr/linux-x86_64/trace-portable.ct` — portable export of the above.
pub const MCR_LINUX_X86_64_PORTABLE_RECORDING_ID: &str = "019e3a35-2540-7a00-8aaa-43ff20010002";

/// `recording_id` reserved for `mcr/linux-arm64/trace.ct` — fixture not yet recorded.
pub const MCR_LINUX_ARM64_RECORDING_ID: &str = "019e3a35-2541-7a00-8aaa-43ff20020001";

/// `recording_id` reserved for `mcr/linux-arm64/trace-portable.ct` — fixture not yet recorded.
pub const MCR_LINUX_ARM64_PORTABLE_RECORDING_ID: &str = "019e3a35-2541-7a00-8aaa-43ff20020002";

/// `recording_id` for `mcr/macos-arm64/trace.ct` — raw MCR trace (Apple Silicon M1).
pub const MCR_MACOS_ARM64_RECORDING_ID: &str = "019e3a35-2542-7a00-8aaa-43ff20030001";

/// `recording_id` for `mcr/macos-arm64/trace-portable.ct` — portable export of the above.
pub const MCR_MACOS_ARM64_PORTABLE_RECORDING_ID: &str = "019e3a35-2542-7a00-8aaa-43ff20030002";

/// `recording_id` for `mcr/ios-arm64/trace.ct` — raw MCR trace (iPhone 17 Pro simulator).
pub const MCR_IOS_ARM64_RECORDING_ID: &str = "019e3a35-2543-7a00-8aaa-43ff20040001";

/// `recording_id` for `mcr/ios-arm64/trace-portable.ct` — portable export of the above.
pub const MCR_IOS_ARM64_PORTABLE_RECORDING_ID: &str = "019e3a35-2543-7a00-8aaa-43ff20040002";

/// `recording_id` for `mcr/android-arm64/trace.ct` — raw MCR trace (Samsung Galaxy S24 Ultra).
pub const MCR_ANDROID_ARM64_RECORDING_ID: &str = "019e3a35-2544-7a00-8aaa-43ff20050001";

/// `recording_id` for `mcr/android-arm64/trace-portable.ct` — portable export of the above.
pub const MCR_ANDROID_ARM64_PORTABLE_RECORDING_ID: &str = "019e3a35-2544-7a00-8aaa-43ff20050002";

/// `recording_id` for `mcr/windows-x86_64/trace.ct` — raw MCR trace (Windows 11 x64 interpose).
pub const MCR_WINDOWS_X86_64_RECORDING_ID: &str = "019e3a35-2545-7a00-8aaa-43ff20060001";

/// `recording_id` for `mcr/windows-x86_64/trace-portable.ct` — portable export of the above.
pub const MCR_WINDOWS_X86_64_PORTABLE_RECORDING_ID: &str = "019e3a35-2545-7a00-8aaa-43ff20060002";

/// Every committed-fixture recording id in deterministic order.
///
/// Tests that need to validate "no two fixtures share an id" can iterate
/// this table. Order is **not** stable for human reading — append new
/// entries to the end so existing tests don't break.
pub const ALL_FIXTURE_RECORDING_IDS: &[&str] = &[
    C_FLOW_TEST_RECORDING_ID,
    GO_FLOW_TEST_RECORDING_ID,
    JAVASCRIPT_FLOW_TEST_RECORDING_ID,
    NIM_FLOW_TEST_RECORDING_ID,
    PYTHON_FLOW_TEST_RECORDING_ID,
    RUBY_FLOW_TEST_RECORDING_ID,
    RUST_FLOW_TEST_RECORDING_ID,
    MCR_LINUX_X86_64_RECORDING_ID,
    MCR_LINUX_X86_64_PORTABLE_RECORDING_ID,
    MCR_LINUX_ARM64_RECORDING_ID,
    MCR_LINUX_ARM64_PORTABLE_RECORDING_ID,
    MCR_MACOS_ARM64_RECORDING_ID,
    MCR_MACOS_ARM64_PORTABLE_RECORDING_ID,
    MCR_IOS_ARM64_RECORDING_ID,
    MCR_IOS_ARM64_PORTABLE_RECORDING_ID,
    MCR_ANDROID_ARM64_RECORDING_ID,
    MCR_ANDROID_ARM64_PORTABLE_RECORDING_ID,
    MCR_WINDOWS_X86_64_RECORDING_ID,
    MCR_WINDOWS_X86_64_PORTABLE_RECORDING_ID,
];

#[cfg(test)]
mod tests {
    use super::*;

    /// Length-and-hyphen-position check: every constant is a canonical
    /// 36-character UUIDv7 string. This guards against typos when adding
    /// new constants — a missing or extra hex digit (or a stray uppercase
    /// letter) would shift the hyphens and trip this test.
    #[test]
    fn every_constant_is_canonical_uuid_v7() {
        for id in ALL_FIXTURE_RECORDING_IDS {
            assert_eq!(id.len(), 36, "{id} is not 36 chars long");

            // Hyphens at positions 8, 13, 18, 23.
            for &pos in &[8usize, 13, 18, 23] {
                assert_eq!(id.as_bytes()[pos], b'-', "{id}: position {pos} is not '-'");
            }

            // Version nibble (position 14) must be '7'.
            assert_eq!(
                id.as_bytes()[14],
                b'7',
                "{id}: version nibble at position 14 is not '7'"
            );

            // Variant nibble (position 19) must be one of {8, 9, a, b}.
            let variant = id.as_bytes()[19];
            assert!(
                matches!(variant, b'8' | b'9' | b'a' | b'b'),
                "{id}: variant nibble at position 19 must be 8/9/a/b, was 0x{variant:02x}"
            );

            // All non-hyphen characters must be lowercase hex.
            for (i, ch) in id.char_indices() {
                if matches!(i, 8 | 13 | 18 | 23) {
                    continue;
                }
                assert!(
                    matches!(ch, '0'..='9' | 'a'..='f'),
                    "{id}: character {ch:?} at position {i} is not lowercase hex"
                );
            }
        }
    }

    /// No two fixtures share an id — collisions would conflict in
    /// `trace_index.db` which uses `recording_id` as the primary key.
    #[test]
    fn all_fixture_ids_are_unique() {
        let mut seen = std::collections::HashSet::new();
        for id in ALL_FIXTURE_RECORDING_IDS {
            assert!(seen.insert(*id), "fixture id {id} is listed twice");
        }
    }
}
