/* Generated by the Nim Compiler v2.2.8 */
var framePtr = null;
var excHandler = 0;
var lastJSError = null;
var NTI134217745 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217751 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217741 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217743 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555187 = {size: 0, kind: 22, base: null, node: null, finalizer: null};
var NTI33554450 = {size: 0,kind: 29,base: null,node: null,finalizer: null};
var NTI33555186 = {size: 0, kind: 22, base: null, node: null, finalizer: null};
var NTI33555183 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555184 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217749 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33554449 = {size: 0,kind: 28,base: null,node: null,finalizer: null};
var NTI1056964621 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI1056964620 = {size: 0, kind: 22, base: null, node: null, finalizer: null};
var NTI1056964623 = {size: 0, kind: 22, base: null, node: null, finalizer: null};
var NTI1056964631 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI1056964630 = {size: 0, kind: 24, base: null, node: null, finalizer: null};
var NTI1056964629 = {size: 0, kind: 24, base: null, node: null, finalizer: null};
var NTI1056964628 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI1056964635 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI33554466 = {size: 0,kind: 1,base: null,node: null,finalizer: null};
var NTI1040187395 = {size: 0, kind: 14, base: null, node: null, finalizer: null};
var NTI1056964634 = {size: 0, kind: 24, base: null, node: null, finalizer: null};
var NTI33555179 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33554435 = {size: 0,kind: 31,base: null,node: null,finalizer: null};
var NTI1056964627 = {size: 0, kind: 24, base: null, node: null, finalizer: null};
var NTI1056964624 = {size: 0, kind: 22, base: null, node: null, finalizer: null};
var NTI1056964626 = {size: 0, kind: 24, base: null, node: null, finalizer: null};
var NTI1056964625 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI1056964622 = {size: 0, kind: 22, base: null, node: null, finalizer: null};
var NTI1056964633 = {size: 0, kind: 24, base: null, node: null, finalizer: null};
var NTI1056964632 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
NTI1056964624.base = NTI1056964632;
NTI1056964626.base = NTI1056964624;
NTI1056964627.base = NTI33554435;
var NNI1056964625 = {kind: 2, len: 2, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "observers", len: 0, typ: NTI1056964626, name: "observers", sons: null}, 
{kind: 1, offset: "observerSlots", len: 0, typ: NTI1056964627, name: "observerSlots", sons: null}]};
NTI1056964625.node = NNI1056964625;
var NNI33555179 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555179.node = NNI33555179;
NTI1056964625.base = NTI33555179;
NTI1056964622.base = NTI1056964625;
NTI1056964633.base = NTI1056964622;
NTI1056964634.base = NTI33554435;
var NNI1040187395 = {kind: 2, offset: 0, typ: null, name: null, len: 3, sons: {"0": {kind: 1, offset: 0, typ: NTI1040187395, name: "csClean", len: 0, sons: null}, 
"1": {kind: 1, offset: 1, typ: NTI1040187395, name: "csStale", len: 0, sons: null}, 
"2": {kind: 1, offset: 2, typ: NTI1040187395, name: "csPending", len: 0, sons: null}}};
NTI1040187395.node = NNI1040187395;
var NNI1056964632 = {kind: 2, len: 7, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "sources", len: 0, typ: NTI1056964633, name: "sources", sons: null}, 
{kind: 1, offset: "sourceSlots", len: 0, typ: NTI1056964634, name: "sourceSlots", sons: null}, 
{kind: 1, offset: "state", len: 0, typ: NTI1040187395, name: "state", sons: null}, 
{kind: 1, offset: "pure", len: 0, typ: NTI33554466, name: "pure", sons: null}, 
{kind: 1, offset: "fn", len: 0, typ: NTI1056964635, name: "fn", sons: null}, 
{kind: 1, offset: "updatedAt", len: 0, typ: NTI33554435, name: "updatedAt", sons: null}, 
{kind: 1, offset: "memoSignal", len: 0, typ: NTI1056964622, name: "memoSignal", sons: null}]};
NTI1056964632.node = NNI1056964632;
NTI1056964629.base = NTI1056964624;
NTI1056964630.base = NTI1056964631;
NTI1056964623.base = NTI1056964628;
var NNI1056964621 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI1056964621.node = NNI1056964621;
NTI1056964620.base = NTI1056964621;
var NNI1056964628 = {kind: 2, len: 4, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "owned", len: 0, typ: NTI1056964629, name: "owned", sons: null}, 
{kind: 1, offset: "cleanups", len: 0, typ: NTI1056964630, name: "cleanups", sons: null}, 
{kind: 1, offset: "owner", len: 0, typ: NTI1056964623, name: "owner", sons: null}, 
{kind: 1, offset: "contextTable", len: 0, typ: NTI1056964620, name: "contextTable", sons: null}]};
NTI1056964628.node = NNI1056964628;
NTI1056964628.base = NTI33555179;
NTI1056964632.base = NTI1056964628;
var NNI134217749 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217749.node = NNI134217749;
var NNI33555184 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555184.node = NNI33555184;
NTI33555186.base = NTI33555183;
NTI33555187.base = NTI33555183;
var NNI33555183 = {kind: 2, len: 5, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "parent", len: 0, typ: NTI33555186, name: "parent", sons: null}, 
{kind: 1, offset: "name", len: 0, typ: NTI33554450, name: "name", sons: null}, 
{kind: 1, offset: "message", len: 0, typ: NTI33554449, name: "msg", sons: null}, 
{kind: 1, offset: "trace", len: 0, typ: NTI33554449, name: "trace", sons: null}, 
{kind: 1, offset: "up", len: 0, typ: NTI33555187, name: "up", sons: null}]};
NTI33555183.node = NNI33555183;
NTI33555183.base = NTI33555179;
NTI33555184.base = NTI33555183;
NTI134217749.base = NTI33555184;
var NNI134217743 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217743.node = NNI134217743;
var NNI134217741 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217741.node = NNI134217741;
NTI134217741.base = NTI33555184;
NTI134217743.base = NTI134217741;
var NNI134217751 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217751.node = NNI134217751;
NTI134217751.base = NTI33555184;
var NNI134217745 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217745.node = NNI134217745;
NTI134217745.base = NTI33555184;

function cmpClosures(a_p0, b_p1) {
        if (a_p0 !== null && a_p0.ClP_0 !== undefined &&
        b_p1 !== null && b_p1.ClP_0 !== undefined) {
      return a_p0.ClP_0 == b_p1.ClP_0 && a_p0.ClE_0 == b_p1.ClE_0;
    } else {
      return a_p0 == b_p1;
    }
  

  
}

function isObj(obj_p0, subclass_p1) {
  var result_33557473 = false;

  BeforeRet: {
    var x_33557474 = obj_p0;
    if ((x_33557474 == subclass_p1)) {
    result_33557473 = true;
    break BeforeRet;
    }
    
    Label1: {
        Label2: while (true) {
        if (!!((x_33557474 == subclass_p1))) break Label2;
          if ((x_33557474 == null)) {
          result_33557473 = false;
          break BeforeRet;
          }
          
          x_33557474 = x_33557474.base;
        }
    };
    result_33557473 = true;
    break BeforeRet;
  };

  return result_33557473;

}

function setConstr() {
        var result = {};
    for (var i = 0; i < arguments.length; ++i) {
      var x = arguments[i];
      if (typeof(x) == "object") {
        for (var j = x[0]; j <= x[1]; ++j) {
          result[j] = true;
        }
      } else {
        result[x] = true;
      }
    }
    return result;
  

  
}
var ConstSet1 = setConstr(17, 16, 4, 18, 27, 19, 23, 22, 21);

function nimCopy(dest_p0, src_p1, ti_p2) {
  var result_33557360 = null;

    switch (ti_p2.kind) {
    case 21:
    case 22:
    case 23:
    case 5:
      if (!(isFatPointer__system_u2908(ti_p2))) {
      result_33557360 = src_p1;
      }
      else {
        result_33557360 = [src_p1[0], src_p1[1]];
      }
      
      break;
    case 19:
            if (dest_p0 === null || dest_p0 === undefined) {
        dest_p0 = {};
      }
      else {
        for (var key in dest_p0) { delete dest_p0[key]; }
      }
      for (var key in src_p1) { dest_p0[key] = src_p1[key]; }
      result_33557360 = dest_p0;
    
      break;
    case 18:
    case 17:
      if (!((ti_p2.base == null))) {
      result_33557360 = nimCopy(dest_p0, src_p1, ti_p2.base);
      }
      else {
      if ((ti_p2.kind == 17)) {
      result_33557360 = (dest_p0 === null || dest_p0 === undefined) ? {m_type: ti_p2} : dest_p0;
      }
      else {
        result_33557360 = (dest_p0 === null || dest_p0 === undefined) ? {} : dest_p0;
      }
      }
      nimCopyAux(result_33557360, src_p1, ti_p2.node);
      break;
    case 4:
    case 16:
            if(ArrayBuffer.isView(src_p1)) { 
        if(dest_p0 === null || dest_p0 === undefined || dest_p0.length != src_p1.length) {
          dest_p0 = new src_p1.constructor(src_p1);
        } else {
          dest_p0.set(src_p1, 0);
        }
        result_33557360 = dest_p0;
      } else {
        if (src_p1 === null) {
          result_33557360 = null;
        }
        else {
          if (dest_p0 === null || dest_p0 === undefined || dest_p0.length != src_p1.length) {
            dest_p0 = new Array(src_p1.length);
          }
          result_33557360 = dest_p0;
          for (var i = 0; i < src_p1.length; ++i) {
            result_33557360[i] = nimCopy(result_33557360[i], src_p1[i], ti_p2.base);
          }
        }
      }
    
      break;
    case 24:
    case 27:
            if (src_p1 === null) {
        result_33557360 = null;
      }
      else {
        if (dest_p0 === null || dest_p0 === undefined || dest_p0.length != src_p1.length) {
          dest_p0 = new Array(src_p1.length);
        }
        result_33557360 = dest_p0;
        for (var i = 0; i < src_p1.length; ++i) {
          result_33557360[i] = nimCopy(result_33557360[i], src_p1[i], ti_p2.base);
        }
      }
    
      break;
    case 28:
            if (src_p1 !== null) {
        result_33557360 = src_p1.slice(0);
      }
    
      break;
    default: 
      result_33557360 = src_p1;
      break;
    }

  return result_33557360;

}

function mnewString(len_p0) {
        var result = new Array(len_p0);
    for (var i = 0; i < len_p0; i++) {result[i] = 0;}
    return result;
  

  
}

function nimAddStrStr(x_p0, y_p1) {
      var L = y_p1.length;
  for (var i = 0; i < L; ++i) {
    x_p0.push(y_p1[i]);
  }
  

  
}

function toJSStr(s_p0) {
  var result_33556949 = null;

    var res_33557003 = newSeq__system_u2546((s_p0).length);
    var i_33557004 = 0;
    var j_33557005 = 0;
    Label1: {
        Label2: while (true) {
        if (!(i_33557004 < (s_p0).length)) break Label2;
          var c_33557006 = s_p0[i_33557004];
          if ((c_33557006 < 128)) {
          res_33557003[j_33557005] = String.fromCharCode(c_33557006);
          i_33557004 += 1;
          }
          else {
            var helper_33557032 = newSeq__system_u2546(0);
            Label3: {
                Label4: while (true) {
                if (!true) break Label4;
                  var code_33557033 = c_33557006.toString(16);
                  if ((((code_33557033) == null ? 0 : (code_33557033).length) == 1)) {
                  helper_33557032.push("%0");;
                  }
                  else {
                  helper_33557032.push("%");;
                  }
                  
                  helper_33557032.push(code_33557033);;
                  i_33557004 += 1;
                  if ((((s_p0).length <= i_33557004) || (s_p0[i_33557004] < 128))) {
                  break Label3;
                  }
                  
                  c_33557006 = s_p0[i_33557004];
                }
            };
++excHandler;
            try {
            res_33557003[j_33557005] = decodeURIComponent(helper_33557032.join(""));
--excHandler;
} catch (EXCEPTION) {
 var prevJSError = lastJSError;
 lastJSError = EXCEPTION;
 --excHandler;
            raiseDefect();
            res_33557003[j_33557005] = helper_33557032.join("");
            lastJSError = prevJSError;
            } finally {
            }
          }
          
          j_33557005 += 1;
        }
    };
    if (res_33557003.length < j_33557005) { for (var i = res_33557003.length ; i < j_33557005 ; ++i) res_33557003.push(null); }
               else { res_33557003.length = j_33557005; };
    result_33556949 = res_33557003.join("");

  return result_33556949;

}

function raiseException(e_p0, ename_p1) {
    e_p0.name = ename_p1;
    if ((excHandler == 0)) {
    unhandledException(e_p0);
    }
    
    throw e_p0;

  
}

function chckIndx(i_p0, a_p1, b_p2) {
  var result_33557395 = 0;

  BeforeRet: {
    if (((a_p1 <= i_p0) && (i_p0 <= b_p2))) {
    result_33557395 = i_p0;
    break BeforeRet;
    }
    else {
    raiseIndexError(i_p0, a_p1, b_p2);
    }
    
  };

  return result_33557395;

}

function subInt(a_p0, b_p1) {
        var result = a_p0 - b_p1;
    checkOverflowInt(result);
    return result;
  

  
}

function chckRange(i_p0, a_p1, b_p2) {
  var result_33557400 = 0;

  BeforeRet: {
    if (((a_p1 <= i_p0) && (i_p0 <= b_p2))) {
    result_33557400 = i_p0;
    break BeforeRet;
    }
    else {
    raiseRangeError();
    }
    
  };

  return result_33557400;

}

function addInt(a_p0, b_p1) {
        var result = a_p0 + b_p1;
    checkOverflowInt(result);
    return result;
  

  
}

function makeNimstrLit(c_p0) {
      var result = [];
  for (var i = 0; i < c_p0.length; ++i) {
    result[i] = c_p0.charCodeAt(i);
  }
  return result;
  

  
}
if (globalThis.Listener_1056964635 === undefined) {
  globalThis.Listener_1056964635 = [null];
}
if (globalThis.Owner_1056964636 === undefined) {
  globalThis.Owner_1056964636 = [null];
}
if (globalThis.ExecCount_1056964637 === undefined) {
  globalThis.ExecCount_1056964637 = [0];
}
var Updates_1073741851 = [new Array()];
var Effects_1073741875 = [new Array()];
var batchDepth_1073741876 = [0];
var updateComputationCb_1073741879 = [null];

function isFatPointer__system_u2908(ti_p0) {
  var result_33557342 = false;

  BeforeRet: {
    result_33557342 = !((ConstSet1[ti_p0.base.kind] != undefined));
    break BeforeRet;
  };

  return result_33557342;

}

function nimCopyAux(dest_p0, src_p1, n_p2) {
    switch (n_p2.kind) {
    case 0:
      break;
    case 1:
            dest_p0[n_p2.offset] = nimCopy(dest_p0[n_p2.offset], src_p1[n_p2.offset], n_p2.typ);
    
      break;
    case 2:
          for (var i = 0; i < n_p2.sons.length; i++) {
      nimCopyAux(dest_p0, src_p1, n_p2.sons[i]);
    }
    
      break;
    case 3:
            dest_p0[n_p2.offset] = nimCopy(dest_p0[n_p2.offset], src_p1[n_p2.offset], n_p2.typ);
      for (var i = 0; i < n_p2.sons.length; ++i) {
        nimCopyAux(dest_p0, src_p1, n_p2.sons[i][1]);
      }
    
      break;
    }

  
}

function addChars__stdZprivateZdigitsutils_u202(result_p0, result_p0_Idx, x_p1, start_p2, n_p3) {
    var Temporary1;

    var old_335544528 = (result_p0[result_p0_Idx]).length;
    if (result_p0[result_p0_Idx].length < (Temporary1 = (old_335544528 + n_p3), Temporary1)) { for (var i = result_p0[result_p0_Idx].length; i < Temporary1; ++i) result_p0[result_p0_Idx].push(0); }
         else {result_p0[result_p0_Idx].length = Temporary1; };
    Label2: {
      var iHEX60gensym4_335544542 = 0;
      var i_1124073745 = 0;
      Label3: {
          Label4: while (true) {
          if (!(i_1124073745 < n_p3)) break Label4;
            iHEX60gensym4_335544542 = i_1124073745;
            result_p0[result_p0_Idx][(old_335544528 + iHEX60gensym4_335544542)] = x_p1.charCodeAt((start_p2 + iHEX60gensym4_335544542));
            i_1124073745 += 1;
          }
      };
    };

  
}

function addChars__stdZprivateZdigitsutils_u198(result_p0, result_p0_Idx, x_p1) {
    addChars__stdZprivateZdigitsutils_u202(result_p0, result_p0_Idx, x_p1, 0, ((x_p1) == null ? 0 : (x_p1).length));

  
}

function addInt__stdZprivateZdigitsutils_u223(result_p0, result_p0_Idx, x_p1) {
    addChars__stdZprivateZdigitsutils_u198(result_p0, result_p0_Idx, ((x_p1) + ""));

  
}

function addInt__stdZprivateZdigitsutils_u241(result_p0, result_p0_Idx, x_p1) {
    addInt__stdZprivateZdigitsutils_u223(result_p0, result_p0_Idx, BigInt(x_p1));

  
}

function HEX24__systemZdollars_u14(xHEX60gensym0_p0) {
  var result_385875984 = [[]];

    result_385875984[0] = nimCopy(null, [], NTI33554449);
    addInt__stdZprivateZdigitsutils_u241(result_385875984, 0, xHEX60gensym0_p0);

  return result_385875984[0];

}

function add__system_u1972(x_p0, x_p0_Idx, y_p1) {
          if (x_p0[x_p0_Idx] === null) { x_p0[x_p0_Idx] = []; }
      var off = x_p0[x_p0_Idx].length;
      x_p0[x_p0_Idx].length += y_p1.length;
      for (var i = 0; i < y_p1.length; ++i) {
        x_p0[x_p0_Idx][off+i] = y_p1.charCodeAt(i);
      }
    

  
}

function newSeq__system_u2546(len_p0) {
  var result_33556982 = [];

    result_33556982 = new Array(len_p0); for (var i = 0 ; i < len_p0 ; ++i) { result_33556982[i] = null; }
  return result_33556982;

}

function isNimException__system_u2043() {
    return lastJSError && lastJSError.m_type;

  
}

function getCurrentException() {
  var result_33556478 = null;

    if (isNimException__system_u2043()) {
    result_33556478 = lastJSError;
    }
    

  return result_33556478;

}

function raiseDefect() {
    if (isNimException__system_u2043()) {
    var e_33556694 = getCurrentException();
    if (isObj(e_33556694.m_type, NTI33555184)) {
    if ((excHandler == 0)) {
    unhandledException(e_33556694);
    }
    
    throw e_33556694;
    }
    
    }
    

  
}

function unhandledException(e_p0) {
    var buf_33556688 = [[]];
    if (!(((e_p0.message).length == 0))) {
    nimAddStrStr(buf_33556688[0], [69,114,114,111,114,58,32,117,110,104,97,110,100,108,101,100,32,101,120,99,101,112,116,105,111,110,58,32]);;
    nimAddStrStr(buf_33556688[0], e_p0.message);;
    }
    else {
    nimAddStrStr(buf_33556688[0], [69,114,114,111,114,58,32,117,110,104,97,110,100,108,101,100,32,101,120,99,101,112,116,105,111,110]);;
    }
    
    nimAddStrStr(buf_33556688[0], [32,91]);;
    add__system_u1972(buf_33556688, 0, e_p0.name);
    nimAddStrStr(buf_33556688[0], [93,10]);;
    var cbuf_33556689 = toJSStr(buf_33556688[0]);
      if (typeof(Error) !== "undefined") {
    throw new Error(cbuf_33556689);
  }
  else {
    throw cbuf_33556689;
  }
  

  
}

function raiseIndexError(i_p0, a_p1, b_p2) {
    var Temporary1;

    if ((b_p2 < a_p1)) {
    Temporary1 = [105,110,100,101,120,32,111,117,116,32,111,102,32,98,111,117,110,100,115,44,32,116,104,101,32,99,111,110,116,97,105,110,101,114,32,105,115,32,101,109,112,116,121];
    }
    else {
    Temporary1 = ([105,110,100,101,120,32]).concat(HEX24__systemZdollars_u14(i_p0),[32,110,111,116,32,105,110,32],HEX24__systemZdollars_u14(a_p1),[32,46,46,32],HEX24__systemZdollars_u14(b_p2));
    }
    
    raiseException({message: nimCopy(null, Temporary1, NTI33554449), parent: null, m_type: NTI134217749, name: null, trace: [], up: null}, "IndexDefect");

  
}

function raiseOverflow() {
    raiseException({message: [111,118,101,114,45,32,111,114,32,117,110,100,101,114,102,108,111,119], parent: null, m_type: NTI134217743, name: null, trace: [], up: null}, "OverflowDefect");

  
}

function checkOverflowInt(a_p0) {
        if (a_p0 > 2147483647 || a_p0 < -2147483648) raiseOverflow();
  

  
}

function raiseRangeError() {
    raiseException({message: [118,97,108,117,101,32,111,117,116,32,111,102,32,114,97,110,103,101], parent: null, m_type: NTI134217751, name: null, trace: [], up: null}, "RangeDefect");

  
}

function removeSourceObserver__OOZOOZOOZOOZOOZisonimZsrcZisonimZcoreZgraph_u94(source_p0, obsSlot_p1) {
    var lastIdx_1056964708 = subInt((source_p0.observers).length, 1);
    if (!((obsSlot_p1 == lastIdx_1056964708))) {
    var movedObs_1056964709 = source_p0.observers[chckIndx(lastIdx_1056964708, 0, (source_p0.observers).length - 1)];
    var movedCSlot_1056964710 = source_p0.observerSlots[chckIndx(lastIdx_1056964708, 0, (source_p0.observerSlots).length - 1)];
    source_p0.observers[chckIndx(obsSlot_p1, 0, (source_p0.observers).length - 1)] = movedObs_1056964709;
    source_p0.observerSlots[chckIndx(obsSlot_p1, 0, (source_p0.observerSlots).length - 1)] = movedCSlot_1056964710;
    if ((movedCSlot_1056964710 < (movedObs_1056964709.sourceSlots).length)) {
    movedObs_1056964709.sourceSlots[chckIndx(movedCSlot_1056964710, 0, (movedObs_1056964709.sourceSlots).length - 1)] = obsSlot_p1;
    }
    
    }
    
    if (source_p0.observers.length < chckRange(lastIdx_1056964708, 0, 2147483647)) { for (var i = source_p0.observers.length ; i < chckRange(lastIdx_1056964708, 0, 2147483647) ; ++i) source_p0.observers.push(null); }
               else { source_p0.observers.length = chckRange(lastIdx_1056964708, 0, 2147483647); };
    if (source_p0.observerSlots.length < chckRange(lastIdx_1056964708, 0, 2147483647)) { for (var i = source_p0.observerSlots.length ; i < chckRange(lastIdx_1056964708, 0, 2147483647) ; ++i) source_p0.observerSlots.push(0); }
               else { source_p0.observerSlots.length = chckRange(lastIdx_1056964708, 0, 2147483647); };

  
}

function sysFatal__stdZassertions_u46(message_p1) {
    raiseException({message: nimCopy(null, message_p1, NTI33554449), m_type: NTI134217745, parent: null, name: null, trace: [], up: null}, "AssertionDefect");

  
}

function raiseAssert__stdZassertions_u44(msg_p0) {
    sysFatal__stdZassertions_u46(msg_p0);

  
}

function failedAssertImpl__stdZassertions_u86(msg_p0) {
    raiseAssert__stdZassertions_u44(msg_p0);

  
}

function cleanNode__OOZOOZOOZOOZOOZisonimZsrcZisonimZcoreZgraph_u115(node_p0) {
    if (isObj(node_p0.m_type, NTI1056964632)) {
    var comp_1056964732 = node_p0;
    Label1: {
      var i_1056964740 = 0;
      var colontmp__1124073727 = 0;
      colontmp__1124073727 = (comp_1056964732.sources).length;
      var i_1124073728 = 0;
      Label2: {
          Label3: while (true) {
          if (!(i_1124073728 < colontmp__1124073727)) break Label3;
            i_1056964740 = i_1124073728;
            var source_1056964741 = comp_1056964732.sources[chckIndx(i_1056964740, 0, (comp_1056964732.sources).length - 1)];
            var obsSlot_1056964742 = comp_1056964732.sourceSlots[chckIndx(i_1056964740, 0, (comp_1056964732.sourceSlots).length - 1)];
            removeSourceObserver__OOZOOZOOZOOZOOZisonimZsrcZisonimZcoreZgraph_u94(source_1056964741, obsSlot_1056964742);
            i_1124073728 = addInt(i_1124073728, 1);
          }
      };
    };
    if (comp_1056964732.sources.length < 0) { for (var i = comp_1056964732.sources.length ; i < 0 ; ++i) comp_1056964732.sources.push(null); }
               else { comp_1056964732.sources.length = 0; };
    if (comp_1056964732.sourceSlots.length < 0) { for (var i = comp_1056964732.sourceSlots.length ; i < 0 ; ++i) comp_1056964732.sourceSlots.push(0); }
               else { comp_1056964732.sourceSlots.length = 0; };
    }
    
    Label4: {
      var child_1056964772 = null;
      var i_1124073732 = 0;
      var L_1124073733 = (node_p0.owned).length;
      Label5: {
          Label6: while (true) {
          if (!(i_1124073732 < L_1124073733)) break Label6;
            child_1056964772 = node_p0.owned[chckIndx(i_1124073732, 0, (node_p0.owned).length - 1)];
            cleanNode__OOZOOZOOZOOZOOZisonimZsrcZisonimZcoreZgraph_u115(child_1056964772);
            i_1124073732 += 1;
            if (!(((node_p0.owned).length == L_1124073733))) {
            failedAssertImpl__stdZassertions_u86(makeNimstrLit("/nix/store/cdgicjj228dg30lm11skn2y8sshsj1kx-nim-2.2.8/nim/lib/system/iterators.nim(254, 11) `len(a) == L` the length of the seq changed while iterating over it"));
            }
            
          }
      };
    };
    if (node_p0.owned.length < 0) { for (var i = node_p0.owned.length ; i < 0 ; ++i) node_p0.owned.push(null); }
               else { node_p0.owned.length = 0; };
    Label7: {
      var cleanup_1056964799 = null;
      var i_1124073737 = 0;
      var L_1124073738 = (node_p0.cleanups).length;
      Label8: {
          Label9: while (true) {
          if (!(i_1124073737 < L_1124073738)) break Label9;
            cleanup_1056964799 = node_p0.cleanups[chckIndx(i_1124073737, 0, (node_p0.cleanups).length - 1)];
            cleanup_1056964799();
            i_1124073737 += 1;
            if (!(((node_p0.cleanups).length == L_1124073738))) {
            failedAssertImpl__stdZassertions_u86(makeNimstrLit("/nix/store/cdgicjj228dg30lm11skn2y8sshsj1kx-nim-2.2.8/nim/lib/system/iterators.nim(254, 11) `len(a) == L` the length of the seq changed while iterating over it"));
            }
            
          }
      };
    };
    if (node_p0.cleanups.length < 0) { for (var i = node_p0.cleanups.length ; i < 0 ; ++i) node_p0.cleanups.push(null); }
               else { node_p0.cleanups.length = 0; };

  
}

function updateComputation__OOZOOZOOZOOZOOZisonimZsrcZisonimZcoreZcomputation_u14(comp_p0) {
  BeforeRet: {
    if (cmpClosures(comp_p0.fn, null)) {
    break BeforeRet;
    }
    
    cleanNode__OOZOOZOOZOOZOOZisonimZsrcZisonimZcoreZgraph_u115(comp_p0);
    comp_p0.state = 0;
    var prevListener_1124073492 = Listener_1056964635[0];
    var prevOwner_1124073493 = Owner_1056964636[0];
    Listener_1056964635[0] = comp_p0;
    Owner_1056964636[0] = comp_p0;
    try {
    comp_p0.fn();
    } finally {
    Listener_1056964635[0] = prevListener_1124073492;
    Owner_1056964636[0] = prevOwner_1124073493;
    }
    comp_p0.updatedAt = ExecCount_1056964637[0];
  };

  
}
var Temporary1;
Temporary1 = updateComputation__OOZOOZOOZOOZOOZisonimZsrcZisonimZcoreZcomputation_u14.bind(null); Temporary1.ClP_0 = updateComputation__OOZOOZOOZOOZOOZisonimZsrcZisonimZcoreZcomputation_u14; Temporary1.ClE_0 = null;
updateComputationCb_1073741879[0] = Temporary1;
var objectID_1207959730 = [0];
if (globalThis.nextMockNodeId_1627389985 === undefined) {
  globalThis.nextMockNodeId_1627389985 = [0];
}
var pendingCallbacks_1761607689 = [[]];
if (globalThis.storeIdCounter_1744830474 === undefined) {
  globalThis.storeIdCounter_1744830474 = [0];
}
