/* Generated by the Nim Compiler v1.6.20 */
var framePtr = null;
var excHandler = 0;
var lastJSError = null;
var NTI33555117 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555128 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555131 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555123 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555125 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555086 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555168 = {size: 0, kind: 22, base: null, node: null, finalizer: null};
var NTI33554439 = {size: 0,kind: 28,base: null,node: null,finalizer: null};
var NTI33554440 = {size: 0,kind: 29,base: null,node: null,finalizer: null};
var NTI33555167 = {size: 0, kind: 22, base: null, node: null, finalizer: null};
var NTI33555115 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555116 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555133 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NNI33555133 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555133.node = NNI33555133;
var NNI33555116 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555116.node = NNI33555116;
NTI33555167.base = NTI33555115;
NTI33555168.base = NTI33555115;
var NNI33555115 = {kind: 2, len: 5, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "parent", len: 0, typ: NTI33555167, name: "parent", sons: null},
{kind: 1, offset: "name", len: 0, typ: NTI33554440, name: "name", sons: null},
{kind: 1, offset: "message", len: 0, typ: NTI33554439, name: "msg", sons: null},
{kind: 1, offset: "trace", len: 0, typ: NTI33554439, name: "trace", sons: null},
{kind: 1, offset: "up", len: 0, typ: NTI33555168, name: "up", sons: null}]};
NTI33555115.node = NNI33555115;
var NNI33555086 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555086.node = NNI33555086;
NTI33555115.base = NTI33555086;
NTI33555116.base = NTI33555115;
NTI33555133.base = NTI33555116;
var NNI33555125 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555125.node = NNI33555125;
var NNI33555123 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555123.node = NNI33555123;
NTI33555123.base = NTI33555116;
NTI33555125.base = NTI33555123;
var NNI33555131 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555131.node = NNI33555131;
NTI33555131.base = NTI33555116;
var NNI33555128 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555128.node = NNI33555128;
var NNI33555117 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555117.node = NNI33555117;
NTI33555117.base = NTI33555115;
NTI33555128.base = NTI33555117;

function makeNimstrLit(c_33556801) {
      var result = [];
  for (var i = 0; i < c_33556801.length; ++i) {
    result[i] = c_33556801.charCodeAt(i);
  }
  return result;



}

function mnewString(len_33556893) {
        return new Array(len_33556893);



}

function toJSStr(s_33556807) {
                    var Temporary5;

  var result_33556808 = null;

    var res_33556842 = newSeq_33556825((s_33556807).length);
    var i_33556843 = 0;
    var j_33556844 = 0;
    Label1: do {
        Label2: while (true) {
        if (!(i_33556843 < (s_33556807).length)) break Label2;
          var c_33556845 = s_33556807[i_33556843];
          if ((c_33556845 < 128)) {
          res_33556842[j_33556844] = String.fromCharCode(c_33556845);
          i_33556843 += 1;
          }
          else {
            var helper_33556857 = newSeq_33556825(0);
            Label3: do {
                Label4: while (true) {
                if (!true) break Label4;
                  var code_33556858 = c_33556845.toString(16);
                  if ((((code_33556858) == null ? 0 : (code_33556858).length) == 1)) {
                  helper_33556857.push("%0");;
                  }
                  else {
                  helper_33556857.push("%");;
                  }

                  helper_33556857.push(code_33556858);;
                  i_33556843 += 1;
                    if (((s_33556807).length <= i_33556843)) Temporary5 = true; else {                      Temporary5 = (s_33556807[i_33556843] < 128);                    }                  if (Temporary5) {
                  break Label3;
                  }

                  c_33556845 = s_33556807[i_33556843];
                }
            } while (false);
++excHandler;
            try {
            res_33556842[j_33556844] = decodeURIComponent(helper_33556857.join(""));
--excHandler;
} catch (EXCEPTION) {
 var prevJSError = lastJSError;
 lastJSError = EXCEPTION;
 --excHandler;
            res_33556842[j_33556844] = helper_33556857.join("");
            lastJSError = prevJSError;
            } finally {
            }
          }

          j_33556844 += 1;
        }
    } while (false);
    if (res_33556842.length < j_33556844) { for (var i = res_33556842.length ; i < j_33556844 ; ++i) res_33556842.push(null); }
               else { res_33556842.length = j_33556844; };
    result_33556808 = res_33556842.join("");

  return result_33556808;

}

function raiseException(e_33556667, ename_33556668) {
    e_33556667.name = ename_33556668;
    if ((excHandler == 0)) {
    unhandledException(e_33556667);
    }

    throw e_33556667;


}

function chckRange(i_33557189, a_33557190, b_33557191) {
      var Temporary1;

  var result_33557192 = 0;

  BeforeRet: do {
      if (!(a_33557190 <= i_33557189)) Temporary1 = false; else {        Temporary1 = (i_33557189 <= b_33557191);      }    if (Temporary1) {
    result_33557192 = i_33557189;
    break BeforeRet;
    }
    else {
    raiseRangeError();
    }

  } while (false);

  return result_33557192;

}

function setConstr() {
        var result = {};
    for (var i = 0; i < arguments.length; ++i) {
      var x = arguments[i];
      if (typeof(x) == "object") {
        for (var j = x[0]; j <= x[1]; ++j) {
          result[j] = true;
        }
      } else {
        result[x] = true;
      }
    }
    return result;



}
var ConstSet1 = setConstr(17, 16, 4, 18, 27, 19, 23, 22, 21);

function nimCopy(dest_33557140, src_33557141, ti_33557142) {
  var result_33557151 = null;

    switch (ti_33557142.kind) {
    case 21:
    case 22:
    case 23:
    case 5:
      if (!(isFatPointer_33557131(ti_33557142))) {
      result_33557151 = src_33557141;
      }
      else {
        result_33557151 = [src_33557141[0], src_33557141[1]];
      }

      break;
    case 19:
            if (dest_33557140 === null || dest_33557140 === undefined) {
        dest_33557140 = {};
      }
      else {
        for (var key in dest_33557140) { delete dest_33557140[key]; }
      }
      for (var key in src_33557141) { dest_33557140[key] = src_33557141[key]; }
      result_33557151 = dest_33557140;

      break;
    case 18:
    case 17:
      if (!((ti_33557142.base == null))) {
      result_33557151 = nimCopy(dest_33557140, src_33557141, ti_33557142.base);
      }
      else {
      if ((ti_33557142.kind == 17)) {
      result_33557151 = (dest_33557140 === null || dest_33557140 === undefined) ? {m_type: ti_33557142} : dest_33557140;
      }
      else {
        result_33557151 = (dest_33557140 === null || dest_33557140 === undefined) ? {} : dest_33557140;
      }
      }
      nimCopyAux(result_33557151, src_33557141, ti_33557142.node);
      break;
    case 24:
    case 4:
    case 27:
    case 16:
            if (src_33557141 === null) {
        result_33557151 = null;
      }
      else {
        if (dest_33557140 === null || dest_33557140 === undefined || dest_33557140.length != src_33557141.length) {
          dest_33557140 = new Array(src_33557141.length);
        }
        result_33557151 = dest_33557140;
        for (var i = 0; i < src_33557141.length; ++i) {
          result_33557151[i] = nimCopy(result_33557151[i], src_33557141[i], ti_33557142.base);
        }
      }

      break;
    case 28:
            if (src_33557141 !== null) {
        result_33557151 = src_33557141.slice(0);
      }

      break;
    default:
      result_33557151 = src_33557141;
      break;
    }

  return result_33557151;

}

function addInt(a_33556940, b_33556941) {
        var result = a_33556940 + b_33556941;
    checkOverflowInt(result);
    return result;



}

function chckIndx(i_33557184, a_33557185, b_33557186) {
      var Temporary1;

  var result_33557187 = 0;

  BeforeRet: do {
      if (!(a_33557185 <= i_33557184)) Temporary1 = false; else {        Temporary1 = (i_33557184 <= b_33557186);      }    if (Temporary1) {
    result_33557187 = i_33557184;
    break BeforeRet;
    }
    else {
    raiseIndexError(i_33557184, a_33557185, b_33557186);
    }

  } while (false);

  return result_33557187;

}

function subInt(a_33556944, b_33556945) {
        var result = a_33556944 - b_33556945;
    checkOverflowInt(result);
    return result;



}
var ConstSet2 = setConstr([65, 90]);

function cstrToNimstr(c_33556804) {
      var ln = c_33556804.length;
  var result = new Array(ln);
  var r = 0;
  for (var i = 0; i < ln; ++i) {
    var ch = c_33556804.charCodeAt(i);

    if (ch < 128) {
      result[r] = ch;
    }
    else {
      if (ch < 2048) {
        result[r] = (ch >> 6) | 192;
      }
      else {
        if (ch < 55296 || ch >= 57344) {
          result[r] = (ch >> 12) | 224;
        }
        else {
            ++i;
            ch = 65536 + (((ch & 1023) << 10) | (c_33556804.charCodeAt(i) & 1023));
            result[r] = (ch >> 18) | 240;
            ++r;
            result[r] = ((ch >> 12) & 63) | 128;
        }
        ++r;
        result[r] = ((ch >> 6) & 63) | 128;
      }
      ++r;
      result[r] = (ch & 63) | 128;
    }
    ++r;
  }
  return result;



}
if (!Math.trunc) {
  Math.trunc = function(v) {
    v = +v;
    if (!isFinite(v)) return v;
    return (v - v % 1) || (v < 0 ? -0 : v === 0 ? v : 0);
  };
}

var objectID_922747042 = [0];
var svgNamespace_1056964859 = [makeNimstrLit("http://www.w3.org/2000/svg")];
var mathNamespace_1056964860 = [makeNimstrLit("http://www.w3.org/1998/Math/MathML")];
var gid_1056965237 = [0];
var jsNl_1023410448 = ["\n"];

function add_33556419(x_33556420, x_33556420_Idx, y_33556421) {
          if (x_33556420[x_33556420_Idx] === null) { x_33556420[x_33556420_Idx] = []; }
      var off = x_33556420[x_33556420_Idx].length;
      x_33556420[x_33556420_Idx].length += y_33556421.length;
      for (var i = 0; i < y_33556421.length; ++i) {
        x_33556420[x_33556420_Idx][off+i] = y_33556421.charCodeAt(i);
      }



}

function newSeq_33556825(len_33556827) {
  var result_33556828 = [];

    result_33556828 = new Array(len_33556827); for (var i = 0 ; i < len_33556827 ; ++i) { result_33556828[i] = null; }
  return result_33556828;

}

function unhandledException(e_33556663) {
    var buf_33556664 = [[]];
    if (!(((e_33556663.message).length == 0))) {
    buf_33556664[0].push.apply(buf_33556664[0], makeNimstrLit("Error: unhandled exception: "));;
    buf_33556664[0].push.apply(buf_33556664[0], e_33556663.message);;
    }
    else {
    buf_33556664[0].push.apply(buf_33556664[0], makeNimstrLit("Error: unhandled exception"));;
    }

    buf_33556664[0].push.apply(buf_33556664[0], makeNimstrLit(" ["));;
    add_33556419(buf_33556664, 0, e_33556663.name);
    buf_33556664[0].push.apply(buf_33556664[0], makeNimstrLit("]\x0A"));;
    var cbuf_33556665 = toJSStr(buf_33556664[0]);
      if (typeof(Error) !== "undefined") {
    throw new Error(cbuf_33556665);
  }
  else {
    throw cbuf_33556665;
  }



}

function raiseRangeError() {
    raiseException({message: makeNimstrLit("value out of range"), parent: null, m_type: NTI33555133, name: null, trace: [], up: null}, "RangeDefect");


}

function isFatPointer_33557131(ti_33557132) {
  var result_33557133 = false;

  BeforeRet: do {
    result_33557133 = !((ConstSet1[ti_33557132.base.kind] != undefined));
    break BeforeRet;
  } while (false);

  return result_33557133;

}

function nimCopyAux(dest_33557144, src_33557145, n_33557146) {
    switch (n_33557146.kind) {
    case 0:
      break;
    case 1:
            dest_33557144[n_33557146.offset] = nimCopy(dest_33557144[n_33557146.offset], src_33557145[n_33557146.offset], n_33557146.typ);

      break;
    case 2:
          for (var i = 0; i < n_33557146.sons.length; i++) {
      nimCopyAux(dest_33557144, src_33557145, n_33557146.sons[i]);
    }

      break;
    case 3:
            dest_33557144[n_33557146.offset] = nimCopy(dest_33557144[n_33557146.offset], src_33557145[n_33557146.offset], n_33557146.typ);
      for (var i = 0; i < n_33557146.sons.length; ++i) {
        nimCopyAux(dest_33557144, src_33557145, n_33557146.sons[i][1]);
      }

      break;
    }


}

function raiseOverflow() {
    raiseException({message: makeNimstrLit("over- or underflow"), parent: null, m_type: NTI33555125, name: null, trace: [], up: null}, "OverflowDefect");


}

function checkOverflowInt(a_33556938) {
        if (a_33556938 > 2147483647 || a_33556938 < -2147483648) raiseOverflow();



}

function addChars_251658415(result_251658417, result_251658417_Idx, x_251658418, start_251658419, n_251658420) {
    var old_251658421 = (result_251658417[result_251658417_Idx]).length;
    (result_251658417[result_251658417_Idx].length = chckRange(addInt(old_251658421, n_251658420), 0, 2147483647));
    Label1: do {
      var iHEX60gensym4_251658435 = 0;
      var i_1174405222 = 0;
      Label2: do {
          Label3: while (true) {
          if (!(i_1174405222 < n_251658420)) break Label3;
            iHEX60gensym4_251658435 = i_1174405222;
            result_251658417[result_251658417_Idx][chckIndx(addInt(old_251658421, iHEX60gensym4_251658435), 0, (result_251658417[result_251658417_Idx]).length - 1)] = x_251658418.charCodeAt(chckIndx(addInt(start_251658419, iHEX60gensym4_251658435), 0, (x_251658418).length - 1));
            i_1174405222 = addInt(i_1174405222, 1);
          }
      } while (false);
    } while (false);


}

function addChars_251658411(result_251658413, result_251658413_Idx, x_251658414) {
    addChars_251658415(result_251658413, result_251658413_Idx, x_251658414, 0, ((x_251658414) == null ? 0 : (x_251658414).length));


}

function addInt_251658436(result_251658437, result_251658437_Idx, x_251658438) {
    addChars_251658411(result_251658437, result_251658437_Idx, ((x_251658438) + ""));


}

function addInt_251658457(result_251658458, result_251658458_Idx, x_251658459) {
    addInt_251658436(result_251658458, result_251658458_Idx, x_251658459);


}

function HEX24_335544323(x_335544324) {
  var result_335544325 = [[]];

    addInt_251658457(result_335544325, 0, x_335544324);

  return result_335544325[0];

}

function raiseIndexError(i_33556754, a_33556755, b_33556756) {
    var Temporary1;

    if ((b_33556756 < a_33556755)) {
    Temporary1 = makeNimstrLit("index out of bounds, the container is empty");
    }
    else {
    Temporary1 = (makeNimstrLit("index ") || []).concat(HEX24_335544323(i_33556754) || [],makeNimstrLit(" not in ") || [],HEX24_335544323(a_33556755) || [],makeNimstrLit(" .. ") || [],HEX24_335544323(b_33556756) || []);
    }

    raiseException({message: nimCopy(null, Temporary1, NTI33554439), parent: null, m_type: NTI33555131, name: null, trace: [], up: null}, "IndexDefect");


}

function nimIdentNormalize_452984937(s_452984938) {
  var result_452984939 = [];

  BeforeRet: do {
    result_452984939 = nimCopy(null, mnewString(chckRange((s_452984938).length, 0, 2147483647)), NTI33554439);
    if (((s_452984938).length == 0)) {
    break BeforeRet;
    }

    result_452984939[chckIndx(0, 0, (result_452984939).length - 1)] = s_452984938[chckIndx(0, 0, (s_452984938).length - 1)];
    var j_452984940 = 1;
    Label1: do {
      var i_452984945 = 0;
      var colontmp__1174405174 = 0;
      colontmp__1174405174 = subInt((s_452984938).length, 1);
      var res_1174405175 = 1;
      Label2: do {
          Label3: while (true) {
          if (!(res_1174405175 <= colontmp__1174405174)) break Label3;
            i_452984945 = res_1174405175;
            if ((ConstSet2[s_452984938[chckIndx(i_452984945, 0, (s_452984938).length - 1)]] != undefined)) {
            result_452984939[chckIndx(j_452984940, 0, (result_452984939).length - 1)] = chckRange(addInt(s_452984938[chckIndx(i_452984945, 0, (s_452984938).length - 1)], 32), 0, 255);
            j_452984940 = addInt(j_452984940, 1);
            }
            else {
            if (!((s_452984938[chckIndx(i_452984945, 0, (s_452984938).length - 1)] == 95))) {
            result_452984939[chckIndx(j_452984940, 0, (result_452984939).length - 1)] = s_452984938[chckIndx(i_452984945, 0, (s_452984938).length - 1)];
            j_452984940 = addInt(j_452984940, 1);
            }
            }
            res_1174405175 = addInt(res_1174405175, 1);
          }
      } while (false);
    } while (false);
    if (!((j_452984940 == (s_452984938).length))) {
    (result_452984939.length = chckRange(j_452984940, 0, 2147483647));
    }

  } while (false);

  return result_452984939;

}

function parseEnum_1174405132(s_1174405134) {
    var Temporary1;

  var result_1174405135 = 0;

    switch (toJSStr(nimIdentNormalize_452984937(s_1174405134))) {
    case "Debug":
      Temporary1 = 0;
      break;
    case "Info":
      Temporary1 = 1;
      break;
    case "Warn":
      Temporary1 = 2;
      break;
    case "Error":
      Temporary1 = 3;
      break;
    default:
      raiseException({message: (makeNimstrLit("Invalid enum value: ") || []).concat(s_1174405134 || []), parent: null, m_type: NTI33555128, name: null, trace: [], up: null}, "ValueError");
      break;
    }
    result_1174405135 = Temporary1;

  return result_1174405135;

}

function get_1191182353(a_1191182354, default_1191182355) {
  var result_1191182356 = [];

  BeforeRet: do {
    var r_1191182357 = process.env[toJSStr(a_1191182354)];
    if ((0 < ((r_1191182357) == null ? 0 : (r_1191182357).length))) {
    result_1191182356 = nimCopy(null, cstrToNimstr(r_1191182357), NTI33554439);
    break BeforeRet;
    }
    else {
      result_1191182356 = nimCopy(null, default_1191182355, NTI33554439);
      break BeforeRet;
    }

  } while (false);

  return result_1191182356;

}
var LOG_LEVEL_1174405215 = parseEnum_1174405132(get_1191182353(makeNimstrLit("CODETRACER_LOG_LEVEL"), makeNimstrLit("INFO")));
var ipcRef_838860818 = [null];
var lspUrl_838860819 = [[]];
var lspUrlObservers_838860826 = [[]];
var lastLspError_838860827 = [[]];
var activeClient_704643118 = [null];
var wsConnection_704643119 = [null];
var reconnectTimer_704643120 = [0];
