//! M5 cross-read proof — the collapsed `memwrites.tc` (`WLOG`) / `linehits.tc`
//! (`LHTS|v1`) byte images the Rust collapse encoder
//! ([`db_backend::ctfs_trace_reader::server_prep_encoding`]) produces are
//! BYTE-IDENTICAL to the authoritative Nim writers' output.
//!
//! The fixtures (`tests/fixtures/server_prep/{memwrites.tc,linehits.tc,
//! server_prep.manifest}`) are generated by the native-recorder Nim generator
//! `codetracer-native-recorder/ct_emulator/tests/gen_server_prep_crossread_fixture.nim`,
//! which emits `memwrites.tc` through the REAL `write_log.nim` `WriteLogWriter`
//! (the same encoder `mcrOmniscientWriteToPath` drives) and `linehits.tc` through
//! the documented `LHTS|v1` layout. The manifest lists the writes / line-hits so
//! this test can rebuild the same logical region and re-encode it with the Rust
//! collapse encoder, then assert the two byte streams match exactly.
//!
//! This is the load-bearing proof for the §6.7.3 interchangeability invariant: a
//! locally lazy-populated + collapsed slice and a server-prepped slice are
//! byte-for-byte identical, so one can replace the other without reconciliation.
//!
//! If the Nim-written fixture is absent (a checkout where the native recorder has
//! not produced it), the test SKIPS the cross-check cleanly (printing
//! `SKIPPED: …`) rather than failing — mirroring the M3/M4 cross-read tests.

#![allow(clippy::expect_used, clippy::unwrap_used)]

use std::path::PathBuf;

use db_backend::ctfs_trace_reader::interval_tagged_map::MemWriteEntry;
use db_backend::ctfs_trace_reader::server_prep_encoding::{
    encode_linehits, encode_memwrites, CollapsedLinehits, CollapsedMemwrites,
};

fn fixture_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/server_prep")
}

/// Parse the Nim-written manifest into per-address writes (sorted ascending by
/// address, each tick-sorted) and per-line tick lists.
#[allow(clippy::type_complexity)]
fn parse_manifest(text: &str) -> (Vec<(u64, Vec<MemWriteEntry>)>, Vec<(u32, u32, Vec<u64>)>) {
    use std::collections::BTreeMap;
    let mut writes: BTreeMap<u64, Vec<MemWriteEntry>> = BTreeMap::new();
    let mut lines: Vec<(u32, u32, Vec<u64>)> = Vec::new();
    for line in text.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let mut p = line.split_whitespace();
        match p.next() {
            Some("W") => {
                let address: u64 = p.next().unwrap().parse().unwrap();
                let tick: u64 = p.next().unwrap().parse().unwrap();
                let pc: u64 = p.next().unwrap().parse().unwrap();
                let size: u32 = p.next().unwrap().parse().unwrap();
                let old_value: u64 = p.next().unwrap().parse().unwrap();
                let new_value: u64 = p.next().unwrap().parse().unwrap();
                writes.entry(address).or_default().push(MemWriteEntry {
                    tick,
                    pc,
                    size,
                    old_value,
                    new_value,
                });
            }
            Some("L") => {
                let file_id: u32 = p.next().unwrap().parse().unwrap();
                let line_no: u32 = p.next().unwrap().parse().unwrap();
                let ticks: Vec<u64> = p.map(|t| t.parse().unwrap()).collect();
                lines.push((file_id, line_no, ticks));
            }
            _ => {}
        }
    }
    for list in writes.values_mut() {
        list.sort_by_key(|w| w.tick);
    }
    (writes.into_iter().collect(), lines)
}

#[test]
fn collapse_bytes_match_nim_server_prep_writer() {
    let dir = fixture_dir();
    let mem_path = dir.join("memwrites.tc");
    let line_path = dir.join("linehits.tc");
    let man_path = dir.join("server_prep.manifest");

    if !mem_path.exists() || !man_path.exists() {
        eprintln!(
            "SKIPPED: collapse_bytes_match_nim_server_prep_writer — Nim fixture absent at {}. \
             Generate it with: direnv exec codetracer-native-recorder nim c -r --path:ct_emulator/src \
             ct_emulator/tests/gen_server_prep_crossread_fixture.nim",
            dir.display()
        );
        return;
    }

    let manifest = std::fs::read_to_string(&man_path).expect("read manifest");
    let (per_address, per_line) = parse_manifest(&manifest);

    // Re-encode with the Rust collapse encoder and compare to the Nim-written
    // memwrites.tc byte-for-byte.
    let rust_mem = encode_memwrites(&CollapsedMemwrites { per_address });
    let nim_mem = std::fs::read(&mem_path).expect("read nim memwrites.tc");
    assert_eq!(
        rust_mem, nim_mem,
        "Rust collapse memwrites bytes must be byte-identical to the Nim WriteLogWriter output"
    );

    // linehits.tc, when present.
    if line_path.exists() {
        let rust_line = encode_linehits(&CollapsedLinehits { per_line });
        let nim_line = std::fs::read(&line_path).expect("read nim linehits.tc");
        assert_eq!(
            rust_line, nim_line,
            "Rust collapse linehits bytes must be byte-identical to the Nim LHTS writer output"
        );
    }
}
