//! Every committed `.ct` fixture whose generator recorded steps at known lines
//! must read those steps back at THOSE lines.
//!
//! # Why a fixture opening cleanly is not the property
//!
//! The line-only `global_position_index` encode is
//! `prefix_sum[file_id] + (line - 1)`, the exact inverse of the decode
//! [`db_backend::ctfs_trace_reader::line_position_space`] performs. A writer
//! that packed `prefix_sum[file_id] + line` instead produces addresses that are
//! all still INSIDE the trace's own space, so every step resolves to a real
//! file and a real line — each one exactly one line above where it was
//! recorded — and nothing anywhere reports an error. A fixture regenerated by
//! such a writer opens, serves steps, and answers every structural assertion
//! the suites next door make about it (span ranges, chunk boundaries, call
//! trees, altitudes), because none of those read a line. It is wrong only in
//! the one number a debugger shows the user.
//!
//! `meta.dat`'s schema version is what refuses a container written under the
//! superseded encode (`ctfs_superseded_line_index_refusal_test.rs`), but a
//! version is a claim by the writer, not a measurement of the bytes. This test
//! is the measurement: it takes each fixture's recorded `(path, line)` table
//! from the generator that produced it and requires the production reader to
//! give those pairs back.
//!
//! # No mocks, and no skips
//!
//! The fixtures are committed, so every case here always runs; a missing one
//! fails loudly. They are opened through `CTFSTraceReader::open`, the same
//! constructor `dap_server` uses.
//!
//! # What is NOT covered here
//!
//! `tests/fixtures/xos/xos_hello.ct` (a `ct_cli record` capture whose thread
//! stream carries no per-line steps), `tests/fixtures/stylus-fund-trace`
//! (a legacy `events.log` bundle whose steps carry `(path_id, line)` directly
//! rather than a packed global index) and `tests/fixtures/gdscript` (produced
//! by the patched Godot fork, which is an unstarted deliverable) have no
//! line-only step stream for this assertion to measure.
//!
//! Two of the six request-panel fixtures are in the same position and for
//! reasons their own README records:
//!
//! * `native_nginx/nginx.ct` is a `ct-mcr` capture of a real nginx. It ships
//!   no `steps.dat` and an EMPTY path table, so there is no `(path, line)`
//!   anywhere in it to read back. Its span coordinates are GEIDs — positions
//!   in the recording's event ordering.
//! * `elixir_plug/app.ct` records an Elixir app through `mix run`, which
//!   reaches the container as call/return records rather than per-line steps.
//!   Its step stream is empty (`step(StepId(0))` is `None`), and a span's
//!   range indexes thread events.
//!
//! Both still had to be re-recorded — `meta.dat`'s version gate refuses a v3
//! container whether or not it carries steps — and both are asserted to open
//! and to be at the current schema version by
//! `every_request_panel_fixture_is_at_the_current_schema_version` below, which
//! is the strongest claim their contents support.

#![allow(clippy::expect_used, clippy::unwrap_used, clippy::panic)]

use std::path::PathBuf;

use codetracer_trace_types::{Line, StepId};

use db_backend::ctfs_trace_reader::CTFSTraceReader;
use db_backend::source_views::SourceViews;
use db_backend::trace_reader::TraceReader;

fn fixture(relative: &str) -> PathBuf {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures")
        .join(relative);
    assert!(
        path.is_file(),
        "committed fixture missing at {} — this test must NOT silently skip",
        path.display()
    );
    path
}

/// Open `relative` and require step `i` to read back at `(source, lines[i])`
/// for every entry of `lines`.
fn assert_steps_read_back(relative: &str, source: &str, lines: &[i64]) {
    let ct = fixture(relative);
    let reader =
        CTFSTraceReader::open(&ct).unwrap_or_else(|e| panic!("{relative}: the committed fixture must open: {e}"));

    for (i, line) in lines.iter().enumerate() {
        let step = reader
            .step(StepId(i as i64))
            .unwrap_or_else(|| panic!("{relative}: step {i} must be present"));
        assert_eq!(
            reader.db().paths[step.path_id],
            source,
            "{relative}: step {i} was recorded in {source}"
        );
        assert_eq!(
            step.line,
            Line(*line),
            "{relative}: step {i} was recorded at line {line} and must read back there, not at {}",
            step.line.0
        );
    }
}

// ── The RS-M2 span-stream fixtures ────────────────────────────────────────
//
// `gen_span_fixtures.nim`'s `writeContainer` registers one path and then
// `registerStep(pathId, line)` for `line` in 1..=8, in every one of the seven
// containers it writes. See that generator's `writeContainer`.

/// The path every span-stream container registers.
const SPAN_STREAM_SOURCE: &str = "/srv/app/index.php";

/// The lines `writeContainer` records, in step order.
const SPAN_STREAM_LINES: [i64; 8] = [1, 2, 3, 4, 5, 6, 7, 8];

#[test]
fn span_stream_fixtures_read_back_at_their_recorded_lines() {
    for name in [
        "no_spans",
        "web_session",
        "web_session_200",
        "web_session_tail_stage1",
        "web_session_tail_stage2",
        "web_session_tail_stage3",
        "web_session_tail_stage4",
    ] {
        assert_steps_read_back(
            &format!("span_stream/{name}.ct"),
            SPAN_STREAM_SOURCE,
            &SPAN_STREAM_LINES,
        );
    }
}

// ── The mixed-trace fixture ───────────────────────────────────────────────
//
// This one bundles its own `.gd` source as a source view, so the assertion can
// go one step further than a line number: it can require the step to land on
// the STATEMENT the fixture documents. That is the check a line-number
// comparison alone cannot make, and the one that would have caught a fixture
// whose numbers round-trip through a writer/reader pair that are wrong
// together.

/// `res://mixed_demo.gd`, the single path `gen_combined_fixture.nim` registers.
const MIXED_SOURCE: &str = "res://mixed_demo.gd";

/// `(recorded line, the source text at that line)` for steps 0..=8, from
/// `gen_combined_fixture.nim`'s step/span layout table.
const MIXED_STEPS: [(i64, &str); 9] = [
    (5, "var total = 0"),
    (6, "total += 1"),
    (7, "total = compute(total)"),
    (12, "var r = n * 2"),
    (17, "var f = 30"),
    (18, "return x * f"),
    (14, "return r"),
    (8, "print(total)"),
    (9, "queue_free()"),
];

#[test]
fn mixed_trace_fixture_steps_land_on_the_statements_it_documents() {
    let relative = "gdscript_mixed/combined_trace.ct";
    let lines: Vec<i64> = MIXED_STEPS.iter().map(|(line, _)| *line).collect();
    assert_steps_read_back(relative, MIXED_SOURCE, &lines);

    let ct = fixture(relative);
    let views = SourceViews::load(&ct).unwrap_or_else(|e| panic!("{relative}: bundled source views must load: {e:?}"));
    let view = views
        .entries()
        .first()
        .unwrap_or_else(|| panic!("{relative}: the fixture bundles its `.gd` source as a source view"));
    let source = String::from_utf8(view.content.clone()).expect("the bundled .gd source is UTF-8");
    let source_lines: Vec<&str> = source.lines().collect();

    for (i, (line, text)) in MIXED_STEPS.iter().enumerate() {
        let index = usize::try_from(*line - 1).expect("a recorded line is 1-based");
        let actual = source_lines
            .get(index)
            .unwrap_or_else(|| panic!("{relative}: step {i} is at line {line}, past the end of the bundled source"))
            .trim();
        assert_eq!(
            actual, *text,
            "{relative}: step {i} is recorded at line {line}, which must be `{text}` in the bundled source"
        );
    }
}

// ── The request-panel language-matrix fixtures ────────────────────────────
//
// `src/tests/gui/tests/request-panel/fixtures/` holds one real recording per
// language row, each produced by that language's recorder driving a real HTTP
// session. They are consumed by the ViewModel tests registered in
// `src/ct_test/release_gate.nim`'s `CoreViewModelGateTests`.
//
// # Why these need an assertion of their own
//
// The ViewModel tests next door read spans, routes and statuses. The strongest
// line-level claim any of them made was `loc.line > 0`, which a reading one
// line high satisfies — which is why they stayed green for the entire life of
// the superseded encode. These fixtures are recordings of REAL application
// source, so the line a step reads back at is checkable against what that
// source actually does at that line, and that is what is checked here.
//
// # Where the expected lines come from
//
// Unlike `gdscript_mixed/combined_trace.ct`, these containers bundle no source
// views — a recording references its sources by the recording machine's
// absolute paths, and the fixtures deliberately drop the source tree rather
// than commit one developer's `$HOME` layout. So the expected `(line, text)`
// pairs below were read off the demo application in each recorder sibling at
// the moment the fixture was recorded, and the statement text is quoted so a
// reader can audit the pairing without the sibling checked out.
//
// The LINE is what is asserted. That is the number the defect moved, and each
// table is a contiguous run of a handler's own statements, so a writer that is
// one line high shifts the whole run and every case here fails. The shift is
// not subtle in any of the three: it lands the last step of a Python handler
// on a blank line, a PHP function-entry step on its `{`, and a JS handler's
// last step on its `});`.

/// A fixture under `src/tests/gui/tests/request-panel/fixtures/`.
///
/// These live outside `tests/fixtures/`, so they get their own resolver rather
/// than a `../` escape through [`fixture`].
fn request_panel_fixture(relative: &str) -> PathBuf {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../tests/gui/tests/request-panel/fixtures")
        .join(relative);
    assert!(
        path.is_file(),
        "committed request-panel fixture missing at {} — this test must NOT silently skip",
        path.display()
    );
    path
}

/// Require `steps[first + i]` to read back in `source_suffix` at `expected[i]`.
///
/// `source_suffix` is matched as a suffix because the recorded path is the
/// recording machine's absolute one.
fn assert_request_panel_run(relative: &str, source_suffix: &str, first: i64, expected: &[(i64, &str)]) {
    let ct = request_panel_fixture(relative);
    let reader =
        CTFSTraceReader::open(&ct).unwrap_or_else(|e| panic!("{relative}: the committed fixture must open: {e}"));

    for (i, (line, text)) in expected.iter().enumerate() {
        let id = first + i as i64;
        let step = reader
            .step(StepId(id))
            .unwrap_or_else(|| panic!("{relative}: step {id} must be present"));
        let path = &reader.db().paths[step.path_id];
        assert!(
            path.ends_with(source_suffix),
            "{relative}: step {id} was recorded in {source_suffix}, not {path}"
        );
        assert_eq!(
            step.line,
            Line(*line),
            "{relative}: step {id} was recorded at line {line} (`{text}`) and must read back there, not at {}",
            step.line.0
        );
    }
}

/// The Flask row: `create_user`, statement by statement, then the `POST`'s
/// `after_request` hook.
///
/// `codetracer-python-recorder/test-programs/web/flask/app.py`. A one-line-high
/// reading puts the final `return` on line 38, which is blank.
#[test]
fn python_flask_fixture_steps_land_on_the_handler_statements_they_recorded() {
    assert_request_panel_run(
        "python_flask/serve.ct",
        "test-programs/web/flask/app.py",
        13,
        &[
            (32, r#"@app.post("/api/users")"#),
            (34, "payload = request.get_json(silent=True) or {}"),
            (35, "new_id = max(USERS) + 1"),
            (
                36,
                r#"USERS[new_id] = {"id": new_id, "name": payload.get("name", "anonymous")}"#,
            ),
            (37, "return jsonify(USERS[new_id]), 201"),
        ],
    );

    assert_request_panel_run(
        "python_flask/serve.ct",
        "test-programs/web/flask/app.py",
        10,
        &[
            (69, "if request.url_rule is not None:"),
            (70, r#"request.environ["codetracer.route"] = str(request.url_rule)"#),
            (71, "return response"),
        ],
    );
}

/// The PHP row: the first request's call chain, each step a function entry.
///
/// `codetracer-php-recorder/tests/programs/web/app.php`. The demo puts each
/// function's `{` on the line after its signature, so a one-line-high reading
/// lands every one of these on a bare brace.
#[test]
fn php_builtin_fixture_steps_land_on_the_function_entries_they_recorded() {
    assert_request_panel_run(
        "php_builtin/app.ct",
        "tests/programs/web/app.php",
        1,
        &[
            (128, "function dispatch(string $method, string $path): void"),
            (29, "function ct_annotate(string $key, string $value): void"),
            (63, "function handle_list_users(): void"),
            (29, "function ct_annotate(string $key, string $value): void"),
            (56, "function json_response(int $status, array $payload): void"),
        ],
    );
}

/// The JavaScript row: the `GET /api/users` handler.
///
/// `codetracer-js-recorder/test-programs/web/express/app.js`. Line 44 repeats
/// because the `sort` comparator on it is called once per comparison — the run
/// is the handler executing, not a synthetic sequence. A one-line-high reading
/// ends it on `});`.
#[test]
fn js_express_fixture_steps_land_on_the_handler_statements_they_recorded() {
    assert_request_panel_run(
        "js_express/index.ct",
        "test-programs/web/express/app.js",
        65,
        &[
            (43, r#"app.get("/api/users", (req, res) => {"#),
            (43, r#"app.get("/api/users", (req, res) => {"#),
            (44, "const users = Object.values(USERS).sort((a, b) => a.id - b.id);"),
            (44, "const users = Object.values(USERS).sort((a, b) => a.id - b.id);"),
            (44, "const users = Object.values(USERS).sort((a, b) => a.id - b.id);"),
            (44, "const users = Object.values(USERS).sort((a, b) => a.id - b.id);"),
            (45, "res.json(users);"),
        ],
    );
}

/// The Ruby row: the `get '/api/users'` block, statement by statement.
///
/// `codetracer-ruby-recorder/test-programs/web/sinatra/app.rb`. This fixture
/// was regenerated ahead of the other five and is the reference shape the rest
/// were checked against: under the superseded encode these same steps decoded
/// to 41..46, ending on line 46, which is blank.
#[test]
fn ruby_sinatra_fixture_steps_land_on_the_handler_statements_they_recorded() {
    assert_request_panel_run(
        "ruby_sinatra/ruby.ct",
        "test-programs/web/sinatra/app.rb",
        60,
        &[
            (40, "get '/api/users' do"),
            (41, "content_type :json"),
            (42, "users = USERS.values"),
            (43, "payload = { 'users' => users, 'count' => users.length }"),
            (44, "JSON.generate(payload)"),
            (45, "end"),
        ],
    );
}

/// Every request-panel fixture opens under the current schema version.
///
/// This is the whole claim for the two rows that carry no per-line steps, and
/// a floor under the four that do. `CTFSTraceReader::open` is what refuses a
/// superseded container, so a v3 fixture fails here by name rather than by
/// reading one line high somewhere downstream.
#[test]
fn every_request_panel_fixture_is_at_the_current_schema_version() {
    for relative in [
        "python_flask/serve.ct",
        "ruby_sinatra/ruby.ct",
        "php_builtin/app.ct",
        "elixir_plug/app.ct",
        "js_express/index.ct",
        "native_nginx/nginx.ct",
    ] {
        let ct = request_panel_fixture(relative);
        CTFSTraceReader::open(&ct)
            .unwrap_or_else(|e| panic!("{relative}: the committed fixture must open at the current version: {e}"));
    }
}
