//! Every committed `.ct` fixture whose generator recorded steps at known lines
//! must read those steps back at THOSE lines.
//!
//! # Why a fixture opening cleanly is not the property
//!
//! The line-only `global_position_index` encode is
//! `prefix_sum[file_id] + (line - 1)`, the exact inverse of the decode
//! [`db_backend::ctfs_trace_reader::line_position_space`] performs. A writer
//! that packed `prefix_sum[file_id] + line` instead produces addresses that are
//! all still INSIDE the trace's own space, so every step resolves to a real
//! file and a real line — each one exactly one line above where it was
//! recorded — and nothing anywhere reports an error. A fixture regenerated by
//! such a writer opens, serves steps, and answers every structural assertion
//! the suites next door make about it (span ranges, chunk boundaries, call
//! trees, altitudes), because none of those read a line. It is wrong only in
//! the one number a debugger shows the user.
//!
//! `meta.dat`'s schema version is what refuses a container written under the
//! superseded encode (`ctfs_superseded_line_index_refusal_test.rs`), but a
//! version is a claim by the writer, not a measurement of the bytes. This test
//! is the measurement: it takes each fixture's recorded `(path, line)` table
//! from the generator that produced it and requires the production reader to
//! give those pairs back.
//!
//! # No mocks, and no skips
//!
//! The fixtures are committed, so every case here always runs; a missing one
//! fails loudly. They are opened through `CTFSTraceReader::open`, the same
//! constructor `dap_server` uses.
//!
//! # What is NOT covered here
//!
//! `tests/fixtures/xos/xos_hello.ct` (a `ct_cli record` capture whose thread
//! stream carries no per-line steps), `tests/fixtures/stylus-fund-trace`
//! (a legacy `events.log` bundle whose steps carry `(path_id, line)` directly
//! rather than a packed global index) and `tests/fixtures/gdscript` (produced
//! by the patched Godot fork, which is an unstarted deliverable) have no
//! line-only step stream for this assertion to measure.

#![allow(clippy::expect_used, clippy::unwrap_used, clippy::panic)]

use std::path::PathBuf;

use codetracer_trace_types::{Line, StepId};

use db_backend::ctfs_trace_reader::CTFSTraceReader;
use db_backend::source_views::SourceViews;
use db_backend::trace_reader::TraceReader;

fn fixture(relative: &str) -> PathBuf {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures")
        .join(relative);
    assert!(
        path.is_file(),
        "committed fixture missing at {} — this test must NOT silently skip",
        path.display()
    );
    path
}

/// Open `relative` and require step `i` to read back at `(source, lines[i])`
/// for every entry of `lines`.
fn assert_steps_read_back(relative: &str, source: &str, lines: &[i64]) {
    let ct = fixture(relative);
    let reader =
        CTFSTraceReader::open(&ct).unwrap_or_else(|e| panic!("{relative}: the committed fixture must open: {e}"));

    for (i, line) in lines.iter().enumerate() {
        let step = reader
            .step(StepId(i as i64))
            .unwrap_or_else(|| panic!("{relative}: step {i} must be present"));
        assert_eq!(
            reader.db().paths[step.path_id],
            source,
            "{relative}: step {i} was recorded in {source}"
        );
        assert_eq!(
            step.line,
            Line(*line),
            "{relative}: step {i} was recorded at line {line} and must read back there, not at {}",
            step.line.0
        );
    }
}

// ── The RS-M2 span-stream fixtures ────────────────────────────────────────
//
// `gen_span_fixtures.nim`'s `writeContainer` registers one path and then
// `registerStep(pathId, line)` for `line` in 1..=8, in every one of the seven
// containers it writes. See that generator's `writeContainer`.

/// The path every span-stream container registers.
const SPAN_STREAM_SOURCE: &str = "/srv/app/index.php";

/// The lines `writeContainer` records, in step order.
const SPAN_STREAM_LINES: [i64; 8] = [1, 2, 3, 4, 5, 6, 7, 8];

#[test]
fn span_stream_fixtures_read_back_at_their_recorded_lines() {
    for name in [
        "no_spans",
        "web_session",
        "web_session_200",
        "web_session_tail_stage1",
        "web_session_tail_stage2",
        "web_session_tail_stage3",
        "web_session_tail_stage4",
    ] {
        assert_steps_read_back(
            &format!("span_stream/{name}.ct"),
            SPAN_STREAM_SOURCE,
            &SPAN_STREAM_LINES,
        );
    }
}

// ── The mixed-trace fixture ───────────────────────────────────────────────
//
// This one bundles its own `.gd` source as a source view, so the assertion can
// go one step further than a line number: it can require the step to land on
// the STATEMENT the fixture documents. That is the check a line-number
// comparison alone cannot make, and the one that would have caught a fixture
// whose numbers round-trip through a writer/reader pair that are wrong
// together.

/// `res://mixed_demo.gd`, the single path `gen_combined_fixture.nim` registers.
const MIXED_SOURCE: &str = "res://mixed_demo.gd";

/// `(recorded line, the source text at that line)` for steps 0..=8, from
/// `gen_combined_fixture.nim`'s step/span layout table.
const MIXED_STEPS: [(i64, &str); 9] = [
    (5, "var total = 0"),
    (6, "total += 1"),
    (7, "total = compute(total)"),
    (12, "var r = n * 2"),
    (17, "var f = 30"),
    (18, "return x * f"),
    (14, "return r"),
    (8, "print(total)"),
    (9, "queue_free()"),
];

#[test]
fn mixed_trace_fixture_steps_land_on_the_statements_it_documents() {
    let relative = "gdscript_mixed/combined_trace.ct";
    let lines: Vec<i64> = MIXED_STEPS.iter().map(|(line, _)| *line).collect();
    assert_steps_read_back(relative, MIXED_SOURCE, &lines);

    let ct = fixture(relative);
    let views = SourceViews::load(&ct).unwrap_or_else(|e| panic!("{relative}: bundled source views must load: {e:?}"));
    let view = views
        .entries()
        .first()
        .unwrap_or_else(|| panic!("{relative}: the fixture bundles its `.gd` source as a source view"));
    let source = String::from_utf8(view.content.clone()).expect("the bundled .gd source is UTF-8");
    let source_lines: Vec<&str> = source.lines().collect();

    for (i, (line, text)) in MIXED_STEPS.iter().enumerate() {
        let index = usize::try_from(*line - 1).expect("a recorded line is 1-based");
        let actual = source_lines
            .get(index)
            .unwrap_or_else(|| panic!("{relative}: step {i} is at line {line}, past the end of the bundled source"))
            .trim();
        assert_eq!(
            actual, *text,
            "{relative}: step {i} is recorded at line {line}, which must be `{text}` in the bundled source"
        );
    }
}
