//! M3b cross-read proof — a CoW namespace B-tree page image written by the
//! production Nim writer (`codetracer_ctfs::cow_btree`) is read correctly by the
//! Rust [`CowNamespaceReader`].
//!
//! The fixture (`tests/fixtures/cow_namespace/cow_btree_typea.cowbt`) and its
//! manifest are generated by the Nim
//! `tests/gen_cow_btree_crossread_fixture.nim` generator, which:
//!
//!   * inserts 600 keys copy-on-write (forcing real leaf + internal node
//!     splits) committing each via the double-buffered atomic root protocol,
//!   * performs an in-place key UPDATE (so the latest committed value must win),
//!   * reclaims superseded pages into the whole-block free list (so the
//!     published image carries free pages the reader must ignore).
//!
//! The manifest lists every live `(key, descriptor-hex)` the highest-valid-
//! commit-id root must resolve to. This test asserts the Rust reader selects the
//! committed root and reproduces every pair byte-for-byte — the load-bearing
//! proof that the Nim CoW writer's on-disk page format is byte-compatible with
//! the Rust reader.
//!
//! If the fixture is absent (a checkout without it / before the generator has
//! been run) the test skips cleanly rather than failing.

#![allow(clippy::expect_used, clippy::unwrap_used)]

use std::path::PathBuf;

use db_backend::ctfs_trace_reader::cow_namespace_reader::{CowLeafType, CowNamespaceReader};
use db_backend::ctfs_trace_reader::cow_namespace_writer::CowNamespaceWriter;

fn fixture_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/cow_namespace")
}

fn parse_manifest(text: &str) -> Vec<(u64, Vec<u8>)> {
    let mut out = Vec::new();
    for line in text.lines() {
        let line = line.trim();
        if line.is_empty() {
            continue;
        }
        let mut parts = line.split_whitespace();
        let key: u64 = parts.next().expect("manifest key").parse().expect("u64 key");
        let hex = parts.next().expect("manifest descriptor hex");
        let bytes: Vec<u8> = (0..hex.len())
            .step_by(2)
            .map(|i| u8::from_str_radix(&hex[i..i + 2], 16).expect("hex byte"))
            .collect();
        out.push((key, bytes));
    }
    out
}

#[test]
fn rust_reader_round_trips_nim_cow_image() {
    let dir = fixture_dir();
    let image_path = dir.join("cow_btree_typea.cowbt");
    let manifest_path = dir.join("cow_btree_typea.manifest");

    if !image_path.exists() || !manifest_path.exists() {
        eprintln!(
            "SKIPPED: CoW namespace fixture not present at {} (run \
             gen_cow_btree_crossread_fixture.nim to generate it)",
            image_path.display()
        );
        return;
    }

    let image = std::fs::read(&image_path).expect("read fixture image");
    let manifest = std::fs::read_to_string(&manifest_path).expect("read manifest");
    let expected = parse_manifest(&manifest);
    assert!(!expected.is_empty(), "manifest must list keys");

    let reader = CowNamespaceReader::open(&image, CowLeafType::TypeA).expect("open Nim-written CoW namespace image");

    // The reader must have selected a committed root (non-empty) and the leaf
    // type the header declares.
    assert!(reader.root_page() != 0, "reader must select a committed root");
    assert_eq!(reader.leaf_type(), CowLeafType::TypeA);

    // Every manifest key resolves to its expected descriptor through the
    // committed root — including the UPDATED key (latest value wins).
    for (key, want) in &expected {
        let got = reader
            .lookup(*key)
            .unwrap_or_else(|e| panic!("lookup key {key} failed: {e}"));
        assert_eq!(got, want.as_slice(), "descriptor mismatch for key {key}");
    }

    // The live key count walked from the committed root matches the manifest —
    // free / superseded pages in the image are correctly ignored.
    let counted = reader.key_count().expect("key_count");
    assert_eq!(counted, expected.len(), "live key count mismatch");

    // A key never inserted must be absent (not a stale free-page hit).
    assert!(reader.lookup(2).is_err(), "key 2 was never inserted");

    eprintln!(
        "OK: Rust CowNamespaceReader round-tripped {} keys from a Nim-written \
         CoW image (commit id {}, root page {})",
        expected.len(),
        reader.commit_id(),
        reader.root_page()
    );
}

/// M4-perf cross-read — a CoW namespace image built by the Nim **bulk-load**
/// constructor (`cow_btree::bulkLoad`, the bottom-up single-commit builder) is
/// read correctly by the Rust [`CowNamespaceReader`].
///
/// The bulk fixture (`cow_btree_bulk_typea.{cowbt,manifest}`) is generated by
/// the Nim `gen_cow_btree_crossread_fixture.nim --bulk` over the SAME final
/// logical key set as the per-key fixture (key 3 carries the updated value), so
/// the manifest is identical. The bulk builder emits the SAME NSB1 wire format
/// (header + immutable page graph) but with denser page packing and no abandoned
/// CoW pages — this test is the load-bearing proof that the Rust reader does not
/// depend on the per-key build's page-allocation pattern: only the bytes' page
/// PACKING changed, not the format the reader parses.
///
/// Skips cleanly when the fixture is absent (run the `--bulk` generator).
#[test]
fn reads_nim_bulk_built_cow_image() {
    let dir = fixture_dir();
    let image_path = dir.join("cow_btree_bulk_typea.cowbt");
    let manifest_path = dir.join("cow_btree_bulk_typea.manifest");

    if !image_path.exists() || !manifest_path.exists() {
        eprintln!(
            "SKIPPED: bulk CoW namespace fixture not present at {} (run \
             gen_cow_btree_crossread_fixture.nim --bulk to generate it)",
            image_path.display()
        );
        return;
    }

    let image = std::fs::read(&image_path).expect("read bulk fixture image");
    let manifest = std::fs::read_to_string(&manifest_path).expect("read bulk manifest");
    let expected = parse_manifest(&manifest);
    assert!(!expected.is_empty(), "bulk manifest must list keys");

    let reader = CowNamespaceReader::open(&image, CowLeafType::TypeA).expect("open Nim bulk-built CoW namespace image");

    assert!(reader.root_page() != 0, "reader must select a committed root");
    assert_eq!(reader.leaf_type(), CowLeafType::TypeA);
    // The bulk build publishes exactly ONE commit (id 1) — proving it is the
    // single-pass constructor, not a per-key build.
    assert_eq!(reader.commit_id(), 1, "bulk build must publish a single commit");

    for (key, want) in &expected {
        let got = reader
            .lookup(*key)
            .unwrap_or_else(|e| panic!("bulk lookup key {key} failed: {e}"));
        assert_eq!(got, want.as_slice(), "bulk descriptor mismatch for key {key}");
    }

    let counted = reader.key_count().expect("bulk key_count");
    assert_eq!(counted, expected.len(), "bulk live key count mismatch");
    assert!(reader.lookup(2).is_err(), "key 2 was never inserted (bulk)");

    eprintln!(
        "OK: Rust CowNamespaceReader round-tripped {} keys from a Nim BULK-built \
         CoW image (commit id {}, root page {})",
        expected.len(),
        reader.commit_id(),
        reader.root_page()
    );
}

/// M4 — emit a CoW namespace image written by the **Rust** writer
/// ([`CowNamespaceWriter`]) plus its `(key, descriptor-hex)` manifest, into the
/// shared fixtures dir. The Nim test `test_cow_btree.nim::"rust-written CoW
/// image reads back through loadCowBTree"` reads it back, proving the Rust
/// writer's on-disk page format is byte-compatible with the Nim reader — the
/// reverse direction of `rust_reader_round_trips_nim_cow_image`, closing the
/// bidirectional wire-format loop the M5/M6 Rust replay-time write path depends
/// on.
///
/// This is a generator, not an assertion test: it writes the fixture, then
/// re-reads it through the Rust reader as a self-check. The Nim consumer test
/// skips cleanly when the fixture is absent.
#[test]
fn gen_rust_written_cow_fixture_for_nim() {
    let dir = fixture_dir();
    std::fs::create_dir_all(&dir).expect("create fixtures dir");

    let mut w = CowNamespaceWriter::new(CowLeafType::TypeA, false);
    // Force real leaf + internal splits (Type A order is (4096-8)/16 = 255).
    const N: u64 = 300;
    for i in 1..=N {
        let key = i * 3;
        w.insert_and_commit(key, &key.to_le_bytes()).expect("insert");
    }
    // In-place UPDATE so the latest committed value must win on read-back.
    w.insert_and_commit(3 * 7, &0xDEAD_BEEFu64.to_le_bytes())
        .expect("update");

    let image = w.serialize();
    let image_path = dir.join("cow_btree_rust_typea.cowbt");
    let manifest_path = dir.join("cow_btree_rust_typea.manifest");
    std::fs::write(&image_path, &image).expect("write image");

    let mut manifest = String::new();
    for i in 1..=N {
        let key = i * 3;
        let val: u64 = if key == 21 { 0xDEAD_BEEF } else { key };
        let hex: String = val.to_le_bytes().iter().map(|b| format!("{b:02x}")).collect();
        manifest.push_str(&format!("{key} {hex}\n"));
    }
    std::fs::write(&manifest_path, &manifest).expect("write manifest");

    // Self-check: the Rust reader round-trips the Rust-written image.
    let r = CowNamespaceReader::open(&image, CowLeafType::TypeA).expect("open Rust-written image");
    assert_eq!(r.key_count().expect("count"), N as usize);
    assert_eq!(r.lookup(21).expect("lookup 21"), &0xDEAD_BEEFu64.to_le_bytes());

    eprintln!(
        "OK: wrote Rust-written CoW fixture ({} keys) to {} for the Nim cross-read",
        N,
        image_path.display()
    );
}
