//! RS-M3 part A — integration tests for the held request-span tail
//! (`ct/load-request-spans-since`).
//!
//! Spec: `codetracer-specs/Trace-Files/CTFS-Request-Span-Streams.md`
//! §"Reader and Frontend Surface"; milestone RS-M3 in
//! `codetracer-specs/Planned-Features/Request-Panel-Live-Sessions.milestones.org`.
//!
//! # No mocks
//!
//! Nothing here is mocked, stubbed or faked. Every test drives
//! [`RequestSpanTail`] against **real `.ct` containers written by the canonical
//! Nim writer** (`codetracer-trace-format-nim`'s `multi_stream_writer` +
//! `span_stream`), committed under `tests/fixtures/span_stream/` and
//! regenerated by the `regenerate.sh` next to them; the legacy-shim test runs
//! against a real file on a real temporary filesystem. The reader under test
//! parses bytes it did not produce.
//!
//! # How a growing container is simulated
//!
//! `web_session_tail_stage1..4.ct` are four snapshots of ONE session, taken as
//! it grows: stage `k+1` holds every record stage `k` held, in the same chunks,
//! plus more. A test publishes them in order over a single path, which is
//! exactly what a tailing client observes while a recorder appends chunks to a
//! container.
//!
//! The one thing that makes this a fair stand-in — that a sealed chunk is
//! IMMUTABLE, so chunk `k` names the same records in every stage — is not
//! assumed. `tail_fixture_stages_form_an_append_only_prefix_chain` asserts it
//! against the committed bytes before any other test relies on it.
//!
//! Publishing a stage sets an explicit, strictly-increasing mtime. That is not
//! a convenience: a `.ct` container is block-padded, so two stages routinely
//! have the same file LENGTH, and mtime is the only change signal the tail's
//! staleness check has. Setting it removes a race with the filesystem clock
//! rather than papering over one — a live recorder's appends always advance it.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

use db_backend::ctfs_trace_reader::ctfs_container::CtfsReader;
use db_backend::ctfs_trace_reader::span_stream::SpanStreamReader;
use db_backend::request_spans::{RequestRecord, RequestSpanTail};
use serde_json::Value;

// ── Fixture plumbing ────────────────────────────────────────────────────

/// Chunk counts of the four tail stages, as the generator lays them out.
///
/// Written down here so the decompression arithmetic below is checkable by
/// hand; `tail_fixture_stages_form_an_append_only_prefix_chain` proves the
/// committed containers really have them.
const STAGE_CHUNKS: [u64; 4] = [2, 3, 5, 8];

fn fixture_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/span_stream")
}

fn stage_container(stage: usize) -> PathBuf {
    fixture_dir().join(format!("web_session_tail_stage{stage}.ct"))
}

/// One settled span as the GENERATOR declared it — ground truth that was
/// written from the values fed to the writer, never by re-reading the
/// container, so a writer bug cannot make the expectations agree with
/// themselves.
#[derive(Debug, Clone, PartialEq, Eq)]
struct ExpectedSpan {
    span_id: u64,
    is_open: bool,
    span_type: String,
    status_code: i64,
    url: String,
}

fn expected_stage(stage: usize) -> Vec<ExpectedSpan> {
    let path = fixture_dir().join(format!("web_session_tail_stage{stage}.expected.jsonl"));
    let text = std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
    text.lines()
        .filter(|l| !l.trim().is_empty())
        .map(|line| {
            let v: Value = serde_json::from_str(line).expect("expected line is JSON");
            let meta = v.get("metadata").and_then(Value::as_object).expect("metadata object");
            let meta_str = |key: &str| meta.get(key).and_then(Value::as_str).unwrap_or_default().to_string();
            ExpectedSpan {
                span_id: v.get("span_id").and_then(Value::as_u64).expect("span_id"),
                is_open: v.get("is_open").and_then(Value::as_bool).expect("is_open"),
                span_type: v.get("span_type").and_then(Value::as_str).expect("span_type").to_string(),
                status_code: meta_str("http.status_code").parse::<i64>().unwrap_or(0),
                url: meta_str("http.url"),
            }
        })
        .collect()
}

/// The stage's expected WEB-REQUEST rows, keyed by span id — i.e. what a
/// correctly-merged client list must hold once it has consumed every delta up
/// to and including this stage.
fn expected_requests(stage: usize) -> BTreeMap<u64, ExpectedSpan> {
    expected_stage(stage)
        .into_iter()
        .filter(|s| s.span_type == "web-request")
        .map(|s| (s.span_id, s))
        .collect()
}

/// Publish stage `stage` of the growing session at `container`, advancing the
/// file's mtime so the tail sees a changed source (see the module header).
fn publish_stage(stage: usize, container: &Path) {
    let src = stage_container(stage);
    std::fs::copy(&src, container).unwrap_or_else(|e| panic!("publish stage {stage}: {e}"));
    // An arbitrary but strictly increasing wall clock, one minute per stage.
    let when = filetime::FileTime::from_unix_time(1_800_000_000 + 60 * stage as i64, 0);
    filetime::set_file_mtime(container, when).expect("set mtime");
}

/// A temporary recording directory holding a single `trace.ct`.
struct Recording {
    dir: tempfile::TempDir,
}

impl Recording {
    fn new() -> Recording {
        Recording {
            dir: tempfile::tempdir().expect("tempdir"),
        }
    }

    fn path(&self) -> &Path {
        self.dir.path()
    }

    fn container(&self) -> PathBuf {
        self.dir.path().join("trace.ct")
    }

    /// Publish a tail stage into this recording.
    fn publish(&self, stage: usize) {
        publish_stage(stage, &self.container());
    }
}

fn ids(spans: &[RequestRecord]) -> Vec<u64> {
    spans.iter().map(|r| r.id).collect()
}

/// The client-side merge the wire contract mandates: last record wins per `id`.
///
/// This is deliberately the whole of it — a `BTreeMap::insert` keyed on `id`.
/// If the backend's contract needed anything more (ordering rules, tombstones,
/// version numbers), that would show up here as extra logic, and its absence is
/// the point: the frontend's merge is `Map.set(record.id, record)`.
fn merge(into: &mut BTreeMap<u64, RequestRecord>, delta: &[RequestRecord]) {
    for record in delta {
        into.insert(record.id, record.clone());
    }
}

fn assert_matches_expected(merged: &BTreeMap<u64, RequestRecord>, stage: usize) {
    let expected = expected_requests(stage);
    assert_eq!(
        merged.keys().copied().collect::<Vec<_>>(),
        expected.keys().copied().collect::<Vec<_>>(),
        "stage {stage}: merged span ids differ from the generator's ground truth"
    );
    for (id, want) in &expected {
        let got = merged.get(id).expect("id present");
        assert_eq!(got.is_open, want.is_open, "stage {stage}: span {id} in-flight state");
        assert_eq!(got.status_code, want.status_code, "stage {stage}: span {id} status");
        assert_eq!(got.url, want.url, "stage {stage}: span {id} url");
    }
}

// ── The fixture's own precondition ──────────────────────────────────────

/// Every later stage must extend the earlier one WITHOUT re-partitioning the
/// chunks it already had.
///
/// This is the property the whole cursor design rests on: a cursor is a chunk
/// count, so chunk `k` has to name the same records in every observation of the
/// container. The writer guarantees it (a sealed chunk is appended and never
/// rewritten), but these fixtures are four separate writer runs rather than one
/// live container, so the guarantee is re-proved here against the committed
/// bytes. If it ever fails, the tail tests below are measuring nothing and this
/// test says so first.
#[test]
fn tail_fixture_stages_form_an_append_only_prefix_chain() {
    let mut previous: Vec<u64> = Vec::new();
    for (i, expected_chunks) in STAGE_CHUNKS.iter().enumerate() {
        let stage = i + 1;
        let path = stage_container(stage);
        let mut ctfs = CtfsReader::open(&path).unwrap_or_else(|e| panic!("open {}: {e}", path.display()));
        let reader = SpanStreamReader::open_from_ctfs(&mut ctfs)
            .expect("span stream reads")
            .expect("stage container declares a span stream");

        assert_eq!(
            reader.chunk_count() as u64,
            *expected_chunks,
            "stage {stage} chunk count"
        );
        assert_eq!(
            reader.chunk_decompressions(),
            0,
            "stage {stage}: opening a stream must still decode nothing"
        );

        let occupancy: Vec<u64> = (0..reader.chunk_count()).map(|c| reader.records_in_chunk(c)).collect();
        assert_eq!(
            occupancy[..previous.len()],
            previous[..],
            "stage {stage} re-partitioned chunks the previous stage had already sealed"
        );
        assert!(
            occupancy.len() > previous.len(),
            "stage {stage} did not add any chunk"
        );
        previous = occupancy;
    }
    assert_eq!(previous.iter().sum::<u64>(), 17, "the session holds 17 raw records");
}

// ── The tail itself ─────────────────────────────────────────────────────

/// RS-M3's central claim: polling a growing recording costs the chunks it
/// GAINED, not the chunks it has.
///
/// The functional result is identical either way — re-decoding the whole stream
/// on every poll returns the same records — so the cost is invisible to any
/// assertion about content. `chunk_decompressions()` is the seam that makes it
/// visible, and this test pins it: four polls over a container that grows to
/// eight chunks decompress eight zstd frames in total, one per chunk, where
/// re-reading the stream each time would decompress 2 + 3 + 5 + 8 = 18.
#[test]
fn tail_decompresses_each_chunk_once_across_a_growing_recording() {
    let recording = Recording::new();
    recording.publish(1);

    let mut tail = RequestSpanTail::new(recording.path());
    let mut merged: BTreeMap<u64, RequestRecord> = BTreeMap::new();
    let mut cursor = 0u64;
    let mut decompressions_before = 0u64;

    for (i, chunks) in STAGE_CHUNKS.iter().enumerate() {
        let stage = i + 1;
        if stage > 1 {
            recording.publish(stage);
        }
        let previous_cursor = cursor;
        let delta = tail.poll(cursor).unwrap_or_else(|e| panic!("stage {stage} poll: {e}"));

        assert_eq!(delta.source, "span-stream", "stage {stage} source");
        assert_eq!(delta.cursor, *chunks, "stage {stage}: cursor must be the new head");
        assert_eq!(
            delta.reset,
            stage == 1,
            "stage {stage}: only the first poll is a snapshot"
        );

        // Exactly the chunks this stage added, and nothing else.
        let new_chunks = chunks - previous_cursor;
        assert_eq!(
            tail.chunk_decompressions() - decompressions_before,
            new_chunks,
            "stage {stage}: decoded more than the {new_chunks} chunk(s) the recording gained"
        );
        decompressions_before = tail.chunk_decompressions();

        merge(&mut merged, &delta.spans);
        assert_matches_expected(&merged, stage);
        cursor = delta.cursor;
    }

    let naive: u64 = STAGE_CHUNKS.iter().sum();
    assert_eq!(naive, 18, "the four stages hold 18 chunk-reads between them");
    assert_eq!(
        tail.chunk_decompressions(),
        8,
        "the tail must decompress each of the 8 chunks exactly once"
    );
    assert!(
        tail.chunk_decompressions() < naive,
        "a tail that re-decoded the stream would have cost {naive} frames"
    );
}

/// A poll against a container that has not changed must cost nothing at all —
/// no container open, no index parse, no zstd frame. This is the state an idle
/// poll loop spends almost all of its time in.
#[test]
fn polling_an_unchanged_recording_decodes_nothing() {
    let recording = Recording::new();
    recording.publish(4);
    let mut tail = RequestSpanTail::new(recording.path());

    let first = tail.poll(0).expect("first poll");
    assert_eq!(first.cursor, 8);
    let after_first = tail.chunk_decompressions();
    assert_eq!(after_first, 8, "the snapshot decodes every chunk once");

    for _ in 0..5 {
        let idle = tail.poll(first.cursor).expect("idle poll");
        assert!(idle.spans.is_empty(), "an up-to-date cursor yields no rows");
        assert!(!idle.reset, "an idle poll must not order the client to reset");
        assert_eq!(idle.cursor, first.cursor, "the head has not moved");
    }
    assert_eq!(
        tail.chunk_decompressions(),
        after_first,
        "idle polls must not decompress anything"
    );
}

/// A client that replays an older cursor — a retry, a reconnect, a second panel
/// — must get something it can merge without corrupting what it already has.
///
/// The response is a SUPERSET of the up-to-date delta, carries no duplicate
/// `span_id`, and merges to exactly the same list. It cannot regress a row,
/// because a delta always ends at the current head: any span in its range is
/// carried at its settled-as-of-now value, never at an earlier one.
#[test]
fn replaying_an_older_cursor_is_a_mergeable_superset() {
    let recording = Recording::new();
    recording.publish(4);
    let mut tail = RequestSpanTail::new(recording.path());

    // The state a client would hold after consuming stages 1 and 2.
    let mut client: BTreeMap<u64, RequestRecord> = BTreeMap::new();
    let stage2_cursor = STAGE_CHUNKS[1];
    let snapshot = tail.poll(0).expect("snapshot");
    merge(&mut client, &snapshot.spans);
    client.retain(|id, _| *id <= 8);

    // The correct next delta, and the one an older cursor produces.
    let current = tail.poll(stage2_cursor).expect("delta from the stage-2 cursor");
    let stale = tail.poll(STAGE_CHUNKS[0]).expect("delta from the stage-1 cursor");

    assert!(!current.reset && !stale.reset, "neither delta demands a reset");
    assert_eq!(current.cursor, stale.cursor, "both deltas end at the same head");

    let current_ids = ids(&current.spans);
    let stale_ids = ids(&stale.spans);
    let mut unique = stale_ids.clone();
    unique.sort_unstable();
    unique.dedup();
    assert_eq!(
        unique.len(),
        stale_ids.len(),
        "an overlapping delta must not carry the same span twice: {stale_ids:?}"
    );
    for id in &current_ids {
        assert!(
            stale_ids.contains(id),
            "the older cursor's delta must be a superset; it is missing span {id}"
        );
    }
    assert!(
        stale_ids.len() > current_ids.len(),
        "the older cursor must reach further back: {stale_ids:?} vs {current_ids:?}"
    );

    // Merging the overlapping delta lands on the same list as merging the
    // correct one — the overlap is absorbed, not accumulated.
    let mut via_stale = client.clone();
    merge(&mut via_stale, &stale.spans);
    let mut via_current = client.clone();
    merge(&mut via_current, &current.spans);
    assert_eq!(
        via_stale.keys().collect::<Vec<_>>(),
        via_current.keys().collect::<Vec<_>>()
    );
    assert_matches_expected(&via_stale, 4);
    assert_matches_expected(&via_current, 4);

    // And re-applying the same delta a second time changes nothing.
    let again = via_stale.clone();
    merge(&mut via_stale, &stale.spans);
    assert_eq!(via_stale, again, "a replayed delta must be idempotent");
}

/// An open record delivered in one delta and its completion in a later one must
/// resolve to ONE settled row on the client.
///
/// Span 6 is published open in stage 1 and completed in stage 2; span 9 is
/// published open in stage 3 and completed in stage 4 — a whole poll later,
/// with two unrelated requests served in between, so nothing about adjacency
/// can be relied on.
#[test]
fn an_open_record_and_its_later_completion_settle_to_one_row() {
    let recording = Recording::new();
    recording.publish(1);
    let mut tail = RequestSpanTail::new(recording.path());
    let mut client: BTreeMap<u64, RequestRecord> = BTreeMap::new();

    let d1 = tail.poll(0).expect("stage 1");
    merge(&mut client, &d1.spans);
    let open6 = client.get(&6).expect("span 6 arrives open in stage 1");
    assert!(open6.is_open, "span 6 must be in flight after stage 1");
    assert_eq!(open6.status_code, 0, "an in-flight request has no status yet");
    assert_eq!(open6.status, "unknown");
    assert_eq!(open6.url, "/api/reports/slow");

    recording.publish(2);
    let d2 = tail.poll(d1.cursor).expect("stage 2");
    assert!(
        ids(&d2.spans).contains(&6),
        "the completion must arrive in the stage-2 delta"
    );
    merge(&mut client, &d2.spans);
    let settled6 = client.get(&6).expect("span 6 still present");
    assert!(!settled6.is_open, "the completion must supersede the open record");
    assert_eq!(settled6.status_code, 200);
    assert_eq!(settled6.duration_ms, 940);
    assert_eq!(
        client.keys().filter(|id| **id == 6).count(),
        1,
        "one span id must never yield two rows"
    );

    // Span 9: open in stage 3, completed in stage 4.
    recording.publish(3);
    let d3 = tail.poll(d2.cursor).expect("stage 3");
    merge(&mut client, &d3.spans);
    assert!(client.get(&9).expect("span 9 open").is_open);

    recording.publish(4);
    let d4 = tail.poll(d3.cursor).expect("stage 4");
    merge(&mut client, &d4.spans);
    let settled9 = client.get(&9).expect("span 9 settled");
    assert!(!settled9.is_open, "span 9 must settle across the delta boundary");
    assert_eq!(settled9.status_code, 204);
    assert_eq!(settled9.status, "ok");
    assert_matches_expected(&client, 4);
}

/// A process span is not a request row, even when it arrives in the very first
/// delta alongside the requests.
#[test]
fn a_process_span_is_never_a_request_row() {
    let recording = Recording::new();
    recording.publish(4);
    let mut tail = RequestSpanTail::new(recording.path());
    let snapshot = tail.poll(0).expect("snapshot");
    assert!(
        !ids(&snapshot.spans).contains(&1),
        "span 1 is the process descriptor and must not be a request row"
    );
    // Ground truth carries it; the delta must not.
    assert!(expected_stage(4).iter().any(|s| s.span_id == 1 && s.span_type == "process"));
}

// ── Invalidation ────────────────────────────────────────────────────────

/// A cursor past the head means the recording the client was tailing is gone.
/// The tail must not error and must not serve a delta against records the
/// cursor no longer names — it re-snapshots and says so.
#[test]
fn a_cursor_past_the_head_forces_a_reset_snapshot() {
    let recording = Recording::new();
    recording.publish(4);
    let mut tail = RequestSpanTail::new(recording.path());
    let full = tail.poll(0).expect("snapshot");
    assert_eq!(full.cursor, 8);

    // The recording is replaced by a shorter one at the same path.
    recording.publish(1);
    let after = tail.poll(full.cursor).expect("poll after replacement");
    assert!(after.reset, "the client must be told to discard its list");
    assert_eq!(after.cursor, STAGE_CHUNKS[0]);
    let mut fresh: BTreeMap<u64, RequestRecord> = BTreeMap::new();
    merge(&mut fresh, &after.spans);
    assert_matches_expected(&fresh, 1);
}

/// The same path holding a DIFFERENT recording is not a continuation, even when
/// its cursor space happens to be large enough to accept the old cursor. The
/// container's `meta.dat` recording id is what settles it.
#[test]
fn a_different_recording_at_the_same_path_forces_a_reset() {
    let recording = Recording::new();
    recording.publish(4);
    let mut tail = RequestSpanTail::new(recording.path());
    let full = tail.poll(0).expect("snapshot");
    assert_eq!(full.cursor, 8);

    // `web_session_200.ct` is a different recording with far more chunks, so
    // the stale cursor 8 is comfortably inside its range: only the recording id
    // distinguishes it.
    std::fs::copy(fixture_dir().join("web_session_200.ct"), recording.container()).expect("swap recording");
    filetime::set_file_mtime(
        recording.container(),
        filetime::FileTime::from_unix_time(1_900_000_000, 0),
    )
    .expect("set mtime");

    let after = tail.poll(full.cursor).expect("poll after the swap");
    assert!(after.reset, "a different recording must reset the client");
    assert_eq!(after.spans.len(), 200, "the snapshot must cover the new recording");
    assert_eq!(after.spans[0].id, 1);
}

/// A recording that carries neither a span stream nor a sidecar tails empty
/// rather than failing: "this program served no HTTP requests" is the ordinary
/// case for almost every recording.
#[test]
fn a_span_free_recording_tails_empty() {
    let recording = Recording::new();
    std::fs::copy(fixture_dir().join("no_spans.ct"), recording.container()).expect("copy");
    let mut tail = RequestSpanTail::new(recording.path());
    let delta = tail.poll(0).expect("poll");
    assert!(delta.spans.is_empty());
    assert_eq!(delta.source, "none");
    assert_eq!(delta.cursor, 0);
    assert_eq!(tail.chunk_decompressions(), 0);
}

// ── The legacy sidecar, tailed ──────────────────────────────────────────

/// The pre-cutover sessions that exist TODAY (the PHP recorder's
/// `session_manifest.jsonl`) are exactly the live sessions the panel wants, so
/// the tail serves them too. There are no chunks to skip, so the cursor counts
/// records already delivered; a poll returns only the lines appended since.
#[test]
fn the_legacy_sidecar_tails_by_record_count() {
    let dir = tempfile::tempdir().expect("tempdir");
    let manifest = dir.path().join("session_manifest.jsonl");
    let all: Vec<String> = std::fs::read_to_string(fixture_dir().join("web_session.manifest.jsonl"))
        .expect("read manifest fixture")
        .lines()
        .filter(|l| !l.trim().is_empty())
        .map(str::to_string)
        .collect();
    assert!(all.len() >= 6, "the manifest fixture must hold enough lines to split");

    let write_prefix = |n: usize, when: i64| {
        std::fs::write(&manifest, all[..n].join("\n") + "\n").expect("write manifest");
        filetime::set_file_mtime(&manifest, filetime::FileTime::from_unix_time(when, 0)).expect("set mtime");
    };

    write_prefix(3, 1_800_000_000);
    let mut tail = RequestSpanTail::new(dir.path());
    let first = tail.poll(0).expect("first poll");
    assert_eq!(first.source, "legacy-jsonl");
    assert!(first.reset);
    assert_eq!(first.cursor, 3);
    assert_eq!(ids(&first.spans), vec![1, 2, 3]);

    write_prefix(all.len(), 1_800_000_060);
    let delta = tail.poll(first.cursor).expect("second poll");
    assert!(!delta.reset, "an append is a delta, not a reset");
    assert_eq!(delta.cursor, all.len() as u64);
    assert_eq!(
        ids(&delta.spans),
        (4..=all.len() as u64).collect::<Vec<_>>(),
        "only the appended lines may come back"
    );

    // An overlapping replay is still a mergeable superset here.
    let stale = tail.poll(1).expect("replayed cursor");
    assert_eq!(ids(&stale.spans), (2..=all.len() as u64).collect::<Vec<_>>());
}

// ── Wire contract ───────────────────────────────────────────────────────

/// The exact JSON the frontend consumes, pinned.
///
/// The delta travels twice — as the `ct/load-request-spans-since` response body
/// and as the `ct/updated-http-requests` event body — and both are this shape.
/// A rename here silently breaks a Nim consumer that reads the field by name,
/// so the names are asserted rather than assumed.
#[test]
fn the_delta_serialises_to_the_documented_wire_shape() {
    let recording = Recording::new();
    recording.publish(1);
    let mut tail = RequestSpanTail::new(recording.path());
    let delta = tail.poll(0).expect("poll");
    let json = serde_json::to_value(&delta).expect("serialise");

    // `serde_json::Map` is key-sorted here (the `preserve_order` feature is
    // off), so the expectations below are alphabetical. That constrains the key
    // SET exactly, which is what a by-name consumer depends on; JSON object
    // order is not part of any contract.
    let obj = json.as_object().expect("delta is an object");
    assert_eq!(
        obj.keys().map(String::as_str).collect::<Vec<_>>(),
        vec!["cursor", "reset", "source", "spans"]
    );
    assert_eq!(obj["cursor"], Value::from(2u64));
    assert_eq!(obj["reset"], Value::Bool(true));
    assert_eq!(obj["source"], Value::from("span-stream"));

    let row = obj["spans"].as_array().expect("spans array")[0]
        .as_object()
        .expect("row is an object");
    assert_eq!(
        row.keys().map(String::as_str).collect::<Vec<_>>(),
        vec![
            "durationMs",
            "externalTracePath",
            "httpMethod",
            "id",
            "isOpen",
            "responseSize",
            "startGeid",
            "status",
            "statusCode",
            "url"
        ],
        "the row is the frontend's RequestRecord plus the additive RS-M2 fields"
    );
    // `id` is the de-duplication key the client merges on, and `isOpen` is how
    // it knows a completion is still coming. Both must be present on every row.
    assert_eq!(row["id"], Value::from(2u64));
    assert_eq!(row["isOpen"], Value::Bool(false));
}
