//! Headless DAP flow test for Solana/SBF traces.
//!
//! Records a trace using a synthetic register trace (simulating the
//! canonical arithmetic: a=10, b=32, sum=42, doubled=84, final=94)
//! and verifies the DAP server can launch and process it.
//!
//! Full end-to-end testing with real compiled SBF programs requires
//! the Solana SBF toolchain (cargo-build-sbf) or Mollusk execution
//! harness with register tracing enabled.

use std::path::PathBuf;

use ct_dap_client::test_support::FlowTestRunner;

mod test_harness;
use test_harness::{Language, TestRecording, find_solana_flow_test, find_solana_recorder};

fn find_db_backend() -> PathBuf {
    PathBuf::from(env!("CARGO_BIN_EXE_replay-server"))
}

/// Record a Solana trace using synthetic register data and verify
/// the DAP server can launch and process it.
#[test]
#[ignore = "requires solana-recorder; run via: just test-solana-flow"]
fn solana_flow_dap_recording_and_launch() {
    assert!(
        find_solana_recorder().is_some(),
        "Solana recorder not found — build codetracer-solana-recorder"
    );

    let source = find_solana_flow_test().expect("Solana test program not found");
    let db_backend = find_db_backend();

    // Record using synthetic register trace (generated by record_solana_trace).
    let recording = TestRecording::create_db_trace(&source, Language::Solana, "solana-flow")
        .expect("Solana recording failed — check that codetracer-solana-recorder is available");

    println!("Trace recorded to: {}", recording.trace_dir.display());

    // Verify trace files exist.
    assert!(
        recording.trace_dir.join("trace.bin").exists()
            || recording.trace_dir.join("trace.json").exists()
            || recording.trace_dir.join("trace.ct").exists(),
        "No trace data file produced"
    );

    // Verify DAP server launches and reaches stopped state.
    let runner =
        FlowTestRunner::new_db_trace(&db_backend, &recording.trace_dir).expect("DAP init failed for Solana trace");
    runner.finish().expect("disconnect failed");

    println!("Solana DAP recording + launch test passed!");
}
