//! RS-M2 — integration tests for the db-backend span-stream reader,
//! `ct/load-request-spans` paging/filtering, and the read-only legacy JSONL
//! shim.
//!
//! Spec: `codetracer-specs/Trace-Files/CTFS-Request-Span-Streams.md`;
//! milestone RS-M2 in
//! `codetracer-specs/Planned-Features/Request-Panel-Live-Sessions.milestones.org`.
//!
//! # No mocks
//!
//! Every test here runs against a **real `.ct` container written by the
//! canonical Nim writer** (`codetracer-trace-format-nim`'s
//! `multi_stream_writer` + `span_stream`), committed under
//! `tests/fixtures/span_stream/` and regenerated by the `regenerate.sh` next to
//! them. Nothing is mocked, stubbed or faked: the Rust reader under test parses
//! bytes it did not produce, which is the entire point — it is the
//! cross-implementation proof that the Nim writer and this Rust reader agree on
//! the wire format.
//!
//! ## Why the fixtures are not "a container recorded by a real server run"
//!
//! RS-M2's `load_request_spans_from_recorded_container` asks for a container
//! from a real server run. **No recorder emits `span_type: "web-request"`
//! records yet.** Per-language emission is RS-M5…RS-M9 (Python, Ruby, PHP,
//! Elixir, JS), every one of which depends on RS-M4, which depends on *this*
//! milestone — RS-M2 is deliberately the readers-first step of the
//! readers-before-writers rollout the spec mandates for `meta.dat` bit 13
//! ("Old readers reject a span-bearing container outright… plan the rollout
//! accordingly (readers first, then writers)"). The most real writer that
//! exists today is therefore the canonical Nim one, and that is what produced
//! these fixtures. When RS-M5 lands, this file's fixture should be replaced by
//! a recorded Flask/PHP session; the assertions below are written against the
//! record contents rather than against fixture-specific byte offsets so that
//! swap is mechanical.
//!
//! The ground-truth `.expected.jsonl` sidecars are emitted by the generator
//! from the span values it fed the writer — **not** by re-reading the
//! container — so a writer bug cannot make the expectations agree with
//! themselves.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

use db_backend::ctfs_trace_reader::ctfs_container::CtfsReader;
use db_backend::ctfs_trace_reader::meta_dat::{FLAG_HAS_SPAN_STREAM, parse_meta_dat};
use db_backend::ctfs_trace_reader::span_stream::{
    SPAN_TYPE_PROCESS, SPAN_TYPE_WEB_REQUEST, SpanRecord, SpanStreamReader, read_span_type_namespace,
    span_ids_of_type,
};
use db_backend::request_spans::{
    LoadRequestSpansArguments, RequestRecord, RequestSpanFilters, RequestSpanSource, RequestSpans,
    load_request_spans,
};
use serde_json::Value;

// ── Fixture plumbing ────────────────────────────────────────────────────

fn fixture_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/span_stream")
}

/// Ground truth for one settled span, as the generator declared it.
#[derive(Debug, Clone, PartialEq, Eq)]
struct ExpectedSpan {
    span_id: u64,
    is_open: bool,
    is_external: bool,
    status: String,
    start_wall_ns: u64,
    end_wall_ns: u64,
    process_ord: u64,
    thread_id: u64,
    start_step: u64,
    end_step: u64,
    external_recording: String,
    external_path: String,
    span_type: String,
    label: String,
    contiguous_on_one_thread: bool,
    shares_timeline: bool,
    concurrent_with_siblings: bool,
    /// Metadata as an ORDERED list, so a reader that rebuilt it from a map is
    /// caught.
    metadata: Vec<(String, String)>,
}

fn load_expected(name: &str) -> Vec<ExpectedSpan> {
    let path = fixture_dir().join(name);
    let text = std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
    text.lines()
        .filter(|l| !l.trim().is_empty())
        .map(|line| {
            let v: Value = serde_json::from_str(line).expect("expected-line JSON");
            let s = |key: &str| v[key].as_str().unwrap_or_default().to_string();
            let u = |key: &str| v[key].as_u64().unwrap_or_default();
            let b = |key: &str| v[key].as_bool().unwrap_or_default();
            let meta_obj = v["metadata"].as_object().expect("metadata object");
            let metadata = v["metadata_order"]
                .as_array()
                .expect("metadata_order array")
                .iter()
                .map(|k| {
                    let key = k.as_str().expect("metadata key").to_string();
                    let value = meta_obj[&key].as_str().expect("metadata value").to_string();
                    (key, value)
                })
                .collect();
            ExpectedSpan {
                span_id: u("span_id"),
                is_open: b("is_open"),
                is_external: b("is_external"),
                status: s("status"),
                start_wall_ns: u("start_wall_ns"),
                end_wall_ns: u("end_wall_ns"),
                process_ord: u("process_ord"),
                thread_id: u("thread_id"),
                start_step: u("start_step"),
                end_step: u("end_step"),
                external_recording: s("external_recording"),
                external_path: s("external_path"),
                span_type: s("span_type"),
                label: s("label"),
                contiguous_on_one_thread: b("contiguous_on_one_thread"),
                shares_timeline: b("shares_timeline"),
                concurrent_with_siblings: b("concurrent_with_siblings"),
                metadata,
            }
        })
        .collect()
}

fn as_expected(span: &SpanRecord) -> ExpectedSpan {
    ExpectedSpan {
        span_id: span.span_id,
        is_open: span.is_open,
        is_external: span.is_external,
        status: match span.status {
            db_backend::ctfs_trace_reader::span_stream::SpanStatus::Unknown => "unknown",
            db_backend::ctfs_trace_reader::span_stream::SpanStatus::Ok => "ok",
            db_backend::ctfs_trace_reader::span_stream::SpanStatus::Error => "error",
        }
        .to_string(),
        start_wall_ns: span.start_wall_ns,
        end_wall_ns: span.end_wall_ns,
        process_ord: span.process_ord,
        thread_id: span.thread_id,
        start_step: span.start_step,
        end_step: span.end_step,
        external_recording: span.external_recording.clone(),
        external_path: span.external_path.clone(),
        span_type: span.span_type.clone(),
        label: span.label.clone(),
        contiguous_on_one_thread: span.contiguous_on_one_thread,
        shares_timeline: span.shares_timeline,
        concurrent_with_siblings: span.concurrent_with_siblings,
        metadata: span.metadata.clone(),
    }
}

/// Lay the `web_session.ct` fixture out as a *session directory*, complete with
/// the child container its external span binds to, so external-binding
/// resolution has something real to resolve against.
fn staged_session(tmp: &Path) -> PathBuf {
    let dir = tmp.join("session");
    std::fs::create_dir_all(dir.join("requests")).expect("mkdir requests");
    std::fs::copy(fixture_dir().join("web_session.ct"), dir.join("trace.ct")).expect("copy container");
    // The external span names `requests/req-0010.ct`.  Any real container will
    // do — what is under test is that the binding resolves to an OPENABLE
    // container path, so we use the span-free fixture (which is itself a valid
    // container the db-backend can open).
    std::fs::copy(fixture_dir().join("no_spans.ct"), dir.join("requests/req-0010.ct")).expect("copy child");
    dir
}

fn record_by_id(records: &[RequestRecord], id: u64) -> &RequestRecord {
    records
        .iter()
        .find(|r| r.id == id)
        .unwrap_or_else(|| panic!("no request record with id {id}"))
}

// ── Required test 1 ─────────────────────────────────────────────────────

/// RS-M2 required test `load_request_spans_from_recorded_container`.
///
/// Asserts that every request in a recorded container comes back through
/// `ct/load-request-spans` with the correct method, URL, status, duration and
/// **step binding**, and that the reader's structural guarantees hold:
///
/// * every wire field of every settled span matches the recording's own ground
///   truth, metadata order included;
/// * last-record-wins collapses the open record and its later, non-adjacent
///   completion into exactly one row;
/// * opening the stream decompresses NOTHING (the `spans.idx` v2 cumulative
///   column is what addresses a record);
/// * the `process` span is present but is not a request row;
/// * the external binding resolves to an openable child container.
///
/// This is also the **cross-implementation proof**: the container was written
/// by the Nim writer and is parsed here by the Rust reader.
#[test]
fn load_request_spans_from_recorded_container() {
    let tmp = tempfile::tempdir().expect("tempdir");
    let session = staged_session(tmp.path());

    // --- The container really does declare the span stream (bit 13). -----
    let mut ctfs = CtfsReader::open(&session.join("trace.ct")).expect("open container");
    let meta = parse_meta_dat(&ctfs.read_file("meta.dat").expect("meta.dat")).expect("parse meta.dat");
    assert_eq!(
        meta.flags & FLAG_HAS_SPAN_STREAM,
        FLAG_HAS_SPAN_STREAM,
        "the Nim writer must have set meta.dat bit 13"
    );

    // --- Opening the stream is index-only. -------------------------------
    let mut reader = SpanStreamReader::open_from_ctfs(&mut ctfs)
        .expect("open span stream")
        .expect("container declares bit 13, so the stream must be present");
    assert_eq!(
        reader.chunk_decompressions(),
        0,
        "opening a span stream must decompress nothing — the cumulative column addresses records"
    );
    // The generator sealed short chunks mid-stream (after records 3, 4 and 9),
    // so `chunk_size` cannot describe this stream and the index must.
    assert!(
        reader.chunk_count() > 1,
        "fixture must exercise multiple chunks, got {}",
        reader.chunk_count()
    );
    assert!(
        reader.records_in_chunk(0) < u64::from(reader.chunk_size_records()),
        "fixture must contain a SHORT chunk so chunk_size cannot be used to address records"
    );
    // 11 raw records: 10 distinct spans plus the open record superseded below.
    assert_eq!(reader.count(), 11, "raw record count");

    // Addressing a record by append-order index must agree with a full walk —
    // this is the binary search over the cumulative column.
    let all_raw = reader.read_all_span_records().expect("read all");
    assert_eq!(all_raw.len(), 11);
    let mut reader2 = SpanStreamReader::open_from_ctfs(&mut ctfs)
        .expect("reopen")
        .expect("stream present");
    for (i, want) in all_raw.iter().enumerate() {
        let got = reader2.read_span(i as u64).expect("read_span");
        assert_eq!(&got, want, "read_span({i}) addressed the wrong record");
    }

    // --- Every settled span matches the recording's ground truth. --------
    let settled = reader.settled_spans().expect("settled spans");
    let expected = load_expected("web_session.expected.jsonl");
    assert_eq!(settled.len(), expected.len(), "settled span count");
    for (got, want) in settled.iter().zip(expected.iter()) {
        assert_eq!(&as_expected(got), want, "span {} differs from ground truth", want.span_id);
    }

    // Last-record-wins: span 9 was appended OPEN first and completed later,
    // with other spans in between.  Exactly one row, and it is the completion.
    let span9 = settled.iter().find(|s| s.span_id == 9).expect("span 9");
    assert!(!span9.is_open, "the completion must supersede the open record");
    assert_eq!(span9.end_step, 5_400);
    assert_eq!(settled.iter().filter(|s| s.span_id == 9).count(), 1);

    // --- The request list served through ct/load-request-spans. ----------
    let spans = load_request_spans(&session)
        .expect("load request spans")
        .expect("session has requests");
    assert_eq!(spans.source, RequestSpanSource::SpanStream);
    let response = spans.page(&LoadRequestSpansArguments::default());
    assert_eq!(response.source, "span-stream");
    assert_eq!(response.skipped_lines, 0);

    // 10 settled spans, of which one is the process descriptor.
    assert_eq!(settled.len(), 10);
    assert_eq!(
        settled.iter().filter(|s| s.span_type == SPAN_TYPE_PROCESS).count(),
        1,
        "the RS-M1b process descriptor must be present"
    );
    assert_eq!(response.requests.len(), 9, "only web-request spans are rows");
    assert!(
        response.requests.iter().all(|r| r.id != 1),
        "the process span must not appear as a request row"
    );

    // --- Method / URL / status / duration / step binding, per request. ---
    // Written out longhand rather than looped so a regression names the row.
    let expect_row = |id: u64, method: &str, url: &str, status: i64, duration: i64, size: i64, geid: u64| {
        let r = record_by_id(&response.requests, id);
        assert_eq!(r.http_method, method, "row {id} method");
        assert_eq!(r.url, url, "row {id} url");
        assert_eq!(r.status_code, status, "row {id} status");
        assert_eq!(r.duration_ms, duration, "row {id} duration");
        assert_eq!(r.response_size, size, "row {id} response size");
        assert_eq!(r.start_geid, geid, "row {id} step binding (startGeid)");
    };
    expect_row(2, "GET", "/api/users", 200, 12, 2148, 120);
    expect_row(3, "POST", "/api/users", 201, 31, 96, 481);
    expect_row(4, "GET", "/api/users/42", 200, 8, 512, 1_041);
    expect_row(5, "GET", "/static/app.css", 304, 1, 0, 1_261);
    expect_row(6, "DELETE", "/api/users/42", 404, 5, 48, 1_291);
    expect_row(7, "PUT", "/api/orders/7", 500, 220, 76, 1_401);
    expect_row(8, "GET", "/health", 200, 1, 2, 2_601);
    expect_row(9, "GET", "/api/reports/slow", 200, 940, 8_192, 2_621);
    expect_row(10, "POST", "/api/orders", 502, 1_200, 64, 0);

    // Span status travels alongside the HTTP code — an aborted request has a
    // status but no code, so the two are not interchangeable.
    assert_eq!(record_by_id(&response.requests, 2).status, "ok");
    assert_eq!(record_by_id(&response.requests, 7).status, "error");
    assert!(response.requests.iter().all(|r| !r.is_open), "nothing is still in flight");

    // --- The external binding resolves to an openable container. ---------
    let external = record_by_id(&response.requests, 10);
    let child = external
        .external_trace_path
        .as_ref()
        .expect("external span must resolve to a child container path");
    assert_eq!(Path::new(child), session.join("requests/req-0010.ct"));
    CtfsReader::open(Path::new(child)).expect("the resolved child path must actually be openable");
    // An inline span has no external path at all.
    assert!(record_by_id(&response.requests, 2).external_trace_path.is_none());

    // --- spantype.ns agrees with the records. ----------------------------
    let entries = read_span_type_namespace(&mut ctfs)
        .expect("read spantype.ns")
        .expect("a span-bearing container carries spantype.ns");
    assert_eq!(
        span_ids_of_type(&entries, SPAN_TYPE_WEB_REQUEST),
        &[2, 3, 4, 5, 6, 7, 8, 9, 10],
        "spantype.ns must list each web-request span id exactly once, ascending"
    );
    assert_eq!(span_ids_of_type(&entries, SPAN_TYPE_PROCESS), &[1]);
}

// ── Required test 2 ─────────────────────────────────────────────────────

/// Reference implementation of "what should this filter return?", computed by a
/// **full scan** over every record in the container, independently of the paging
/// code under test.
fn full_scan_reference(spans: &RequestSpans, filters: &RequestSpanFilters) -> Vec<RequestRecord> {
    spans
        .spans
        .iter()
        .filter(|s| s.span_type == SPAN_TYPE_WEB_REQUEST)
        .map(|s| spans.to_request_record(s))
        .filter(|r| filters.matches(r))
        .collect()
}

/// RS-M2 required test `load_request_spans_pagination_and_filters`.
///
/// Pages a 200-request recording in chunks and asserts that, for every filter
/// combination, the concatenation of the pages is **byte-identical** to a
/// full-scan reference over the same container — same rows, same order, no gaps,
/// no repeats — and that the reported `total` matches the reference size.
///
/// The page size (17) is deliberately coprime with the record count, with the
/// writer's chunk-seal points and with every filter's match count, so no page
/// boundary can accidentally coincide with a chunk boundary.
#[test]
fn load_request_spans_pagination_and_filters() {
    let container = fixture_dir().join("web_session_200.ct");
    let spans = load_request_spans(&container)
        .expect("load request spans")
        .expect("the 200-request fixture has requests");
    assert_eq!(spans.source, RequestSpanSource::SpanStream);

    // The recording really does hold 200 requests, and they match the
    // generator's ground truth.
    let expected = load_expected("web_session_200.expected.jsonl");
    assert_eq!(expected.len(), 200);
    assert_eq!(spans.spans.len(), 200);
    for (got, want) in spans.spans.iter().zip(expected.iter()) {
        assert_eq!(&as_expected(got), want, "span {} differs from ground truth", want.span_id);
    }

    let no_filter = RequestSpanFilters::default();
    let cases: Vec<(&str, RequestSpanFilters)> = vec![
        ("unfiltered", no_filter.clone()),
        (
            "method=GET",
            RequestSpanFilters {
                method: Some("GET".to_string()),
                ..Default::default()
            },
        ),
        (
            "method=delete (case-insensitive)",
            RequestSpanFilters {
                method: Some("delete".to_string()),
                ..Default::default()
            },
        ),
        (
            "status=5xx",
            RequestSpanFilters {
                status_class: Some("5xx".to_string()),
                ..Default::default()
            },
        ),
        (
            "status=2xx",
            RequestSpanFilters {
                status_class: Some("2xx".to_string()),
                ..Default::default()
            },
        ),
        (
            "url contains /api/",
            RequestSpanFilters {
                url_contains: Some("/api/".to_string()),
                ..Default::default()
            },
        ),
        (
            "url contains USERS (case-insensitive)",
            RequestSpanFilters {
                url_contains: Some("USERS".to_string()),
                ..Default::default()
            },
        ),
        (
            "method=POST + status=4xx + url contains order",
            RequestSpanFilters {
                method: Some("POST".to_string()),
                status_class: Some("4xx".to_string()),
                url_contains: Some("order".to_string()),
            },
        ),
        (
            "a filter that matches nothing",
            RequestSpanFilters {
                method: Some("PATCH".to_string()),
                ..Default::default()
            },
        ),
    ];

    for (name, filters) in cases {
        let reference = full_scan_reference(&spans, &filters);

        // Every filter case must be meaningfully populated (except the one
        // deliberately chosen to be empty), otherwise the case proves nothing.
        if name != "a filter that matches nothing" {
            assert!(!reference.is_empty(), "filter case {name:?} matched nothing — fixture drift?");
            assert!(
                reference.len() < 200 || name == "unfiltered",
                "filter case {name:?} narrowed nothing"
            );
        }

        // One-shot: no paging at all.
        let whole = spans.page(&LoadRequestSpansArguments {
            filters: Some(filters.clone()),
            ..Default::default()
        });
        assert_eq!(whole.requests, reference, "{name}: unpaged result differs from full scan");
        assert_eq!(whole.total, reference.len(), "{name}: total");
        assert_eq!(whole.next_span_id, None, "{name}: an unlimited page is never continued");

        // Paged: follow the cursor until it runs out.
        for page_size in [1usize, 17, 199, 200, 201] {
            let mut walked: Vec<RequestRecord> = Vec::new();
            let mut cursor = Some(0u64);
            let mut pages = 0usize;
            while let Some(from) = cursor {
                let page = spans.page(&LoadRequestSpansArguments {
                    from_span_id: Some(from),
                    limit: Some(page_size),
                    filters: Some(filters.clone()),
                });
                assert_eq!(page.total, reference.len(), "{name}/{page_size}: total on every page");
                assert!(
                    page.requests.len() <= page_size,
                    "{name}/{page_size}: page overran its limit"
                );
                walked.extend(page.requests);
                cursor = page.next_span_id;
                pages += 1;
                assert!(pages <= 300, "{name}/{page_size}: paging did not terminate");
            }
            assert_eq!(
                walked, reference,
                "{name}/{page_size}: paged concatenation differs from the full scan"
            );
        }
    }

    // `fromSpanId` is an inclusive lower bound on the *span id*, not an offset,
    // so a caller resuming from a known id never re-reads a row it has seen.
    let tail = spans.page(&LoadRequestSpansArguments {
        from_span_id: Some(150),
        ..Default::default()
    });
    assert_eq!(tail.requests.len(), 51);
    assert_eq!(tail.requests[0].id, 150);
    assert_eq!(tail.requests.last().expect("last").id, 200);
}

// ── Required test 3 ─────────────────────────────────────────────────────

/// RS-M2 required test `legacy_jsonl_session_still_opens`.
///
/// Opens a pre-cutover PHP-style session directory — one whose only description
/// of its requests is a `session_manifest.jsonl` sidecar — and asserts the shim
/// yields the same records the stream path does for the same session.
///
/// The manifest fixture is generated from the *same* span list as
/// `web_session.ct` (see `gen_span_fixtures.nim`), so the two artefacts cannot
/// drift into describing different sessions.
///
/// The comparison is on every column the sidecar format is capable of carrying.
/// The two it is **not** capable of carrying — `startGeid` and `responseSize` —
/// are asserted to be absent, because that gap is the whole reason the span
/// stream exists and hiding it would make the shim look lossless.
#[test]
fn legacy_jsonl_session_still_opens() {
    let tmp = tempfile::tempdir().expect("tempdir");

    // The stream-path reference: the same session, read from the container.
    let stream_session = staged_session(tmp.path());
    let stream_spans = load_request_spans(&stream_session)
        .expect("load stream spans")
        .expect("stream session has requests");
    assert_eq!(stream_spans.source, RequestSpanSource::SpanStream);
    let stream_rows = stream_spans.page(&LoadRequestSpansArguments::default()).requests;

    // The pre-cutover session directory: a sidecar and nothing else.  This is
    // what a PHP-FPM worker running `web_bootstrap.php` leaves behind.
    let manifest = std::fs::read_to_string(fixture_dir().join("web_session.manifest.jsonl")).expect("read manifest");
    for sidecar_name in ["session_manifest.jsonl", "codetracer_spans.jsonl"] {
        let legacy = tmp.path().join(format!("legacy-{sidecar_name}"));
        std::fs::create_dir_all(&legacy).expect("mkdir");
        std::fs::write(legacy.join(sidecar_name), &manifest).expect("write sidecar");

        let legacy_spans = load_request_spans(&legacy)
            .expect("load legacy spans")
            .expect("a pre-cutover session must still open");
        assert_eq!(
            legacy_spans.source,
            RequestSpanSource::LegacyJsonl,
            "{sidecar_name}: must come through the shim"
        );
        let response = legacy_spans.page(&LoadRequestSpansArguments::default());
        assert_eq!(response.source, "legacy-jsonl");
        assert_eq!(response.skipped_lines, 0, "{sidecar_name}: nothing may be skipped");

        let legacy_rows = response.requests;
        assert_eq!(
            legacy_rows.len(),
            stream_rows.len(),
            "{sidecar_name}: the shim must yield one record per request"
        );

        for (legacy, stream) in legacy_rows.iter().zip(stream_rows.iter()) {
            let ctx = format!("{sidecar_name} {} {}", stream.http_method, stream.url);
            assert_eq!(legacy.http_method, stream.http_method, "{ctx}: method");
            assert_eq!(legacy.url, stream.url, "{ctx}: url");
            assert_eq!(legacy.status_code, stream.status_code, "{ctx}: status");
            assert_eq!(legacy.duration_ms, stream.duration_ms, "{ctx}: duration");
            assert_eq!(legacy.status, stream.status, "{ctx}: span status");
            assert_eq!(legacy.is_open, stream.is_open, "{ctx}: in-flight state");

            // The two columns the sidecar format never carried.  Asserting the
            // zero (rather than skipping the field) documents the deficiency
            // the span stream removes: a legacy row cannot seek to its handler.
            assert_eq!(legacy.start_geid, 0, "{ctx}: the sidecar has no step binding");
            assert_eq!(legacy.response_size, 0, "{ctx}: the sidecar has no response size");
        }

        // Ids differ by exactly one because the stream ALSO numbers the
        // process-descriptor span (span_id 1), which the sidecar never
        // described.  Both are 1-based capture ordinals within their own
        // artefact, and both are dense — which is what makes them usable as the
        // paging cursor.
        let legacy_ids: Vec<u64> = legacy_rows.iter().map(|r| r.id).collect();
        let stream_ids: Vec<u64> = stream_rows.iter().map(|r| r.id).collect();
        assert_eq!(legacy_ids, (1..=9).collect::<Vec<u64>>());
        assert_eq!(stream_ids, (2..=10).collect::<Vec<u64>>());

        // Every sidecar entry named a `trace_dir`, which the shim models as the
        // external binding the spec says it replaces.
        assert!(
            legacy_spans.spans.iter().all(|s| s.is_external && !s.external_path.is_empty()),
            "{sidecar_name}: every sidecar row carries a trace_dir external binding"
        );

        // Paging and filtering work identically on the shim's output — the two
        // sources are interchangeable from `ct/load-request-spans`' point of
        // view, which is the compatibility promise.
        let filtered = legacy_spans.page(&LoadRequestSpansArguments {
            filters: Some(RequestSpanFilters {
                method: Some("GET".to_string()),
                ..Default::default()
            }),
            limit: Some(2),
            ..Default::default()
        });
        assert!(filtered.requests.iter().all(|r| r.http_method == "GET"));
        assert!(filtered.requests.len() <= 2);
        assert_eq!(filtered.total, stream_rows.iter().filter(|r| r.http_method == "GET").count());
    }
}

// ── Supporting guarantees ───────────────────────────────────────────────

/// A container WITHOUT a span stream must open exactly as it did before RS-M2 —
/// bit 13 clear, no `spans.dat`, no behaviour change.
///
/// This is the spec's Design Goal 6 ("A container *without* spans is
/// byte-identical to pre-RS-M1 output") from the reader's side: adding bit 13 to
/// the reader's `KNOWN_FLAGS_MASK` must not perturb the bit-13-clear path.
#[test]
fn container_without_span_stream_opens_unchanged() {
    let container = fixture_dir().join("no_spans.ct");
    let mut ctfs = CtfsReader::open(&container).expect("open span-free container");
    let meta = parse_meta_dat(&ctfs.read_file("meta.dat").expect("meta.dat")).expect("parse meta.dat");
    assert_eq!(meta.flags & FLAG_HAS_SPAN_STREAM, 0, "bit 13 must be clear");
    assert!(!ctfs.has_file("spans.dat"));
    assert!(!ctfs.has_file("spans.idx"));
    assert!(!ctfs.has_file("spantype.ns"));

    assert!(
        SpanStreamReader::open_from_ctfs(&mut ctfs).expect("must not error").is_none(),
        "no bit 13 means no span stream, not an error"
    );
    assert!(
        read_span_type_namespace(&mut ctfs).expect("must not error").is_none(),
        "a span-free container has no spantype.ns"
    );

    // And the whole request-span surface degrades to "this recording has no
    // requests" rather than failing.
    let tmp = tempfile::tempdir().expect("tempdir");
    std::fs::copy(&container, tmp.path().join("trace.ct")).expect("copy");
    assert!(
        load_request_spans(tmp.path()).expect("must not error").is_none(),
        "a span-free recording with no sidecar has no request list"
    );
}

/// The wire format agrees end to end: the metadata the Nim writer emitted, in
/// the order it emitted it, is what the Rust reader hands the panel.
///
/// Metadata order is part of the contract ("consumers render metadata in the
/// order the recorder emitted it"), and it is the one property a map-based
/// decoder would silently destroy, so it gets its own assertion against a
/// deliberately non-alphabetical key order.
#[test]
fn nim_written_metadata_survives_the_rust_reader_in_order() {
    let container = fixture_dir().join("web_session.ct");
    let mut ctfs = CtfsReader::open(&container).expect("open");
    let mut reader = SpanStreamReader::open_from_ctfs(&mut ctfs)
        .expect("open stream")
        .expect("stream present");
    let settled = reader.settled_spans().expect("settled");

    let request = settled.iter().find(|s| s.span_id == 2).expect("span 2");
    let keys: Vec<&str> = request.metadata.iter().map(|(k, _)| k.as_str()).collect();
    assert_eq!(
        keys,
        vec![
            "http.method",
            "http.url",
            "http.status_code",
            "http.duration_ms",
            "http.response_size",
            "http.remote_addr",
            "framework",
        ],
        "metadata must survive in emission order, not sorted"
    );
    assert_ne!(
        keys,
        {
            let mut sorted = keys.clone();
            sorted.sort_unstable();
            sorted
        },
        "the fixture's key order must be non-alphabetical for this assertion to mean anything"
    );

    // The process descriptor carries the fields the dead `meta.json` process
    // table used to hold (RS-M1b).
    let process = settled.iter().find(|s| s.span_type == SPAN_TYPE_PROCESS).expect("process span");
    let by_key: BTreeMap<&str, &str> = process
        .metadata
        .iter()
        .map(|(k, v)| (k.as_str(), v.as_str()))
        .collect();
    assert_eq!(by_key.get("process.pid"), Some(&"4242"));
    assert_eq!(by_key.get("process.exe"), Some(&"/usr/bin/php-fpm"));
    assert_eq!(by_key.get("process.has_execed"), Some(&"false"));
}
