"""Type stubs for codetracer.types -- data types for the Trace Query API."""

from dataclasses import dataclass
from typing import Any, Optional

@dataclass(frozen=True)
class Location:
    """A source-code location (path, line, optional column)."""
    path: str
    line: int
    column: int = ...
    def __str__(self) -> str: ...

@dataclass(frozen=True)
class Variable:
    """A captured variable value at a specific point in execution."""
    name: str
    value: str
    type_name: Optional[str] = ...
    children: list[Variable] = ...

@dataclass(frozen=True)
class Frame:
    """A single call-frame on the execution stack."""
    function_name: str
    location: Location
    variables: list[Variable] = ...

@dataclass(frozen=True)
class FlowStep:
    """One step in an execution flow (a single executed source line)."""
    location: Location
    ticks: int = ...
    loop_id: int = ...
    iteration: int = ...
    before_values: dict[str, str] = ...
    after_values: dict[str, str] = ...
    variables: list[Variable] = ...
    step_index: Optional[int] = ...

@dataclass(frozen=True)
class Flow:
    """An execution flow: a contiguous sequence of executed steps."""
    steps: list[FlowStep] = ...
    loops: list[Loop] = ...

@dataclass(frozen=True)
class Loop:
    """A detected loop in the execution trace."""
    id: int = ...
    location: Location = ...
    start_line: int = ...
    end_line: int = ...
    iteration_count: int = ...
    body_steps: list[FlowStep] = ...

@dataclass(frozen=True)
class Call:
    """A recorded function/method call."""
    function_name: str
    location: Location
    arguments: list[Variable] = ...
    return_value: Optional[Variable] = ...
    id: int = ...
    children_count: int = ...
    depth: int = ...

@dataclass(frozen=True)
class Event:
    """A trace event (e.g. stdout output, stderr output, signal)."""
    kind: str
    message: str
    location: Optional[Location] = ...
    data: Optional[dict[str, Any]] = ...
    id: int = ...
    ticks: int = ...
    content: str = ...

@dataclass(frozen=True)
class Process:
    """A process in a multi-process trace."""
    id: int
    name: str
    command: str
