#!/usr/bin/env bash
set -euo pipefail

# Generate isonim's build/tailwind-styles.json before any frontend Nim
# compile. ``src/frontend/ui_js.nim`` transitively imports
# ``isonim/dsl/tailwind``, which ``staticRead``s that file at Nim compile
# time — a missing file is an uncatchable compile error
# (see isonim/src/isonim/dsl/tailwind.nim), so the ``frontend-ui-js``
# build action fails without it. ``build-tailwind.sh`` regenerates it each
# run (cheap), driving the extract over BOTH isonim's and CodeTracer's own
# ``.nim`` sources so frontend-only utility classes are not silently
# dropped. Failures must propagate — the uncatchable staticRead otherwise
# resurfaces as an opaque Nim compile error several minutes later.
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# Sibling repos first -- before ANY build step, including build-tailwind.sh,
# which itself drives an extract over ../isonim's sources. Every consumer of a
# missing sibling degrades badly (nim silently ignores a nonexistent --path;
# cargo path deps fail with "failed to load manifest"; build.rs used to skip
# its link directives and leave 81 undefined `mcr*` symbols), so the only place
# the workspace can be diagnosed by name is here, up front.
"${BASH:-bash}" "$SCRIPT_DIR/require-siblings.sh"

"$SCRIPT_DIR/build-tailwind.sh"

# ---------------------------------------------------------------------------
# Single source of truth for the resolved build identity.
#
# `scripts/build.sh` (`just build`) drives this script and then starts watchers
# over the SAME output tree. Re-deriving config -> variant -> output root there
# is exactly what let `just build` hardcode `tup build-debug` and
# `livereload src/build-debug` while `just build-once` honoured
# CODETRACER_CONFIG -- half of issue #599. So this script, which owns the
# derivation, publishes what it resolved and build.sh consumes it rather than
# guessing.
#
# Contract: when CODETRACER_BUILD_ENV_FILE names a path, this script writes a
# shell-sourceable file with exactly these keys, and writes it BEFORE the build
# work starts so a later failure still leaves callers a usable answer:
#
#   CT_BUILD_HOST     reprobuild host id ("darwin" | "linux" | "windows"), or
#                     "" for the legacy tup branch. This is the branch
#                     selector; callers must not re-implement the uname case.
#   CT_BUILD_CONFIG   "debug" | "release" (from CODETRACER_CONFIG).
#   CT_BUILD_VARIANT  tup variant directory name ("build-debug"), or "" on the
#                     reprobuild branch, which has no tup variant.
#   CT_BUILD_OUT_ROOT the output tree, relative to the repo root -- the
#                     directory holding bin/ct and the assets livereload
#                     watches.
#
# Values are single-quoted so a path containing spaces round-trips.
# ---------------------------------------------------------------------------
ct_publish_build_env() {
	if [ -z "${CODETRACER_BUILD_ENV_FILE:-}" ]; then
		return 0
	fi
	local host="$1" config="$2" variant="$3" out_root="$4"
	local dir
	dir="$(dirname "$CODETRACER_BUILD_ENV_FILE")"
	mkdir -p "$dir"
	cat >"$CODETRACER_BUILD_ENV_FILE" <<EOF
# Generated by scripts/build-once.sh -- do not edit.
CT_BUILD_HOST='$host'
CT_BUILD_CONFIG='$config'
CT_BUILD_VARIANT='$variant'
CT_BUILD_OUT_ROOT='$out_root'
EOF
}

# Reprobuild branch: macOS (Darwin) and Linux both use Nix tool
# provisioning (the codetracer dev shell provisions every `uses:` tool
# into /nix/store, picked up via the cakNix adapter); Windows (MINGW* /
# MSYS* via Git Bash) uses Scoop/PATH provisioning since the codetracer
# DIY toolchain bootstrap (`. env.ps1`) has already populated PATH with
# every tool the codetracer `uses:` clause references on its Windows
# branch. On all three, the codetracer recipe lives in `reprobuild.nim`
# and is built end-to-end via the local `repro` binary.
case "$(uname -s)" in
Darwin) ct_reprobuild_host="darwin" ;;
Linux)
	# Reprobuild is the default build driver on macOS, but on Linux it is
	# still experimental: keep `just build-once` on the legacy tup path by
	# default while we gain more experience with reprobuild here. Developers
	# can opt in per-invocation with CODETRACER_REPROBUILD_LINUX=1. Windows
	# keeps the reprobuild branch because it has no tup fallback in this
	# script.
	if [ -n "${CODETRACER_REPROBUILD_LINUX:-}" ]; then
		ct_reprobuild_host="linux"
	else
		ct_reprobuild_host=""
	fi
	;;
MINGW* | MSYS* | CYGWIN*) ct_reprobuild_host="windows" ;;
*) ct_reprobuild_host="" ;;
esac

if [ -n "$ct_reprobuild_host" ]; then
	# Build configuration (debug/release), selected by CODETRACER_CONFIG
	# (default: debug). It picks the reprobuild output tree
	# (`src/build-<config>-repro` on all platforms — the `-repro` suffix keeps
	# it out of tup's `src/build-debug` variant dir) and threads the
	# `buildType` reprobuild variant to the recipe so the value participates in
	# the graph cache key (see reprobuild-specs/Standard-Configurations.md and
	# `buildDebugRoot()` in reprobuild.nim, the source of truth). `--release`
	# on a `repro` with the standard-config shorthands is equivalent to
	# `REPRO_VARIANTS=buildType=release`; we set the env directly so this works
	# with any `repro` binary.
	ct_config="${CODETRACER_CONFIG:-debug}"
	ct_repro_out_root="src/build-${ct_config}-repro"
	# The reprobuild branch has no tup variant, hence the empty third field.
	ct_publish_build_env "$ct_reprobuild_host" "$ct_config" "" "$ct_repro_out_root"
	if [ -z "${REPRO_VARIANTS:-}" ]; then
		export REPRO_VARIANTS="buildType=${ct_config}"
	elif ! printf '%s' "$REPRO_VARIANTS" | grep -q "buildType="; then
		export REPRO_VARIANTS="${REPRO_VARIANTS},buildType=${ct_config}"
	fi

	repro_bin="${REPROBUILD_BIN:-}"
	reprobuild_root="${CODETRACER_REPROBUILD_REPO_PATH:-}"

	if [ -z "$reprobuild_root" ]; then
		for candidate in ../reprobuild ../../reprobuild; do
			if [ -d "$candidate/libs/repro_cli_support" ]; then
				reprobuild_root="$(cd "$candidate" && pwd)"
				break
			fi
		done
	fi

	if [ -z "$reprobuild_root" ] && [ -n "${REPROBUILD_SOURCE_ROOT:-}" ] &&
		[[ $REPROBUILD_SOURCE_ROOT != /nix/store/* ]]; then
		reprobuild_root="$REPROBUILD_SOURCE_ROOT"
	fi

	# On Windows, `repro` ships as `repro.exe`; the `repro` (no extension)
	# alias may not exist depending on how the sibling reprobuild was
	# built. Probe both filenames under the sibling's `build/bin/`.
	if [ -z "$repro_bin" ] && [ -n "$reprobuild_root" ]; then
		for cand in "$reprobuild_root/build/bin/repro.exe" "$reprobuild_root/build/bin/repro"; do
			if [ -x "$cand" ]; then
				repro_bin="$cand"
				break
			fi
		done
	fi

	if [ -z "$repro_bin" ]; then
		repro_bin="$(command -v repro || true)"
	fi

	if [ -z "$repro_bin" ]; then
		echo "Error: repro is required for codetracer reprobuild builds on $ct_reprobuild_host." >&2
		echo "Set REPROBUILD_BIN or CODETRACER_REPROBUILD_REPO_PATH, or put repro on PATH." >&2
		exit 127
	fi

	if [ -n "$reprobuild_root" ]; then
		export REPROBUILD_SOURCE_ROOT="$reprobuild_root"
		export CODETRACER_REPROBUILD_REPO_PATH="${CODETRACER_REPROBUILD_REPO_PATH:-$reprobuild_root}"
	fi

	# Point the fs-snoop process monitor at the shim library that ships
	# next to the repro binary. repro normally finds librepro_monitor_shim
	# via getAppDir()/../lib, but the daemon-hosted build runs through a
	# relocated `repro-daemon` copy under ~/.local/state/repro/daemon/, whose
	# appDir has no sibling lib/ — so without an explicit path every monitored
	# action aborts with "cannot find librepro_monitor_shim". The daemon
	# inherits this env var from `repro build`, and the fs-snoop resolver
	# honours REPRO_MONITOR_SHIM_LIB ahead of the appDir probes (see
	# reprobuild libs/repro_monitor_depfile/.../fs_snoop.nim). Only set it
	# when we can actually locate the co-located shim and the caller hasn't
	# pinned one already.
	if [ -z "${REPRO_MONITOR_SHIM_LIB:-}" ]; then
		case "$ct_reprobuild_host" in
		darwin) ct_shim_name="librepro_monitor_shim.dylib" ;;
		windows) ct_shim_name="librepro_monitor_shim.dll" ;;
		*) ct_shim_name="librepro_monitor_shim.so" ;;
		esac
		ct_repro_bin_dir="$(cd "$(dirname "$repro_bin")" && pwd)"
		for ct_shim_candidate in \
			"$ct_repro_bin_dir/../lib/$ct_shim_name" \
			"$ct_repro_bin_dir/$ct_shim_name"; do
			if [ -f "$ct_shim_candidate" ]; then
				# Declare and assign separately so the command substitution's
				# exit status is not masked by ``export`` (shellcheck SC2155).
				ct_shim_dir="$(cd "$(dirname "$ct_shim_candidate")" && pwd)"
				ct_shim_abs="$ct_shim_dir/$(basename "$ct_shim_candidate")"
				export REPRO_MONITOR_SHIM_LIB="$ct_shim_abs"
				break
			fi
		done
	fi

	# The codetracer reprobuild build is nix-provisioned, so mirror the
	# pure-nix package build (nix/packages/default.nix) for the db-backend
	# cargo crate's build scripts instead of letting them re-enter a nested
	# ``direnv exec`` / ``nix develop``:
	#   * CODETRACER_DB_BACKEND_SKIP_DIRENV=1 makes
	#     src/db-backend/build.rs::regenerate_c invoke ``bash`` directly. The
	#     default POSIX path spawns ``direnv exec <native-recorder> bash
	#     build_native_api.sh``, which re-enters a full ``nix develop`` of the
	#     native-recorder flake *inside* the fs-snoop sandbox — minutes-long
	#     on first run and fragile under process monitoring.
	#   * CODETRACER_TRACE_FORMAT_NIM_SKIP_NIMBLE_INSTALL=1 keeps
	#     codetracer_trace_writer_nim's build.rs from running a network
	#     ``nimble install``.
	#   * CT_EMULATOR_EXTRA_NIM_PATHS / CODETRACER_TRACE_FORMAT_NIM_EXTRA_PATHS
	#     inject codetracer's vendored ``stew`` tree (which ships the newer
	#     results.nim those scripts rely on) so their ``nim c`` resolves
	#     ``results`` / ``stew`` without a nimble package store.
	# Windows skips direnv unconditionally in build.rs and sets up Nim via
	# env.ps1, so leave that branch untouched.
	if [ "$ct_reprobuild_host" != "windows" ]; then
		export CODETRACER_DB_BACKEND_SKIP_DIRENV="${CODETRACER_DB_BACKEND_SKIP_DIRENV:-1}"
		export CODETRACER_TRACE_FORMAT_NIM_SKIP_NIMBLE_INSTALL="${CODETRACER_TRACE_FORMAT_NIM_SKIP_NIMBLE_INSTALL:-1}"
		if [ -z "${CT_EMULATOR_EXTRA_NIM_PATHS:-}" ] && [ -d "$PWD/libs/nim-stew/stew" ]; then
			ct_nim_paths_lib="$PWD/libs/nim-stew/stew:$PWD/libs/nim-stew"
			export CT_EMULATOR_EXTRA_NIM_PATHS="$ct_nim_paths_lib"
			export CODETRACER_TRACE_FORMAT_NIM_EXTRA_PATHS="${CODETRACER_TRACE_FORMAT_NIM_EXTRA_PATHS:-$ct_nim_paths_lib}"
		fi
	fi

	# Ask the daemon binary to identify itself. `runquotad --version` prints its
	# version and exits, but only when it is the SOLE argument -- with anything
	# else alongside it the process goes on to serve -- so pass nothing else.
	# The call is run detached behind a bounded wait rather than through
	# `timeout(1)`, which is not available on every host this script supports
	# (notably stock macOS), so an unexpected binary that ignores the flag and
	# keeps running cannot stall the failure report. Only ever called on a
	# failure path.
	ct_runquotad_version() {
		local out_file="$runquota_log.version" version_pid waited=0
		: >"$out_file" 2>/dev/null || true
		"$runquotad_bin" --version >"$out_file" 2>&1 </dev/null &
		version_pid="$!"
		while [ "$waited" -lt 50 ] && kill -0 "$version_pid" 2>/dev/null; do
			sleep 0.1
			waited=$((waited + 1))
		done
		kill "$version_pid" 2>/dev/null || true
		wait "$version_pid" 2>/dev/null || true
		# Keep it to a couple of lines on one line: an old binary answers an
		# unrecognised flag with its usage text, which is itself the answer.
		#
		# The trailing ``|| true`` is load-bearing under ``set -o pipefail``:
		# when the probe file could not be created (an unwritable
		# ``.repro/runquota``, a full disk) ``head`` exits non-zero, that
		# status becomes the function's, and the caller's
		# ``version_output="$(...)"`` assignment would abort the script under
		# ``set -e`` -- suppressing the very report this function exists to
		# decorate. A missing version string must degrade to "unknown", never
		# to a silent exit.
		head -n 3 "$out_file" 2>/dev/null | tr '\n' ' ' || true
	}

	# Report everything needed to diagnose a daemon that would not come up.
	# Both failure paths below used to print just the *path* of the daemon log,
	# which nobody ever gets to read: the script exits immediately and CI
	# discards the workspace, so the one artefact naming the cause was thrown
	# away exactly when it was needed. Print the resolved binary (a stale one on
	# PATH rejecting a newer flag looks identical to a daemon crash from the
	# outside), how it was found, its argv, the socket, and the log itself.
	ct_report_runquotad_failure() {
		local reason="$1" version_output arg
		# Belt and braces alongside the guard inside ct_runquotad_version: a
		# diagnostic helper must not be able to take the script down before it
		# has printed anything, so nothing this reporter gathers is allowed to
		# be fatal.
		version_output="$(ct_runquotad_version)" || version_output=""
		{
			echo "Error: $reason"
			echo "----- runquotad diagnostics -----"
			echo "binary:      $runquotad_bin"
			echo "resolved by: $runquotad_origin"
			echo "version:     ${version_output:-(no output from --version)}"
			# The byte count matters: the socket path is derived from TMPDIR,
			# and a Unix-domain socket path is limited to ~108 bytes
			# (`sun_path` in `man 7 unix`), so a long TMPDIR makes the daemon
			# fail at bind time on a path that otherwise looks perfectly fine.
			echo "socket:      $runquota_socket (${#runquota_socket} bytes)"
			echo "argv:"
			for arg in "${runquotad_argv[@]}"; do
				printf '  %s\n' "$arg"
			done
			echo "----- begin $runquota_log -----"
			if [ ! -f "$runquota_log" ]; then
				echo "(no log file was created at $runquota_log)"
			elif [ ! -s "$runquota_log" ]; then
				echo "(log file $runquota_log exists but is empty)"
			else
				cat "$runquota_log"
			fi
			echo "----- end $runquota_log -----"
		} >&2
	}

	runquotad_pid=""
	if [ -z "${RUNQUOTA_SOCKET:-}" ]; then
		# Windows ships `runquotad.exe`; macOS / Linux ship a bare
		# `runquotad`. Search both filenames.
		runquotad_candidates=(
			"../runquota/build/bin/runquotad.exe"
			"../../runquota/build/bin/runquotad.exe"
			"../runquota/build/bin/runquotad"
			"../../runquota/build/bin/runquotad"
		)
		# Which of the three resolution routes won. Reported on failure: the
		# same script can legitimately pick a sibling build, an explicitly
		# pinned binary or whatever happens to be on PATH, and those can be
		# different revisions of runquota.
		runquotad_origin=""
		runquotad_bin="${RUNQUOTAD_BIN:-}"
		if [ -n "$runquotad_bin" ]; then
			runquotad_origin="RUNQUOTAD_BIN"
		else
			for candidate in "${runquotad_candidates[@]}"; do
				if [ -x "$candidate" ]; then
					runquotad_bin="$(cd "$(dirname "$candidate")" && pwd)/$(basename "$candidate")"
					runquotad_origin="sibling checkout candidate $candidate"
					break
				fi
			done
		fi
		if [ -z "$runquotad_bin" ]; then
			runquotad_bin="$(command -v runquotad || true)"
			if [ -n "$runquotad_bin" ]; then
				runquotad_origin="PATH lookup"
			fi
		fi
		if [ -z "$runquotad_bin" ]; then
			echo "Error: runquotad is required for Reprobuild builds with RunQuota." >&2
			echo "Build ../runquota or set RUNQUOTAD_BIN/RUNQUOTA_SOCKET." >&2
			echo "RUNQUOTAD_BIN: (unset or empty)" >&2
			echo "Searched, relative to $PWD:" >&2
			for candidate in "${runquotad_candidates[@]}"; do
				echo "  $candidate (no executable file there)" >&2
			done
			echo "  runquotad on PATH: not found" >&2
			echo "PATH: $PATH" >&2
			exit 127
		fi

		mkdir -p .repro/runquota
		runquota_socket="${TMPDIR:-/tmp}/codetracer-reprobuild-$$.sock"
		runquota_log=".repro/runquota/runquotad.log"
		# Kept in an array so the failure report can echo back the exact
		# command line, argument for argument, instead of a prose summary that
		# drifts from the code.
		runquotad_argv=(
			"$runquotad_bin"
			--socket "$runquota_socket"
			--cpu-milli "${CODETRACER_RUNQUOTA_CPU_MILLI:-8000}"
			--memory-bytes "${CODETRACER_RUNQUOTA_MEMORY_BYTES:-17179869184}"
			--pool console=1
		)
		rm -f "$runquota_socket"
		"${runquotad_argv[@]}" >"$runquota_log" 2>&1 &
		runquotad_pid="$!"
		trap 'if [ -n "$runquotad_pid" ]; then kill "$runquotad_pid" 2>/dev/null || true; wait "$runquotad_pid" 2>/dev/null || true; fi' EXIT
		for _ in {1..300}; do
			if grep -q "runquotad listening" "$runquota_log" 2>/dev/null; then
				export RUNQUOTA_SOCKET="$runquota_socket"
				break
			fi
			if ! kill -0 "$runquotad_pid" 2>/dev/null; then
				ct_report_runquotad_failure "runquotad exited before becoming ready."
				exit 1
			fi
			sleep 0.05
		done
		if [ -z "${RUNQUOTA_SOCKET:-}" ]; then
			ct_report_runquotad_failure "runquotad did not become ready within 15s."
			exit 1
		fi
	fi

	# macOS-only: pick up the system SDK path so cargo's cc-rs and the
	# Nim compiler can resolve `<sys/...>` includes when invoked outside
	# the `nix develop` shell.
	if [ "$ct_reprobuild_host" = "darwin" ] && [ -z "${SDKROOT:-}" ]; then
		sdkroot="$(xcrun --sdk macosx --show-sdk-path 2>/dev/null || true)"
		if [ -n "$sdkroot" ]; then
			export SDKROOT="$sdkroot"
		fi
	fi

	# macOS / Linux Nix path: realize node_modules via the flake when the
	# tree hasn't run `yarn install` yet. Windows installs node_modules via
	# env.ps1's `Ensure-NodeTooling`, so this fallback is a no-op there.
	if { [ "$ct_reprobuild_host" = "darwin" ] || [ "$ct_reprobuild_host" = "linux" ]; } &&
		[ ! -e node_modules ] && command -v nix >/dev/null 2>&1; then
		node_modules_drv="$(nix build --no-link --print-out-paths .#node-modules-derivation 2>/dev/null || true)"
		if [ -n "$node_modules_drv" ] && [ -d "$node_modules_drv/bin/node_modules" ]; then
			ln -s "$node_modules_drv/bin/node_modules" node_modules
		fi
	fi

	if { [ "$ct_reprobuild_host" = "darwin" ] || [ "$ct_reprobuild_host" = "linux" ]; } &&
		command -v nix >/dev/null 2>&1; then
		# clingo is Reprobuild's ASP solver: repro_solver dlopen()s
		# ``libclingo.{dylib,so}`` by leaf name at runtime (see
		# ``libs/repro_solver/src/repro_solver/clingo_bindings.nim``), and
		# that dlopen also happens inside the ``extract_runner`` helper that
		# ``repro`` compiles and spawns to load the project interface. Neither
		# ``repro`` nor that helper links clingo, so the shared library must be
		# discoverable via the platform run-time loader path (``DYLD_LIBRARY_PATH``
		# on macOS, ``LD_LIBRARY_PATH`` on Linux) for both the parent and its
		# children. The same paths also feed ``LIBRARY_PATH`` so the codetracer
		# native binaries' ``-lssl/-lcrypto/-lsqlite3/-lpcre/-lzip`` link step
		# resolves outside a full ``nix develop`` shell. clingo is a
		# single-output derivation so it has no ``.out`` attribute.
		#
		# Windows provisions clingo.dll via `non-nix-build/windows/
		# ensure-clingo.ps1` (downloads the conda-forge bundle), and env.ps1
		# puts its bin dir on PATH so the Win32 loader resolves it.
		native_lib_roots="$(nix build --no-link --print-out-paths \
			nixpkgs#openssl.out nixpkgs#sqlite.out nixpkgs#pcre.out nixpkgs#libzip.out \
			nixpkgs#zstd.dev nixpkgs#zstd.out nixpkgs#clingo \
			2>/dev/null || true)"
		if [ -n "$native_lib_roots" ]; then
			while IFS= read -r root; do
				if [ -d "$root/lib" ]; then
					export LIBRARY_PATH="$root/lib${LIBRARY_PATH:+:$LIBRARY_PATH}"
					if [ "$ct_reprobuild_host" = "darwin" ]; then
						export DYLD_LIBRARY_PATH="$root/lib${DYLD_LIBRARY_PATH:+:$DYLD_LIBRARY_PATH}"
					else
						export LD_LIBRARY_PATH="$root/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
					fi
				fi
				if [ -d "$root/include" ]; then
					export C_INCLUDE_PATH="$root/include${C_INCLUDE_PATH:+:$C_INCLUDE_PATH}"
					export NIX_CFLAGS_COMPILE="-isystem $root/include${NIX_CFLAGS_COMPILE:+ $NIX_CFLAGS_COMPILE}"
				fi
			done <<<"$native_lib_roots"
		fi
	fi

	# Default tool-provisioning differs by host: macOS uses Nix
	# (cakNix adapter pulls every `uses:` entry from /nix/store);
	# Windows uses Scoop — the reprobuild stdlib package files at
	# libs/repro_dsl_stdlib/packages/<tool>.nim carry per-tool
	# `scoopApp(bucket = "main", app = "...", preferredVersion =
	# ">=...")` entries that drive a real `scoop install bucket/app`
	# for every uses: selector that isn't already on disk.
	case "$ct_reprobuild_host" in
	darwin) ct_tool_provisioning_default="nix" ;;
	windows) ct_tool_provisioning_default="scoop" ;;
	*) ct_tool_provisioning_default="nix" ;;
	esac

	"$repro_bin" "${CODETRACER_REPROBUILD_COMMAND:-build}" "${CODETRACER_REPROBUILD_TARGET:-.}" \
		--tool-provisioning="${CODETRACER_REPROBUILD_TOOL_PROVISIONING:-$ct_tool_provisioning_default}" \
		--progress="${CODETRACER_REPROBUILD_PROGRESS:-bar-line}" \
		--write-diagnostics="${CODETRACER_REPROBUILD_DIAGNOSTICS:-.repro/build/reprobuild/build-diagnostics.log}" \
		--log="${CODETRACER_REPROBUILD_LOG:-quiet}"
	# post-build-setcap.sh re-applies BPF capabilities (cap_bpf +
	# cap_perfmon + cap_dac_read_search) to the freshly built ct binary
	# via the codetracer-setcap helper — the same post-build step the
	# legacy Tup path runs below. It is Linux-only functionality, but the
	# script self-guards (no-ops when codetracer-setcap is absent or
	# passwordless sudo is unavailable), so it is safe to call on macOS
	# too. Windows has no Linux setcap concept, so skip it there.
	if [ "$ct_reprobuild_host" = "linux" ] || [ "$ct_reprobuild_host" = "darwin" ]; then
		scripts/post-build-setcap.sh "$ct_repro_out_root/bin/ct"
	fi
	exit 0
fi

# Tup build variant for the selected configuration. CODETRACER_CONFIG=release
# builds the `build-release` variant (src/build-release/tup.config, CONFIG_DEBUG=0
# → release Nim flags); the default is `build-debug`. The two variants live in
# separate output dirs so they don't collide.
ct_tup_config="${CODETRACER_CONFIG:-debug}"
ct_tup_variant="build-${ct_tup_config}"
ct_publish_build_env "" "$ct_tup_config" "$ct_tup_variant" "src/$ct_tup_variant"

# tup's dependency tracking is a FUSE mount, and libfuse can only obtain
# /dev/fuse through a setuid helper at a path compiled into the binary. When
# that helper is missing, tup reports a mount timeout three layers away from
# the cause -- which is how `cross-process-linux` spent its runs failing at
# "Unable to mount FUSE on .tup/mnt". Check it here, where the diagnostic can
# still name the host requirement.
"${BASH:-bash}" "$SCRIPT_DIR/require-fuse-mount-helper.sh" "${TUP:-tup}"

# We have to make the dist directory here, because it's missing on a fresh check out
# It will be created by the webpack command below, but we have an a chicken and egg
# problem because the Tupfiles refer to it.
mkdir -p src/public/dist

# tup expands `: foreach <dir>/<glob>` at PARSE time and produces zero rules --
# no warning, no error -- when the directory is absent or the glob matches
# nothing. Issue #605 was exactly that: an asset-publication rule pointed at a
# directory the SVGs had not been moved into yet, so it published nothing and
# the build failed several steps later with an error that named neither the
# Tupfile nor the directory. Run after the `mkdir -p` above, because
# `src/public/dist` is one of the directories the rules glob.
"${BASH:-bash}" "$SCRIPT_DIR/require-tup-globs.sh"

cd src
"${TUP:-tup}" "$ct_tup_variant"
cd ..

# Build frontend_bundle.js in the dist folder
node_modules/.bin/webpack --progress

# We need to execute another tup run because webpack may have created some new files
# that tup will discover
cd src
"${TUP:-tup}" "$ct_tup_variant"
cd ..

# Re-apply BPF capabilities on the ct binary. Tup's FUSE sandbox prevents
# sudo from running during the build, so we do this as a post-build step.
# Silently skips if codetracer-setcap is not installed.
scripts/post-build-setcap.sh "src/$ct_tup_variant/bin/ct"
