#!/usr/bin/env bash
#
# reclaim-hook-dispatchers.sh -- after git-hooks.nix's installer, give each hook
# slot back to Reprobuild's dispatcher and chain the pre-commit shim behind it.
#
#   bash ci/dev/reclaim-hook-dispatchers.sh
#
# `pre-commit install` finds Reprobuild's dispatcher ("# reprobuild hook
# dispatcher") in a slot, moves it to `<hook>.legacy` and writes its own shim
# there. The managed hook -- for pre-push, the publication gate -- then runs
# only because pre-commit's shim chains `.legacy`. Reprobuild's model is the
# reverse: the dispatcher owns `<hook>` and runs the repository's own hook from
# `<hook>.repro-local`. For every `.legacy` dispatcher this script:
#
#   * slot holds a pre-commit/prek shim (or nothing) -> chain the shim as
#     `.repro-local` and put the dispatcher back;
#   * slot already holds a dispatcher -> drop the stale `.legacy` copy;
#   * anything else (a hand-written hook in the slot or in `.repro-local`) ->
#     touch nothing and say so; `repro hooks ensure --vcs` reconciles it.
#
# A repository with no dispatcher is left exactly as the installer left it.
# Never fails the caller.
#
# Contract suite: ci/test/reclaim-hook-dispatchers-test.sh
set -uo pipefail

say() { echo "reclaim-hook-dispatchers: $*" >&2; }
dispatcher='reprobuild hook dispatcher'
generated='^# File generated by (pre-commit|prek)'

hooks="$(git rev-parse --path-format=absolute --git-path hooks 2>/dev/null)" || exit 0
[ -d "$hooks" ] || exit 0

for legacy in "$hooks"/*.legacy; do
	if [ ! -f "$legacy" ] || ! grep -q "$dispatcher" "$legacy"; then
		continue
	fi
	slot="${legacy%.legacy}"
	name="$(basename "$slot")"
	if [ -f "$slot" ] && grep -q "$dispatcher" "$slot"; then
		rm -f "$legacy"
		continue
	fi
	if [ -e "$slot" ] && ! grep -Eq "$generated" "$slot"; then
		say "$name is not a pre-commit shim; leaving the dispatcher at $name.legacy."
		say "  Run 'repro hooks ensure --vcs' to reconcile."
		continue
	fi
	if [ -f "$slot.repro-local" ] && ! grep -Eq "$generated" "$slot.repro-local"; then
		say "$name.repro-local is your own hook; not replacing it with the shim."
		say "  Run 'repro hooks ensure --vcs' to reconcile."
		continue
	fi
	if [ -e "$slot" ]; then
		mv -f "$slot" "$slot.repro-local" || continue
	fi
	mv -f "$legacy" "$slot" || continue
	say "kept the Reprobuild dispatcher at $name (pre-commit chained as $name.repro-local)"
done
exit 0
